'use client';

import { useEffect, useMemo, useState } from 'react';
import styles from '../admin.module.css';

type Review={id:string;location_id:string;author_name:string;rating:number;title?:string;body?:string;created_at:string;image_path?:string};
type Staff={id:string;username:string;displayName?:string;role:string};
type Location={id:string;name:string;city?:string;region?:string};
type OwnerClaim={id:string;location_id:string;user_id:string;claimant_name:string;business_email?:string;business_phone?:string;role_title?:string;business_website?:string;evidence_text?:string;status:'pending'|'approved'|'rejected';display_name?:string;username?:string;email?:string;yerbas_address?:string;created_at:string;location?:Location};

export default function CommunityAdminPage(){
 const[reviews,setReviews]=useState<Review[]>([]),[claims,setClaims]=useState<OwnerClaim[]>([]),[staff,setStaff]=useState<Staff[]>([]),[locations,setLocations]=useState<Location[]>([]),[ownerId,setOwnerId]=useState(''),[locationId,setLocationId]=useState(''),[note,setNote]=useState(''),[message,setMessage]=useState<string|null>(null);
 const load=async()=>{const [reviewRes,claimRes,staffRes,dispRes,candidateRes]=await Promise.all([fetch('/api/admin/community/reviews',{cache:'no-store'}),fetch('/api/admin/owner-claims?status=pending',{cache:'no-store'}),fetch('/api/admin/staff',{cache:'no-store'}),fetch('/api/dispensaries',{cache:'no-store'}),fetch('/api/map-candidates',{cache:'no-store'})]);if(reviewRes.ok)setReviews((await reviewRes.json()).reviews||[]);if(claimRes.ok)setClaims((await claimRes.json()).claims||[]);if(staffRes.ok){const d=await staffRes.json();setStaff(d.staff||d.users||d.admins||[]);}const merged:Location[]=[];if(dispRes.ok){const d=await dispRes.json();for(const x of d.dispensaries||[])merged.push({id:x.id,name:x.name,city:x.city,region:x.region});}if(candidateRes.ok){const d=await candidateRes.json();for(const x of d.candidates||[])if(!merged.some(y=>y.id===x.id))merged.push({id:x.id,name:x.name,city:x.city,region:x.region});}setLocations(merged.sort((a,b)=>a.name.localeCompare(b.name)));};
 useEffect(()=>{void load();},[]);
 const reviewGroups=useMemo(()=>reviews.reduce<Record<string,Review[]>>((acc,r)=>{(acc[r.id]??=[]).push(r);return acc;},{}),[reviews]);
 async function moderate(id:string,status:'approved'|'rejected'){const r=await fetch('/api/admin/community/reviews',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reviewId:id,status})});const d=await r.json().catch(()=>({}));setMessage(r.ok?`Review ${status}.`:d.error||'Moderation failed.');if(r.ok)void load();}
 async function moderateClaim(id:string,status:'approved'|'rejected'){const moderationNote=status==='rejected'?window.prompt('Optional reason shown to the claimant:','')||'':window.prompt('Optional verification note:','')||'';const r=await fetch('/api/admin/owner-claims',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({claimId:id,status,note:moderationNote})});const d=await r.json().catch(()=>({}));setMessage(r.ok?`Ownership claim ${status}.`:d.error||'Claim moderation failed.');if(r.ok)void load();}
 async function assign(){const r=await fetch('/api/admin/dispensary-owners',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({adminUserId:ownerId,locationId,note})});const d=await r.json().catch(()=>({}));setMessage(r.ok?'Verified dispensary owner assigned.':d.error||'Owner assignment failed.');}
 return <main className={styles.shell}><header className={styles.header}><div><a href="/admin" className={styles.adminHomeLink}><span className={styles.eyebrow}>GEOWEEDO ADMIN</span></a><h1>Community moderation</h1><p>Approve reviews and photos, review public ownership claims, and manage verified shop access.</p></div></header>
  {message&&<div className="admin-community-message">{message}</div>}
  <section className={styles.section}><div className={styles.sectionHead}><div><span className={styles.eyebrow}>OWNER CLAIMS</span><h2>Pending business verification</h2></div><span className={styles.count}>{claims.length}</span></div><div className="admin-community-list">{claims.length===0?<div className={styles.card}>No pending ownership claims.</div>:claims.map(claim=><article className={styles.card} key={claim.id}><div className={styles.cardTop}><span className={styles.partialBadge}>PENDING</span><h3>{claim.location?.name||claim.location_id}</h3></div><p><strong>{claim.claimant_name}</strong>{claim.role_title?` · ${claim.role_title}`:''}</p><div className="admin-claim-contact">{claim.business_email&&<span>Business email: {claim.business_email}</span>}{claim.business_phone&&<span>Business phone: {claim.business_phone}</span>}{claim.business_website&&<a href={/^https?:\/\//i.test(claim.business_website)?claim.business_website:`https://${claim.business_website}`} target="_blank" rel="noreferrer">Business website ↗</a>}</div>{claim.evidence_text&&<div className="admin-claim-evidence"><strong>Verification evidence</strong><p>{claim.evidence_text}</p></div>}<small>GeoWeedo account: {claim.display_name||claim.username||claim.user_id}{claim.email?` · ${claim.email}`:''}</small><div className={styles.cardActions}><button className={styles.primaryLink} onClick={()=>moderateClaim(claim.id,'approved')}>Approve + grant owner access</button><button className={styles.secondaryLink} onClick={()=>moderateClaim(claim.id,'rejected')}>Reject</button></div></article>)}</div></section>
  <section className={styles.section}><div className={styles.sectionHead}><div><span className={styles.eyebrow}>REVIEWS</span><h2>Pending community content</h2></div><span className={styles.count}>{Object.keys(reviewGroups).length}</span></div><div className="admin-community-list">{Object.values(reviewGroups).length===0?<div className={styles.card}>No pending reviews.</div>:Object.values(reviewGroups).map(rows=>{const r=rows[0];return <article className={styles.card} key={r.id}><div className={styles.cardTop}><span className={styles.partialBadge}>PENDING</span><h3>{'★'.repeat(r.rating)}{'☆'.repeat(5-r.rating)} · {r.author_name}</h3></div>{r.title&&<strong>{r.title}</strong>}{r.body&&<p>{r.body}</p>}<small>Location {r.location_id}</small>{rows.filter(x=>x.image_path).length>0&&<div className="admin-community-images">{rows.filter(x=>x.image_path).map(x=><img key={x.image_path} src={x.image_path} alt="Pending review upload"/>)}</div>}<div className={styles.cardActions}><button className={styles.primaryLink} onClick={()=>moderate(r.id,'approved')}>Approve</button><button className={styles.secondaryLink} onClick={()=>moderate(r.id,'rejected')}>Reject</button></div></article>;})}</div></section>
  <section className={styles.section}><div className={styles.sectionHead}><div><span className={styles.eyebrow}>MANUAL OWNER ACCESS</span><h2>Assign an existing owner-admin account</h2></div></div><article className={styles.card}><p>This remains available for manually created owner accounts. Public claims above use the claimant's normal GeoWeedo account and do not require a second login.</p><div className="admin-owner-form"><label>Owner account<select value={ownerId} onChange={e=>setOwnerId(e.target.value)}><option value="">Choose account…</option>{staff.map(s=><option key={s.id} value={s.id}>{s.displayName||s.username} · {s.role}</option>)}</select></label><label>Dispensary<select value={locationId} onChange={e=>setLocationId(e.target.value)}><option value="">Choose dispensary…</option>{locations.map(l=><option key={l.id} value={l.id}>{l.name} · {[l.city,l.region].filter(Boolean).join(', ')}</option>)}</select></label><label>Verification note<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="How ownership was confirmed"/></label><button className={styles.primaryLink} disabled={!ownerId||!locationId} onClick={assign}>Verify owner + assign shop</button></div></article></section>
 </main>;
}
