'use client';

import { useEffect, useMemo, useState } from 'react';
import { ADMIN_PERMISSIONS, PERMISSION_LABELS, ROLE_LABELS, ROLE_PERMISSIONS, type AdminPermission, type AdminRole } from '@/lib/adminPermissions';

type Staff={id:string;username:string;displayName:string;role:AdminRole;permissions:AdminPermission[];active:boolean;lastLoginAt?:string|null;createdAt:string};
const empty={username:'',displayName:'',password:'',role:'moderator' as AdminRole,permissions:[...ROLE_PERMISSIONS.moderator] as AdminPermission[]};

export default function StaffPage(){
 const[staff,setStaff]=useState<Staff[]>([]),[form,setForm]=useState(empty),[status,setStatus]=useState('Loading staff…'),[busy,setBusy]=useState(false),[selectedId,setSelectedId]=useState(''),[selectedRole,setSelectedRole]=useState<AdminRole>('moderator');
 async function load(){const r=await fetch('/api/admin/staff',{cache:'no-store'});if(r.status===401){window.location.href='/admin';return;}const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load staff.');const list:Staff[]=d.staff||[];setStaff(list);setSelectedId(current=>current||list[0]?.id||'');setStatus('Staff permissions ready.');}
 useEffect(()=>{load().catch(e=>setStatus(e.message));},[]);
 useEffect(()=>{const member=staff.find(s=>s.id===selectedId);if(member)setSelectedRole(member.role);},[selectedId,staff]);
 const moderators=useMemo(()=>staff.filter(s=>s.role==='moderator').length,[staff]);
 const verifiedDispensaries=useMemo(()=>staff.filter(s=>s.role==='verified_dispensary').length,[staff]);
 function togglePermission(permission:AdminPermission){setForm(current=>({...current,permissions:current.permissions.includes(permission)?current.permissions.filter(p=>p!==permission):[...current.permissions,permission]}));}
 async function createStaff(){setBusy(true);try{const r=await fetch('/api/admin/staff',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)}),d=await r.json();if(!r.ok)throw new Error(d.error||'Could not create staff account.');setStaff(d.staff||[]);setForm(empty);setStatus(`${form.username} created.`);}catch(e){setStatus(e instanceof Error?e.message:'Could not create staff account.');}finally{setBusy(false);}}
 async function patch(id:string,changes:Record<string,unknown>){setBusy(true);try{const r=await fetch('/api/admin/staff',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,...changes})}),d=await r.json();if(!r.ok)throw new Error(d.error||'Could not update staff account.');setStaff(d.staff||[]);setStatus('Staff account updated.');}catch(e){setStatus(e instanceof Error?e.message:'Could not update staff account.');}finally{setBusy(false);}}
 async function assignRole(){if(!selectedId)return;await patch(selectedId,{role:selectedRole,permissions:ROLE_PERMISSIONS[selectedRole]});}
 const editableRole=form.role!=='admin';
 return <main className="admin-shell"><style>{`
 .staff-head{display:flex;justify-content:space-between;gap:16px;align-items:center;flex-wrap:wrap}.staff-grid{display:grid;grid-template-columns:minmax(320px,.8fr) minmax(0,1.2fr);gap:16px}.staff-card{border:1px solid var(--line);border-radius:14px;background:var(--panel);padding:18px}.staff-form{display:grid;gap:10px}.staff-form input,.staff-form select{width:100%}.permission-list{display:grid;gap:7px;margin-top:10px}.permission-list label{display:flex;gap:9px;align-items:flex-start;padding:9px;border:1px solid var(--line);border-radius:9px;background:rgba(255,255,255,.02)}.permission-list input{margin-top:2px}.staff-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:14px;padding:14px 0;border-bottom:1px solid var(--line)}.staff-row:last-child{border-bottom:0}.staff-meta{color:var(--muted);font-size:12px;margin-top:4px}.staff-actions{display:flex;gap:7px;align-items:center;flex-wrap:wrap;justify-content:flex-end}.role-badge{display:inline-flex;padding:4px 7px;border-radius:999px;font-size:10px;font-weight:800;letter-spacing:.08em;border:1px solid var(--line)}.role-badge.mod{color:#f5c451}.role-badge.admin{color:#67d66e}.role-badge.verified{color:#8bd9ff}.permission-chips{display:flex;gap:5px;flex-wrap:wrap;margin-top:9px}.permission-chips span{font-size:10px;padding:4px 6px;border-radius:999px;background:rgba(255,255,255,.04);color:#b6c2b8}.role-note{padding:10px 12px;border:1px solid var(--line);border-radius:9px;color:var(--muted);font-size:12px;line-height:1.45;background:rgba(255,255,255,.02)}.role-assign{display:grid;grid-template-columns:minmax(220px,1fr) minmax(180px,.6fr) auto;gap:9px;align-items:end}.role-assign label{display:grid;gap:5px;font-size:12px;color:var(--muted)}@media(max-width:900px){.staff-grid{grid-template-columns:1fr}.staff-row{grid-template-columns:1fr}.staff-actions{justify-content:flex-start}.role-assign{grid-template-columns:1fr}}
 `}</style><header className="admin-header"><div><a href="/admin" className="eyebrow" style={{textDecoration:'none',color:'inherit'}}>GEOWEEDO ADMIN</a><h1>Staff & permissions</h1></div><div className="admin-links"><a href="/admin">Control center</a><a href="/admin/dispensaries">Dispensaries</a><a href="/">Game</a></div></header><div className="admin-status">{status}</div><section className="admin-panel"><div className="staff-head"><div><span className="eyebrow">ACCESS CONTROL</span><h2 style={{margin:'5px 0'}}>Staff positions</h2><p style={{margin:0,color:'var(--muted)'}}>{staff.length} staff · {moderators} moderators · {verifiedDispensaries} verified dispensaries</p></div></div>
 <div className="staff-card" style={{marginTop:16}}><h3 style={{marginTop:0}}>Assign staff role</h3><p style={{marginTop:0,color:'var(--muted)',fontSize:13}}>Select a user, then select the role they should have.</p><div className="role-assign"><label>User<select value={selectedId} onChange={e=>setSelectedId(e.target.value)} disabled={busy||staff.length===0}><option value="">Select user…</option>{staff.map(member=><option key={member.id} value={member.id}>{member.displayName||member.username} (@{member.username})</option>)}</select></label><label>Role<select value={selectedRole} onChange={e=>setSelectedRole(e.target.value as AdminRole)} disabled={busy||!selectedId}><option value="moderator">Moderator</option><option value="verified_dispensary">Verified Dispensary</option><option value="admin">Administrator</option></select></label><button className="primary" type="button" onClick={assignRole} disabled={busy||!selectedId}>{busy?'Saving…':'Assign role'}</button></div>{selectedRole==='moderator'&&<div className="role-note" style={{marginTop:10}}><strong>Moderator:</strong> can view and edit dispensary/location information, including directly from a GEOWEEDO DISPENSARY profile page.</div>}</div>
 <div className="staff-grid" style={{marginTop:16}}><div className="staff-card"><h3 style={{marginTop:0}}>Add staff member</h3><div className="staff-form"><input placeholder="Username" value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/><input placeholder="Display name" value={form.displayName} onChange={e=>setForm({...form,displayName:e.target.value})}/><input type="password" placeholder="Temporary password · 12+ characters" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><select value={form.role} onChange={e=>{const role=e.target.value as AdminRole;setForm({...form,role,permissions:[...ROLE_PERMISSIONS[role]]});}}><option value="moderator">Moderator</option><option value="verified_dispensary">Verified Dispensary</option><option value="admin">Administrator</option></select>{form.role==='verified_dispensary'&&<div className="role-note"><strong>Verified Dispensary defaults:</strong> admin dashboard only unless explicitly granted additional access.</div>}{editableRole&&<div><strong style={{fontSize:12}}>{ROLE_LABELS[form.role]} permissions</strong><div className="permission-list">{ADMIN_PERMISSIONS.map(permission=><label key={permission}><input type="checkbox" checked={form.permissions.includes(permission)} onChange={()=>togglePermission(permission)}/><span><strong style={{display:'block',fontSize:12}}>{PERMISSION_LABELS[permission]}</strong><small style={{color:'var(--muted)'}}>{permission}</small></span></label>)}</div></div>}<button className="primary" type="button" onClick={createStaff} disabled={busy}>{busy?'Saving…':'Create staff account'}</button></div></div><div className="staff-card"><h3 style={{marginTop:0}}>Current staff</h3>{staff.length===0?<p>No staff accounts found.</p>:staff.map(member=>{const badgeClass=member.role==='admin'?'admin':member.role==='verified_dispensary'?'verified':'mod';return <div className="staff-row" key={member.id}><div><strong>{member.displayName||member.username}</strong> <span className={`role-badge ${badgeClass}`}>{ROLE_LABELS[member.role].toUpperCase()}</span>{!member.active&&<span className="role-badge">INACTIVE</span>}<div className="staff-meta">@{member.username}{member.lastLoginAt?` · last login ${new Date(member.lastLoginAt).toLocaleString()}`:' · never logged in'}</div><div className="permission-chips">{member.role==='admin'?<span>All permissions</span>:member.permissions.map(p=><span key={p}>{p}</span>)}</div></div><div className="staff-actions"><button type="button" disabled={busy} onClick={()=>patch(member.id,{active:!member.active})}>{member.active?'Deactivate':'Activate'}</button></div></div>})}</div></div></section></main>;
}
