'use client';

import { useEffect, useMemo, useState } from 'react';
import styles from '../admin.module.css';
import { RankedBarChart, TrafficTrendExplorer } from '@/components/AdminAnalyticsCharts';
import AdminTrafficOverview from '@/components/AdminTrafficOverview';

type NetworkRow={network:string;sessions:number;visitors:number;page_views:number;first_seen:string;last_seen:string;country?:string;region?:string;city?:string};
type Summary={days:number;currentAdminIp?:string;filters:{excludeAdmin:boolean;excludedIpCount:number;excludedMatchedSessions:number};totals:{visitors:number;sessions:number;pageViews:number;activeNow:number;avgDurationMs:number;errors:number};topPages:Array<{path:string;views:number}>;daily:Array<{day:string;page_views:number;visitors:number;sessions:number}>;referrers:Array<{referrer:string;sessions:number}>;locations:Array<{country:string;region:string;city:string;sessions:number}>;devices:Array<{device:string;sessions:number}>;browsers:Array<{browser:string;sessions:number}>;languages:Array<{language:string;sessions:number}>;timezones:Array<{timezone:string;sessions:number}>;eventTypes:Array<{event_type:string;events:number}>;networks:NetworkRow[]};
function when(v:string){return new Date(v).toLocaleString();}
const FILTER_KEY='geoweedo_admin_analytics_excluded_ips';

export default function AnalyticsPage(){
 const[data,setData]=useState<Summary|null>(null),[days,setDays]=useState(30),[error,setError]=useState(''),[excludeAdmin,setExcludeAdmin]=useState(true),[excludedIps,setExcludedIps]=useState<string[]>([]),[ipInput,setIpInput]=useState('');
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem(FILTER_KEY)||'[]');if(Array.isArray(saved))setExcludedIps(saved.map(String).filter(Boolean));}catch{}},[]);
 useEffect(()=>{try{localStorage.setItem(FILTER_KEY,JSON.stringify(excludedIps));}catch{}},[excludedIps]);
 useEffect(()=>{setError('');const params=new URLSearchParams({days:String(days),excludeAdmin:excludeAdmin?'1':'0'});if(excludedIps.length)params.set('excludeIps',excludedIps.join(','));fetch(`/api/admin/analytics?${params}`,{cache:'no-store'}).then(async r=>{const d=await r.json();if(r.status===401){location.href='/admin/login';return null;}if(!r.ok)throw new Error(d.error||'Analytics failed to load.');return d;}).then(d=>{if(d)setData(d);}).catch(e=>setError(e instanceof Error?e.message:'Analytics failed to load.'));},[days,excludeAdmin,excludedIps]);
 const addIp=(value:string)=>{const ip=value.trim();if(!ip)return;setExcludedIps(current=>current.includes(ip)?current:[...current,ip]);setIpInput('');};
 const topPages=useMemo(()=>data?.topPages.map(row=>({name:row.path||'/',value:Number(row.views||0)}))||[],[data]);const referrers=useMemo(()=>data?.referrers.map(row=>({name:row.referrer||'Direct',value:Number(row.sessions||0)}))||[],[data]);const devices=useMemo(()=>data?.devices.map(row=>({name:row.device,value:Number(row.sessions||0)}))||[],[data]);const browsers=useMemo(()=>data?.browsers.map(row=>({name:row.browser,value:Number(row.sessions||0)}))||[],[data]);
 return <main className={styles.shell}>
  <header className={styles.header}><div><a href="/admin" className={styles.adminHomeLink}><span className={styles.eyebrow}>GEOWEEDO ADMIN</span></a><h1>Analytics</h1><p>First-party traffic, engagement, acquisition, audience, geography, and reliability analytics stored by GeoWeedo.</p></div><div className={styles.headerActions}><a href="/admin" className={styles.ghost}>Control center</a></div></header>
  <section className={styles.section}><div className={styles.sectionHead}><div><span className={styles.eyebrow}>FILTERS</span><h2>Clean traffic view</h2><p>Remove admin pages and your own network from every metric and graph.</p></div><select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={1}>Today</option><option value={7}>7 days</option><option value={30}>30 days</option><option value={90}>90 days</option></select></div><article className={styles.card} style={{minHeight:0}}><div style={{display:'flex',gap:14,alignItems:'center',flexWrap:'wrap'}}><label style={{display:'flex',gap:8,alignItems:'center',fontWeight:700}}><input type="checkbox" checked={excludeAdmin} onChange={e=>setExcludeAdmin(e.target.checked)}/> Exclude /admin traffic</label>{data?.currentAdminIp&&<button className={styles.secondaryLink} type="button" onClick={()=>addIp(data.currentAdminIp!)} disabled={excludedIps.includes(data.currentAdminIp)}>Exclude my current IP</button>}<div style={{display:'flex',gap:8,flex:'1 1 360px'}}><input value={ipInput} onChange={e=>setIpInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();addIp(ipInput);}}} placeholder="IP address to exclude" style={{flex:1,minWidth:180,padding:10,borderRadius:8,border:'1px solid rgba(255,255,255,.12)',background:'#0f1411',color:'#fff'}}/><button className={styles.secondaryLink} type="button" onClick={()=>addIp(ipInput)}>Add IP</button></div></div>{excludedIps.length>0&&<div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:12}}>{excludedIps.map(ip=><button key={ip} type="button" onClick={()=>setExcludedIps(current=>current.filter(v=>v!==ip))}>{ip} ×</button>)}</div>}{excludedIps.length>0&&data&&<p style={{margin:'10px 0 0',fontSize:12,fontWeight:700,color:data.filters.excludedMatchedSessions>0?'var(--accent)':'#ffcf70'}}>{data.filters.excludedMatchedSessions>0?`${data.filters.excludedMatchedSessions.toLocaleString()} matching session${data.filters.excludedMatchedSessions===1?'':'s'} excluded from this view.`:'No stored sessions matched the excluded IP(s). If you expected a drop, the historical analytics were likely recorded without the matching network hash.'}</p>}<p style={{opacity:.65,fontSize:12,marginBottom:0}}>Raw IP addresses are not stored. GeoWeedo checks both the historical rotating daily hash and the stable salted network fingerprint when applying exclusions.</p></article></section>
  <section className={styles.section}>{error&&<p>{error}</p>}{!data?<p>Loading analytics…</p>:<><AdminTrafficOverview totals={data.totals} daily={data.daily} excludedMatchedSessions={data.filters.excludedMatchedSessions}/><div style={{marginTop:12}}><TrafficTrendExplorer excludeAdmin={excludeAdmin} excludedIps={excludedIps}/></div></>}</section>
  {data&&<section className={styles.section}><div className={styles.sectionHead}><div><span className={styles.eyebrow}>NETWORK TRAFFIC</span><h2>Repeat visitor networks</h2><p>Stable pseudonymous network IDs let you identify repeat traffic without retaining raw IP addresses.</p></div></div><div style={{overflowX:'auto'}}><table className="admin-table" style={{minWidth:900}}><thead><tr><th>Network ID</th><th>Location</th><th>Visitors</th><th>Sessions</th><th>Page views</th><th>First seen</th><th>Last seen</th></tr></thead><tbody>{data.networks?.length?data.networks.map(n=><tr key={n.network}><td><code>{n.network}</code></td><td>{[n.city,n.region,n.country].filter(Boolean).join(', ')||'Unknown'}</td><td>{Number(n.visitors).toLocaleString()}</td><td>{Number(n.sessions).toLocaleString()}</td><td>{Number(n.page_views).toLocaleString()}</td><td>{when(n.first_seen)}</td><td>{when(n.last_seen)}</td></tr>):<tr><td colSpan={7}>No stable network data yet. New sessions will populate this table after deployment.</td></tr>}</tbody></table></div></section>}
  {data&&<section className={styles.section}><div className={styles.sectionHead}><div><span className={styles.eyebrow}>ENGAGEMENT</span><h2>What people use</h2></div></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(320px,1fr))',gap:16}}><RankedBarChart title="Top pages" subtitle="Most-viewed pages in the selected period" rows={topPages}/><RankedBarChart title="Referrers" subtitle="Where sessions originated" rows={referrers}/></div></section>}
  {data&&<section className={styles.section}><div className={styles.sectionHead}><div><span className={styles.eyebrow}>AUDIENCE</span><h2>Devices and browsers</h2></div></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(320px,1fr))',gap:16}}><RankedBarChart title="Device class" subtitle="Derived from first-party screen width" rows={devices}/><RankedBarChart title="Browsers" subtitle="Derived from the browser user-agent" rows={browsers}/></div></section>}
  {data&&<section className={styles.section}><div className={styles.sectionHead}><div><span className={styles.eyebrow}>COARSE LOCATION</span><h2>Visitor geography</h2></div></div><div className={styles.grid}>{data.locations.map((row,i)=><article className={styles.card} key={`${row.country}-${row.region}-${row.city}-${i}`}><h3>{[row.city,row.region,row.country].filter(Boolean).join(', ')||'Unknown'}</h3><p>{Number(row.sessions).toLocaleString()} sessions</p></article>)}</div></section>}
  {data&&<section className={styles.section}><div className={styles.sectionHead}><div><span className={styles.eyebrow}>BEHAVIOR + RELIABILITY</span><h2>Tracked events</h2></div></div><div className={styles.grid}>{data.eventTypes.length?data.eventTypes.map((row,i)=><article className={styles.card} key={`${row.event_type}-${i}`}><h3>{row.event_type.replaceAll('_',' ')}</h3><p>{Number(row.events).toLocaleString()} events</p></article>):<article className={styles.card}><h3>No custom events yet</h3></article>}</div></section>}
  <section className={styles.section}><div className={styles.sectionHead}><div><span className={styles.eyebrow}>PRIVACY</span><h2>Collection policy</h2></div></div><article className={styles.card}><p>Raw analytics events are retained for 90 days by default. Raw IP addresses are not stored. A stable salted fingerprint supports repeat-network analysis; a separate rotating one-way daily hash supports historical IP exclusions. Browser Do Not Track and <code>geoweedo_analytics_optout</code> still disable collection.</p></article></section>
 </main>;
}
