import AdminStateGroupsPortal from '@/components/AdminStateGroupsPortal';
import AdminFullDispensaryEditor from '@/components/AdminFullDispensaryEditor';
import AdminDispensaryEnrichment from '@/components/AdminDispensaryEnrichment';
import AdminBatchEnrichmentQueue from '@/components/AdminBatchEnrichmentQueue';
import AdminBulkRejectedCandidates from '@/components/AdminBulkRejectedCandidates';
import AdminEnabledProfileAudit from '@/components/AdminEnabledProfileAudit';
import AdminHoursInputDefaults from '@/components/AdminHoursInputDefaults';

export const metadata = { title: 'GeoWeedo Admin · Dispensaries' };
export default function AdminDispensariesPage(){return <div className="dispensaries-admin-order"><AdminHoursInputDefaults/><style>{`
.dispensaries-admin-order .admin-shell{display:flex;flex-direction:column;min-width:0}.dispensaries-admin-order .admin-shell>*{order:5;min-width:0}.dispensaries-admin-order .admin-shell>.admin-header{order:0}.dispensaries-admin-order .admin-shell>.admin-status{order:1}.dispensaries-admin-order .admin-shell>.state-grouped-dispensaries{order:2}.dispensaries-admin-order .admin-shell>#dispensary-edit-panel{order:3}
.dispensaries-admin-order .admin-card{min-width:0;max-width:100%;overflow:hidden}.dispensaries-admin-order .admin-card>div:first-child{min-width:0}.dispensaries-admin-order .admin-card>div:first-child>div:first-child{min-width:0;overflow-wrap:anywhere;word-break:break-word}.dispensaries-admin-order .admin-card>div:first-child>div:last-child{flex:0 0 auto;display:flex;gap:8px;align-self:flex-start}.dispensaries-admin-order .admin-card>div:not(:first-child){min-width:0;overflow-wrap:anywhere;word-break:break-word}.dispensaries-admin-order .admin-card a{overflow-wrap:anywhere;word-break:break-all}
`}</style><main className="admin-shell"><header className="admin-header"><div><a href="/admin" className="eyebrow" style={{textDecoration:'none',color:'inherit'}}>GEOWEEDO ADMIN</a><h1>Dispensaries</h1><p style={{color:'var(--muted)'}}>Street View readiness is checked automatically during approval. Google 360° imagery is immediately game-ready; fallback imagery must still meet movement-quality rules.</p></div><div className="admin-links"><a href="/admin">Control center</a><a href="/admin/data">Data import</a><a href="/admin/community">Community</a><a href="/admin/dispensaries/imagery">Manual imagery</a><a href="/">Game</a></div></header><AdminEnabledProfileAudit/><AdminBatchEnrichmentQueue/><AdminBulkRejectedCandidates/><details><summary style={{cursor:'pointer',margin:'8px 0 14px'}}>Single-record website enrichment tool</summary><AdminDispensaryEnrichment/></details><AdminFullDispensaryEditor/></main><AdminStateGroupsPortal/></div>}
