import { NextRequest, NextResponse } from 'next/server';
import { analyticsNetworkHash, analyticsStableNetworkHash, getAnalyticsDb, pruneAnalytics, recordAnalyticsEvent } from '@/lib/analytics';
import { getUserFromRequest } from '@/lib/userAuth';

export const runtime='nodejs';
function clean(value:unknown,max=500){return typeof value==='string'?value.slice(0,max):'';}
function ipFrom(request:NextRequest){return clean(request.headers.get('x-forwarded-for')?.split(',')[0]?.trim()||request.headers.get('x-real-ip')||'',128);}
function positiveInt(value:unknown,max:number){const n=Number(value);return Number.isFinite(n)&&n>=0?Math.min(Math.round(n),max):null;}
function ensureIpColumn(){const database=getAnalyticsDb();const columns=database.prepare(`PRAGMA table_info(analytics_sessions)`).all() as Array<{name:string}>;if(!columns.some(c=>c.name==='ip_address'))database.exec(`ALTER TABLE analytics_sessions ADD COLUMN ip_address TEXT`);database.exec(`CREATE INDEX IF NOT EXISTS analytics_sessions_ip_idx ON analytics_sessions(ip_address,started_at)`);return database;}
function headerGeo(request:NextRequest){return{country:clean(request.headers.get('cf-ipcountry')||request.headers.get('x-vercel-ip-country')||request.headers.get('x-country-code'),80),region:clean(request.headers.get('x-vercel-ip-country-region'),120),city:clean(request.headers.get('x-vercel-ip-city'),120)};}
function publicIp(ip:string){return Boolean(ip&&!/^(127\.|10\.|192\.168\.|169\.254\.|::1$|fc|fd)/i.test(ip)&&!/^172\.(1[6-9]|2\d|3[01])\./.test(ip));}
async function geoForIp(ip:string){if(!publicIp(ip)||process.env.ANALYTICS_GEOLOOKUP_DISABLED==='1')return{country:'',region:'',city:''};try{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),1200);const response=await fetch(`https://ipwho.is/${encodeURIComponent(ip)}?fields=success,country,region,city`,{cache:'no-store',signal:controller.signal});clearTimeout(timer);if(!response.ok)return{country:'',region:'',city:''};const data=await response.json() as any;if(!data?.success)return{country:'',region:'',city:''};return{country:clean(data.country,80),region:clean(data.region,120),city:clean(data.city,120)};}catch{return{country:'',region:'',city:''};}}
export async function POST(request:NextRequest){try{const body=await request.json().catch(()=>null) as Record<string,unknown>|null;if(!body)return NextResponse.json({error:'Invalid analytics payload.'},{status:400});const sessionId=clean(body.sessionId,100),visitorId=clean(body.visitorId,100),eventType=clean(body.eventType,80),pagePath=clean(body.path,500);if(!sessionId||!visitorId||!eventType)return NextResponse.json({error:'Missing analytics identifiers.'},{status:400});if(!/^[a-zA-Z0-9._:-]+$/.test(sessionId)||!/^[a-zA-Z0-9._:-]+$/.test(visitorId)||!/^[a-z0-9_:-]+$/i.test(eventType))return NextResponse.json({error:'Invalid analytics identifiers.'},{status:400});const database=ensureIpColumn(),existing=database.prepare('SELECT id,country,region,city FROM analytics_sessions WHERE id=?').get(sessionId) as any,props=body.properties&&typeof body.properties==='object'&&!Array.isArray(body.properties)?body.properties as Record<string,unknown>:null,ip=ipFrom(request),user=getUserFromRequest(request),fromHeaders=headerGeo(request);let geo=fromHeaders;if(!existing&&ip&&!geo.country&&!geo.region&&!geo.city)geo=await geoForIp(ip);recordAnalyticsEvent({sessionId,visitorId,userId:user?.id||null,eventType,path:pagePath||null,durationMs:positiveInt(body.durationMs,86400000),properties:props,networkHash:ip?analyticsNetworkHash(ip):null,stableNetworkHash:ip?analyticsStableNetworkHash(ip):null,country:geo.country||null,region:geo.region||null,city:geo.city||null,userAgent:clean(request.headers.get('user-agent'),500)||null,language:clean(body.language,80)||null,timezone:clean(body.timezone,100)||null,screenWidth:positiveInt(body.screenWidth,20000),screenHeight:positiveInt(body.screenHeight,20000),referrer:clean(body.referrer,1000)||null});if(ip)database.prepare(`UPDATE analytics_sessions SET ip_address=COALESCE(NULLIF(ip_address,''),?),country=COALESCE(NULLIF(country,''),?),region=COALESCE(NULLIF(region,''),?),city=COALESCE(NULLIF(city,''),?) WHERE id=?`).run(ip,geo.country||null,geo.region||null,geo.city||null,sessionId);if(Math.random()<0.01)pruneAnalytics(Number(process.env.ANALYTICS_RAW_RETENTION_DAYS||90));return NextResponse.json({ok:true});}catch(error){console.error('GeoWeedo analytics event error',error);return NextResponse.json({error:'Analytics event could not be recorded.'},{status:500});}}
