'use client';

import { useEffect, useMemo, useState } from 'react';
import DispensaryLogoUploader from '@/components/DispensaryLogoUploader';

type Owned={locationId:string;verifiedAt:string;location:{id:string;name:string;city?:string;region?:string;country?:string};profile?:{overview?:string;phone?:string;website?:string;hours?:Record<string,string>;amenities?:string[];social?:Record<string,string>}};
const DAYS=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];

export default function OwnerPage(){
 const[items,setItems]=useState<Owned[]>([]),[selected,setSelected]=useState(''),[loading,setLoading]=useState(true),[message,setMessage]=useState<string|null>(null),[saving,setSaving]=useState(false),[overview,setOverview]=useState(''),[phone,setPhone]=useState(''),[website,setWebsite]=useState(''),[amenities,setAmenities]=useState(''),[hours,setHours]=useState<Record<string,string>>({}),[instagram,setInstagram]=useState(''),[facebook,setFacebook]=useState(''),[x,setX]=useState('');
 const current=useMemo(()=>items.find(i=>i.locationId===selected)||null,[items,selected]);
 const apply=(item:Owned|null)=>{setOverview(item?.profile?.overview||'');setPhone(item?.profile?.phone||'');setWebsite(item?.profile?.website||'');setAmenities((item?.profile?.amenities||[]).join(', '));setHours(item?.profile?.hours||{});setInstagram(item?.profile?.social?.instagram||'');setFacebook(item?.profile?.social?.facebook||'');setX(item?.profile?.social?.x||'');};
 const load=async()=>{setLoading(true);try{const r=await fetch('/api/owner/dispensaries',{cache:'no-store'});if(r.status===401){window.location.href='/account';return;}const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load owner access.');const owned:Owned[]=d.dispensaries||[];setItems(owned);const next=selected&&owned.some(i=>i.locationId===selected)?selected:owned[0]?.locationId||'';setSelected(next);apply(owned.find(i=>i.locationId===next)||null);}catch(e){setMessage(e instanceof Error?e.message:'Could not load owner access.');}finally{setLoading(false);}};
 useEffect(()=>{void load();},[]);
 useEffect(()=>{if(current)apply(current);},[selected]);
 async function save(){if(!current)return;setSaving(true);setMessage(null);try{const r=await fetch('/api/owner/dispensaries',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({locationId:current.locationId,overview,phone,website,hours,amenities:amenities.split(',').map(v=>v.trim()).filter(Boolean),social:{instagram,facebook,x}})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Could not save profile.');setMessage('Dispensary profile updated.');await load();}catch(e){setMessage(e instanceof Error?e.message:'Could not save profile.');}finally{setSaving(false);}}
 if(loading)return <main className="owner-shell"><div className="owner-panel">Loading owner workspace…</div></main>;
 return <main className="owner-shell"><header className="owner-header"><div><a href="/">✦ GEOWEEDO</a><span>VERIFIED DISPENSARY OWNER</span><h1>Manage your shop</h1><p>Update public business information without changing official licensing, source, coordinates, gameplay, reviews, users, or finance records.</p></div><div className="owner-header-actions"><a href="/account">Account</a><a href="/">View map</a></div></header>{message&&<div className="owner-message">{message}</div>}{items.length===0?<section className="owner-panel"><h2>No verified dispensary yet</h2><p>Your ownership claim may still be under review. Open the dispensary profile to check its claim status or submit a claim.</p><a className="owner-primary" href="/">Browse dispensaries</a></section>:<><section className="owner-panel"><label>Managed dispensary<select value={selected} onChange={e=>setSelected(e.target.value)}>{items.map(item=><option key={item.locationId} value={item.locationId}>{item.location.name} · {[item.location.city,item.location.region].filter(Boolean).join(', ')}</option>)}</select></label>{current&&<small>Verified {new Date(current.verifiedAt).toLocaleDateString()}</small>}</section>{current&&<section className="owner-panel owner-form"><div className="owner-panel-head"><div><span>PUBLIC PROFILE</span><h2>{current.location.name}</h2></div><a href={`/dispensary/${encodeURIComponent(current.locationId)}`} target="_blank" rel="noreferrer">View public profile ↗</a></div><DispensaryLogoUploader locationId={current.locationId}/><label>Overview<textarea value={overview} onChange={e=>setOverview(e.target.value)} maxLength={5000} placeholder="Tell visitors about the shop, specialties, atmosphere, services, and what makes it useful."/></label><div className="owner-grid"><label>Phone<input value={phone} onChange={e=>setPhone(e.target.value)} maxLength={80}/></label><label>Website<input value={website} onChange={e=>setWebsite(e.target.value)} maxLength={500}/></label></div><label>Amenities / services<input value={amenities} onChange={e=>setAmenities(e.target.value)} placeholder="Parking, Delivery, Curbside pickup, ATM, Wheelchair accessible"/><small>Separate items with commas.</small></label><div className="owner-hours"><strong>Hours</strong>{DAYS.map(day=><label key={day}><span>{day}</span><input value={hours[day]||''} onChange={e=>setHours(v=>({...v,[day]:e.target.value}))} placeholder="9:00 AM – 9:00 PM"/></label>)}</div><div className="owner-grid"><label>Instagram<input value={instagram} onChange={e=>setInstagram(e.target.value)} placeholder="https://instagram.com/..."/></label><label>Facebook<input value={facebook} onChange={e=>setFacebook(e.target.value)} placeholder="https://facebook.com/..."/></label><label>X / Twitter<input value={x} onChange={e=>setX(e.target.value)} placeholder="https://x.com/..."/></label></div><button className="owner-primary" type="button" disabled={saving} onClick={save}>{saving?'Saving…':'Save public profile'}</button></section>}</>}</main>;
}
