import 'server-only';
import 'pdf-parse/worker';
import { PDFParse } from 'pdf-parse';
export type AlaskaCandidate={name:string;streetAddress?:string;city?:string;region:string;country:string;licenseNumber?:string;dataSource:string;sourceUrl:string;sourceLicense:string;imageryStatus:'missing_coordinates'};
const SEARCH_URL='https://www.commerce.alaska.gov/abc/marijuana/Home/licensesearch';
const RENEWAL_URL='https://www.commerce.alaska.gov/web/Portals/9/pub/MCB/MarijuanaApplication/MCB_2026-2027_List_of_%20Licenses_%20up_%20for_%20renewal_due_by_6.30.2026.pdf';
function decode(value:string){return value.replace(/&amp;/g,'&').replace(/&#39;|&apos;/g,"'").replace(/&quot;/g,'"').replace(/&nbsp;/g,' ').replace(/&#8211;|&ndash;/g,'–').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();}
function parseAddress(text:string){const m=text.match(/Physical Address:\s*(\d{1,6}\s+[^\n]{2,120}?)\s+([A-Za-z .'-]+),\s*AK\s+\d{5}(?:-\d{4})?/i);return m?{streetAddress:m[1].trim(),city:m[2].trim()}:{};}
function headers(){return{Accept:'text/html,application/xhtml+xml,application/pdf;q=0.9,*/*;q=0.8','User-Agent':'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/124 Safari/537.36','Accept-Language':'en-US,en;q=0.9'};}
function parseSearchResults(html:string){const unique=new Map<string,{url:string;licenseNumber:string;name:string}>();const re=/href=["']([^"']*\/abc\/marijuana\/Home\/License\/[0-9a-f-]+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m:RegExpExecArray|null;while((m=re.exec(html))!==null){const url=new URL(m[1],SEARCH_URL).toString(),label=decode(m[2]),around=decode(html.slice(Math.max(0,m.index-500),m.index+700)),licenseNumber=around.match(/(?:License\s*(?:#|Number)?\s*:?\s*)(\d{3,8})/i)?.[1]||label.match(/\b(\d{3,8})\b/)?.[1]||'',name=around.match(/(?:Doing Business As|DBA)\s*:?\s*([A-Za-z0-9][A-Za-z0-9 &'.,/()-]{2,100}?)(?:\s+License|\s+Retail Marijuana Store|$)/i)?.[1]?.trim()||label.replace(/\b\d{3,8}\b/g,'').trim();if(licenseNumber&&name&&!unique.has(licenseNumber))unique.set(licenseNumber,{url,licenseNumber,name});}return Array.from(unique.values());}
async function detail(item:{url:string;licenseNumber:string;name:string}){const response=await fetch(item.url,{headers:headers(),cache:'no-store',signal:AbortSignal.timeout(30000)});if(!response.ok)return null;const text=decode(await response.text());if(!/License Status:\s*Active-Operating/i.test(text)||!/License Type:\s*Retail Marijuana Store/i.test(text))return null;const a=parseAddress(text);return{name:item.name,streetAddress:a.streetAddress,city:a.city,region:'Alaska',country:'USA',licenseNumber:item.licenseNumber,dataSource:'Alaska AMCO Marijuana License Search',sourceUrl:SEARCH_URL,sourceLicense:'Official Alaska AMCO license data; Active-Operating Retail Marijuana Store licenses only.',imageryStatus:'missing_coordinates' as const};}
function renewalRows(text:string){const rows:AlaskaCandidate[]=[];const lines=text.split(/\n+/).map(v=>decode(v)).filter(Boolean);for(let i=0;i<lines.length;i++){const block=lines.slice(i,Math.min(lines.length,i+6)).join(' ');if(!/Retail Marijuana Store/i.test(block))continue;const license=block.match(/\b(?:License\s*(?:#|No\.?|Number)?\s*)?(\d{4,6})\b/i)?.[1];if(!license)continue;let name=block.replace(/\b(?:License\s*(?:#|No\.?|Number)?\s*)?\d{4,6}\b/i,' ').replace(/Retail Marijuana Store/ig,' ').replace(/\s+/g,' ').trim();name=name.replace(/^(?:Active|Renewal|Marijuana)\s+/i,'').trim();if(name.length<2)continue;rows.push({name,region:'Alaska',country:'USA',licenseNumber:license,dataSource:'Alaska AMCO 2026-2027 Renewal License List',sourceUrl:RENEWAL_URL,sourceLicense:'Official Alaska AMCO 2026-2027 renewal list; Retail Marijuana Store entries. Addresses require normal coordinate/address enrichment.',imageryStatus:'missing_coordinates'});}const unique=new Map<string,AlaskaCandidate>();for(const row of rows)if(row.licenseNumber&&!unique.has(row.licenseNumber))unique.set(row.licenseNumber,row);return Array.from(unique.values());}
export async function fetchAlaskaCandidates():Promise<AlaskaCandidate[]>{let search:Response|null=null;try{search=await fetch(SEARCH_URL,{headers:headers(),cache:'no-store',signal:AbortSignal.timeout(30000)});}catch{}if(search?.ok){const found=parseSearchResults(await search.text()),rows:AlaskaCandidate[]=[];for(const item of found){const row=await detail(item);if(row)rows.push(row);}if(rows.length)return rows;}
 const renewal=await fetch(RENEWAL_URL,{headers:headers(),cache:'no-store',signal:AbortSignal.timeout(30000)});if(!renewal.ok)throw new Error(`Alaska AMCO search returned ${search?.status||'unavailable'} and renewal list returned ${renewal.status}`);const buffer=Buffer.from(await renewal.arrayBuffer());const parser=new PDFParse({data:buffer});try{const result=await parser.getText();const rows=renewalRows(result.text||'');if(!rows.length)throw new Error(`Alaska AMCO search returned ${search?.status||'unavailable'} and renewal PDF contained no parseable Retail Marijuana Store entries.`);return rows;}finally{await parser.destroy();}}
