export type AlaskaCandidate={name:string;streetAddress?:string;city?:string;region:string;country:string;licenseNumber?:string;dataSource:string;sourceUrl:string;sourceLicense:string;imageryStatus:'missing_coordinates'};

const SEARCH_URL='https://www.commerce.alaska.gov/abc/marijuana/Home/licensesearch';
const RENEWAL_URL='https://www.commerce.alaska.gov/web/Portals/9/pub/MCB/MarijuanaApplication/MCB_2026-2027_List_of_%20Licenses_%20up_%20for_%20renewal_due_by_6.30.2026.pdf';

function decode(value:string){return value.replace(/&amp;/g,'&').replace(/&#39;|&apos;/g,"'").replace(/&quot;/g,'"').replace(/&nbsp;/g,' ').replace(/&#8211;|&ndash;/g,'–').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();}
function parseAddress(text:string){const m=text.match(/Physical Address:\s*(\d{1,6}\s+[^\n]{2,120}?)\s+([A-Za-z .'-]+),\s*AK\s+\d{5}(?:-\d{4})?/i);return m?{streetAddress:m[1].trim(),city:m[2].trim()}:{};}
function headers(){return {Accept:'text/html,application/xhtml+xml,application/pdf;q=0.9,*/*;q=0.8','User-Agent':'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124 Safari/537.36','Accept-Language':'en-US,en;q=0.9'};}

async function fetchText(url:string){const response=await fetch(url,{headers:headers(),cache:'no-store',signal:AbortSignal.timeout(30000)});if(!response.ok)throw new Error(`Alaska AMCO source returned ${response.status}`);return response.text();}

function parseSearchResults(html:string){const unique=new Map<string,{url:string;licenseNumber:string;name:string}>();const linkRegex=/href=["']([^"']*\/abc\/marijuana\/Home\/License\/[0-9a-f-]+)["'][^>]*>([\s\S]*?)<\/a>/gi;let match:RegExpExecArray|null;while((match=linkRegex.exec(html))!==null){const url=new URL(match[1],SEARCH_URL).toString();const label=decode(match[2]);const around=decode(html.slice(Math.max(0,(match.index||0)-500),(match.index||0)+700));const licenseNumber=around.match(/(?:License\s*(?:#|Number)?\s*:?\s*)(\d{3,8})/i)?.[1]||label.match(/\b(\d{3,8})\b/)?.[1]||'';const name=around.match(/(?:Doing Business As|DBA)\s*:?\s*([A-Za-z0-9][A-Za-z0-9 &'.,/()-]{2,100}?)(?:\s+License|\s+Retail Marijuana Store|$)/i)?.[1]?.trim()||label.replace(/\b\d{3,8}\b/g,'').trim();if(licenseNumber&&name&&!unique.has(licenseNumber))unique.set(licenseNumber,{url,licenseNumber,name});}return Array.from(unique.values());}

async function detail(url:string,licenseNumber:string,name:string):Promise<AlaskaCandidate|null>{const response=await fetch(url,{headers:headers(),cache:'no-store',signal:AbortSignal.timeout(30000)});if(!response.ok)return null;const text=decode(await response.text());if(!/License Status:\s*Active-Operating/i.test(text)||!/License Type:\s*Retail Marijuana Store/i.test(text))return null;const address=parseAddress(text);return{name,streetAddress:address.streetAddress,city:address.city,region:'Alaska',country:'USA',licenseNumber,dataSource:'Alaska AMCO Marijuana License Search',sourceUrl:SEARCH_URL,sourceLicense:'Official Alaska Alcohol & Marijuana Control Office license data; Active-Operating Retail Marijuana Store licenses only.',imageryStatus:'missing_coordinates'};}

function parseRenewalList(text:string):AlaskaCandidate[]{const rows:AlaskaCandidate[]=[];const normalized=decode(text);const re=/\b(\d{4,6})\s+([A-Za-z0-9][A-Za-z0-9 &'.,/()#-]{2,100}?)\s+Retail Marijuana Store\b/gi;let m:RegExpExecArray|null;while((m=re.exec(normalized))!==null){rows.push({name:m[2].trim(),region:'Alaska',country:'USA',licenseNumber:m[1],dataSource:'Alaska AMCO 2026-2027 Renewal License List',sourceUrl:RENEWAL_URL,sourceLicense:'Official Alaska AMCO 2026-2027 marijuana renewal list; Retail Marijuana Store entries. Search endpoint was unavailable to the server, so these records require normal coordinate/address enrichment.',imageryStatus:'missing_coordinates'});}const unique=new Map<string,AlaskaCandidate>();for(const row of rows)if(row.licenseNumber&&!unique.has(row.licenseNumber))unique.set(row.licenseNumber,row);return Array.from(unique.values());}

export async function fetchAlaskaCandidates():Promise<AlaskaCandidate[]>{
 let searchResponse:Response|null=null;
 try{searchResponse=await fetch(SEARCH_URL,{headers:headers(),cache:'no-store',signal:AbortSignal.timeout(30000)});}catch{}
 if(searchResponse?.ok){const results=parseSearchResults(await searchResponse.text());if(results.length){const rows:AlaskaCandidate[]=[];for(const item of results){const row=await detail(item.url,item.licenseNumber,item.name);if(row)rows.push(row);}if(rows.length)return rows;}}
 // Alaska AMCO sometimes returns HTTP 403 to automated server requests even though the public search remains browser-accessible.
 // Fall back to AMCO's official current renewal list rather than failing the nationwide sync or using a third-party dataset.
 const renewal=await fetch(RENEWAL_URL,{headers:headers(),cache:'no-store',signal:AbortSignal.timeout(30000)});if(!renewal.ok)throw new Error(`Alaska AMCO license search returned ${searchResponse?.status||'unavailable'} and official renewal fallback returned ${renewal.status}`);const type=renewal.headers.get('content-type')||'';if(/pdf/i.test(type))throw new Error(`Alaska AMCO license search returned ${searchResponse?.status||'unavailable'}; official renewal fallback is PDF and requires the Alaska PDF parser before it can be imported safely.`);const rows=parseRenewalList(await renewal.text());if(!rows.length)throw new Error(`Alaska AMCO license search returned ${searchResponse?.status||'unavailable'} and official renewal fallback contained no parseable retail records.`);return rows;
}
