import 'server-only';
import { getDatabase } from '@/lib/sqlite';

export type AlaskaCandidate={name:string;streetAddress?:string;city?:string;region:string;country:string;licenseNumber?:string;dataSource:string;sourceUrl:string;sourceLicense:string;imageryStatus:'missing_coordinates'};
const SEARCH_URL='https://www.commerce.alaska.gov/abc/marijuana/Home/licensesearch';
const LEGACY_SOURCE='Alaska AMCO 2026-2027 Renewal License List';
function decode(value:string){return value.replace(/&amp;/g,'&').replace(/&#39;|&apos;/g,"'").replace(/&quot;/g,'"').replace(/&nbsp;/g,' ').replace(/&#8211;|&ndash;/g,'–').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();}
function parseAddress(text:string){const m=text.match(/Physical Address:\s*(\d{1,6}\s+[^\n]{2,120}?)\s+([A-Za-z .'-]+),\s*AK\s+\d{5}(?:-\d{4})?/i);return m?{streetAddress:m[1].trim(),city:m[2].trim()}:{};}
function headers(){return{Accept:'text/html,application/xhtml+xml;q=0.9,*/*;q=0.8','User-Agent':'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/124 Safari/537.36','Accept-Language':'en-US,en;q=0.9'};}
function cleanLegacyRenewalCandidates(){const db=getDatabase();const result=db.prepare(`DELETE FROM dispensary_candidates
 WHERE status != 'approved'
   AND lower(COALESCE(region,''))='alaska'
   AND (
     data_source = ?
     OR lower(COALESCE(data_source,'')) LIKE '%alaska amco%renewal%'
     OR lower(COALESCE(source_license,'')) LIKE '%alaska amco%renewal%'
     OR lower(COALESCE(source_license,'')) LIKE '%2026-2027 renewal%'
     OR lower(COALESCE(source_url,'')) LIKE '%mcb_2026-2027_list_of_%'
     OR lower(COALESCE(source_url,'')) LIKE '%licenses_up_for_renewal%'
   )`).run(LEGACY_SOURCE);return Number(result.changes||0);}
function parseSearchResults(html:string){const unique=new Map<string,{url:string;licenseNumber:string;name:string}>();const re=/href=["']([^"']*\/abc\/marijuana\/Home\/License\/[0-9a-f-]+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m:RegExpExecArray|null;while((m=re.exec(html))!==null){const url=new URL(m[1],SEARCH_URL).toString(),label=decode(m[2]),around=decode(html.slice(Math.max(0,m.index-500),m.index+700)),licenseNumber=around.match(/(?:License\s*(?:#|Number)?\s*:?\s*)(\d{3,8})/i)?.[1]||label.match(/\b(\d{3,8})\b/)?.[1]||'',name=around.match(/(?:Doing Business As|DBA)\s*:?\s*([A-Za-z0-9][A-Za-z0-9 &'.,/()-]{2,100}?)(?:\s+License|\s+Retail Marijuana Store|$)/i)?.[1]?.trim()||label.replace(/\b\d{3,8}\b/g,'').trim();if(licenseNumber&&name&&!unique.has(licenseNumber))unique.set(licenseNumber,{url,licenseNumber,name});}return Array.from(unique.values());}
async function detail(item:{url:string;licenseNumber:string;name:string}){const response=await fetch(item.url,{headers:headers(),cache:'no-store',signal:AbortSignal.timeout(30000)});if(!response.ok)return null;const text=decode(await response.text());if(!/License Status:\s*Active-Operating/i.test(text)||!/License Type:\s*Retail Marijuana Store/i.test(text))return null;const a=parseAddress(text);if(!a.streetAddress||!a.city)return null;return{name:item.name,streetAddress:a.streetAddress,city:a.city,region:'Alaska',country:'USA',licenseNumber:item.licenseNumber,dataSource:'Alaska AMCO Marijuana License Search',sourceUrl:SEARCH_URL,sourceLicense:'Official Alaska AMCO license data; Active-Operating Retail Marijuana Store licenses with physical addresses only.',imageryStatus:'missing_coordinates' as const};}
export async function fetchAlaskaCandidates():Promise<AlaskaCandidate[]>{const cleaned=cleanLegacyRenewalCandidates();let search:Response;try{search=await fetch(SEARCH_URL,{headers:headers(),cache:'no-store',signal:AbortSignal.timeout(30000)});}catch(error){throw new Error(`Alaska AMCO live license search was unavailable. Removed ${cleaned} legacy renewal-list candidate(s). Renewal-list fallback is intentionally disabled because it does not provide reliable active-retail locations: ${error instanceof Error?error.message:String(error)}`);}if(!search.ok)throw new Error(`Alaska AMCO live license search returned ${search.status}. Removed ${cleaned} legacy renewal-list candidate(s). Renewal-list fallback is intentionally disabled because it does not provide reliable active-retail locations.`);const found=parseSearchResults(await search.text()),rows:AlaskaCandidate[]=[];for(const item of found){const row=await detail(item);if(row)rows.push(row);}if(!rows.length)throw new Error(`Alaska AMCO live license search returned no verifiable Active-Operating Retail Marijuana Store locations with physical addresses. Removed ${cleaned} legacy renewal-list candidate(s). Renewal-list fallback is intentionally disabled.`);return rows;}
