type CandidateRow={name:string;streetAddress?:string;city?:string;region?:string;country:string;latitude?:number;longitude?:number;licenseNumber?:string;dataSource:string;sourceUrl:string;sourceLicense:string;imageryStatus:'unchecked'|'missing_coordinates'};
type AmsterdamFetchResult={rows:CandidateRow[];source:'official'|'osm-fallback';sourceLabel:string;warning?:string};
const SOURCE_URL='https://api.data.amsterdam.nl/v1/docs/datasets/horeca@v1.html';
const API_URL='https://api.data.amsterdam.nl/v1/horeca/v1/exploitatievergunning/';
const OSM_SOURCE_URL='https://www.openstreetmap.org/copyright';
const OVERPASS_URL=process.env.OVERPASS_API_URL?.trim()||'https://overpass-api.de/api/interpreter';
function coord(v:any){const n=Number(v);return Number.isFinite(n)?n:undefined;}
function location(v:any){if(!v)return{};const c=v.coordinates??v.geometry?.coordinates;if(Array.isArray(c)&&c.length>=2){const longitude=coord(c[0]),latitude=coord(c[1]);if(latitude!==undefined&&longitude!==undefined&&Math.abs(latitude)<=90&&Math.abs(longitude)<=180)return{latitude,longitude};}return{latitude:coord(v.latitude??v.lat),longitude:coord(v.longitude??v.lng??v.lon)};}
function records(body:any):any[]{if(Array.isArray(body))return body;const embedded=body?._embedded;if(embedded&&typeof embedded==='object'){for(const value of Object.values(embedded))if(Array.isArray(value))return value as any[];}for(const key of ['results','data','items','exploitatievergunning'])if(Array.isArray(body?.[key]))return body[key];return[];}
function nextUrl(body:any){const next=body?._links?.next;return typeof next==='string'?next:next?.href||null;}
function requestHeaders(){const headers:Record<string,string>={Accept:'application/hal+json','User-Agent':'GeoWeedo/0.5 (https://geoweedo.com)'};const apiKey=process.env.AMSTERDAM_API_KEY?.trim();if(apiKey)headers['X-Api-Key']=apiKey;return headers;}
function officialRows(all:any[]):CandidateRow[]{const shops=all.filter(r=>/coffeeshop/i.test([r.zaakCategorie,r.zaakSpecificatie,r.zaaknaam].filter(Boolean).join(' '))).filter(r=>!/ingetrokken|vervallen|geweigerd|beëindigd|beeindigd/i.test(String(r.statusVergunning||'')));const unique=new Map<string,CandidateRow>();for(const r of shops){const geo=location(r.locatie);const row:CandidateRow={name:String(r.zaaknaam||'Amsterdam Coffeeshop').trim(),streetAddress:String(r.adres||'').trim()||undefined,city:'Amsterdam',region:'North Holland',country:'Netherlands',latitude:geo.latitude,longitude:geo.longitude,licenseNumber:r.zaaknummer!=null?String(r.zaaknummer):undefined,dataSource:'Amsterdam Horeca Exploitatievergunningen · Coffeeshops',sourceUrl:SOURCE_URL,sourceLicense:'Official public Gemeente Amsterdam horeca exploitation-permit data; records identified as coffeeshops.',imageryStatus:geo.latitude!==undefined&&geo.longitude!==undefined?'unchecked':'missing_coordinates'};const id=row.licenseNumber||`${row.name}|${row.streetAddress||''}`;if(!unique.has(id))unique.set(id,row);}return Array.from(unique.values());}
async function fetchOfficial():Promise<{all:any[];rows:CandidateRow[]}>{let url=API_URL;const all:any[]=[];for(let page=0;page<20&&url;page++){const response=await fetch(url,{headers:requestHeaders(),cache:'no-store',signal:AbortSignal.timeout(30000)});if(!response.ok){const detail=(await response.text().catch(()=>''))?.slice(0,220).replace(/\s+/g,' ').trim();throw new Error(`Amsterdam Horeca API returned ${response.status}${detail?`: ${detail}`:''}.`);}const body=await response.json();const pageRows=records(body);all.push(...pageRows);url=nextUrl(body);if(!url)break;}return{all,rows:officialRows(all)};}
function osmAddress(tags:Record<string,string>){const street=[tags['addr:street'],tags['addr:housenumber']].filter(Boolean).join(' ').trim();return street||tags['addr:full']||undefined;}
async function fetchOsmFallback():Promise<CandidateRow[]>{const query=`[out:json][timeout:25];(nwr["shop"="cannabis"](52.278,4.728,52.431,5.016);nwr["cannabis:recreational"~"^(yes|only)$",i](52.278,4.728,52.431,5.016););out center tags;`;const response=await fetch(OVERPASS_URL,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8','User-Agent':'GeoWeedo/0.5 (https://geoweedo.com)'},body:new URLSearchParams({data:query}),cache:'no-store',signal:AbortSignal.timeout(30000)});if(!response.ok){const detail=(await response.text().catch(()=>''))?.slice(0,220).replace(/\s+/g,' ').trim();throw new Error(`OpenStreetMap fallback returned ${response.status}${detail?`: ${detail}`:''}.`);}const body=await response.json();const unique=new Map<string,CandidateRow>();for(const e of Array.isArray(body?.elements)?body.elements:[]){const tags=(e?.tags||{}) as Record<string,string>;if(tags.shop&&tags.shop!=='cannabis'&&!/^(yes|only)$/i.test(tags['cannabis:recreational']||''))continue;if(/headshop|smartshop|growshop/i.test(tags.shop||''))continue;const latitude=coord(e.lat??e.center?.lat),longitude=coord(e.lon??e.center?.lon);const name=String(tags.name||tags.brand||'Amsterdam Coffeeshop').trim();const row:CandidateRow={name,streetAddress:osmAddress(tags),city:tags['addr:city']||'Amsterdam',region:'North Holland',country:'Netherlands',latitude,longitude,licenseNumber:`OSM-${e.type}-${e.id}`,dataSource:'OpenStreetMap · Amsterdam cannabis shops (fallback)',sourceUrl:OSM_SOURCE_URL,sourceLicense:'Supplemental OpenStreetMap data © OpenStreetMap contributors, available under the Open Data Commons Open Database License (ODbL). Not an official Gemeente Amsterdam permit registry.',imageryStatus:latitude!==undefined&&longitude!==undefined?'unchecked':'missing_coordinates'};const id=`${name.toLowerCase()}|${latitude??''}|${longitude??''}`;if(!unique.has(id))unique.set(id,row);}return Array.from(unique.values());}
export async function fetchAmsterdamCoffeeshopCandidates():Promise<AmsterdamFetchResult>{let officialError='';try{const official=await fetchOfficial();if(official.all.length&&official.rows.length)return{rows:official.rows,source:'official',sourceLabel:'Amsterdam · Gemeente Amsterdam'};if(official.all.length&&!official.rows.length)officialError=`Amsterdam Horeca API returned ${official.all.length} permit records, but none were identified as coffeeshops.`;else officialError='Amsterdam Horeca API is reachable, but the official exploitation-permit dataset currently contains no records.';}catch(error){officialError=error instanceof Error?error.message:String(error);}const fallback=await fetchOsmFallback();if(!fallback.length)throw new Error(`${officialError} OpenStreetMap fallback also returned zero cannabis-shop records. No candidates were imported.`);return{rows:fallback,source:'osm-fallback',sourceLabel:'Amsterdam · OpenStreetMap fallback',warning:`${officialError} Using supplemental OpenStreetMap cannabis-shop data instead.`};}
