type CandidateRow={name:string;streetAddress?:string;city?:string;region?:string;country:string;latitude?:number;longitude?:number;licenseNumber?:string;dataSource:string;sourceUrl:string;sourceLicense:string;imageryStatus:'unchecked'|'missing_coordinates'};
const SOURCE_URL='https://api.data.amsterdam.nl/v1/docs/datasets/horeca@v1.html';
const API_URL='https://api.data.amsterdam.nl/v1/horeca/v1/exploitatievergunning/';
function coord(v:any){const n=Number(v);return Number.isFinite(n)?n:undefined;}
function location(v:any){if(!v)return{};const c=v.coordinates??v.geometry?.coordinates;if(Array.isArray(c)&&c.length>=2){const longitude=coord(c[0]),latitude=coord(c[1]);if(latitude!==undefined&&longitude!==undefined&&Math.abs(latitude)<=90&&Math.abs(longitude)<=180)return{latitude,longitude};}return{latitude:coord(v.latitude??v.lat),longitude:coord(v.longitude??v.lng??v.lon)};}
function records(body:any):any[]{if(Array.isArray(body))return body;const embedded=body?._embedded;if(embedded&&typeof embedded==='object'){for(const value of Object.values(embedded))if(Array.isArray(value))return value as any[];}for(const key of ['results','data','items','exploitatievergunning'])if(Array.isArray(body?.[key]))return body[key];return[];}
function nextUrl(body:any){const next=body?._links?.next;return typeof next==='string'?next:next?.href||null;}
function requestHeaders(){const headers:Record<string,string>={Accept:'application/hal+json','User-Agent':'GeoWeedo/0.5 (https://geoweedo.com)'};const apiKey=process.env.AMSTERDAM_API_KEY?.trim();if(apiKey)headers['X-Api-Key']=apiKey;return headers;}
export async function fetchAmsterdamCoffeeshopCandidates():Promise<CandidateRow[]>{let url=API_URL;const all:any[]=[];for(let page=0;page<20&&url;page++){const response=await fetch(url,{headers:requestHeaders(),cache:'no-store',signal:AbortSignal.timeout(30000)});if(!response.ok){const detail=(await response.text().catch(()=>''))?.slice(0,220).replace(/\s+/g,' ').trim();throw new Error(`Amsterdam Horeca API returned ${response.status}${detail?`: ${detail}`:''}.`);}const body=await response.json();const pageRows=records(body);all.push(...pageRows);url=nextUrl(body);if(!url)break;}if(!all.length)throw new Error('Amsterdam Horeca API is reachable, but the official exploitation-permit dataset currently contains no records. No candidates were imported.');const shops=all.filter(r=>/coffeeshop/i.test([r.zaakCategorie,r.zaakSpecificatie,r.zaaknaam].filter(Boolean).join(' '))).filter(r=>!/ingetrokken|vervallen|geweigerd|beëindigd|beeindigd/i.test(String(r.statusVergunning||'')));if(!shops.length)throw new Error(`Amsterdam Horeca API returned ${all.length} permit records, but none were identified as coffeeshops. No candidates were imported.`);const unique=new Map<string,CandidateRow>();for(const r of shops){const geo=location(r.locatie);const row:CandidateRow={name:String(r.zaaknaam||'Amsterdam Coffeeshop').trim(),streetAddress:String(r.adres||'').trim()||undefined,city:'Amsterdam',region:'North Holland',country:'Netherlands',latitude:geo.latitude,longitude:geo.longitude,licenseNumber:r.zaaknummer!=null?String(r.zaaknummer):undefined,dataSource:'Amsterdam Horeca Exploitatievergunningen · Coffeeshops',sourceUrl:SOURCE_URL,sourceLicense:'Official public Gemeente Amsterdam horeca exploitation-permit data; records identified as coffeeshops.',imageryStatus:geo.latitude!==undefined&&geo.longitude!==undefined?'unchecked':'missing_coordinates'};const id=row.licenseNumber||`${row.name}|${row.streetAddress||''}`;if(!unique.has(id))unique.set(id,row);}return Array.from(unique.values());}
