import 'server-only';

type Row={name:string;streetAddress?:string;city?:string;region:string;country:string;latitude?:number;longitude?:number;website?:string;licenseNumber?:string;dataSource:string;sourceUrl:string;sourceLicense:string;imageryStatus:'unchecked'|'missing_coordinates'};
const SOURCE='https://data.ct.gov/d/4vi8-t7ex';
const API='https://data.ct.gov/resource/4vi8-t7ex.json?$limit=5000';
function clean(v:unknown){return String(v??'').replace(/\s+/g,' ').trim();}
function key(v:string){return v.toLowerCase().replace(/[^a-z0-9]/g,'');}
function normalize(raw:Record<string,unknown>){const out:Record<string,unknown>={};for(const [k,v] of Object.entries(raw||{}))out[key(k)]=v;return out;}
function pick(r:Record<string,unknown>,names:string[]){for(const name of names){const v=r[key(name)];if(v!==undefined&&v!==null&&clean(v))return clean(v);}return '';}
function num(v:unknown){const n=Number(v);return Number.isFinite(n)?n:undefined;}
function point(v:unknown){if(!v)return{};if(typeof v==='object'){const o=v as any;return{latitude:num(o.latitude??o.lat??o.coordinates?.[1]),longitude:num(o.longitude??o.lng??o.lon??o.coordinates?.[0])};}const m=clean(v).match(/POINT\s*\(\s*(-?\d+(?:\.\d+)?)\s+(-?\d+(?:\.\d+)?)\s*\)/i);return m?{longitude:Number(m[1]),latitude:Number(m[2])}:{};}
export async function fetchConnecticutCandidates():Promise<Row[]>{const response=await fetch(API,{headers:{Accept:'application/json','User-Agent':'GeoWeedo/0.8 (https://geoweedo.com)'},cache:'no-store',signal:AbortSignal.timeout(30000)});if(!response.ok)throw new Error(`Connecticut DCP retail-location dataset returned ${response.status}`);const body=await response.json();if(!Array.isArray(body)||!body.length)throw new Error('Connecticut DCP retail-location dataset returned no rows.');const rows:Row[]=[];for(const raw of body){const r=normalize(raw),type=pick(r,['type','Credential Type','License Type','Facility Type','Retailer Type']),joined=Object.values(r).map(clean).join(' | ');if(type&&!/hybrid retailer|medical marijuana.*dispensary|medical marijuana only|dispensary facility|retailer/i.test(type))continue;if(!type&&!/hybrid retailer|medical marijuana.*dispensary|medical marijuana only/i.test(joined))continue;const name=pick(r,['dba','DBA','Doing Business As','Trade Name','Facility Name','Business Name','Legal Business Name','Licensee Name','business','Name']);const streetAddress=pick(r,['street','Address','Street Address','Facility Address','Physical Address','Location Address']);const city=pick(r,['city','City','Town','Municipality']);const zip=pick(r,['zipcode','Zip','Zip Code','Postal Code']);const licenseNumber=pick(r,['license','Credential Number','License Number','Credential']);const website=pick(r,['website','Website','Business Website','URL']);const geo=point(r.location??r.geocodedcolumn??r.geocodedlocation??r.point),latitude=num(r.latitude)??geo.latitude,longitude=num(r.longitude)??geo.longitude;if(!name||!streetAddress||!city)continue;rows.push({name,streetAddress:zip&&!streetAddress.includes(zip)?`${streetAddress}, ${city}, CT ${zip}`:streetAddress,city,region:'Connecticut',country:'USA',latitude,longitude,website:website||undefined,licenseNumber:licenseNumber||undefined,dataSource:'Connecticut DCP Cannabis Retail Locations',sourceUrl:SOURCE,sourceLicense:'Official Connecticut Department of Consumer Protection open-data retail locations; medical marijuana dispensary and hybrid retailer locations only.',imageryStatus:Number.isFinite(latitude)&&Number.isFinite(longitude)?'unchecked':'missing_coordinates'});}const unique=new Map<string,Row>();for(const row of rows){const id=(row.licenseNumber||`${row.name}|${row.streetAddress}`).toLowerCase();if(!unique.has(id))unique.set(id,row);}if(!unique.size){const sample=body.slice(0,3).map((r:any)=>Object.keys(r).join(', ')).join(' ; ');throw new Error(`Connecticut DCP returned zero parseable retail locations. Sample fields: ${sample}`);}return Array.from(unique.values());}
