export type DelawareCandidate={name:string;streetAddress:string;city?:string;region:string;country:string;dataSource:string;sourceUrl:string;sourceLicense:string;imageryStatus:'missing_coordinates'};
const SOURCE_URL='https://omc.delaware.gov/dispensaries/';
function clean(value:string){return value.replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&#39;|&apos;/g,"'").replace(/&nbsp;/g,' ').replace(/\s+/g,' ').trim();}
function cityFromAddress(address:string){const m=address.match(/,\s*([^,]+),\s*DE\s+\d{5}(?:-\d{4})?\b/i);return m?.[1]?.trim();}
export async function fetchDelawareCandidates():Promise<DelawareCandidate[]>{
 const response=await fetch(SOURCE_URL,{headers:{Accept:'text/html,application/xhtml+xml','User-Agent':'GeoWeedo/0.7 (https://geoweedo.com)'},cache:'no-store',signal:AbortSignal.timeout(30000)});if(!response.ok)throw new Error(`Delaware OMC dispensary list returned ${response.status}`);const html=await response.text();const text=clean(html);
 const knownSection=text.match(/Dispensaries\s+Dispensaries provide[\s\S]*?Delaware Office of the Marijuana Commissioner/i)?.[0]||text;
 const addressRegex=/(\d{1,6}\s+[A-Za-z0-9][A-Za-z0-9 .#'&/-]{2,90}?,\s*[A-Za-z .'-]+,\s*DE\s+\d{5}(?:-\d{4})?)/gi;const matches:Array<{index:number;address:string}>=[];let m:RegExpExecArray|null;while((m=addressRegex.exec(knownSection))!==null)matches.push({index:m.index,address:m[1].trim()});
 if(!matches.length)throw new Error('Delaware OMC returned zero parseable dispensary addresses; refusing an unverified import.');
 const brandNames=['Best Buds (CannTech)','Columbia Care Delaware','Field Supply Cannabis & Provisions','Fresh Delaware','The Farm','Thrive Dispensary'];const rows:DelawareCandidate[]=[];
 for(const item of matches){const before=knownSection.slice(Math.max(0,item.index-180),item.index);let name='';for(const brand of brandNames){if(before.lastIndexOf(brand)>=0)name=brand;}if(!name){const parts=before.split(/\s{2,}|(?<=\.)\s+/).map(v=>v.trim()).filter(Boolean);name=parts[parts.length-1]||'';}if(!name||/Commissioner|Dispensaries provide/i.test(name))continue;rows.push({name,streetAddress:item.address,city:cityFromAddress(item.address),region:'Delaware',country:'USA',dataSource:'Delaware OMC Dispensaries',sourceUrl:SOURCE_URL,sourceLicense:'Official Delaware Office of the Marijuana Commissioner dispensary list; state-regulated dispensary storefronts serving medical patients and adult-use customers.',imageryStatus:'missing_coordinates'});}
 const unique=new Map<string,DelawareCandidate>();for(const row of rows){const id=`${row.name}|${row.streetAddress}`.toLowerCase();if(!unique.has(id))unique.set(id,row);}if(!unique.size)throw new Error('Delaware OMC dispensary page changed format; refusing an unverified import.');return Array.from(unique.values());
}
