export type MaineCandidate={name:string;streetAddress?:string;city?:string;region:string;country:string;licenseNumber?:string;dataSource:string;sourceUrl:string;sourceLicense:string;imageryStatus:'missing_coordinates'};
const SOURCE_URL='https://www.maine.gov/dafs/ocp/open-data/adult-use/licensee-search';
function parseCsv(text:string){const rows:string[][]=[];let row:string[]=[],field='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'){if(quoted&&text[i+1]==='"'){field+='"';i++;}else quoted=!quoted;}else if(ch===','&&!quoted){row.push(field);field='';}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(field);field='';if(row.some(v=>v.trim()))rows.push(row);row=[];}else field+=ch;}if(field||row.length){row.push(field);if(row.some(v=>v.trim()))rows.push(row);}return rows;}
function key(v:string){return v.toLowerCase().replace(/[^a-z0-9]/g,'');}
function decodeHref(value:string){return value.replace(/&amp;/g,'&').replace(/&#38;/g,'&');}
async function currentCsvUrl(){const response=await fetch(SOURCE_URL,{headers:{Accept:'text/html,application/xhtml+xml','User-Agent':'GeoWeedo/0.8 (https://geoweedo.com)'},cache:'no-store',signal:AbortSignal.timeout(30000)});if(!response.ok)throw new Error(`Maine OCP licensee page returned ${response.status}`);const html=await response.text();const re=/href=["']([^"']+\.csv(?:\?[^"']*)?)["']/gi;let match:RegExpExecArray|null;const urls:string[]=[];while((match=re.exec(html))!==null){const href=decodeHref(match[1]);if(/adult|use|license|applicant|establish/i.test(href))urls.push(new URL(href,SOURCE_URL).toString());}if(!urls.length)throw new Error('Maine OCP page exposed no downloadable adult-use CSV; refusing a stale import.');return urls[0];}
export async function fetchMaineCandidates():Promise<MaineCandidate[]>{
 const csvUrl=await currentCsvUrl();const response=await fetch(csvUrl,{headers:{Accept:'text/csv,*/*','User-Agent':'GeoWeedo/0.8 (https://geoweedo.com)'},cache:'no-store',signal:AbortSignal.timeout(30000)});if(!response.ok)throw new Error(`Maine OCP adult-use CSV returned ${response.status}`);const parsed=parseCsv((await response.text()).replace(/^\uFEFF/,''));if(parsed.length<2)throw new Error('Maine OCP adult-use CSV contained no records.');
 // Current OCP exports can include title/metadata rows before the actual column headings. Locate the header row instead of assuming row zero.
 let headerIndex=-1;for(let i=0;i<Math.min(parsed.length,25);i++){const ks=parsed[i].map(key);const hasType=ks.some(v=>/licensetype|establishmenttype|facilitytype|type/.test(v));const hasStatus=ks.some(v=>/licensestatus|status/.test(v));const hasName=ks.some(v=>/dba|doingbusinessas|establishmentname|businessname|entityname|licenseename/.test(v));if(hasType&&hasStatus&&hasName){headerIndex=i;break;}}
 if(headerIndex<0)throw new Error(`Maine OCP CSV schema was not recognized. First row: ${parsed[0].slice(0,8).join(' | ')}`);
 const headers=parsed[headerIndex].map(key);const get=(row:string[],names:string[])=>{for(const name of names){const i=headers.indexOf(key(name));if(i>=0&&row[i]?.trim())return row[i].trim();}return '';};const rows:MaineCandidate[]=[];
 for(const raw of parsed.slice(headerIndex+1)){const type=get(raw,['License Type','Establishment Type','Facility Type','Type']);const status=get(raw,['License Status','Status','Application Status']);if(!/retail/i.test(type)||!/active/i.test(status)||/inactive|expired|revoked|surrendered|denied|pending|conditional/i.test(status))continue;const name=get(raw,['DBA','Doing Business As','Establishment Name','Business Name','Entity Name','Licensee Name','Legal Name']);const streetAddress=get(raw,['Physical Address','Street Address','Establishment Address','Facility Address','Address','Address 1']);const city=get(raw,['Host Municipality','Municipality','City','Town','Facility City']);const licenseNumber=get(raw,['License Number','License #','License','Establishment License Number']);if(!name||!city)continue;rows.push({name,streetAddress:streetAddress||undefined,city,region:'Maine',country:'USA',licenseNumber:licenseNumber||undefined,dataSource:'Maine OCP Adult Use Applicant and Licensee Data',sourceUrl:SOURCE_URL,sourceLicense:'Official Maine Office of Cannabis Policy downloadable adult-use licensee data; active retail establishments only.',imageryStatus:'missing_coordinates'});}
 const unique=new Map<string,MaineCandidate>();for(const row of rows){const id=(row.licenseNumber||`${row.name}|${row.streetAddress||''}|${row.city||''}`).toLowerCase();if(!unique.has(id))unique.set(id,row);}if(!unique.size)throw new Error(`Maine OCP returned zero active retail records. Columns: ${parsed[headerIndex].slice(0,14).join(' | ')}`);return Array.from(unique.values());
}
