export type MaineCandidate={name:string;streetAddress?:string;city?:string;region:string;country:string;licenseNumber?:string;dataSource:string;sourceUrl:string;sourceLicense:string;imageryStatus:'missing_coordinates'};
const SOURCE_URL='https://www.maine.gov/dafs/ocp/open-data/adult-use/licensee-search';
const CSV_URL='https://www.maine.gov/dafs/ocp/sites/maine.gov.dafs.ocp/files/inline-files/Adult_Use_Establishments_And_Contacts_2026_07_01.csv';
function parseCsv(text:string){const rows:string[][]=[];let row:string[]=[],field='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'){if(quoted&&text[i+1]==='"'){field+='"';i++;}else quoted=!quoted;}else if(ch===','&&!quoted){row.push(field);field='';}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(field);field='';if(row.some(v=>v.trim()))rows.push(row);row=[];}else field+=ch;}if(field||row.length){row.push(field);if(row.some(v=>v.trim()))rows.push(row);}return rows;}
function key(v:string){return v.toLowerCase().replace(/[^a-z0-9]/g,'');}
export async function fetchMaineCandidates():Promise<MaineCandidate[]>{
 const response=await fetch(CSV_URL,{headers:{Accept:'text/csv,*/*','User-Agent':'GeoWeedo/0.7 (https://geoweedo.com)'},cache:'no-store',signal:AbortSignal.timeout(30000)});if(!response.ok)throw new Error(`Maine OCP adult-use CSV returned ${response.status}`);const parsed=parseCsv(await response.text());if(parsed.length<2)throw new Error('Maine OCP adult-use CSV contained no records.');const headers=parsed[0].map(key);const get=(row:string[],names:string[])=>{for(const name of names){const i=headers.indexOf(key(name));if(i>=0&&row[i]?.trim())return row[i].trim();}return '';};const rows:MaineCandidate[]=[];
 for(const raw of parsed.slice(1)){const type=get(raw,['License Type','Establishment Type','Type']);const status=get(raw,['License Status','Status']);if(!/retail\s*store/i.test(type)||!/^active$/i.test(status))continue;const name=get(raw,['DBA','Doing Business As','Establishment Name','Business Name','Entity Name','Licensee Name']);const streetAddress=get(raw,['Physical Address','Street Address','Establishment Address','Address']);const city=get(raw,['Host Municipality','Municipality','City','Town']);const licenseNumber=get(raw,['License Number','License #','License']);if(!name||!city)continue;rows.push({name,streetAddress:streetAddress||undefined,city,region:'Maine',country:'USA',licenseNumber:licenseNumber||undefined,dataSource:'Maine OCP Adult Use Applicant and Licensee Data',sourceUrl:SOURCE_URL,sourceLicense:'Official Maine Office of Cannabis Policy downloadable adult-use licensee data; Active Retail Store establishments only.',imageryStatus:'missing_coordinates'});}
 const unique=new Map<string,MaineCandidate>();for(const row of rows){const id=(row.licenseNumber||`${row.name}|${row.streetAddress||''}|${row.city||''}`).toLowerCase();if(!unique.has(id))unique.set(id,row);}if(!unique.size)throw new Error('Maine OCP returned zero Active Retail Store records; refusing an unverified import.');return Array.from(unique.values());
}
