export type MarylandCandidate={name:string;streetAddress:string;city?:string;region:string;country:string;dataSource:string;sourceUrl:string;sourceLicense:string;imageryStatus:'missing_coordinates'};
const SOURCE_URL='https://cannabis.maryland.gov/Pages/Dispensary-Locator.aspx';
function clean(value:string){return value.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&#39;|&apos;/g,"'").replace(/&nbsp;/g,' ').replace(/\s+/g,' ').trim();}
function cityFromAddress(address:string){const m=address.match(/\b([A-Za-z][A-Za-z .'-]+)\s+Maryland\s+\d{5}\b/i);return m?.[1]?.trim();}
export async function fetchMarylandCandidates():Promise<MarylandCandidate[]>{
 const response=await fetch(SOURCE_URL,{headers:{Accept:'text/html,application/xhtml+xml','User-Agent':'GeoWeedo/0.7 (https://geoweedo.com)'},cache:'no-store',signal:AbortSignal.timeout(30000)});if(!response.ok)throw new Error(`Maryland MCA dispensary locator returned ${response.status}`);const html=await response.text();const rows:MarylandCandidate[]=[];const tr=/<tr[^>]*>([\s\S]*?)<\/tr>/gi;let m:RegExpExecArray|null;
 while((m=tr.exec(html))!==null){const cells:string[]=[];const td=/<t[dh][^>]*>([\s\S]*?)<\/t[dh]>/gi;let c:RegExpExecArray|null;while((c=td.exec(m[1]))!==null)cells.push(clean(c[1]));if(cells.length<2)continue;const name=cells[0];const address=cells.find(v=>/\bMaryland\s+\d{5}\b/i.test(v))||'';if(!name||!address||/delivery\s*only/i.test(name)||/^NA$/i.test(address))continue;rows.push({name,streetAddress:address,city:cityFromAddress(address),region:'Maryland',country:'USA',dataSource:'Maryland MCA Dispensary Locator',sourceUrl:SOURCE_URL,sourceLicense:'Official Maryland Cannabis Administration licensed dispensary locator; physical licensed dispensaries only, excluding delivery-only entries.',imageryStatus:'missing_coordinates'});}
 const unique=new Map<string,MarylandCandidate>();for(const row of rows){const id=`${row.name}|${row.streetAddress}`.toLowerCase();if(!unique.has(id))unique.set(id,row);}if(!unique.size)throw new Error('Maryland MCA returned zero parseable physical dispensaries; refusing an unverified import.');return Array.from(unique.values());
}
