import 'server-only';
import { PDFParse } from 'pdf-parse';

type Row={name:string;streetAddress:string;city?:string;region:string;country:string;licenseNumber?:string;dataSource:string;sourceUrl:string;sourceLicense:string;imageryStatus:'missing_coordinates'};
type Dataset={module:'Adult_Use'|'Licenses';tab:'Adult_Use'|'Licenses';label:string;accept:(type:string,license:string)=>boolean};
type DownloadAction={kind:'post'|'get'|'submit';target?:string;argument?:string;href?:string;name?:string;value?:string};

const SOURCE='https://www.michigan.gov/cra/verify-a-license-1';
const HOSTS=['https://aca3.accela.com','https://aca-prod.accela.com'];
const ANNUAL_REPORT='https://www.michigan.gov/lara/-/media/Project/Websites/lara/about/Legislative-Reports/Boilerplate-Required-Reports/FY2026/Section-601-and-602-Annual-Statistical-Report---CRA.pdf?rev=5c9267627d534eae999d4121ceb55b40';
const DATASETS:Dataset[]=[
 {module:'Adult_Use',tab:'Adult_Use',label:'adult-use establishments',accept:(type,license)=>(/mari(?:j|h)uana\s+retailer/i.test(type)||/cannabis\s+retailer/i.test(type)||/^AU-R-/i.test(license))},
 {module:'Licenses',tab:'Licenses',label:'medical marijuana facilities',accept:(type)=>/provisioning\s+center/i.test(type)},
];

function clean(value:unknown){return String(value??'').replace(/&amp;/g,'&').replace(/&#39;|&apos;|&#x27;/g,"'").replace(/&quot;/g,'"').replace(/&nbsp;/g,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();}
function key(value:string){return value.toLowerCase().replace(/[^a-z0-9]/g,'');}
function decodeHtml(value:string){return value.replace(/&amp;/g,'&').replace(/&#39;|&apos;|&#x27;/g,"'").replace(/&quot;/g,'"').replace(/&#x2F;/g,'/');}
function pick(row:Record<string,string>,names:string[]){for(const name of names){const value=row[key(name)];if(value)return clean(value);}return '';}
function parseAddress(value:string){const address=clean(value);const match=address.match(/^(.*?)(?:,\s*|\s+)([A-Za-z .'-]{2,60}),?\s+MI\s+(\d{5}(?:-\d{4})?)(?:\s+United States)?$/i);return{streetAddress:address,city:match?.[2]?.trim()};}
function isHtml(text:string,contentType:string|null){return /^\s*</.test(text)||/text\/html|application\/xhtml/i.test(contentType||'');}

function cookiesFrom(response:Response){const headers=response.headers as Headers&{getSetCookie?:()=>string[]};const raw=headers.getSetCookie?.()??(response.headers.get('set-cookie')?[response.headers.get('set-cookie')!]:[]);return raw.map(item=>item.split(';',1)[0]).filter(Boolean);}
function mergeCookies(current:string[],response:Response){const map=new Map(current.map(item=>[item.split('=',1)[0],item]));for(const item of cookiesFrom(response))map.set(item.split('=',1)[0],item);return Array.from(map.values());}
function hiddenFields(html:string){const values=new URLSearchParams();const input=/<input\b[^>]*>/gi;let match:RegExpExecArray|null;while((match=input.exec(html))!==null){const tag=match[0];const type=tag.match(/\btype=["']?([^"'\s>]+)/i)?.[1]?.toLowerCase()||'';if(type&&type!=='hidden')continue;const name=decodeHtml(tag.match(/\bname=["']([^"']+)["']/i)?.[1]||'');if(!name)continue;const value=decodeHtml(tag.match(/\bvalue=["']([^"']*)["']/i)?.[1]||'');values.set(name,value);}return values;}
function searchButton(html:string){const tags=html.match(/<button\b[^>]*>[\s\S]*?<\/button>|<input\b[^>]*>/gi)||[];for(const tag of tags){const label=clean(tag.match(/\bvalue=["']([^"']*)["']/i)?.[1]||tag);if(!/^search$/i.test(label)&&!/search all records/i.test(label))continue;const name=decodeHtml(tag.match(/\bname=["']([^"']+)["']/i)?.[1]||'');const value=decodeHtml(tag.match(/\bvalue=["']([^"']*)["']/i)?.[1]||'Search');if(name)return{name,value};}return{name:'ctl00$PlaceHolderMain$btnNewSearch',value:'Search'};}
function downloadAction(html:string):DownloadAction|null{const elements=html.match(/<a\b[^>]*>[\s\S]*?<\/a>|<button\b[^>]*>[\s\S]*?<\/button>|<input\b[^>]*>/gi)||[];for(const element of elements){const value=decodeHtml(element.match(/\bvalue=["']([^"']*)["']/i)?.[1]||'');const label=clean(value||element);if(!/download\s+results|export\s+results/i.test(label))continue;const href=decodeHtml(element.match(/\bhref=["']([^"']+)["']/i)?.[1]||'');const onclick=decodeHtml(element.match(/\bonclick=["']([^"']+)["']/i)?.[1]||'');const script=`${href} ${onclick}`;const post=script.match(/__doPostBack\(['"]([^'"]+)['"],\s*['"]([^'"]*)['"]\)/i);if(post)return{kind:'post',target:post[1],argument:post[2]};if(href&&!/^javascript:/i.test(href))return{kind:'get',href};const name=decodeHtml(element.match(/\bname=["']([^"']+)["']/i)?.[1]||'');if(name)return{kind:'submit',name,value:value||'Download results'};}const scriptPost=html.match(/__doPostBack\(['"]([^'"]*(?:download|export)[^'"]*)['"],\s*['"]([^'"]*)['"]\)/i);if(scriptPost)return{kind:'post',target:scriptPost[1],argument:scriptPost[2]};return null;}
function generatedDownloadUrl(html:string,base:string){const candidates:string[]=[];for(const re of [/\bhref=["']([^"']+)["']/gi,/\b(?:location(?:\.href)?|window\.open)\s*(?:=|\()\s*["']([^"']+)["']/gi,/<meta[^>]+http-equiv=["']refresh["'][^>]+content=["'][^;]+;\s*url=([^"']+)["']/gi]){let m:RegExpExecArray|null;while((m=re.exec(html))!==null)candidates.push(decodeHtml(m[1]));}for(const candidate of candidates){if(/download|export|report|\.csv(?:\?|$)|\.txt(?:\?|$)|\.xls(?:x)?(?:\?|$)/i.test(candidate)&&!/^javascript:/i.test(candidate)){try{return new URL(candidate,base).toString();}catch{}}}return null;}
function parseCsv(csv:string){const records:string[][]=[];let row:string[]=[],cell='',quoted=false;const text=csv.replace(/^\uFEFF/,'');for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;continue;}if(ch===','&&!quoted){row.push(cell.trim());cell='';continue;}if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(cell.trim());cell='';if(row.some(value=>value))records.push(row);row=[];continue;}cell+=ch;}row.push(cell.trim());if(row.some(value=>value))records.push(row);if(records.length<2)return[];const headers=records[0].map(key);return records.slice(1).map(cells=>{const out:Record<string,string>={};headers.forEach((header,index)=>{out[header]=cells[index]??'';});return out;});}

async function request(url:string,init:RequestInit,cookies:string[]){const headers=new Headers(init.headers);headers.set('User-Agent','Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36');headers.set('Accept-Language','en-US,en;q=0.9');if(cookies.length)headers.set('Cookie',cookies.join('; '));return fetch(url,{...init,headers,cache:'no-store',redirect:'follow',signal:AbortSignal.timeout(45000)});}
async function performAction(action:DownloadAction,html:string,url:string,host:string,cookies:string[]){if(action.kind==='get')return request(new URL(action.href!,url).toString(),{headers:{Accept:'text/csv,application/csv,text/plain,application/octet-stream,*/*',Referer:url}},cookies);const fields=hiddenFields(html);if(action.kind==='post'){fields.set('__EVENTTARGET',action.target||'');fields.set('__EVENTARGUMENT',action.argument||'');}else{fields.delete('__EVENTTARGET');fields.delete('__EVENTARGUMENT');fields.set(action.name||'',action.value||'Download results');}return request(url,{method:'POST',headers:{Accept:'text/csv,application/csv,text/plain,application/octet-stream,*/*','Content-Type':'application/x-www-form-urlencoded',Origin:host,Referer:url},body:fields.toString()},cookies);}
async function resolveCsvResponse(response:Response,url:string,host:string,cookies:string[],label:string){cookies.splice(0,cookies.length,...mergeCookies(cookies,response));if(!response.ok)throw new Error(`${label} Download results returned ${response.status}`);let body=await response.text();let contentType=response.headers.get('content-type');if(!isHtml(body,contentType)){const rows=parseCsv(body);if(!rows.length)throw new Error(`${label} export contained no parseable records`);return rows;}for(let hop=0;hop<4;hop++){const direct=generatedDownloadUrl(body,url);if(direct){const next=await request(direct,{headers:{Accept:'text/csv,application/csv,text/plain,application/octet-stream,*/*',Referer:url}},cookies);cookies.splice(0,cookies.length,...mergeCookies(cookies,next));if(!next.ok)throw new Error(`${label} generated export URL returned ${next.status}`);body=await next.text();contentType=next.headers.get('content-type');if(!isHtml(body,contentType)){const rows=parseCsv(body);if(rows.length)return rows;}continue;}const nested=downloadAction(body);if(nested){const next=await performAction(nested,body,url,host,cookies);cookies.splice(0,cookies.length,...mergeCookies(cookies,next));if(!next.ok)throw new Error(`${label} nested Download results returned ${next.status}`);body=await next.text();contentType=next.headers.get('content-type');if(!isHtml(body,contentType)){const rows=parseCsv(body);if(rows.length)return rows;}continue;}break;}const title=clean(body.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]||'').slice(0,100);throw new Error(`${label} Download results remained HTML after following Accela export redirects${title?` (${title})`:''}`);}
async function downloadDataset(host:string,dataset:Dataset){const url=`${host}/MIMM/Cap/CapHome.aspx?TabName=${dataset.tab}&module=${dataset.module}`;let cookies:string[]=[];const initial=await request(url,{headers:{Accept:'text/html,application/xhtml+xml'}},cookies);cookies=mergeCookies(cookies,initial);if(!initial.ok)throw new Error(`${dataset.label} initial Accela page returned ${initial.status}`);const initialHtml=await initial.text();if(!/__VIEWSTATE|ACA_CS_FIELD/i.test(initialHtml))throw new Error(`${dataset.label} Accela page did not expose a searchable public form`);const form=hiddenFields(initialHtml),button=searchButton(initialHtml);form.set(button.name,button.value);form.set('ctl00$PlaceHolderMain$ddlSearchType',form.get('ctl00$PlaceHolderMain$ddlSearchType')||'0');const search=await request(url,{method:'POST',headers:{Accept:'text/html,application/xhtml+xml','Content-Type':'application/x-www-form-urlencoded',Origin:host,Referer:url},body:form.toString()},cookies);cookies=mergeCookies(cookies,search);if(!search.ok)throw new Error(`${dataset.label} blank Accela search returned ${search.status}`);const searchHtml=await search.text();const action=downloadAction(searchHtml);if(!action)throw new Error(`${dataset.label} blank Accela search returned no recognizable Download results control`);const download=await performAction(action,searchHtml,url,host,cookies);return resolveCsvResponse(download,url,host,cookies,dataset.label);}
async function officialDownload(dataset:Dataset){const errors:string[]=[];for(const host of HOSTS){try{return await downloadDataset(host,dataset);}catch(error){errors.push(`${new URL(host).host}: ${error instanceof Error?error.message:String(error)}`);}}throw new Error(errors.join(' ; '));}

function rowsFromCsv(dataset:Dataset,records:Record<string,string>[]):Row[]{const rows:Row[]=[];for(const record of records){const status=pick(record,['Status','Record Status','License Status']);if(status&&!/^active$/i.test(status))continue;const licenseNumber=pick(record,['Record Number','License Number','License #','Record #']);const recordType=pick(record,['Record Type','License Type','Type']);if(!dataset.accept(recordType,licenseNumber))continue;const name=pick(record,['Doing Business As (DBA) Name','DBA Name','Licensee Name','License Name','Business Name','Name']);const address=pick(record,['Address','Street Address','Facility Address','Physical Address']);if(!name||!address||!licenseNumber)continue;const parsed=parseAddress(address);rows.push({name,streetAddress:parsed.streetAddress,city:parsed.city,region:'Michigan',country:'USA',licenseNumber,dataSource:'Michigan CRA Verify a License database export',sourceUrl:SOURCE,sourceLicense:'Official Michigan Cannabis Regulatory Agency Verify a License database export; Active adult-use Marijuana/Cannabis Retailer and medical Provisioning Center license records only.',imageryStatus:'missing_coordinates'});}return rows;}

function findAddress(segment:string){const location=segment.match(/,\s*([A-Za-z .'-]{2,60}),\s*MI\s+(\d{5}(?:-\d{4})?)/i);if(!location||location.index===undefined)return null;const end=location.index+location[0].length;const prefix=segment.slice(0,end);const starts:Array<{index:number;address:string}> = [];const re=/\b\d{1,6}\s+/g;let match:RegExpExecArray|null;while((match=re.exec(prefix))!==null){const candidate=prefix.slice(match.index,end);if(/\b(?:ST|STREET|RD|ROAD|AVE|AVENUE|DR|DRIVE|BLVD|BOULEVARD|HWY|HIGHWAY|CT|COURT|LN|LANE|WAY|PKWY|PARKWAY|PL|PLACE|TRL|TRAIL|CIR|CIRCLE|M[- ]?\d+|US[- ]?\d+)\b/i.test(candidate))starts.push({index:match.index,address:candidate});}const chosen=starts.at(-1);if(!chosen)return null;return{index:chosen.index,address:clean(chosen.address)};}
function parseAnnualText(text:string):Row[]{const normalized=clean(text);const rows:Row[]=[];const idRe=/\b(AU-R-\d{6}|PC-\d{6})\b/g;let match:RegExpExecArray|null;while((match=idRe.exec(normalized))!==null){const licenseNumber=match[1];const start=match.index+licenseNumber.length;const tail=normalized.slice(start,start+360);const nextLicense=tail.search(/\b(?:AU-[A-Z-]+|PC|GR-[A-Z]|PR|SC|ST|SA)-\d{6}\b/i);const segment=clean(nextLicense>0?tail.slice(0,nextLicense):tail);const addressInfo=findAddress(segment);if(!addressInfo)continue;let name=clean(segment.slice(0,addressInfo.index)).replace(/^(?:Marihuana|Marijuana|Cannabis) Retailer\s+/i,'').replace(/^Provisioning Center\s+/i,'');if(!name||name.length>160)continue;const parsed=parseAddress(addressInfo.address);if(!parsed.city)continue;rows.push({name,streetAddress:parsed.streetAddress,city:parsed.city,region:'Michigan',country:'USA',licenseNumber,dataSource:'Michigan CRA FY2025 Annual Statistical Report',sourceUrl:ANNUAL_REPORT,sourceLicense:'Official Michigan Cannabis Regulatory Agency annual report; registered names and addresses of licensed MMFL facilities and adult-use establishments as of September 30, 2025. Used as a verified fallback when the live Accela export is unavailable.',imageryStatus:'missing_coordinates'});}return rows;}
async function annualReportFallback(){let parser:PDFParse|undefined;try{parser=new PDFParse({url:ANNUAL_REPORT});const result=await parser.getText();const rows=parseAnnualText(result.text);if(!rows.length)throw new Error('annual report parsed but yielded zero retailer/provisioning-center rows');return rows;}finally{if(parser)await parser.destroy();}}
function dedupe(rows:Row[]){const unique=new Map<string,Row>();for(const row of rows){const id=row.licenseNumber?.toLowerCase();if(id&&!unique.has(id))unique.set(id,row);}return Array.from(unique.values());}

export async function fetchMichiganCandidates():Promise<Row[]>{const results=await Promise.allSettled(DATASETS.map(dataset=>officialDownload(dataset)));const rows:Row[]=[];const failures:string[]=[];for(let index=0;index<DATASETS.length;index++){const result=results[index];if(result.status==='fulfilled')rows.push(...rowsFromCsv(DATASETS[index],result.value));else failures.push(`${DATASETS[index].label}: ${result.reason instanceof Error?result.reason.message:String(result.reason)}`);}if(failures.length){try{rows.push(...await annualReportFallback());}catch(error){throw new Error(`Michigan CRA live Accela export failed and the verified CRA annual-report fallback also failed. Accela: ${failures.join(' | ')} | Annual report: ${error instanceof Error?error.message:String(error)}`);}}const unique=dedupe(rows);if(!unique.length)throw new Error('Michigan CRA official sources yielded zero Marijuana/Cannabis Retailer or Provisioning Center records; refusing an unverified import.');return unique;}
