import 'server-only';
import 'pdf-parse/worker';
import { PDFParse } from 'pdf-parse';

type Row={name:string;streetAddress:string;city?:string;region:string;country:string;licenseNumber?:string;dataSource:string;sourceUrl:string;sourceLicense:string;imageryStatus:'missing_coordinates'};
const REPORT_ROOT='https://www.michigan.gov/cra/resources/cannabis-regulatory-agency-licensing-reports/adult-use-marijuana-licensing-report';
const REPORT_PAGE=`${REPORT_ROOT}/2026-adult-use-marijuana-licensing-reports`;
function clean(s:string){return s.replace(/\s+/g,' ').trim();}
function decode(s:string){return s.replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'");}
function headers(){return{Accept:'text/html,application/xhtml+xml,application/pdf;q=0.9,*/*;q=0.8','User-Agent':'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/124 Safari/537.36','Accept-Language':'en-US,en;q=0.9'};}
async function getHtml(url:string){const r=await fetch(url,{headers:headers(),cache:'no-store',signal:AbortSignal.timeout(30000)});if(!r.ok)return '';return r.text();}
function pdfLinks(html:string){const links:string[]=[];const re=/href=["']([^"']+\.pdf[^"']*)["']/gi;let m:RegExpExecArray|null;while((m=re.exec(html))!==null){const href=decode(m[1]);if(/Licensing-Report|Adult-Use|marihuana|marijuana/i.test(href))links.push(href.startsWith('http')?href:new URL(href,'https://www.michigan.gov').toString());}return links;}
async function parsePdf(href:string):Promise<Row[]>{const response=await fetch(href,{headers:headers(),cache:'no-store',signal:AbortSignal.timeout(30000)});if(!response.ok)return[];const parser=new PDFParse({data:Buffer.from(await response.arrayBuffer())});try{const result=await parser.getText();const text=result.text||'';const rows:Row[]=[];const re=/([^\n]{2,120})\n(AU-R-\d{6})[\s\S]{0,180}?Marihuana Retailer[^\n]*\n([^\n]{3,140})\n([^\n,]{2,60}),\s*MI\s*(\d{5})/gi;let m:RegExpExecArray|null;while((m=re.exec(text))!==null){const name=clean(m[1]),streetAddress=clean(`${m[3]}, ${m[4]}, MI ${m[5]}`);if(name&&/\d/.test(streetAddress))rows.push({name,streetAddress,city:clean(m[4]),region:'Michigan',country:'USA',licenseNumber:m[2].toUpperCase(),dataSource:'Michigan CRA Adult-Use Licensing Reports',sourceUrl:REPORT_ROOT,sourceLicense:'Official Michigan Cannabis Regulatory Agency adult-use licensing reports; Marihuana Retailer licenses only.',imageryStatus:'missing_coordinates'});}return rows;}finally{await parser.destroy();}}
export async function fetchMichiganCandidates():Promise<Row[]>{
 // Michigan documents that the complete licensee database is available through Verify a License. Its search UI is JS-backed and may block server requests, so use the public licensing-report pages as the machine-readable official fallback.
 const pages=[REPORT_PAGE,REPORT_ROOT];const links:string[]=[];for(const page of pages){const html=await getHtml(page);for(const href of pdfLinks(html))if(!links.includes(href))links.push(href);}if(!links.length)throw new Error('Michigan CRA public pages exposed no reachable adult-use licensing report PDFs; Verify a License remains the authoritative source but its download endpoint must be discovered before importing.');
 const all:Row[]=[];for(const href of links.slice(0,12)){const rows=await parsePdf(href);all.push(...rows);if(rows.length)break;}const unique=new Map<string,Row>();for(const row of all)unique.set(row.licenseNumber||`${row.name}|${row.streetAddress}`,row);if(!unique.size)throw new Error('Michigan CRA official reports contained no parseable Marihuana Retailer rows; refusing an unverified import.');return Array.from(unique.values());
}
