import 'server-only';

type Row={name:string;streetAddress:string;city?:string;region:string;country:string;latitude?:number;longitude?:number;website?:string;licenseNumber?:string;dataSource:string;sourceUrl:string;sourceLicense:string;imageryStatus:'unchecked'|'missing_coordinates'};
const SOURCE='https://www.michigan.gov/cra/verify-a-license-1';
const APP_ID='cd5a1a76daaf470b823a382691c0ff60';
function clean(v:unknown){return String(v??'').replace(/\s+/g,' ').trim();}
function key(v:string){return v.toLowerCase().replace(/[^a-z0-9]/g,'');}
function normalized(raw:Record<string,unknown>){const out:Record<string,unknown>={};for(const [k,v] of Object.entries(raw||{}))out[key(k)]=v;return out;}
function pick(r:Record<string,unknown>,names:string[]){for(const n of names){const v=r[key(n)];if(v!==undefined&&v!==null&&clean(v))return clean(v);}return '';}
async function json(url:string){const r=await fetch(url,{headers:{Accept:'application/json','User-Agent':'GeoWeedo/0.8 (https://geoweedo.com)'},cache:'no-store',signal:AbortSignal.timeout(30000)});if(!r.ok)throw new Error(`Michigan CRA map source returned ${r.status}`);return r.json();}
function collect(value:unknown,services:Set<string>,ids:Set<string>){if(typeof value==='string'){const service=value.match(/https:\/\/[^"'\s]+\/FeatureServer(?:\/\d+)?/i)?.[0];if(service)services.add(service.replace(/\\u002F/g,'/'));if(/^[0-9a-f]{32}$/i.test(value))ids.add(value);return;}if(Array.isArray(value)){for(const v of value)collect(v,services,ids);return;}if(value&&typeof value==='object')for(const v of Object.values(value as Record<string,unknown>))collect(v,services,ids);}
async function discoverServices(){const services=new Set<string>(),seen=new Set<string>(),queue=[APP_ID];while(queue.length&&seen.size<30){const id=queue.shift()!;if(seen.has(id))continue;seen.add(id);let data:any;try{data=await json(`https://www.arcgis.com/sharing/rest/content/items/${id}/data?f=json`);}catch{continue;}const ids=new Set<string>();collect(data,services,ids);for(const next of Array.from(ids))if(!seen.has(next)&&!queue.includes(next))queue.push(next);}return Array.from(services);}
async function layerUrls(service:string){if(/\/FeatureServer\/\d+$/i.test(service))return[service];try{const meta:any=await json(`${service}?f=json`);const layers=Array.isArray(meta?.layers)?meta.layers:[];return layers.map((l:any)=>`${service}/${l.id}`);}catch{return[];}}
function parseAddress(value:string){const text=clean(value);const m=text.match(/^(.*?)(?:,\s*|\s+)([A-Za-z .'-]{2,60}),?\s+MI\s+(\d{5}(?:-\d{4})?)$/i);return{text,city:m?.[2]?.trim()};}
export async function fetchMichiganCandidates():Promise<Row[]>{const services=await discoverServices();if(!services.length)throw new Error('Michigan CRA official Find a Facility map exposed no public ArcGIS feature services.');const rows:Row[]=[];for(const service of services.slice(0,20)){for(const layer of (await layerUrls(service)).slice(0,20)){let body:any;try{body=await json(`${layer}/query?where=1%3D1&outFields=*&returnGeometry=true&outSR=4326&f=json&resultRecordCount=2000`);}catch{continue;}for(const feature of Array.isArray(body?.features)?body.features:[]){const a=normalized(feature?.attributes||{}),joined=Object.values(a).map(clean).join(' | '),licenseNumber=pick(a,['License Number','LicenseNumber','License','Credential Number']),businessType=pick(a,['Business Type','License Type','Facility Type','Type']);const retailer=/retailer|provisioning\s*center/i.test(`${businessType} ${joined}`)||/^AU-R-/i.test(licenseNumber);if(!retailer)continue;if(!/retailer|provisioning\s*center/i.test(`${businessType} ${joined}`)&&!/AU-R-/i.test(licenseNumber))continue;const name=pick(a,['Business Name','DBA','Trade Name','Facility Name','Licensee Name','Name']);const address=pick(a,['Address','Facility Address','Physical Address','Street Address','Location Address']);if(!name||!address)continue;const parsed=parseAddress(address),geometry=feature?.geometry||{},latitude=Number(geometry.y),longitude=Number(geometry.x),hasCoords=Number.isFinite(latitude)&&Number.isFinite(longitude);rows.push({name,streetAddress:parsed.text,city:pick(a,['City','Municipality'])||parsed.city,region:'Michigan',country:'USA',latitude:hasCoords?latitude:undefined,longitude:hasCoords?longitude:undefined,website:pick(a,['Website','Business Website','URL'])||undefined,licenseNumber:licenseNumber||undefined,dataSource:'Michigan CRA Active Facilities Map',sourceUrl:SOURCE,sourceLicense:'Official Michigan Cannabis Regulatory Agency Find a Facility map; adult-use retailer/provisioning-center locations only.',imageryStatus:hasCoords?'unchecked':'missing_coordinates'});}}}const unique=new Map<string,Row>();for(const row of rows){const id=(row.licenseNumber||`${row.name}|${row.streetAddress}`).toLowerCase();if(!unique.has(id))unique.set(id,row);}if(!unique.size)throw new Error(`Michigan CRA official facility map yielded zero retailer locations from ${services.length} discovered service(s); refusing an unverified import.`);return Array.from(unique.values());}
