import 'server-only';
import { inflateRawSync } from 'node:zlib';
type Row={name:string;streetAddress?:string;city?:string;region:string;country:string;licenseNumber?:string;dataSource:string;sourceUrl:string;sourceLicense:string;imageryStatus:'missing_coordinates'};
const PAGE='https://mn.gov/ocm/data-reports/application-data/';
function clean(s:string){return s.replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\s+/g,' ').trim();}
function entries(buf:Buffer){const out=new Map<string,Buffer>();let p=0;while(p+30<buf.length){if(buf.readUInt32LE(p)!==0x04034b50){p++;continue;}const method=buf.readUInt16LE(p+8),size=buf.readUInt32LE(p+18),nameLen=buf.readUInt16LE(p+26),extraLen=buf.readUInt16LE(p+28);const name=buf.subarray(p+30,p+30+nameLen).toString();const start=p+30+nameLen+extraLen;if(size===0&&method!==0){p=start;continue;}const raw=buf.subarray(start,start+size);try{out.set(name,method===8?inflateRawSync(raw):raw);}catch{}p=start+size;}return out;}
function xlsxRows(buf:Buffer){const files=entries(buf),shared=(files.get('xl/sharedStrings.xml')?.toString().match(/<si[\s\S]*?<\/si>/g)||[]).map(v=>clean(Array.from(v.matchAll(/<t[^>]*>([\s\S]*?)<\/t>/g)).map(m=>m[1]).join('')));const sheet=files.get('xl/worksheets/sheet1.xml')?.toString();if(!sheet)throw new Error('Minnesota OCM workbook did not contain sheet1.xml.');const rows:string[][]=[];for(const rm of sheet.matchAll(/<row[^>]*>([\s\S]*?)<\/row>/g)){const row:string[]=[];for(const cm of rm[1].matchAll(/<c[^>]*?(?:t="([^"]+)")?[^>]*>([\s\S]*?)<\/c>/g)){const type=cm[1],body=cm[2],v=body.match(/<v>([\s\S]*?)<\/v>/)?.[1]??body.match(/<t[^>]*>([\s\S]*?)<\/t>/)?.[1]??'';row.push(clean(type==='s'?shared[Number(v)]||'':v));}rows.push(row);}return rows;}
function key(s:string){return s.toLowerCase().replace(/[^a-z0-9]/g,'');}
export async function fetchMinnesotaCandidates():Promise<Row[]>{const page=await fetch(PAGE,{headers:{'User-Agent':'GeoWeedo/0.7 (https://geoweedo.com)'},cache:'no-store',signal:AbortSignal.timeout(30000)});if(!page.ok)throw new Error(`Minnesota OCM data page returned ${page.status}`);const html=await page.text();const match=html.match(/href=["']([^"']*MN_OCM_licensed_businesses_[^"']*\.xlsx)["']/i);if(!match)throw new Error('Minnesota OCM public license-holder workbook link was not found.');const url=new URL(match[1],PAGE).toString();const response=await fetch(url,{headers:{'User-Agent':'GeoWeedo/0.7 (https://geoweedo.com)'},cache:'no-store',signal:AbortSignal.timeout(30000)});if(!response.ok)throw new Error(`Minnesota OCM workbook returned ${response.status}`);const table=xlsxRows(Buffer.from(await response.arrayBuffer()));if(table.length<2)throw new Error('Minnesota OCM workbook was empty.');const headers=table[0].map(key);const col=(names:string[])=>{for(const n of names){const i=headers.indexOf(key(n));if(i>=0)return i;}return -1;};const typeI=col(['license type','licensetype']),nameI=col(['business name','legal business name','businessname','dba']),licenseI=col(['license number','licensenumber']),addressI=col(['business address','site address','physical address','address']),cityI=col(['city']),statusI=col(['license status','status']);const rows:Row[]=[];for(const r of table.slice(1)){const type=r[typeI]||'',status=statusI>=0?r[statusI]||'':'';if(!/cannabis retailer/i.test(type)||/denied|expired|revoked|withdrawn|preliminar/i.test(status))continue;const name=r[nameI]||'',licenseNumber=licenseI>=0?r[licenseI]:undefined,streetAddress=addressI>=0?r[addressI]:undefined,city=cityI>=0?r[cityI]:undefined;if(!name)continue;rows.push({name,streetAddress,city,region:'Minnesota',country:'USA',licenseNumber,dataSource:'Minnesota OCM Public License Holder Data',sourceUrl:PAGE,sourceLicense:'Official Minnesota Office of Cannabis Management public license-holder workbook; Cannabis Retailer license holders only, excluding preliminary/non-issued statuses.',imageryStatus:'missing_coordinates'});}const unique=new Map(rows.map(r=>[r.licenseNumber||`${r.name}|${r.streetAddress||''}|${r.city||''}`.toLowerCase(),r]));if(!unique.size)throw new Error('Minnesota OCM workbook contained zero parseable issued Cannabis Retailer records; refusing an unverified import.');return Array.from(unique.values());}
