import 'server-only';
type Row={name:string;streetAddress:string;city?:string;region:string;country:string;latitude?:number;longitude?:number;website?:string;licenseNumber?:string;dataSource:string;sourceUrl:string;sourceLicense:string;imageryStatus:'unchecked'|'missing_coordinates'};
const SOURCE='https://health.mo.gov/business-professionals/cannabis-regulation/licensee-compliance-guidance/licensed-facilities';
const EXPERIENCE_ID='c8517c6db03a4d87a5127030bb7361e6';
function clean(v:unknown){return String(v??'').replace(/\s+/g,' ').trim();}
function key(v:string){return v.toLowerCase().replace(/[^a-z0-9]/g,'');}
function normalized(raw:Record<string,unknown>){const out:Record<string,unknown>={};for(const [k,v] of Object.entries(raw||{}))out[key(k)]=v;return out;}
function pick(r:Record<string,unknown>,names:string[]){for(const n of names){const v=r[key(n)];if(v!==undefined&&v!==null&&clean(v))return clean(v);}return '';}
async function json(url:string){const r=await fetch(url,{headers:{Accept:'application/json','User-Agent':'GeoWeedo/0.8 (https://geoweedo.com)'},cache:'no-store',signal:AbortSignal.timeout(30000)});if(!r.ok)throw new Error(`Missouri DCR map source returned ${r.status}`);return r.json();}
function collect(value:unknown,services:Set<string>,ids:Set<string>){if(typeof value==='string'){const service=value.match(/https:\/\/[^"'\s]+\/(?:FeatureServer|MapServer)(?:\/\d+)?/i)?.[0];if(service)services.add(service.replace(/\\u002F/g,'/'));if(/^[0-9a-f]{32}$/i.test(value))ids.add(value);return;}if(Array.isArray(value)){for(const v of value)collect(v,services,ids);return;}if(value&&typeof value==='object')for(const v of Object.values(value as Record<string,unknown>))collect(v,services,ids);}
async function discoverServices(){const services=new Set<string>(),seen=new Set<string>(),queue=[EXPERIENCE_ID];while(queue.length&&seen.size<35){const id=queue.shift()!;if(seen.has(id))continue;seen.add(id);let data:any;try{data=await json(`https://www.arcgis.com/sharing/rest/content/items/${id}/data?f=json`);}catch{continue;}const ids=new Set<string>();collect(data,services,ids);for(const next of Array.from(ids))if(!seen.has(next)&&!queue.includes(next))queue.push(next);}return Array.from(services);}
async function layerUrls(service:string){if(/\/(?:FeatureServer|MapServer)\/\d+$/i.test(service))return[service];try{const meta:any=await json(`${service}?f=json`);return(Array.isArray(meta?.layers)?meta.layers:[]).map((l:any)=>`${service}/${l.id}`);}catch{return[];}}
function parseAddress(value:string){const text=clean(value),m=text.match(/^(.*?)(?:,\s*|\s+)([A-Za-z .'-]{2,60}),?\s+MO\s+(\d{5}(?:-\d{4})?)$/i);return{text,city:m?.[2]?.trim()};}
export async function fetchMissouriCandidates():Promise<Row[]>{const services=await discoverServices();if(!services.length)throw new Error('Missouri DCR Verified Dispensary map exposed no public ArcGIS feature services.');const rows:Row[]=[],samples:string[]=[];let featureCount=0;for(const service of services.slice(0,20)){for(const layer of (await layerUrls(service)).slice(0,30)){let body:any;try{body=await json(`${layer}/query?where=1%3D1&outFields=*&returnGeometry=true&outSR=4326&f=json&resultRecordCount=2000`);}catch{continue;}for(const feature of Array.isArray(body?.features)?body.features:[]){featureCount++;const raw=feature?.attributes||{};if(samples.length<5)samples.push(Object.keys(raw).join(', '));const a=normalized(raw),joined=Object.values(a).map(clean).join(' | '),licenseNumber=pick(a,['License Number','LicenseNumber','License','Facility License Number','USER_License_']),type=pick(a,['License Type','Facility Type','Business Type','Type']),ato=pick(a,['ATO Status','Approval to Operate','Operating Status','Status']);const looksDispensary=/dispensary/i.test(`${type} ${joined}`)||/^DIS/i.test(licenseNumber)||/^(?:[A-Z0-9.-]*DIS[A-Z0-9.-]*)$/i.test(licenseNumber);if(!looksDispensary)continue;if(/not approved to operate|not approved|inactive|revoked|expired|suspended/i.test(ato))continue;const name=pick(a,['DBA','Trade Name','Business Name','Entity Name','Facility Name','Name','USER_Entity_Name','PlaceName']);const address=pick(a,['Facility Address','Address','Physical Address','Street Address','Location Address','USER_Address','Place_addr','Match_addr','StAddr']);if(!name||!address)continue;const parsed=parseAddress(address),geometry=feature?.geometry||{},latitude=Number(geometry.y),longitude=Number(geometry.x),hasCoords=Number.isFinite(latitude)&&Number.isFinite(longitude);rows.push({name,streetAddress:parsed.text,city:pick(a,['City','Facility City','USER_City'])||parsed.city,region:'Missouri',country:'USA',latitude:hasCoords?latitude:undefined,longitude:hasCoords?longitude:undefined,website:pick(a,['Website','URL','Business Website'])||undefined,licenseNumber:licenseNumber||undefined,dataSource:'Missouri DCR Verified Dispensary Map',sourceUrl:SOURCE,sourceLicense:'Official Missouri Division of Cannabis Regulation Verified Dispensary map; licensed dispensary locations approved to operate only.',imageryStatus:hasCoords?'unchecked':'missing_coordinates'});}}}const unique=new Map<string,Row>();for(const row of rows){const id=(row.licenseNumber||`${row.name}|${row.streetAddress}`).toLowerCase();if(!unique.has(id))unique.set(id,row);}if(!unique.size)throw new Error(`Missouri DCR verified map yielded zero approved dispensary locations from ${services.length} discovered service(s) and ${featureCount} feature(s). Sample fields: ${samples.join(' ; ')||'none'}`);return Array.from(unique.values());}
