import 'server-only';
import { inflateRawSync } from 'node:zlib';

type Row={name:string;streetAddress?:string;city?:string;region:string;country:string;licenseNumber?:string;dataSource:string;sourceUrl:string;sourceLicense:string;imageryStatus:'missing_coordinates'};
const CROP='https://crop.rld.nm.gov/';
const CATALOG=new URL('data-catalog.html',CROP).toString();
const LICENSING=new URL('licensing-data.html',CROP).toString();
const LOOKUP='https://nmrldlpi.my.site.com/ccd/s/public-license-search';

function clean(v:unknown){return String(v??'').replace(/&amp;/g,'&').replace(/&#39;|&apos;|&#x27;/g,"'").replace(/&quot;/g,'"').replace(/&nbsp;/g,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();}
function key(v:string){return v.toLowerCase().replace(/[^a-z0-9]/g,'');}
function pick(r:Record<string,string>,names:string[]){for(const n of names){const v=r[key(n)];if(v)return v;}return '';}
async function get(url:string){const response=await fetch(url,{headers:{Accept:'text/html,text/csv,application/json,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,*/*','User-Agent':'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/124 Safari/537.36','Accept-Language':'en-US,en;q=0.9',Referer:CROP},cache:'no-store',redirect:'follow',signal:AbortSignal.timeout(45000)});if(!response.ok)throw new Error(`New Mexico CCD ${new URL(url).host} returned ${response.status}`);return response;}
function csv(text:string){const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(ch===','&&!quoted){row.push(cell);cell='';}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(v=>v.trim()))rows.push(row);row=[];cell='';}else cell+=ch;}row.push(cell);if(row.some(v=>v.trim()))rows.push(row);return rows;}
function xml(v:string){return clean(v.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(Number(n))).replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCharCode(parseInt(n,16))));}
function unzip(buffer:Buffer){const files=new Map<string,Buffer>();let eocd=-1;for(let i=buffer.length-22;i>=Math.max(0,buffer.length-65557);i--)if(buffer.readUInt32LE(i)===0x06054b50){eocd=i;break;}if(eocd<0)throw new Error('New Mexico CCD workbook is not a valid XLSX archive.');const count=buffer.readUInt16LE(eocd+10),offset=buffer.readUInt32LE(eocd+16);let p=offset;for(let i=0;i<count&&p+46<=buffer.length;i++){if(buffer.readUInt32LE(p)!==0x02014b50)break;const method=buffer.readUInt16LE(p+10),compressed=buffer.readUInt32LE(p+20),nameLen=buffer.readUInt16LE(p+28),extraLen=buffer.readUInt16LE(p+30),commentLen=buffer.readUInt16LE(p+32),local=buffer.readUInt32LE(p+42),name=buffer.subarray(p+46,p+46+nameLen).toString('utf8'),localName=buffer.readUInt16LE(local+26),localExtra=buffer.readUInt16LE(local+28),start=local+30+localName+localExtra,data=buffer.subarray(start,start+compressed);if(method===0)files.set(name,data);else if(method===8)files.set(name,inflateRawSync(data));p+=46+nameLen+extraLen+commentLen;}return files;}
function xlsx(buffer:Buffer){const files=unzip(buffer),shared:string[]=[];const sx=files.get('xl/sharedStrings.xml')?.toString('utf8')||'';const sr=/<si\b[^>]*>([\s\S]*?)<\/si>/gi;let sm:RegExpExecArray|null;while((sm=sr.exec(sx))!==null){let value='';const tr=/<t\b[^>]*>([\s\S]*?)<\/t>/gi;let tm:RegExpExecArray|null;while((tm=tr.exec(sm[1]))!==null)value+=xml(tm[1]);shared.push(value);}const sheet=files.get('xl/worksheets/sheet1.xml')?.toString('utf8')||'';if(!sheet)throw new Error('New Mexico CCD workbook contains no readable worksheet.');const rows:string[][]=[],rr=/<row\b[^>]*>([\s\S]*?)<\/row>/gi;let rm:RegExpExecArray|null;while((rm=rr.exec(sheet))!==null){const cells:string[]=[],cr=/<c\b([^>]*)>([\s\S]*?)<\/c>/gi;let cm:RegExpExecArray|null;while((cm=cr.exec(rm[1]))!==null){const ref=cm[1].match(/\br="([A-Z]+)\d+"/i)?.[1]||'',type=cm[1].match(/\bt="([^"]+)"/i)?.[1]||'',raw=cm[2].match(/<v>([\s\S]*?)<\/v>/i)?.[1]??cm[2].match(/<t\b[^>]*>([\s\S]*?)<\/t>/i)?.[1]??'';let col=0;for(let i=0;i<ref.length;i++)col=col*26+(ref.charCodeAt(i)-64);const value=type==='s'?shared[Number(raw)]||'':xml(raw);if(col)cells[col-1]=value;else cells.push(value);}if(cells.some(Boolean))rows.push(cells);}return rows;}
function records(rows:string[][]){if(rows.length<2)return[];let hi=rows.findIndex(r=>r.some(v=>/license/i.test(v))&&r.some(v=>/name|business|dba/i.test(v)));if(hi<0)hi=0;const headers=rows[hi].map(key);return rows.slice(hi+1).map(c=>{const o:Record<string,string>={};headers.forEach((h,i)=>{if(h)o[h]=clean(c[i]);});return o;});}
function normalizeObject(input:Record<string,unknown>){const out:Record<string,string>={};for(const [k,v] of Object.entries(input)){if(v===null||v===undefined)continue;if(typeof v==='string'||typeof v==='number'||typeof v==='boolean')out[key(k)]=clean(v);}return out;}
function retailerRows(input:Record<string,string>[],sourceUrl:string){const out:Row[]=[];for(const r of input){const license=pick(r,['License Number','License #','License','Principal License Number','License ID','LicenseNumber','license_number']);const type=pick(r,['License Type','Activity','Licensed Activity','Business Type','Type','LicenseType','license_type']);const status=pick(r,['License Status','Status','LicenseStatus','license_status']);if(!(/retail/i.test(type)||/^RTLR-/i.test(license)||/-RTLR-/i.test(license)))continue;if(status&&!/active|approved|issued|current|operating/i.test(status))continue;const name=pick(r,['DBA','DBA Name','Business Name','Licensee Name','Legal Name','Establishment Name','Name','BusinessName','LicenseeName']);const address=pick(r,['Physical Address','Premise Address','Licensed Premise Address','Address','Street Address','PhysicalAddress','PremiseAddress']);const city=pick(r,['City','Premise City','Municipality','PremiseCity']);if(!name||!license)continue;out.push({name,streetAddress:address||undefined,city:city||undefined,region:'New Mexico',country:'USA',licenseNumber:license,dataSource:'New Mexico CCD Public License Data',sourceUrl,sourceLicense:'Official New Mexico Cannabis Control Division public license data; active retail licensed activity only.',imageryStatus:'missing_coordinates'});}return out;}
function explicitDataUrls(text:string,base:string){const found:string[]=[];const attr=/(?:href|src)=["']([^"']+\.(?:csv|xlsx?|json)(?:\?[^"']*)?)["']/gi;let m:RegExpExecArray|null;while((m=attr.exec(text))!==null){try{found.push(new URL(m[1].replace(/&amp;/g,'&'),base).toString());}catch{}}const quoted=/["']((?:https?:\/\/|\/|\.\.\/|\.\/)[^"']+\.(?:csv|xlsx?|json)(?:\?[^"']*)?)["']/gi;while((m=quoted.exec(text))!==null){try{found.push(new URL(m[1],base).toString());}catch{}}return Array.from(new Set(found));}
function tableRecords(html:string){const rows:string[][]=[];const tr=/<tr\b[^>]*>([\s\S]*?)<\/tr>/gi;let rm:RegExpExecArray|null;while((rm=tr.exec(html))!==null){const cells:string[]=[];const td=/<t[dh]\b[^>]*>([\s\S]*?)<\/t[dh]>/gi;let cm:RegExpExecArray|null;while((cm=td.exec(rm[1]))!==null)cells.push(clean(cm[1]));if(cells.some(Boolean))rows.push(cells);}return records(rows);}
function collectObjects(value:unknown,out:Record<string,string>[],depth=0){if(depth>10||value===null||value===undefined)return;if(Array.isArray(value)){for(const item of value)collectObjects(item,out,depth+1);return;}if(typeof value!=='object')return;const obj=value as Record<string,unknown>;const normalized=normalizeObject(obj);if(Object.keys(normalized).some(k=>/license|business|dba|activity|premise|status/.test(k)))out.push(normalized);for(const child of Object.values(obj))collectObjects(child,out,depth+1);}
function embeddedJsonRecords(html:string){const out:Record<string,string>[]=[];const script=/<script\b[^>]*>([\s\S]*?)<\/script>/gi;let m:RegExpExecArray|null;while((m=script.exec(html))!==null){const body=m[1].trim();if(!body)continue;const attempts:string[]=[];if((body.startsWith('{')&&body.endsWith('}'))||(body.startsWith('[')&&body.endsWith(']')))attempts.push(body);const assignment=/(?:window\.[A-Za-z0-9_$]+\s*=|var\s+[A-Za-z0-9_$]+\s*=|const\s+[A-Za-z0-9_$]+\s*=)\s*([\[{][\s\S]*?[\]}])\s*;?/g;let am:RegExpExecArray|null;while((am=assignment.exec(body))!==null)attempts.push(am[1]);for(const raw of attempts){try{collectObjects(JSON.parse(raw),out);}catch{}}}return out;}
async function parseDataset(url:string){const response=await get(url),buffer=Buffer.from(await response.arrayBuffer()),type=response.headers.get('content-type')||'';if(buffer.subarray(0,2).toString()==='PK'||/spreadsheet|excel/i.test(type))return records(xlsx(buffer));const text=buffer.toString('utf8');if(/^\s*[\[{]/.test(text)){const data=JSON.parse(text),objects:Record<string,string>[]=[];collectObjects(data,objects);return objects;}return records(csv(text));}

export async function fetchNewMexicoCandidates():Promise<Row[]>{const rows:Row[]=[];const errors:string[]=[];const datasetUrls:string[]=[];for(const page of [CATALOG,LICENSING,new URL('default.html',CROP).toString()]){try{const html=await (await get(page)).text();datasetUrls.push(...explicitDataUrls(html,page));const scriptRe=/<script\b[^>]*src=["']([^"']+\.js(?:\?[^"']*)?)["']/gi;let sm:RegExpExecArray|null;while((sm=scriptRe.exec(html))!==null){try{const url=new URL(sm[1],page).toString(),js=await (await get(url)).text();datasetUrls.push(...explicitDataUrls(js,url));}catch{}}}catch(error){errors.push(`${page}: ${error instanceof Error?error.message:String(error)}`);}}
for(const url of Array.from(new Set(datasetUrls)).filter(u=>/licen|dispens|retail|cannabis|crop/i.test(u)).slice(0,30)){try{rows.push(...retailerRows(await parseDataset(url),url));}catch(error){errors.push(`${url}: ${error instanceof Error?error.message:String(error)}`);}}
try{const lookupHtml=await (await get(LOOKUP)).text();rows.push(...retailerRows(tableRecords(lookupHtml),LOOKUP));rows.push(...retailerRows(embeddedJsonRecords(lookupHtml),LOOKUP));}catch(error){errors.push(`${LOOKUP}: ${error instanceof Error?error.message:String(error)}`);}
const unique=new Map<string,Row>();for(const row of rows){const k=String(row.licenseNumber||'').toLowerCase();if(k&&!unique.has(k))unique.set(k,row);}if(unique.size<25)throw new Error(`New Mexico CCD public-source discovery yielded only ${unique.size} recognizable active retail licenses; refusing a partial/unverified import. C.R.O.P no longer exposes a reliable downloadable retailer dataset, so GeoWeedo also checked the current CCD public license lookup.${errors.length?` First error: ${errors[0]}`:''}`);return Array.from(unique.values());}
