import 'server-only';
import { inflateRawSync } from 'node:zlib';

type Row={name:string;streetAddress?:string;city?:string;region:string;country:string;licenseNumber?:string;dataSource:string;sourceUrl:string;sourceLicense:string;imageryStatus:'missing_coordinates'};
const CROP='https://crop.rld.nm.gov/';
const CATALOG=new URL('data-catalog.html',CROP).toString();

function clean(v:unknown){return String(v??'').replace(/&amp;/g,'&').replace(/&#39;|&apos;|&#x27;/g,"'").replace(/&quot;/g,'"').replace(/&nbsp;/g,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();}
function key(v:string){return v.toLowerCase().replace(/[^a-z0-9]/g,'');}
function pick(r:Record<string,string>,names:string[]){for(const n of names){const v=r[key(n)];if(v)return v;}return '';}
async function get(url:string){const response=await fetch(url,{headers:{Accept:'text/html,text/csv,application/json,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,*/*','User-Agent':'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/124 Safari/537.36','Accept-Language':'en-US,en;q=0.9',Referer:CROP},cache:'no-store',redirect:'follow',signal:AbortSignal.timeout(45000)});if(!response.ok)throw new Error(`New Mexico CCD ${new URL(url).host} returned ${response.status}`);return response;}
function csv(text:string){const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(ch===','&&!quoted){row.push(cell);cell='';}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(v=>v.trim()))rows.push(row);row=[];cell='';}else cell+=ch;}row.push(cell);if(row.some(v=>v.trim()))rows.push(row);return rows;}
function xml(v:string){return clean(v.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(Number(n))).replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCharCode(parseInt(n,16))));}
function unzip(buffer:Buffer){const files=new Map<string,Buffer>();let eocd=-1;for(let i=buffer.length-22;i>=Math.max(0,buffer.length-65557);i--)if(buffer.readUInt32LE(i)===0x06054b50){eocd=i;break;}if(eocd<0)throw new Error('New Mexico CCD workbook is not a valid XLSX archive.');const count=buffer.readUInt16LE(eocd+10),offset=buffer.readUInt32LE(eocd+16);let p=offset;for(let i=0;i<count&&p+46<=buffer.length;i++){if(buffer.readUInt32LE(p)!==0x02014b50)break;const method=buffer.readUInt16LE(p+10),compressed=buffer.readUInt32LE(p+20),nameLen=buffer.readUInt16LE(p+28),extraLen=buffer.readUInt16LE(p+30),commentLen=buffer.readUInt16LE(p+32),local=buffer.readUInt32LE(p+42),name=buffer.subarray(p+46,p+46+nameLen).toString('utf8'),localName=buffer.readUInt16LE(local+26),localExtra=buffer.readUInt16LE(local+28),start=local+30+localName+localExtra,data=buffer.subarray(start,start+compressed);if(method===0)files.set(name,data);else if(method===8)files.set(name,inflateRawSync(data));p+=46+nameLen+extraLen+commentLen;}return files;}
function xlsx(buffer:Buffer){const files=unzip(buffer),shared:string[]=[];const sx=files.get('xl/sharedStrings.xml')?.toString('utf8')||'';const sr=/<si\b[^>]*>([\s\S]*?)<\/si>/gi;let sm:RegExpExecArray|null;while((sm=sr.exec(sx))!==null){let value='';const tr=/<t\b[^>]*>([\s\S]*?)<\/t>/gi;let tm:RegExpExecArray|null;while((tm=tr.exec(sm[1]))!==null)value+=xml(tm[1]);shared.push(value);}const sheet=files.get('xl/worksheets/sheet1.xml')?.toString('utf8')||'';if(!sheet)throw new Error('New Mexico CCD workbook contains no readable worksheet.');const rows:string[][]=[],rr=/<row\b[^>]*>([\s\S]*?)<\/row>/gi;let rm:RegExpExecArray|null;while((rm=rr.exec(sheet))!==null){const cells:string[]=[],cr=/<c\b([^>]*)>([\s\S]*?)<\/c>/gi;let cm:RegExpExecArray|null;while((cm=cr.exec(rm[1]))!==null){const ref=cm[1].match(/\br="([A-Z]+)\d+"/i)?.[1]||'',type=cm[1].match(/\bt="([^"]+)"/i)?.[1]||'',raw=cm[2].match(/<v>([\s\S]*?)<\/v>/i)?.[1]??cm[2].match(/<t\b[^>]*>([\s\S]*?)<\/t>/i)?.[1]??'';let col=0;for(let i=0;i<ref.length;i++)col=col*26+(ref.charCodeAt(i)-64);const value=type==='s'?shared[Number(raw)]||'':xml(raw);if(col)cells[col-1]=value;else cells.push(value);}if(cells.some(Boolean))rows.push(cells);}return rows;}
function records(rows:string[][]){if(rows.length<2)return[];let hi=rows.findIndex(r=>r.some(v=>/license/i.test(v))&&r.some(v=>/name|business|dba/i.test(v)));if(hi<0)hi=0;const headers=rows[hi].map(key);return rows.slice(hi+1).map(c=>{const o:Record<string,string>={};headers.forEach((h,i)=>{if(h)o[h]=clean(c[i]);});return o;});}
function retailerRows(input:Record<string,string>[],sourceUrl:string){const out:Row[]=[];for(const r of input){const license=pick(r,['License Number','License #','License','Principal License Number','License ID']);const type=pick(r,['License Type','Activity','Licensed Activity','Business Type','Type']);const status=pick(r,['License Status','Status']);if(!(/retail/i.test(type)||/^RTLR-/i.test(license)))continue;if(status&&!/active|approved|issued|current|operating/i.test(status))continue;const name=pick(r,['DBA','DBA Name','Business Name','Licensee Name','Legal Name','Establishment Name','Name']);const address=pick(r,['Physical Address','Premise Address','Licensed Premise Address','Address','Street Address']);const city=pick(r,['City','Premise City','Municipality']);if(!name||!license)continue;out.push({name,streetAddress:address||undefined,city:city||undefined,region:'New Mexico',country:'USA',licenseNumber:license,dataSource:'New Mexico CCD C.R.O.P Licensing Data',sourceUrl,sourceLicense:'Official New Mexico Cannabis Control Division C.R.O.P public licensing data; active retail licensed activity only.',imageryStatus:'missing_coordinates'});}return out;}
function urls(text:string,base:string){const found:string[]=[];const re=/(?:href|src)=["']([^"']+)["']/gi;let m:RegExpExecArray|null;while((m=re.exec(text))!==null)try{found.push(new URL(m[1].replace(/&amp;/g,'&'),base).toString());}catch{}const files=/(?:https?:\/\/[^"'\s)]+|[A-Za-z0-9_./%-]+\.(?:csv|xlsx?|json)(?:\?[^"'\s)]*)?)/gi;while((m=files.exec(text))!==null)try{found.push(new URL(m[0],base).toString());}catch{}return Array.from(new Set(found));}

export async function fetchNewMexicoCandidates():Promise<Row[]>{const pages=[CATALOG,new URL('licensing-data.html',CROP).toString(),new URL('default.html',CROP).toString()];const discovered:string[]=[];for(const page of pages){const html=await (await get(page)).text();discovered.push(...urls(html,page));for(const script of urls(html,page).filter(u=>/\.js(?:\?|$)/i.test(u)).slice(0,20)){try{const js=await (await get(script)).text();discovered.push(...urls(js,script));}catch{}}}const candidates=Array.from(new Set(discovered)).filter(u=>/\.csv|\.xlsx?|\.json/i.test(u)&&/licen|dispens|retail|cannabis|crop/i.test(u));const rows:Row[]=[];const errors:string[]=[];for(const url of candidates.slice(0,30)){try{const response=await get(url),buffer=Buffer.from(await response.arrayBuffer()),type=response.headers.get('content-type')||'';let parsed:string[][]=[];if(buffer.subarray(0,2).toString()==='PK'||/spreadsheet|excel/i.test(type))parsed=xlsx(buffer);else{const text=buffer.toString('utf8');if(/^\s*[\[{]/.test(text)){const data=JSON.parse(text);const list=Array.isArray(data)?data:Array.isArray(data?.data)?data.data:Array.isArray(data?.records)?data.records:[];if(list.length){const keys=Object.keys(list[0]||{});parsed=[keys,...list.map((r:any)=>keys.map(k=>String(r?.[k]??'')))];}}else parsed=csv(text);}rows.push(...retailerRows(records(parsed),url));}catch(error){errors.push(`${url}: ${error instanceof Error?error.message:String(error)}`);}}const unique=new Map<string,Row>();for(const row of rows){const k=String(row.licenseNumber||'').toLowerCase();if(k&&!unique.has(k))unique.set(k,row);}if(unique.size<25)throw new Error(`New Mexico CCD C.R.O.P discovery yielded only ${unique.size} recognizable active retail licenses; refusing a partial/unverified import.${candidates.length?` Checked ${candidates.length} published dataset candidate(s).`: ' No downloadable licensing dataset was exposed by C.R.O.P.'}${errors.length?` First error: ${errors[0]}`:''}`);return Array.from(unique.values());}
