import 'server-only';
import { inflateRawSync } from 'node:zlib';

type Row={name:string;streetAddress?:string;city?:string;region:string;country:string;licenseNumber?:string;dataSource:string;sourceUrl:string;sourceLicense:string;imageryStatus:'missing_coordinates'};
const SOURCE='https://ccb.vermont.gov/licenses';

function clean(v:unknown){return String(v??'').replace(/&amp;/g,'&').replace(/&#39;|&apos;|&#x27;/g,"'").replace(/&quot;/g,'"').replace(/&nbsp;/g,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();}
function key(v:string){return v.toLowerCase().replace(/[^a-z0-9]/g,'');}
function xml(v:string){return clean(v.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(Number(n))).replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCharCode(parseInt(n,16))));}
async function get(url:string,accept:string){const response=await fetch(url,{headers:{Accept:accept,'User-Agent':'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/124 Safari/537.36','Accept-Language':'en-US,en;q=0.9',Referer:SOURCE},cache:'no-store',redirect:'follow',signal:AbortSignal.timeout(45000)});if(!response.ok)throw new Error(`Vermont CCB ${new URL(url).host} returned ${response.status}`);return response;}
function unzip(buffer:Buffer){const files=new Map<string,Buffer>();let eocd=-1;for(let i=buffer.length-22;i>=Math.max(0,buffer.length-65557);i--)if(buffer.readUInt32LE(i)===0x06054b50){eocd=i;break;}if(eocd<0)throw new Error('Vermont CCB Excel report is not a valid XLSX archive.');const count=buffer.readUInt16LE(eocd+10),offset=buffer.readUInt32LE(eocd+16);let p=offset;for(let i=0;i<count&&p+46<=buffer.length;i++){if(buffer.readUInt32LE(p)!==0x02014b50)break;const method=buffer.readUInt16LE(p+10),compressed=buffer.readUInt32LE(p+20),nameLen=buffer.readUInt16LE(p+28),extraLen=buffer.readUInt16LE(p+30),commentLen=buffer.readUInt16LE(p+32),local=buffer.readUInt32LE(p+42),name=buffer.subarray(p+46,p+46+nameLen).toString('utf8');const localName=buffer.readUInt16LE(local+26),localExtra=buffer.readUInt16LE(local+28),start=local+30+localName+localExtra,data=buffer.subarray(start,start+compressed);if(method===0)files.set(name,data);else if(method===8)files.set(name,inflateRawSync(data));p+=46+nameLen+extraLen+commentLen;}return files;}
function parseXlsx(buffer:Buffer){const files=unzip(buffer),shared:string[]=[];const sharedXml=files.get('xl/sharedStrings.xml')?.toString('utf8')||'';const siRe=/<si\b[^>]*>([\s\S]*?)<\/si>/gi;let si:RegExpExecArray|null;while((si=siRe.exec(sharedXml))!==null){let value='';const tRe=/<t\b[^>]*>([\s\S]*?)<\/t>/gi;let t:RegExpExecArray|null;while((t=tRe.exec(si[1]))!==null)value+=xml(t[1]);shared.push(value);}const workbook=files.get('xl/workbook.xml')?.toString('utf8')||'',rels=files.get('xl/_rels/workbook.xml.rels')?.toString('utf8')||'';const first=workbook.match(/<sheet\b[^>]*r:id="([^"]+)"/i)?.[1];let sheetPath='xl/worksheets/sheet1.xml';if(first){const target=rels.match(new RegExp(`<Relationship\\b[^>]*Id=["']${first}["'][^>]*Target=["']([^"']+)`, 'i'))?.[1];if(target)sheetPath=target.startsWith('/')?target.slice(1):`xl/${target.replace(/^\.\//,'')}`;}const sheet=files.get(sheetPath)?.toString('utf8')||files.get('xl/worksheets/sheet1.xml')?.toString('utf8')||'';if(!sheet)throw new Error('Vermont CCB Excel report contains no readable worksheet.');const rows:string[][]=[];const rowRe=/<row\b[^>]*>([\s\S]*?)<\/row>/gi;let rm:RegExpExecArray|null;while((rm=rowRe.exec(sheet))!==null){const cells:string[]=[];const cellRe=/<c\b([^>]*)>([\s\S]*?)<\/c>/gi;let cm:RegExpExecArray|null;while((cm=cellRe.exec(rm[1]))!==null){const attrs=cm[1],body=cm[2],ref=attrs.match(/\br="([A-Z]+)\d+"/i)?.[1]||'',type=attrs.match(/\bt="([^"]+)"/i)?.[1]||'',raw=body.match(/<v>([\s\S]*?)<\/v>/i)?.[1]??body.match(/<t\b[^>]*>([\s\S]*?)<\/t>/i)?.[1]??'';let col=0;for(let i=0;i<ref.length;i++){const ch=ref.charAt(i).toUpperCase();col=col*26+(ch.charCodeAt(0)-64);}const value=type==='s'?shared[Number(raw)]||'':xml(raw);if(col)cells[col-1]=value;else cells.push(value);}if(cells.some(Boolean))rows.push(cells);}return rows;}
function toRecords(rows:string[][]){if(rows.length<2)return[];let headerIndex=rows.findIndex(r=>r.some(v=>/license\s*#|license\s*number/i.test(v))&&r.some(v=>/business|name/i.test(v)));if(headerIndex<0)headerIndex=0;const headers=rows[headerIndex].map(v=>key(v));return rows.slice(headerIndex+1).map(cells=>{const out:Record<string,string>={};headers.forEach((h,i)=>{if(h)out[h]=clean(cells[i]);});return out;});}
function pick(r:Record<string,string>,names:string[]){for(const n of names){const v=r[key(n)];if(v)return v;}return '';}
async function discoverExcel(html:string){const links:string[]=[];const re=/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m:RegExpExecArray|null;while((m=re.exec(html))!==null){const href=m[1].replace(/&amp;/g,'&'),label=clean(m[2]);if(/excel|license report|download/i.test(label)||/\.xlsx?(?:\?|$)/i.test(href)){try{links.push(new URL(href,SOURCE).toString());}catch{}}}return links.find(u=>/\.xlsx?(?:\?|$)/i.test(u))||links[0];}

export async function fetchVermontCandidates():Promise<Row[]>{const page=await get(SOURCE,'text/html,application/xhtml+xml');const html=await page.text();const excel=await discoverExcel(html);if(!excel)throw new Error('Vermont CCB license portal did not expose its published Excel license report; refusing an unverified import.');const report=await get(excel,'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel,application/octet-stream,*/*');const buffer=Buffer.from(await report.arrayBuffer());if(buffer.subarray(0,2).toString()!=='PK')throw new Error('Vermont CCB license-report download was not an XLSX file; refusing an unverified import.');const records=toRecords(parseXlsx(buffer)),rows:Row[]=[];for(const record of records){const licenseNumber=pick(record,['License #','License Number','License','License ID']);const type=pick(record,['License Type','Type','License Category']);const status=pick(record,['Status','License Status']);if(!(/^RTLR/i.test(licenseNumber)||/licensed retailer|retailer cannabis establishment|retail/i.test(type)))continue;if(status&&!/active|approved|issued|operating|current/i.test(status))continue;const name=pick(record,['Business Name','DBA','DBA Name','Establishment Name','Licensee Name','Name']);const address=pick(record,['Address','Street Address','Physical Address','Location Address']);const city=pick(record,['City','Town','Municipality']);if(!name||!licenseNumber)continue;rows.push({name,streetAddress:address||undefined,city:city||undefined,region:'Vermont',country:'USA',licenseNumber,dataSource:'Vermont CCB Licensed Cannabis Establishments',sourceUrl:SOURCE,sourceLicense:'Official Vermont Cannabis Control Board license report; licensed retail cannabis establishments only.',imageryStatus:'missing_coordinates'});}const unique=new Map<string,Row>();for(const row of rows)if(!unique.has(row.licenseNumber!.toLowerCase()))unique.set(row.licenseNumber!.toLowerCase(),row);if(!unique.size)throw new Error('Vermont CCB Excel report yielded zero licensed retailer records; refusing an unverified import.');return Array.from(unique.values());}
