'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import GuessMap, { LatLng } from '@/components/GuessMap';
import SiteHeader from '@/components/SiteHeader';
import StreetViewStage from '@/components/StreetViewStage';
import { dispensaries, type Dispensary } from '@/data/dispensaries';
import { DEFAULT_YERB_PER_POINT, yerbFromScore } from '@/lib/yerbasRewards';
const MAX_SCORE=5000;
type PublicMapCandidate={id:string;name:string;latitude:number;longitude:number;city?:string;region?:string;country?:string;dataSource?:string;status?:string;imageryStatus?:string;mapCandidate?:boolean};type PublicMapStats={total:number;mapped:number;missingCoordinates:number;states:number};
function distanceKm(a:LatLng,b:LatLng){const r=6371.0088,rad=(v:number)=>(v*Math.PI)/180,dLat=rad(b.lat-a.lat),dLng=rad(b.lng-a.lng),lat1=rad(a.lat),lat2=rad(b.lat),h=Math.sin(dLat/2)**2+Math.cos(lat1)*Math.cos(lat2)*Math.sin(dLng/2)**2;return r*2*Math.atan2(Math.sqrt(h),Math.sqrt(1-h));}function scoreFromDistance(km:number){return Math.max(0,Math.min(MAX_SCORE,Math.round(MAX_SCORE*Math.exp(-km/500))));}
function shuffle<T>(items:T[]){const copy=items.slice();for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));const tmp=copy[i];copy[i]=copy[j];copy[j]=tmp;}return copy;}
export default function HomePage(){const[started,setStarted]=useState(false),[round,setRound]=useState(0),[scores,setScores]=useState<number[]>([]),[guess,setGuess]=useState<LatLng|null>(null),[revealed,setRevealed]=useState(false),[roundDistance,setRoundDistance]=useState<number|null>(null),[roundScore,setRoundScore]=useState<number|null>(null),[approvedDispensaries,setApprovedDispensaries]=useState<Dispensary[]>([]),[mapCandidates,setMapCandidates]=useState<PublicMapCandidate[]>([]),[mapStats,setMapStats]=useState<PublicMapStats|null>(null),[gameRounds,setGameRounds]=useState<Dispensary[]>([]),[homeCardOpen,setHomeCardOpen]=useState(true);
useEffect(()=>{fetch('/api/dispensaries',{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject()).then(d=>setApprovedDispensaries(Array.isArray(d.dispensaries)?d.dispensaries:[])).catch(()=>setApprovedDispensaries([]));fetch('/api/map-candidates',{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject()).then(d=>{setMapCandidates(Array.isArray(d.candidates)?d.candidates:[]);setMapStats(d.stats&&typeof d.stats==='object'?d.stats:null);}).catch(()=>{setMapCandidates([]);setMapStats(null);});},[]);
const playableLocations=useMemo(()=>approvedDispensaries.filter(item=>item.active&&item.verified&&item.imageryPhotoId),[approvedDispensaries]);
const rounds=started?gameRounds:playableLocations;
const homeLocations=useMemo(()=>{const merged=[...approvedDispensaries.filter(item=>item.active).map(item=>({id:item.id,name:item.name,lat:item.latitude,lng:item.longitude,city:item.city,region:item.region,sponsored:item.sponsored,approved:true,imageryReady:Boolean(item.verified&&item.imageryPhotoId),source:'GeoWeedo approved'})),...mapCandidates.map(item=>({id:item.id,name:item.name,lat:item.latitude,lng:item.longitude,city:item.city||'',region:item.region||'',sponsored:false,approved:item.status==='approved',imageryReady:item.imageryStatus==='coverage',source:item.dataSource||'Official source'})),...dispensaries.filter(item=>item.active).map(item=>({id:item.id,name:item.name,lat:item.latitude,lng:item.longitude,city:item.city,region:item.region,sponsored:item.sponsored,approved:false,imageryReady:false,source:'GeoWeedo starter'}))];const seen=new Set<string>();return merged.filter(item=>{if(!Number.isFinite(item.lat)||!Number.isFinite(item.lng))return false;const key=`${item.name}|${item.lat.toFixed(5)}|${item.lng.toFixed(5)}`.toLowerCase();if(seen.has(key))return false;seen.add(key);return true;});},[approvedDispensaries,mapCandidates]);
const current=rounds[round],total=scores.reduce((s,v)=>s+v,0),completedTotal=total+(revealed&&roundScore!==null?roundScore:0),estimatedYerb=yerbFromScore(completedTotal,DEFAULT_YERB_PER_POINT),onGuess=useCallback((v:LatLng)=>setGuess(v),[]);const beginGame=()=>{const randomized=shuffle(playableLocations).slice(0,Math.min(5,playableLocations.length));setGameRounds(randomized);setStarted(true);setRound(0);setScores([]);setGuess(null);setRevealed(false);setRoundDistance(null);setRoundScore(null);};const revealGuess=()=>{if(!guess||!current)return;const distance=distanceKm(guess,{lat:current.latitude,lng:current.longitude});setRoundDistance(distance);setRoundScore(scoreFromDistance(distance));setRevealed(true);};const nextRound=()=>{if(roundScore===null)return;setScores(p=>[...p,roundScore]);setRound(p=>p+1);setGuess(null);setRevealed(false);setRoundDistance(null);setRoundScore(null);};
if(!started)return <main className="landing-shell map-first-home"><SiteHeader/><section className="home-map-stage"><div className="home-map-canvas"><GuessMap guess={null} revealed={false} onGuess={()=>{}} browseMode locations={homeLocations}/></div>{homeCardOpen?<div className="home-play-card"><button type="button" aria-label="Close game intro" onClick={()=>setHomeCardOpen(false)} style={{position:'absolute',right:14,top:14,width:34,height:34,border:0,borderRadius:'50%',background:'rgba(255,255,255,.07)',color:'var(--text)',fontSize:22,lineHeight:1,cursor:'pointer'}}>×</button><div className="eyebrow" style={{paddingRight:36}}>THE DISPENSARY GEOGRAPHY GAME</div><h1>GeoWeedo</h1><p>Explore real dispensary locations, read the clues, and pinpoint where you are.</p><button className="primary home-play-button" onClick={beginGame} disabled={playableLocations.length===0}>{playableLocations.length?`Play GeoWeedo · ${Math.min(5,playableLocations.length)} random round${Math.min(5,playableLocations.length)===1?'':'s'}`:'No quality-approved rounds yet'}</button><div className="home-play-meta"><span>{playableLocations.length} playable</span><span>{homeLocations.length.toLocaleString()} mapped</span>{mapStats&&<span>{mapStats.total.toLocaleString()} candidates</span>}{mapStats&&<span>{mapStats.states} states</span>}<span>YERB rewards</span></div>{playableLocations.length===0&&<p className="map-coverage-note">Browse locations are visible, but gameplay stays disabled until imagery passes the quality validator.</p>}{mapStats&&mapStats.missingCoordinates>0&&<p className="map-coverage-note">{mapStats.missingCoordinates.toLocaleString()} imported locations still need coordinates before they can appear on the public map.</p>}</div>:<button type="button" onClick={()=>setHomeCardOpen(true)} aria-label="Show game intro" style={{position:'absolute',zIndex:5,left:18,bottom:18,border:'1px solid rgba(255,255,255,.14)',borderRadius:12,background:'rgba(11,14,12,.92)',color:'var(--text)',padding:'10px 14px',fontWeight:800,cursor:'pointer'}}>Play GeoWeedo</button>}</section></main>;
if(!current){if(scores.length===0)return <main className="result-shell"><div className="result-card"><div className="eyebrow">NO PLAYABLE ROUNDS</div><h1>0</h1><p>GeoWeedo only starts rounds with quality-approved navigable imagery.</p><a className="primary" href="/">Back to map</a></div></main>;return <main className="result-shell"><div className="result-card"><div className="eyebrow">GAME COMPLETE</div><h1>{total.toLocaleString()} <small>/ {(rounds.length*MAX_SCORE).toLocaleString()}</small></h1><p className="yerb-score">Estimated eligible reward: {yerbFromScore(total,DEFAULT_YERB_PER_POINT)} YERB</p><div className="score-list">{scores.map((score,index)=><div key={index}><span>Round {index+1}</span><strong>{score.toLocaleString()}</strong></div>)}</div><button className="primary" onClick={beginGame}>Play again</button></div></main>;}
const actual={lat:current.latitude,lng:current.longitude};return <main className="game-shell"><header className="game-header"><a className="brand brand-link" href="/"><span className="brand-pin">✦</span> GEOWEEDO</a><div className="round-meter">ROUND {round+1} / {rounds.length}</div><div className="running-score">{completedTotal.toLocaleString()} pts · <span className="yerb-score">~{estimatedYerb} YERB</span></div></header><section className="panorama-stage live-panorama"><StreetViewStage latitude={current.imageryLatitude??current.latitude} longitude={current.imageryLongitude??current.longitude} heading={current.imageryHeading??current.heading} photoId={current.imageryPhotoId} imageryProvider={current.imageryProvider} imageUrl={current.imageryUrl} projection={current.imageryProjection} fieldOfView={current.imageryFieldOfView}/><aside className="guess-card live-guess-card"><GuessMap guess={guess} actual={actual} revealed={revealed} onGuess={onGuess}/>{!revealed?<div className="guess-actions"><div className="guess-status">{guess?'Pin placed — move it by clicking elsewhere.':'Place a pin where you think the dispensary is.'}</div><button className="primary full" disabled={!guess} onClick={revealGuess}>{guess?'Make Guess':'Place a Pin First'}</button></div>:<div className="reveal"><span className="eyebrow">ACTUAL LOCATION</span><h3>{current.name}</h3><p>{current.city}, {current.region}{current.sponsored?' · Featured':''}</p><div className="reveal-stat"><span>Distance</span><strong>{roundDistance===null?'—':roundDistance<1?`${Math.round(roundDistance*1000)} m`:`${roundDistance.toFixed(1)} km`}</strong></div><div className="reveal-stat"><span>Score</span><strong>{roundScore?.toLocaleString()??'—'}</strong></div><button className="primary full" onClick={nextRound}>{round+1===rounds.length?'See Results':'Next Round'}</button></div>}</aside></section></main>;
}
