'use client';

import {useEffect,useMemo,useState} from 'react';

type JobReason={status:string;message:string;count:number};
type Job={id:string;status:string;total:number;counts:Record<string,number>;reasons?:JobReason[];scope:any;auto_apply:number;created_at:string};
type Review={id:string;location_id:string;location_name:string;review_type:'discovery'|'enrichment';confidence:string;score?:number|null;payload:any;created_at:string};
type Data={options:{countries:string[];regions:string[]};jobs:Job[];reviews:Review[];discoveryConfigured?:boolean};

export default function AdminBatchEnrichmentQueue(){
 const[data,setData]=useState<Data>({options:{countries:[],regions:[]},jobs:[],reviews:[]}),[country,setCountry]=useState(''),[region,setRegion]=useState(''),[recordType,setRecordType]=useState('all'),[missing,setMissing]=useState('any'),[autoApply,setAutoApply]=useState(true),[busy,setBusy]=useState(false),[running,setRunning]=useState<string|null>(null),[message,setMessage]=useState('');
 async function load(){const r=await fetch('/api/admin/dispensary-batch-enrichment',{cache:'no-store'});if(r.status===401){location.href='/admin/login';return;}const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load batch enrichment queue.');setData(d);}
 useEffect(()=>{load().catch(e=>setMessage(e instanceof Error?e.message:'Load failed.'));},[]);
 const regions=useMemo(()=>data.options.regions,[data.options.regions]);
 async function create(){setBusy(true);setMessage('Creating enrichment queue…');try{const r=await fetch('/api/admin/dispensary-batch-enrichment',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'create',scope:{country:country||undefined,region:region||undefined,recordType,missing},autoApply})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not create batch.');await load();const processable=Number(d.job?.counts?.pending||0),blocked=Number(d.job?.counts?.blocked||0);setMessage(`${d.job.total.toLocaleString()} matching records found · ${processable.toLocaleString()} processable${blocked?` · ${blocked.toLocaleString()} blocked until site discovery is configured`:''}.`);if(processable)void run(d.job.id);}catch(e){setMessage(e instanceof Error?e.message:'Could not create batch.');}finally{setBusy(false);}}
 async function run(jobId:string){if(running&&running!==jobId)return;setRunning(jobId);setMessage('Batch processing is running in small chunks. You can leave this page and resume later.');try{for(let i=0;i<500;i++){const r=await fetch('/api/admin/dispensary-batch-enrichment',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'process',jobId,chunkSize:5})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Batch processing failed.');await load();if(d.job?.status==='completed'){const c=d.job.counts||{};setMessage(`Batch complete · ${c.applied||0} applied · ${c.review||0} awaiting review · ${c.blocked||0} blocked · ${c.failed||0} failed.`);break;}}}catch(e){setMessage(e instanceof Error?e.message:'Batch processing stopped.');}finally{setRunning(null);await load().catch(()=>{});}}
 async function review(id:string,action:'approve'|'reject'){setBusy(true);try{const r=await fetch('/api/admin/dispensary-batch-enrichment',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({reviewId:id,action})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Review action failed.');await load();setMessage(action==='approve'?'Review approved and applied.':'Review rejected.');}catch(e){setMessage(e instanceof Error?e.message:'Review action failed.');}finally{setBusy(false);}}
 return <section className="admin-panel" style={{marginBottom:24}}>
  <div className="admin-panel-heading"><div><span className="eyebrow">AUTOMATED ENRICHMENT</span><h2>Batch discovery + enrichment queue</h2></div></div>
  <p className="admin-copy">Queue hundreds or thousands of incomplete records at once. High-confidence official-site matches and structured business data are applied automatically; anything uncertain stops in the review queue below.</p>
  {data.discoveryConfigured===false&&<p className="admin-status">Official-site search is not configured. Records that already have websites can still be enriched. Records without websites are now marked <b>Blocked</b> instead of being sent through discovery and counted as failures.</p>}
  <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(170px,1fr))',gap:10}}>
   <label>Country<select value={country} onChange={e=>{setCountry(e.target.value);setRegion('');}}><option value="">All countries</option>{data.options.countries.map(v=><option key={v}>{v}</option>)}</select></label>
   <label>State / region<select value={region} onChange={e=>setRegion(e.target.value)}><option value="">All states / regions</option>{regions.map(v=><option key={v}>{v}</option>)}</select></label>
   <label>Records<select value={recordType} onChange={e=>setRecordType(e.target.value)}><option value="all">Approved + candidates</option><option value="dispensary">Approved dispensaries</option><option value="candidate">Imported candidates</option></select></label>
   <label>Needs<select value={missing} onChange={e=>setMissing(e.target.value)}><option value="any">Any missing information</option><option value="website">Website</option><option value="phone">Phone</option><option value="hours">Hours</option><option value="amenities">Amenities / services</option></select></label>
  </div>
  <div style={{display:'flex',gap:12,alignItems:'center',marginTop:14,flexWrap:'wrap'}}><label style={{display:'flex',gap:7,alignItems:'center'}}><input type="checkbox" checked={autoApply} onChange={e=>setAutoApply(e.target.checked)}/> Auto-apply high-confidence results only</label><button className="primary" disabled={busy||Boolean(running)} onClick={create}>Create & run batch</button></div>
  {message&&<p className="admin-status" style={{marginTop:12}}>{message}</p>}
  <h3>Recent batch jobs</h3>
  <div style={{overflowX:'auto'}}><table className="admin-table"><thead><tr><th>Scope</th><th>Status</th><th>Total</th><th>Pending</th><th>Applied</th><th>Review</th><th>Blocked</th><th>Skipped</th><th>Failed</th><th></th></tr></thead><tbody>{data.jobs.map(j=><tr key={j.id}><td><div>{[j.scope?.country||'All',j.scope?.region,j.scope?.recordType!=='all'?j.scope?.recordType:null,j.scope?.missing].filter(Boolean).join(' · ')}</div>{j.reasons?.length?<div style={{marginTop:5,display:'grid',gap:2}}>{j.reasons.slice(0,3).map((reason,index)=><small key={`${reason.status}-${index}`} style={{opacity:.75}}>{reason.count.toLocaleString()} {reason.status}: {reason.message}</small>)}</div>:null}</td><td>{j.status}</td><td>{j.total}</td><td>{j.counts?.pending||0}</td><td>{j.counts?.applied||0}</td><td>{j.counts?.review||0}</td><td>{j.counts?.blocked||0}</td><td>{j.counts?.skipped||0}</td><td>{j.counts?.failed||0}</td><td>{j.status!=='completed'&&<button className="ghost" disabled={Boolean(running)} onClick={()=>void run(j.id)}>{running===j.id?'Running…':'Resume'}</button>}</td></tr>)}</tbody></table></div>
  <div style={{display:'flex',justifyContent:'space-between',alignItems:'end',gap:10,marginTop:20}}><div><span className="eyebrow">ADMIN REVIEW</span><h3 style={{margin:'4px 0'}}>Uncertain matches</h3></div><strong>{data.reviews.length} pending</strong></div>
  {!data.reviews.length?<p className="admin-copy">No enrichment results currently need manual review.</p>:<div style={{display:'grid',gap:10,marginTop:10}}>{data.reviews.map(r=>{const selected=r.payload?.selected;const p=r.payload;return <div className="admin-card" key={r.id}><div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><div><strong>{r.location_name}</strong><div><small>{r.review_type==='discovery'?'Official website match':'First-party enrichment'} · {r.confidence} confidence{r.score!=null?` · score ${r.score}`:''}</small></div></div><div style={{display:'flex',gap:8}}><button className="ghost" disabled={busy} onClick={()=>review(r.id,'reject')}>Reject</button><button className="primary" disabled={busy} onClick={()=>review(r.id,'approve')}>Approve</button></div></div>{r.review_type==='discovery'?<div style={{marginTop:8}}><div><b>Candidate:</b> {selected?.url?<a href={selected.url} target="_blank" rel="noreferrer">{selected.url}</a>:'No candidate found'}</div>{selected?.reasons?.length?<div><b>Why matched:</b> {selected.reasons.join(', ')}</div>:null}{r.payload?.candidates?.slice(1,4).map((c:any)=><div key={c.url}><small>Alternative {c.score}: {c.url}</small></div>)}</div>:<div style={{marginTop:8}}><div><b>Source:</b> {p.sourceUrl?<a href={p.sourceUrl} target="_blank" rel="noreferrer">{p.sourceUrl}</a>:'—'}</div><div><b>Phone:</b> {p.phone||'—'} · <b>Website:</b> {p.website||'—'}</div><div><b>Hours:</b> {Object.keys(p.hours||{}).length?Object.entries(p.hours).map(([d,h])=>`${d}: ${h}`).join(' · '):'—'}</div><div><b>Amenities:</b> {(p.amenities||[]).join(', ')||'—'}</div></div>}</div>})}</div>}
 </section>;
}
