'use client';

import {useEffect,useMemo,useState} from 'react';

type Dispensary={id:string;name:string;city:string;region:string;active:boolean};
type Entitlement={id:string;dispensaryId:string;businessId:string;status:string;startsAt:string;endsAt:string;source:string;planCode:string;currency:'USD'};
type Claim={id:string;location_id:string;claimant_name:string;business_email?:string;business_phone?:string;role_title?:string;status:string;created_at:string;location?:{name?:string;city?:string;region?:string}};
type Plan={code:string;name:string;currency:'USD';monthlyPriceCents:number;annualPriceCents:number};
type DurationPreset='day'|'week'|'month'|'year';
type GameType='classic'|'daily'|'hunt';
type EditorTab='featured'|'game';
type Campaign={id:string;dispensaryId:string;businessId:string;gameType:GameType;placement:string;geographyType:string;geographyValue:string|null;radiusKm:number|null;startsAt:string;endsAt:string;status:string;source:string;amountCents:number|null;currency:'USD';title:string|null};
type GameProducts=Record<GameType,{name:string;dayPriceCents?:number;weekPriceCents?:number;monthPriceCents?:number}>;

function localInput(date:Date){const copy=new Date(date.getTime()-date.getTimezoneOffset()*60000);return copy.toISOString().slice(0,16);}
function money(cents:number){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(cents/100);}
function addDuration(startValue:string,preset:DurationPreset){const start=new Date(startValue);if(!Number.isFinite(start.getTime()))return startValue;const end=new Date(start);if(preset==='day')end.setDate(end.getDate()+1);if(preset==='week')end.setDate(end.getDate()+7);if(preset==='month')end.setMonth(end.getMonth()+1);if(preset==='year')end.setFullYear(end.getFullYear()+1);return localInput(end);}
function gameLabel(game:GameType){return game==='classic'?'Classic GeoWeedo':game==='daily'?'Daily Weedo':'Weedo Hunt';}
const DEFAULT_PRODUCTS:GameProducts={classic:{name:'Classic Sponsor',dayPriceCents:1000,weekPriceCents:4900,monthPriceCents:14900},daily:{name:'Daily Weedo Sponsor',dayPriceCents:1500,weekPriceCents:7900,monthPriceCents:24900},hunt:{name:'Sponsored Weedo Hunt',weekPriceCents:9900,monthPriceCents:29900}};

export default function AdminSponsorshipManager(){
 const[dispensaries,setDispensaries]=useState<Dispensary[]>([]),[items,setItems]=useState<Entitlement[]>([]),[campaigns,setCampaigns]=useState<Campaign[]>([]),[claims,setClaims]=useState<Claim[]>([]);
 const[plan,setPlan]=useState<Plan>({code:'featured',name:'GeoWeedo Featured',currency:'USD',monthlyPriceCents:3900,annualPriceCents:39000}),[products,setProducts]=useState<GameProducts>(DEFAULT_PRODUCTS);
 const now=()=>localInput(new Date());
 const[selectedDispensaryId,setSelectedDispensaryId]=useState('');
 const[form,setForm]=useState({source:'admin_comp',status:'active',startsAt:now(),endsAt:localInput(new Date(Date.now()+30*86400000))});
 const[campaignForm,setCampaignForm]=useState({gameType:'classic' as GameType,title:'',geographyType:'all',geographyValue:'',radiusKm:'25',source:'admin_comp',status:'active',startsAt:now(),endsAt:localInput(new Date(Date.now()+86400000)),amountUsd:''});
 const[dispensarySearch,setDispensarySearch]=useState(''),[status,setStatus]=useState('Loading business sponsorship workspace…'),[busy,setBusy]=useState(false),[editorTab,setEditorTab]=useState<EditorTab>('featured');
 const names=useMemo(()=>new Map(dispensaries.map(item=>[item.id,item])),[dispensaries]);
 const choices=useMemo(()=>{const q=dispensarySearch.trim().toLowerCase();return q?dispensaries.filter(item=>`${item.name} ${item.city} ${item.region}`.toLowerCase().includes(q)):dispensaries;},[dispensaries,dispensarySearch]);
 const selectedFeatured=useMemo(()=>items.find(item=>item.dispensaryId===selectedDispensaryId),[items,selectedDispensaryId]);
 const selectedName=names.get(selectedDispensaryId)?.name||selectedDispensaryId||'No dispensary selected';

 async function load(){
  const[sponsorResponse,claimResponse]=await Promise.all([fetch('/api/admin/sponsorships',{cache:'no-store'}),fetch('/api/admin/owner-claims?status=pending',{cache:'no-store'})]);
  if(sponsorResponse.status===401||claimResponse.status===401){window.location.href='/admin/login?next=/admin/sponsorships';return;}
  const sponsorData=await sponsorResponse.json().catch(()=>({})),claimData=await claimResponse.json().catch(()=>({}));
  if(sponsorResponse.status===403||claimResponse.status===403)throw new Error(sponsorData.error||claimData.error||'Your admin account does not have permission to manage sponsorships.');
  if(!sponsorResponse.ok)throw new Error(sponsorData.error||'Sponsorship admin access failed.');
  if(!claimResponse.ok)throw new Error(claimData.error||'Could not load ownership claims.');
  const ds:Dispensary[]=sponsorData.dispensaries||[];
  setDispensaries(ds);setItems(sponsorData.entitlements||[]);setCampaigns(sponsorData.campaigns||[]);setClaims(claimData.claims||[]);
  if(sponsorData.plan)setPlan(sponsorData.plan);if(sponsorData.gameProducts)setProducts(sponsorData.gameProducts);
  setSelectedDispensaryId(current=>current&&ds.some(item=>item.id===current)?current:(ds[0]?.id||''));
  setStatus('Sponsorship workspace ready. Featured and game sponsorships control promotion only; normal game selection odds remain unchanged.');
 }
 useEffect(()=>{load().catch(error=>setStatus(error.message));},[]);

 function selectDispensary(id:string,loadExisting=true){
  if(!id)return;
  setSelectedDispensaryId(id);
  if(loadExisting){
   const existing=items.find(item=>item.dispensaryId===id);
   if(existing){setForm({source:existing.source,status:existing.status,startsAt:localInput(new Date(existing.startsAt)),endsAt:localInput(new Date(existing.endsAt))});}
   else{const start=now();setForm({source:'admin_comp',status:'active',startsAt:start,endsAt:addDuration(start,'month')});}
  }
 }
 function handleSearch(value:string){
  setDispensarySearch(value);
  const q=value.trim().toLowerCase();
  if(!q)return;
  const matches=dispensaries.filter(item=>`${item.name} ${item.city} ${item.region}`.toLowerCase().includes(q));
  if(matches.length===1)selectDispensary(matches[0].id);
 }
 function editFeatured(item:Entitlement){setDispensarySearch('');selectDispensary(item.dispensaryId);setEditorTab('featured');window.scrollTo({top:0,behavior:'smooth'});}
 function quickButtons(onPick:(p:DurationPreset)=>void){return <div style={{display:'flex',gap:6,flexWrap:'wrap',alignItems:'center'}}><span style={{fontSize:12,opacity:.72,marginRight:2}}>Duration:</span>{([['day','1 day'],['week','1 week'],['month','1 month'],['year','1 year']] as Array<[DurationPreset,string]>).map(([p,label])=><button key={p} type="button" className="ghost" style={{padding:'6px 10px',minHeight:0}} onClick={()=>onPick(p)}>{label}</button>)}</div>;}

 async function saveFeatured(){if(!selectedDispensaryId)return;setBusy(true);setStatus(`Saving Featured listing for ${selectedName}…`);try{const response=await fetch('/api/admin/sponsorships',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({dispensaryId:selectedDispensaryId,...form,startsAt:new Date(form.startsAt).toISOString(),endsAt:new Date(form.endsAt).toISOString()})});if(response.status===401){window.location.href='/admin/login?next=/admin/sponsorships';return;}const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Could not save Featured entitlement.');setStatus(`Featured listing saved for ${selectedName}.`);await load();}catch(error){setStatus(error instanceof Error?error.message:'Could not save Featured entitlement.');}finally{setBusy(false);}}
 async function saveCampaign(){if(!selectedDispensaryId)return;setBusy(true);setStatus(`Saving ${gameLabel(campaignForm.gameType)} sponsorship for ${selectedName}…`);try{const response=await fetch('/api/admin/sponsorships',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'campaign',dispensaryId:selectedDispensaryId,...campaignForm,startsAt:new Date(campaignForm.startsAt).toISOString(),endsAt:new Date(campaignForm.endsAt).toISOString(),amountCents:campaignForm.amountUsd===''?null:Math.round(Number(campaignForm.amountUsd)*100)})});if(response.status===401){window.location.href='/admin/login?next=/admin/sponsorships';return;}const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Could not save game sponsorship.');setStatus(`${gameLabel(campaignForm.gameType)} sponsorship activated for ${selectedName}.`);await load();}catch(error){setStatus(error instanceof Error?error.message:'Could not save game sponsorship.');}finally{setBusy(false);}}
 async function endSponsorship(kind:'featured'|'campaign',id:string,label:string){if(!window.confirm(`End sponsorship for ${label} now?`))return;setBusy(true);setStatus(`Ending sponsorship for ${label}…`);try{const response=await fetch('/api/admin/sponsorships',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind,id})});if(response.status===401){window.location.href='/admin/login?next=/admin/sponsorships';return;}const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Could not end sponsorship.');setStatus(`Sponsorship ended for ${label}.`);await load();}catch(error){setStatus(error instanceof Error?error.message:'Could not end sponsorship.');}finally{setBusy(false);}}
 async function moderateClaim(claimId:string,nextStatus:'approved'|'rejected'){setBusy(true);setStatus(`${nextStatus==='approved'?'Approving':'Rejecting'} ownership claim…`);try{const response=await fetch('/api/admin/owner-claims',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({claimId,status:nextStatus})});if(response.status===401){window.location.href='/admin/login?next=/admin/sponsorships';return;}const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Could not moderate ownership claim.');setStatus(`Ownership claim ${nextStatus}.`);await load();}catch(error){setStatus(error instanceof Error?error.message:'Could not moderate ownership claim.');}finally{setBusy(false);}}
 async function logout(){await fetch('/api/admin/auth/logout',{method:'POST'});window.location.href='/admin/login';}

 const product=products[campaignForm.gameType]||DEFAULT_PRODUCTS[campaignForm.gameType];
 const priceLine=[product.dayPriceCents&&`${money(product.dayPriceCents)}/day`,product.weekPriceCents&&`${money(product.weekPriceCents)}/week`,product.monthPriceCents&&`${money(product.monthPriceCents)}/month`].filter(Boolean).join(' · ');
 const tabButton=(tab:EditorTab,label:string)=><button type="button" className={editorTab===tab?'primary':'ghost'} onClick={()=>setEditorTab(tab)} style={{padding:'9px 14px',minHeight:0}}>{label}</button>;

 return <main className="admin-shell">
  <header className="admin-header"><div><span className="eyebrow">GEOWEEDO ADMIN</span><h1>Businesses & Sponsorships</h1></div><div className="admin-links"><a href="/admin/data">Data import</a><a href="/admin/dispensaries">Dispensaries</a><a href="/admin/rewards">Rewards</a><a href="/">Game</a><button className="ghost" onClick={logout}>Log out</button></div></header>
  <div className="admin-status">{status}</div>

  <section className="admin-panel sponsorship-compact" style={{padding:'18px 20px'}}>
   <div style={{display:'flex',justifyContent:'space-between',gap:18,alignItems:'flex-start',flexWrap:'wrap',marginBottom:12}}><div><h2 style={{margin:'0 0 4px'}}>GeoWeedo Featured</h2><p style={{margin:0,opacity:.72,fontSize:13}}>{money(plan.monthlyPriceCents)}/month · {money(plan.annualPriceCents)}/year · Featured + optional game sponsorships</p></div><div style={{display:'flex',gap:8}}>{tabButton('featured','Featured listing')}{tabButton('game','Game sponsorship')}</div></div>

   <div className="admin-form" style={{gap:10}}>
    <div className="field-row"><label><span>Search dispensaries</span><input type="search" value={dispensarySearch} onChange={e=>handleSearch(e.target.value)} placeholder="Search by name, city or state…"/></label><label><span>Dispensary</span><select value={selectedDispensaryId} onChange={e=>selectDispensary(e.target.value)}>{choices.length===0?<option value="">No matching dispensaries</option>:choices.map(item=><option value={item.id} key={item.id}>{item.name} — {item.city}, {item.region}</option>)}</select></label></div>
    {choices.length>1&&dispensarySearch.trim()&&<div style={{display:'flex',gap:6,flexWrap:'wrap'}}>{choices.slice(0,12).map(item=><button key={item.id} type="button" className={selectedDispensaryId===item.id?'primary':'ghost'} style={{padding:'6px 10px',minHeight:0}} onClick={()=>selectDispensary(item.id)}>{item.name} · {item.city}</button>)}</div>}

    <div style={{display:'flex',justifyContent:'space-between',gap:14,alignItems:'center',padding:'10px 12px',border:'1px solid rgba(255,255,255,.09)',borderRadius:12,background:'rgba(255,255,255,.025)',flexWrap:'wrap'}}><div><strong>Selected: {selectedName}</strong><div style={{fontSize:12,opacity:.72,marginTop:3}}>Current Featured status: {selectedFeatured?<><b style={{textTransform:'uppercase',color:selectedFeatured.status==='active'?'#67d66e':'inherit'}}>{selectedFeatured.status}</b> · {new Date(selectedFeatured.startsAt).toLocaleString()} → {new Date(selectedFeatured.endsAt).toLocaleString()}</>:'Not Featured'}</div></div>{selectedFeatured?.status==='active'?<button type="button" className="ghost" disabled={busy} onClick={()=>endSponsorship('featured',selectedFeatured.id,selectedName)}>End sponsorship</button>:null}</div>

    {editorTab==='featured'?<div style={{display:'grid',gap:10,paddingTop:6,borderTop:'1px solid rgba(255,255,255,.08)'}}>
     <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,flexWrap:'wrap'}}><div><strong>Featured listing</strong><div style={{fontSize:12,opacity:.68,marginTop:2}}>Enhanced pin, profile treatment, Browse priority and Featured analytics.</div></div>{quickButtons(p=>setForm(current=>({...current,endsAt:addDuration(current.startsAt,p)})))}</div>
     <div className="field-row"><label><span>Starts</span><input type="datetime-local" value={form.startsAt} onChange={e=>setForm({...form,startsAt:e.target.value})}/></label><label><span>Ends</span><input type="datetime-local" value={form.endsAt} onChange={e=>setForm({...form,endsAt:e.target.value})}/></label></div>
     <div className="field-row"><label><span>Source</span><select value={form.source} onChange={e=>setForm({...form,source:e.target.value})}><option value="admin_comp">Admin comp / beta</option><option value="manual_invoice">Manual USD invoice</option><option value="subscription">USD subscription</option></select></label><label><span>Status</span><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="active">Active</option><option value="expired">Expired</option><option value="cancelled">Cancelled</option></select></label></div>
     <button className="primary" disabled={busy||!selectedDispensaryId} onClick={saveFeatured}>Save Featured listing for {selectedName}</button>
    </div>:<div style={{display:'grid',gap:10,paddingTop:6,borderTop:'1px solid rgba(255,255,255,.08)'}}>
     <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,flexWrap:'wrap'}}><div><strong>{product.name}</strong><div style={{fontSize:12,opacity:.68,marginTop:2}}>{priceLine} · Presented by placement · no change to mystery-location odds.</div></div>{quickButtons(p=>setCampaignForm(current=>({...current,endsAt:addDuration(current.startsAt,p)})))}</div>
     <div className="field-row"><label><span>Game</span><select value={campaignForm.gameType} onChange={e=>setCampaignForm({...campaignForm,gameType:e.target.value as GameType})}><option value="classic">Classic GeoWeedo</option><option value="daily">Daily Weedo</option><option value="hunt">Weedo Hunt</option></select></label><label><span>Campaign title (optional)</span><input value={campaignForm.title} onChange={e=>setCampaignForm({...campaignForm,title:e.target.value})} placeholder="e.g. Green Gold California Hunt"/></label></div>
     <div className="field-row"><label><span>Geography</span><select value={campaignForm.geographyType} onChange={e=>setCampaignForm({...campaignForm,geographyType:e.target.value})}><option value="all">All players</option><option value="country">Country</option><option value="region">State / Province</option><option value="city">City / Region</option><option value="radius">Radius around sponsor</option></select></label>{campaignForm.geographyType!=='all'&&campaignForm.geographyType!=='radius'?<label><span>Target value</span><input value={campaignForm.geographyValue} onChange={e=>setCampaignForm({...campaignForm,geographyValue:e.target.value})} placeholder={campaignForm.geographyType==='country'?'USA':campaignForm.geographyType==='region'?'California':'San Andreas'}/></label>:campaignForm.geographyType==='radius'?<label><span>Radius (km)</span><input type="number" min="1" step="1" value={campaignForm.radiusKm} onChange={e=>setCampaignForm({...campaignForm,radiusKm:e.target.value})}/></label>:<label><span>Target</span><input value="All GeoWeedo players" disabled/></label>}</div>
     <div className="field-row"><label><span>Starts</span><input type="datetime-local" value={campaignForm.startsAt} onChange={e=>setCampaignForm({...campaignForm,startsAt:e.target.value})}/></label><label><span>Ends</span><input type="datetime-local" value={campaignForm.endsAt} onChange={e=>setCampaignForm({...campaignForm,endsAt:e.target.value})}/></label></div>
     <div className="field-row"><label><span>Source</span><select value={campaignForm.source} onChange={e=>setCampaignForm({...campaignForm,source:e.target.value})}><option value="admin_comp">Admin comp / beta</option><option value="manual_invoice">Manual USD invoice</option><option value="subscription">USD subscription</option></select></label><label><span>Amount USD (optional)</span><input type="number" min="0" step="1" value={campaignForm.amountUsd} onChange={e=>setCampaignForm({...campaignForm,amountUsd:e.target.value})} placeholder="0"/></label></div>
     <div className="field-row"><label><span>Status</span><select value={campaignForm.status} onChange={e=>setCampaignForm({...campaignForm,status:e.target.value})}><option value="active">Active</option><option value="paused">Paused</option><option value="expired">Expired</option><option value="cancelled">Cancelled</option></select></label><label><span>Placement</span><input value="Presented by" disabled/></label></div>
     <button className="primary" disabled={busy||!selectedDispensaryId} onClick={saveCampaign}>Save {gameLabel(campaignForm.gameType)} sponsorship for {selectedName}</button>
    </div>}
   </div>

   <details style={{marginTop:12,borderTop:'1px solid rgba(255,255,255,.08)',paddingTop:10}}><summary style={{cursor:'pointer',fontWeight:800}}>Policy & current capabilities</summary><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:8,marginTop:10}}><div className="source-note"><strong>Classic GeoWeedo</strong><span>Presented by exposure and sponsor analytics. Sponsors never influence the five mystery Street View rounds.</span></div><div className="source-note"><strong>Daily Weedo</strong><span>One overlapping active sponsor. Daily location remains deterministic and identical for every player.</span></div><div className="source-note"><strong>Weedo Hunt</strong><span>Sponsored Hunt / Presented by promotion and analytics. Standard Hunt target selection remains independent.</span></div><div className="source-note"><strong>Scheduling & billing</strong><span>Exact dates or 1 day, 1 week, 1 month and 1 year shortcuts. Admin comp, manual USD invoice or USD subscription.</span></div><div className="source-note"><strong>Geography</strong><span>All players, country, state/province, city/region or radius can be stored. Viewer-side geographic enforcement is not live yet.</span></div><div className="source-note"><strong>Analytics</strong><span>Game impressions/completions, sponsor profile/website activity and Featured map/profile analytics.</span></div></div></details>
  </section>

  <section className="admin-panel approved-list"><h2>Active & scheduled game sponsorships</h2>{campaigns.length===0?<p>No game sponsorships yet. Use the GeoWeedo Featured panel above to create a 1-day Admin comp test.</p>:campaigns.map(item=>{const d=names.get(item.dispensaryId);const geo=item.geographyType==='all'?'all players':item.geographyType==='radius'?`${item.radiusKm} km radius`:`${item.geographyType}: ${item.geographyValue||'—'}`;return <div className="candidate-row" key={item.id}><div><strong>{gameLabel(item.gameType)} · {item.title||d?.name||item.dispensaryId}</strong><span>{d?.name||item.dispensaryId} · {new Date(item.startsAt).toLocaleString()} → {new Date(item.endsAt).toLocaleString()}</span><small>{geo} · {item.source.replaceAll('_',' ')}{item.amountCents!=null?` · ${money(item.amountCents)}`:''}</small></div><div className="candidate-actions"><span className={`status-pill ${item.status}`}>{item.status}</span>{item.status==='active'||item.status==='paused'?<button disabled={busy} onClick={()=>endSponsorship('campaign',item.id,`${gameLabel(item.gameType)} · ${d?.name||item.dispensaryId}`)}>End sponsorship</button>:null}</div></div>;})}</section>
  <section className="admin-panel approved-list"><h2>Pending business claims</h2>{claims.length===0?<p>No pending ownership claims.</p>:claims.map(claim=><div className="candidate-row" key={claim.id}><div><strong>{claim.location?.name||claim.location_id}</strong><span>{claim.claimant_name}{claim.role_title?` · ${claim.role_title}`:''}</span><small>{claim.business_email||claim.business_phone||'No contact shown'} · submitted {new Date(claim.created_at).toLocaleDateString()}</small></div><div className="candidate-actions"><button disabled={busy} onClick={()=>moderateClaim(claim.id,'approved')}>Approve claim</button><button disabled={busy} onClick={()=>moderateClaim(claim.id,'rejected')}>Reject</button></div></div>)}</section>
  <section className="admin-panel approved-list"><h2>All Featured listings</h2>{items.length===0?<p>No Featured listings yet.</p>:items.map(item=>{const d=names.get(item.dispensaryId),label=d?.name||item.dispensaryId;return <div className="candidate-row" key={item.id}><div><strong>{label}</strong><span>{plan.name} · USD · {new Date(item.startsAt).toLocaleDateString()} → {new Date(item.endsAt).toLocaleDateString()}</span><small>{item.source.replaceAll('_',' ')} · business {item.businessId}</small></div><div className="candidate-actions"><span className={`status-pill ${item.status}`}>{item.status}</span><button disabled={busy} onClick={()=>editFeatured(item)}>Edit</button>{item.status==='active'?<button disabled={busy} onClick={()=>endSponsorship('featured',item.id,label)}>End sponsorship</button>:null}</div></div>;})}</section>
 </main>;
}
