'use client';

import {useEffect,useMemo,useState} from 'react';

type LocationRow={country:string;region:string;city:string;sessions:number};
type Visitor={visitorId:string;sessions:number;pageViews:number;lastSeen:string;country:string;region:string;city:string;activeNow:boolean};
type GeoRow={key:string;country:string;region:string;city:string;label:string;sessions:number;users:number;pageViews:number;live:number;lastSeen:string;share:number};
type SortKey='sessions'|'users'|'pageViews'|'live'|'share'|'lastSeen';
type Props={locations:LocationRow[];totalSessions:number;days:number;excludeAdmin:boolean;excludedIps:string[]};

function geoKey(city:string,region:string,country:string){return `${city.trim().toLowerCase()}|${region.trim().toLowerCase()}|${country.trim().toLowerCase()}`;}
function labelFor(city:string,region:string,country:string){return [city,region,country].map(v=>v.trim()).filter(Boolean).join(', ')||'Unknown';}
function when(value:string){return value?new Date(value).toLocaleString():'—';}
async function responseJson(response:Response){const text=await response.text();if(!text)throw new Error(`Analytics API returned an empty response (${response.status}).`);try{return JSON.parse(text);}catch{throw new Error(`Analytics API returned an invalid response (${response.status}).`);}}

export default function AdminAnalyticsGeography({locations,totalSessions,days,excludeAdmin,excludedIps}:Props){
 const [visitors,setVisitors]=useState<Visitor[]>([]),[query,setQuery]=useState(''),[sortKey,setSortKey]=useState<SortKey>('sessions'),[descending,setDescending]=useState(true),[error,setError]=useState('');
 useEffect(()=>{let cancelled=false;const load=async()=>{try{const params=new URLSearchParams({mode:'users',days:String(days),excludeAdmin:excludeAdmin?'1':'0'});if(excludedIps.length)params.set('excludeIps',excludedIps.join(','));const response=await fetch(`/api/admin/analytics?${params}`,{cache:'no-store'});const data=await responseJson(response);if(response.status===401){location.href='/admin/login';return;}if(!response.ok)throw new Error(data?.error||'Visitor geography details failed to load.');if(!cancelled){setVisitors(Array.isArray(data?.users)?data.users:[]);setError('');}}catch(e){if(!cancelled)setError(e instanceof Error?e.message:'Visitor geography details failed to load.');}};void load();return()=>{cancelled=true};},[days,excludeAdmin,excludedIps]);
 const rows=useMemo(()=>{
  const userMap=new Map<string,{ids:Set<string>;pageViews:number;live:number;lastSeen:string}>();
  for(const visitor of visitors){const key=geoKey(visitor.city||'',visitor.region||'',visitor.country||'');const current=userMap.get(key)||{ids:new Set<string>(),pageViews:0,live:0,lastSeen:''};current.ids.add(visitor.visitorId);current.pageViews+=Number(visitor.pageViews||0);if(visitor.activeNow)current.live+=1;if(visitor.lastSeen&&(!current.lastSeen||visitor.lastSeen>current.lastSeen))current.lastSeen=visitor.lastSeen;userMap.set(key,current);}
  return locations.map((location,index)=>{const country=String(location.country||''),region=String(location.region||''),city=String(location.city||''),key=geoKey(city,region,country),details=userMap.get(key),sessions=Number(location.sessions||0);return{key:`${key}-${index}`,country,region,city,label:labelFor(city,region,country),sessions,users:details?.ids.size||0,pageViews:details?.pageViews||0,live:details?.live||0,lastSeen:details?.lastSeen||'',share:totalSessions>0?sessions/totalSessions:0};});
 },[locations,visitors,totalSessions]);
 const unknown=useMemo(()=>rows.filter(row=>row.label==='Unknown').reduce((acc,row)=>({sessions:acc.sessions+row.sessions,users:acc.users+row.users,pageViews:acc.pageViews+row.pageViews,live:acc.live+row.live,share:acc.share+row.share}),{sessions:0,users:0,pageViews:0,live:0,share:0}),[rows]);
 const known=useMemo(()=>{const q=query.trim().toLowerCase();const filtered=rows.filter(row=>row.label!=='Unknown'&&(!q||row.label.toLowerCase().includes(q)));return [...filtered].sort((a,b)=>{let result=0;if(sortKey==='lastSeen')result=a.lastSeen.localeCompare(b.lastSeen);else result=Number(a[sortKey])-Number(b[sortKey]);if(result===0)result=a.label.localeCompare(b.label);return descending?-result:result;});},[rows,query,sortKey,descending]);
 const knownSessions=rows.filter(row=>row.label!=='Unknown').reduce((sum,row)=>sum+row.sessions,0),countryCount=new Set(rows.filter(row=>row.label!=='Unknown'&&row.country).map(row=>row.country)).size;
 const setSort=(key:SortKey)=>{if(sortKey===key)setDescending(value=>!value);else{setSortKey(key);setDescending(true);}};
 const sortButton=(key:SortKey,label:string)=><button type="button" onClick={()=>setSort(key)} style={{border:0,background:'transparent',color:'inherit',font:'inherit',fontWeight:800,padding:0,cursor:'pointer',whiteSpace:'nowrap'}}>{label}{sortKey===key?(descending?' ↓':' ↑'):''}</button>;
 return <div style={{display:'grid',gap:12}}>
  <div style={{display:'flex',gap:10,flexWrap:'wrap',alignItems:'stretch'}}>
   <div style={{flex:'1 1 150px',padding:'12px 14px',border:'1px solid rgba(255,255,255,.1)',borderRadius:12,background:'rgba(255,255,255,.025)'}}><small style={{opacity:.62}}>KNOWN GEO SESSIONS</small><strong style={{display:'block',fontSize:22,marginTop:2}}>{knownSessions.toLocaleString()}</strong><span style={{fontSize:12,opacity:.68}}>{totalSessions?`${Math.round((knownSessions/totalSessions)*100)}% of traffic`:'No traffic yet'}</span></div>
   <div style={{flex:'1 1 150px',padding:'12px 14px',border:'1px solid rgba(255,255,255,.1)',borderRadius:12,background:'rgba(255,255,255,.025)'}}><small style={{opacity:.62}}>COUNTRIES</small><strong style={{display:'block',fontSize:22,marginTop:2}}>{countryCount.toLocaleString()}</strong><span style={{fontSize:12,opacity:.68}}>with known location</span></div>
   <div style={{flex:'1 1 150px',padding:'12px 14px',border:'1px solid rgba(255,255,255,.1)',borderRadius:12,background:'rgba(255,255,255,.025)'}}><small style={{opacity:.62}}>UNKNOWN</small><strong style={{display:'block',fontSize:22,marginTop:2}}>{unknown.sessions.toLocaleString()}</strong><span style={{fontSize:12,opacity:.68}}>{totalSessions?`${Math.round(unknown.share*100)}% of traffic`:'0% of traffic'}</span></div>
   <div style={{flex:'2 1 260px',display:'flex',alignItems:'center'}}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search city, region, or country…" style={{width:'100%',padding:'11px 12px',borderRadius:10,border:'1px solid rgba(255,255,255,.12)',background:'#0f1411',color:'#fff'}}/></div>
  </div>
  {error&&<div style={{fontSize:12,color:'#ffb3b3'}}>{error}</div>}
  <div style={{overflowX:'auto',border:'1px solid rgba(255,255,255,.1)',borderRadius:14}}>
   <table style={{width:'100%',borderCollapse:'collapse',minWidth:820}}>
    <thead><tr style={{textAlign:'left',background:'rgba(255,255,255,.035)'}}><th style={{padding:'11px 12px'}}>Location</th><th style={{padding:'11px 12px'}}>{sortButton('sessions','Sessions')}</th><th style={{padding:'11px 12px'}}>{sortButton('users','Users')}</th><th style={{padding:'11px 12px'}}>{sortButton('pageViews','Views')}</th><th style={{padding:'11px 12px'}}>{sortButton('live','Live')}</th><th style={{padding:'11px 12px'}}>{sortButton('share','Traffic share')}</th><th style={{padding:'11px 12px'}}>{sortButton('lastSeen','Last seen')}</th></tr></thead>
    <tbody>{known.length?known.map(row=><tr key={row.key} style={{borderTop:'1px solid rgba(255,255,255,.07)'}}><td style={{padding:'10px 12px',fontWeight:750}}>{row.label}</td><td style={{padding:'10px 12px'}}>{row.sessions.toLocaleString()}</td><td style={{padding:'10px 12px'}}>{row.users.toLocaleString()}</td><td style={{padding:'10px 12px'}}>{row.pageViews.toLocaleString()}</td><td style={{padding:'10px 12px'}}>{row.live?<strong style={{color:'var(--accent)'}}>{row.live.toLocaleString()}</strong>:'—'}</td><td style={{padding:'10px 12px',minWidth:150}}><div style={{display:'flex',alignItems:'center',gap:8}}><span style={{width:48,fontVariantNumeric:'tabular-nums'}}>{(row.share*100).toFixed(row.share>=.1?0:1)}%</span><span style={{display:'block',height:7,flex:1,minWidth:60,borderRadius:999,background:'rgba(255,255,255,.07)',overflow:'hidden'}}><i style={{display:'block',height:'100%',width:`${Math.max(row.share>0?2:0,row.share*100)}%`,background:'var(--accent)',borderRadius:999}}/></span></div></td><td style={{padding:'10px 12px',whiteSpace:'nowrap'}}>{when(row.lastSeen)}</td></tr>):<tr><td colSpan={7} style={{padding:18,opacity:.65}}>No known locations match this search.</td></tr>}</tbody>
    {unknown.sessions>0&&<tfoot><tr style={{borderTop:'1px solid rgba(255,255,255,.12)',background:'rgba(255,255,255,.02)',opacity:.72}}><td style={{padding:'10px 12px',fontWeight:750}}>Unknown location</td><td style={{padding:'10px 12px'}}>{unknown.sessions.toLocaleString()}</td><td style={{padding:'10px 12px'}}>{unknown.users.toLocaleString()}</td><td style={{padding:'10px 12px'}}>{unknown.pageViews.toLocaleString()}</td><td style={{padding:'10px 12px'}}>{unknown.live||'—'}</td><td style={{padding:'10px 12px'}}>{(unknown.share*100).toFixed(1)}%</td><td style={{padding:'10px 12px'}}>—</td></tr></tfoot>}
   </table>
  </div>
  <div style={{fontSize:11,opacity:.58}}>Sessions and traffic share include all recorded traffic with the current filters. Users, views, live status, and last-seen detail are enriched from identified visitor records.</div>
 </div>;
}
