'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { Viewer } from '@photo-sphere-viewer/core';
import { gradeImagery } from '@/lib/imageryQuality';

type StreetPhoto = { id:string; lat:number; lng:number; heading:number; fieldOfView:number; projection:string; imageUrl:string; sequenceId:string; sequenceIndex:number; shotDate?:string|null; width?:number; height?:number; status?:string; qualityLevel?:number };
type SavedDispensary = { id:string; name:string; city:string; region:string; country:string; imageryProvider:string; dataSource?:string; active:boolean };
type CandidateDraft = { name?:string; streetAddress?:string; city?:string; region?:string; country?:string; website?:string; latitude?:number; longitude?:number; dataSource?:string; sourceUrl?:string; sourceLicense?:string };

const emptyForm = { name:'', streetAddress:'', city:'', region:'', country:'USA', website:'', dataSource:'manual', sourceUrl:'', sourceLicense:'', latitude:'', longitude:'', recreational:true, medical:false };

export default function AdminDispensaryManager(){
  const [form,setForm]=useState(emptyForm),[photos,setPhotos]=useState<StreetPhoto[]>([]),[selectedIndex,setSelectedIndex]=useState(0),[imageryProvider,setImageryProvider]=useState<'kartaview'|'geoweedo'>('kartaview'),[hostedFile,setHostedFile]=useState<File|null>(null),[hosted360,setHosted360]=useState(false),[saved,setSaved]=useState<SavedDispensary[]>([]),[status,setStatus]=useState('Loading imagery validator…'),[busy,setBusy]=useState(false);
  const sphereRef=useRef<HTMLDivElement|null>(null),viewerRef=useRef<Viewer|null>(null);

  useEffect(()=>{try{const raw=sessionStorage.getItem('geoweedo-candidate-draft');if(raw){const d=JSON.parse(raw) as CandidateDraft;setForm(c=>({...c,name:d.name||'',streetAddress:d.streetAddress||'',city:d.city||'',region:d.region||'',country:d.country||'USA',website:d.website||'',latitude:d.latitude===undefined?'':String(d.latitude),longitude:d.longitude===undefined?'':String(d.longitude),dataSource:d.dataSource||'state-registry',sourceUrl:d.sourceUrl||'',sourceLicense:d.sourceLicense||''}));setStatus('Candidate loaded. It must pass gameplay imagery grading before approval.');sessionStorage.removeItem('geoweedo-candidate-draft');}}catch{}loadSaved().catch(e=>setStatus(e.message));},[]);

  const selected=photos[selectedIndex];
  const isSphere=useMemo(()=>Boolean(selected&&(selected.projection==='SPHERE'||selected.projection==='EQUIRECTANGULAR'||selected.fieldOfView>=300)),[selected]);
  const quality=useMemo(()=>{
    if(imageryProvider==='geoweedo'){
      if(selected&&isSphere)return {playable:true,grade:'A' as const,mode:'360' as const,reason:'GeoWeedo-hosted 360° panorama.',frameCount:1,landscapeFrames:0,landscapeRatio:1};
      return {playable:false,grade:'F' as const,mode:'unusable' as const,reason:'A single flat hosted image is not navigable gameplay imagery. Upload a true 360° panorama.',frameCount:selected?1:0,landscapeFrames:0,landscapeRatio:0};
    }
    return gradeImagery(selected,photos);
  },[selected,photos,imageryProvider,isSphere]);

  useEffect(()=>{viewerRef.current?.destroy();viewerRef.current=null;if(!selected||!isSphere||!sphereRef.current)return;viewerRef.current=new Viewer({container:sphereRef.current,panorama:selected.imageUrl,navbar:['zoom','move','fullscreen'],defaultYaw:((selected.heading||0)*Math.PI)/180,mousemove:true,mousewheel:true,mousewheelCtrlKey:false,touchmoveTwoFingers:false});return()=>{viewerRef.current?.destroy();viewerRef.current=null;};},[selected,isSphere]);

  async function loadSaved(){const r=await fetch('/api/admin/dispensaries',{cache:'no-store'});if(r.status===401){window.location.href='/admin/login';return;}const d=await r.json();if(!r.ok)throw new Error(d.error||'Admin access failed.');setSaved(d.dispensaries||[]);setStatus(c=>c.startsWith('Candidate loaded')?c:'Imagery validator ready.');}
  async function geocode(){const q=[form.streetAddress,form.city,form.region,form.country].filter(Boolean).join(', ');if(!q)return setStatus('Enter an address first.');setBusy(true);try{const r=await fetch(`/api/admin/geocode?q=${encodeURIComponent(q)}`);if(r.status===401){window.location.href='/admin/login';return;}const d=await r.json();if(!r.ok)throw new Error(d.error||'Address lookup failed.');const h=d.results?.[0];if(!h)throw new Error('No OpenStreetMap address match found.');setForm(c=>({...c,latitude:String(h.lat),longitude:String(h.lng),city:c.city||h.city||'',region:c.region||h.region||'',country:c.country||h.country||'USA'}));setStatus(`Address matched: ${h.displayName}`);}catch(e){setStatus(e instanceof Error?e.message:'Address lookup failed.');}finally{setBusy(false);}}
  async function checkCoverage(){const lat=Number(form.latitude),lng=Number(form.longitude);if(!Number.isFinite(lat)||!Number.isFinite(lng))return setStatus('Valid coordinates are required first.');setBusy(true);setPhotos([]);setImageryProvider('kartaview');try{const r=await fetch(`/api/street-imagery?lat=${encodeURIComponent(lat)}&lng=${encodeURIComponent(lng)}`);const d=await r.json();if(!r.ok)throw new Error(d.error||'KartaView lookup failed.');const next=d.photos||[];setPhotos(next);setSelectedIndex(Math.min(Math.max(d.initialIndex||0,0),Math.max(0,next.length-1)));setStatus(next.length?`KartaView check complete. ${d.quality?.playable?`Grade ${d.quality.grade}: ${d.quality.reason}`:`Rejected for gameplay: ${d.quality?.reason||'coverage does not meet quality requirements.'}`}`:(d.message||'No KartaView coverage found.'));}catch(e){setStatus(e instanceof Error?e.message:'Coverage lookup failed.');}finally{setBusy(false);}}
  async function uploadHosted(){const lat=Number(form.latitude),lng=Number(form.longitude);if(!hostedFile)return setStatus('Choose a JPEG, PNG, or WebP image first.');if(!form.name.trim())return setStatus('Enter the dispensary name before uploading.');if(!Number.isFinite(lat)||!Number.isFinite(lng))return setStatus('Confirm dispensary coordinates before uploading imagery.');setBusy(true);try{const body=new FormData();body.set('file',hostedFile);body.set('slug',form.name);const r=await fetch('/api/admin/imagery/upload',{method:'POST',body});if(r.status===401){window.location.href='/admin/login';return;}const d=await r.json();if(!r.ok)throw new Error(d.error||'Image upload failed.');const photo:StreetPhoto={id:d.photoId,lat,lng,heading:0,fieldOfView:hosted360?360:0,projection:hosted360?'SPHERE':'FLAT',imageUrl:d.imageUrl,sequenceId:'geoweedo',sequenceIndex:0};setImageryProvider('geoweedo');setPhotos([photo]);setSelectedIndex(0);setStatus(hosted360?'Hosted 360° panorama uploaded. Grade A and eligible after review.':'Flat hosted image uploaded for reference, but it is not eligible for gameplay.');}catch(e){setStatus(e instanceof Error?e.message:'Image upload failed.');}finally{setBusy(false);}}
  async function approve(){if(!selected)return setStatus('Choose imagery first.');if(!quality.playable)return setStatus(`Approval blocked: ${quality.reason}`);setBusy(true);try{const r=await fetch('/api/admin/dispensaries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,latitude:Number(form.latitude),longitude:Number(form.longitude),imageryProvider,imageryPhotoId:selected.id,imagerySequenceId:selected.sequenceId,imageryLatitude:selected.lat,imageryLongitude:selected.lng,imageryHeading:selected.heading,imageryFieldOfView:selected.fieldOfView,imageryProjection:selected.projection,imageryUrl:selected.imageUrl,active:true})});if(r.status===401){window.location.href='/admin/login';return;}const d=await r.json();if(!r.ok)throw new Error(d.error||'Approval failed.');setStatus(`${d.dispensary.name} approved · Grade ${quality.grade} ${quality.mode}.`);setForm(emptyForm);setPhotos([]);setSelectedIndex(0);setHostedFile(null);setHosted360(false);setImageryProvider('kartaview');await loadSaved();}catch(e){setStatus(e instanceof Error?e.message:'Approval failed.');}finally{setBusy(false);}}
  async function toggle(item:SavedDispensary){const r=await fetch('/api/admin/dispensaries',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:item.id,active:!item.active})});if(r.status===401){window.location.href='/admin/login';return;}if(r.ok)await loadSaved();}
  async function logout(){await fetch('/api/admin/auth/logout',{method:'POST'});window.location.href='/admin/login';}

  return <main className="admin-shell">
    <header className="admin-header"><div><span className="eyebrow">GEOWEEDO ADMIN</span><h1>Dispensary imagery validation</h1></div><div className="admin-links"><a href="/admin/data">Data import</a><a href="/admin/rewards">Rewards</a><a href="/admin/sponsorships">Sponsorships</a><a href="/admin/withdrawals">Withdrawals</a><a href="/">Game</a><button className="ghost" onClick={logout}>Log out</button></div></header>
    <div className="admin-status">{status}</div>
    <section className="admin-grid">
      <div className="admin-panel"><h2>Dispensary</h2><div className="admin-form">
        <input placeholder="Dispensary name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input placeholder="Street address" value={form.streetAddress} onChange={e=>setForm({...form,streetAddress:e.target.value})}/>
        <div className="field-row"><input placeholder="City" value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/><input placeholder="State / region" value={form.region} onChange={e=>setForm({...form,region:e.target.value})}/></div>
        <div className="field-row"><input placeholder="Country" value={form.country} onChange={e=>setForm({...form,country:e.target.value})}/><input placeholder="Website (optional)" value={form.website} onChange={e=>setForm({...form,website:e.target.value})}/></div>
        <div className="field-row"><select value={form.dataSource} onChange={e=>setForm({...form,dataSource:e.target.value})}><option value="manual">Manual / business supplied</option><option value="state-registry">Official license registry</option><option value="open-data">Compatible open data</option><option value="weedmaps-authorized">Weedmaps authorized/API</option></select><input placeholder="Source URL (optional)" value={form.sourceUrl} onChange={e=>setForm({...form,sourceUrl:e.target.value})}/></div>
        <input placeholder="Source license / permission note (optional)" value={form.sourceLicense} onChange={e=>setForm({...form,sourceLicense:e.target.value})}/><button onClick={geocode} disabled={busy}>Find coordinates from address</button>
        <div className="field-row"><input placeholder="Latitude" value={form.latitude} onChange={e=>setForm({...form,latitude:e.target.value})}/><input placeholder="Longitude" value={form.longitude} onChange={e=>setForm({...form,longitude:e.target.value})}/></div>
        <div className="check-row"><label><input type="checkbox" checked={form.recreational} onChange={e=>setForm({...form,recreational:e.target.checked})}/> Recreational</label><label><input type="checkbox" checked={form.medical} onChange={e=>setForm({...form,medical:e.target.checked})}/> Medical</label></div>
        <button className="primary" onClick={checkCoverage} disabled={busy}>Check & grade KartaView coverage</button>
        <div className="hosted-upload"><strong>Or use GeoWeedo-hosted 360° imagery</strong><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setHostedFile(e.target.files?.[0]||null)}/><label><input type="checkbox" checked={hosted360} onChange={e=>setHosted360(e.target.checked)}/> Equirectangular 360° panorama</label><button onClick={uploadHosted} disabled={busy||!hostedFile}>Upload hosted image</button></div>
      </div></div>
      <div className="admin-panel preview-panel"><h2>Validate gameplay imagery</h2>{!selected?<div className="empty-preview">No imagery selected yet.</div>:<><div className="admin-imagery">{isSphere?<div ref={sphereRef} className="admin-sphere"/>:<img src={selected.imageUrl} alt="Selected starting frame"/>}</div>{photos.length>1&&<div className="frame-controls"><button onClick={()=>setSelectedIndex(Math.max(0,selectedIndex-1))} disabled={selectedIndex===0}>← Previous</button><strong>{selectedIndex+1} / {photos.length}</strong><button onClick={()=>setSelectedIndex(Math.min(photos.length-1,selectedIndex+1))} disabled={selectedIndex>=photos.length-1}>Next →</button></div>}<div className="frame-meta"><span>{imageryProvider==='geoweedo'?'GeoWeedo hosted':'KartaView'}</span><span>Photo {selected.id}</span><span>{selected.width&&selected.height?`${selected.width}×${selected.height}`:(isSphere?'360°':'dimensions unavailable')}</span></div><div className={`imagery-quality grade-${quality.grade.toLowerCase()}`}><strong>Grade {quality.grade} · {quality.playable?'PLAYABLE':'BLOCKED'}</strong><span>{quality.reason}</span></div><button className="primary full" onClick={approve} disabled={busy||!quality.playable}>{quality.playable?'Approve into game pool':'Imagery does not qualify'}</button></>}</div>
    </section>
    <section className="admin-panel approved-list"><h2>Approved game pool</h2>{saved.length===0?<p>No approved real dispensaries yet.</p>:saved.map(item=><div className="approved-row" key={item.id}><div><strong>{item.name}</strong><span>{item.city}, {item.region} · {item.imageryProvider} · {item.dataSource||'manual'}</span></div><button onClick={()=>toggle(item)}>{item.active?'Deactivate':'Activate'}</button></div>)}</section>
    <p className="admin-attribution">Gameplay requires Grade A 360° imagery or Grade B landscape KartaView sequences. Portrait, undersized, short, or unverifiable sequences are blocked.</p>
  </main>;
}
