'use client';

import { useEffect, useMemo, useState } from 'react';

type Candidate={id:string;name:string;streetAddress?:string;city?:string;region?:string;country?:string;latitude?:number;longitude?:number;website?:string;licenseNumber?:string;dataSource:string;sourceUrl?:string;sourceLicense?:string;status:string;imageryStatus?:'unchecked'|'coverage'|'no_coverage'|'missing_coordinates'|'error';imageryCount?:number;imageryCheckedAt?:string;imageryMessage?:string;};
type DirectPreset='all'|'oregon-olcc'|'nevada-ccb'|'washington-lcb'|'connecticut-dcp'|'new-york-ocm'|'montana-dor';
const directSources:[DirectPreset,string,string][]=[
 ['oregon-olcc','Oregon · OLCC','Official OLCC cannabis business license data'],
 ['nevada-ccb','Nevada · CCB','Official Cannabis Compliance Board retail locations'],
 ['washington-lcb','Washington · LCB','Official Washington cannabis renewal open data'],
 ['connecticut-dcp','Connecticut · DCP','Licensed cannabis and medical marijuana retail locations'],
 ['new-york-ocm','New York · OCM','Current OCM licenses filtered to retail/dispensary licenses'],
 ['montana-dor','Montana · DOR','Official licensed dispensary locations'],
];

export default function AdminDataManager(){
 const[file,setFile]=useState<File|null>(null),[source,setSource]=useState('official-license-registry'),[sourceUrl,setSourceUrl]=useState(''),[sourceLicense,setSourceLicense]=useState('official public data'),[candidates,setCandidates]=useState<Candidate[]>([]),[status,setStatus]=useState('Loading official licensing data…'),[busy,setBusy]=useState(false);
 const stats=useMemo(()=>({total:candidates.length,coverage:candidates.filter(i=>i.imageryStatus==='coverage').length,noCoverage:candidates.filter(i=>i.imageryStatus==='no_coverage').length,missingCoordinates:candidates.filter(i=>i.imageryStatus==='missing_coordinates').length,unchecked:candidates.filter(i=>!i.imageryStatus||i.imageryStatus==='unchecked').length,mapReady:candidates.filter(i=>Number.isFinite(i.latitude)&&Number.isFinite(i.longitude)&&i.status!=='rejected').length,states:new Set(candidates.map(i=>i.region).filter(Boolean)).size}),[candidates]);
 async function load(){const response=await fetch('/api/admin/candidates',{cache:'no-store'});if(response.status===401){window.location.href='/admin/login';return;}const data=await response.json();if(!response.ok)throw new Error(data.error||'Admin access failed.');setCandidates((data.candidates||[]).slice().reverse());setStatus(`Loaded ${data.candidates?.length||0} candidate records across ${new Set((data.candidates||[]).map((i:Candidate)=>i.region).filter(Boolean)).size} states.`);}
 useEffect(()=>{load().catch(e=>setStatus(e.message));},[]);
 async function upload(){if(!file)return setStatus('Choose a CSV or JSON file first.');setBusy(true);try{const form=new FormData();form.set('file',file);form.set('dataSource',source);form.set('sourceUrl',sourceUrl);form.set('sourceLicense',sourceLicense);const response=await fetch('/api/admin/candidates/import',{method:'POST',body:form});if(response.status===401){window.location.href='/admin/login';return;}const data=await response.json();if(!response.ok)throw new Error(data.error||'Import failed.');setStatus(`Parsed ${data.parsed} rows; added ${data.added} new candidates. ${data.total} candidates are queued.${typeof data.mapReady==='number'?` ${data.mapReady} imported rows are map-ready.`:''}`);await load();}catch(error){setStatus(error instanceof Error?error.message:'Import failed.');}finally{setBusy(false);}}
 async function fetchOfficial(preset:DirectPreset,label:string){setBusy(true);try{const response=await fetch('/api/admin/candidates/fetch-official',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({preset})});if(response.status===401){window.location.href='/admin/login';return;}const data=await response.json();if(!response.ok&&!Array.isArray(data.details))throw new Error(data.error||`${label} fetch failed.`);if(Array.isArray(data.details)){const failed=data.details.filter((i:any)=>!i.ok);const detail=data.details.map((i:any)=>i.ok?`${i.source}: ${i.fetched} / ${i.added} new / ${i.geocoded} map-ready`:`${i.source}: FAILED (${i.error})`).join(' · ');setStatus(`${label}: ${data.fetched||0} fetched, ${data.added||0} new, ${data.geocoded||0} map-ready.${failed.length?` ${failed.length} source(s) failed.`:''} ${detail}`);}else setStatus(`${label}: fetched ${data.fetched}, added ${data.added} new, ${data.geocoded||0} map-ready. ${data.total} queued.`);await load();}catch(error){setStatus(error instanceof Error?error.message:`${label} fetch failed.`);}finally{setBusy(false);}}
 async function checkImageryBatch(){setBusy(true);try{const response=await fetch('/api/admin/candidates/check-imagery',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({limit:10})});if(response.status===401){window.location.href='/admin/login';return;}const data=await response.json();if(!response.ok)throw new Error(data.error||'Batch imagery check failed.');setStatus(`Checked ${data.checked} candidates. KartaView checks remain limited to 10 per run.`);await load();}catch(error){setStatus(error instanceof Error?error.message:'Batch imagery check failed.');}finally{setBusy(false);}}
 function useCaliforniaPreset(){setSource('california-dcc');setSourceUrl('https://www.cannabis.ca.gov/resources/search-for-licensed-business/');setSourceLicense('California DCC official License Search export; GeoWeedo filters to active Type 10 storefront retailers');setStatus('California preset ready. Export DCC license results, choose the file below, then import.');}
 function review(item:Candidate){sessionStorage.setItem('geoweedo-candidate-draft',JSON.stringify(item));window.location.href='/admin/dispensaries';}
 async function reject(item:Candidate){const response=await fetch('/api/admin/candidates',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:item.id,status:'rejected'})});if(response.status===401){window.location.href='/admin/login';return;}await load();}
 async function logout(){await fetch('/api/admin/auth/logout',{method:'POST'});window.location.href='/admin/login';}
 function imageryLabel(item:Candidate){if(item.imageryStatus==='coverage')return`KartaView: ${item.imageryCount||0} nearby`;if(item.imageryStatus==='no_coverage')return'Needs hosted imagery';if(item.imageryStatus==='missing_coordinates')return'Needs coordinates';if(item.imageryStatus==='error')return'Imagery check error';return'Imagery unchecked';}
 return <main className="admin-shell">
  <header className="admin-header"><div><span className="eyebrow">GEOWEEDO ADMIN</span><h1>Official data import</h1></div><div className="admin-links"><a href="/admin/dispensaries">Imagery validator</a><a href="/admin/rewards">Rewards</a><a href="/admin/sponsorships">Sponsorships</a><a href="/admin/withdrawals">Withdrawals</a><a href="/">Game</a><button className="ghost" onClick={logout}>Log out</button></div></header>
  <div className="admin-status">{status}</div>
  <section className="admin-grid">
   <div className="admin-panel"><h2>Import official CSV / JSON</h2><div className="admin-form"><select value={source} onChange={e=>setSource(e.target.value)}><option value="official-license-registry">Official license registry</option><option value="california-dcc">California DCC</option><option value="state-open-data">Other state open data</option><option value="business-supplied">Business supplied</option><option value="weedmaps-authorized">Weedmaps authorized/API</option></select><input value={sourceUrl} onChange={e=>setSourceUrl(e.target.value)} placeholder="Official source URL"/><input value={sourceLicense} onChange={e=>setSourceLicense(e.target.value)} placeholder="Source/license note"/><input type="file" accept=".csv,.json,text/csv,application/json" onChange={e=>setFile(e.target.files?.[0]||null)}/><button className="primary" disabled={busy||!file} onClick={upload}>Import candidates</button></div><p className="admin-help">Use this for official state exports that do not expose a stable direct endpoint. Records stay candidates until imagery is validated.</p></div>
   <div className="admin-panel"><h2>Nationwide official-source sync</h2><div className="source-note"><strong>Direct state feeds</strong><span>Sync every currently integrated direct official source independently. A failure in one state will not block the others.</span><button className="primary" disabled={busy} onClick={()=>fetchOfficial('all','Multi-state official sync')}>Fetch all available states</button></div><div className="source-note"><strong>California · DCC</strong><span>California requires its current DCC export. GeoWeedo filters it to active Type 10 storefront retailers.</span><div className="candidate-actions"><a className="secondary" href="https://www.cannabis.ca.gov/resources/search-for-licensed-business/" target="_blank" rel="noreferrer">Open DCC License Search</a><button className="secondary" onClick={useCaliforniaPreset}>Prepare California import</button></div></div>{directSources.map(([preset,label,description])=><div className="source-note" key={preset}><strong>{label}</strong><span>{description}</span><button className="secondary" disabled={busy} onClick={()=>fetchOfficial(preset,label)}>Fetch now</button></div>)}</div>
  </section>
  <section className="admin-panel approved-list"><div className="queue-toolbar"><div><h2>Coverage & imagery</h2><p className="admin-help">States {stats.states} · Candidates {stats.total} · Public map ready {stats.mapReady} · KartaView coverage {stats.coverage} · Hosted imagery needed {stats.noCoverage} · Coordinates needed {stats.missingCoordinates} · Unchecked {stats.unchecked}</p></div><button className="primary" disabled={busy||stats.unchecked===0} onClick={checkImageryBatch}>Check next 10</button></div></section>
  <section className="admin-panel approved-list"><h2>Candidate review queue</h2>{candidates.length===0?<p>No candidates imported yet.</p>:candidates.slice(0,300).map(item=><div className="candidate-row" key={item.id}><div><strong>{item.name}</strong><span>{[item.streetAddress,item.city,item.region].filter(Boolean).join(', ')||'Address needs review'} · {item.dataSource}</span>{item.licenseNumber&&<small>License {item.licenseNumber}</small>}<small>{imageryLabel(item)}</small></div><div className="candidate-actions"><span className={`status-pill ${item.imageryStatus||'unchecked'}`}>{item.imageryStatus||'unchecked'}</span><button onClick={()=>review(item)}>Review imagery</button><button onClick={()=>reject(item)}>Reject</button></div></div>)}</section>
 </main>;
}
