'use client';
import {useEffect,useState} from 'react';
type Daily={day:string;page_views:number;visitors:number;sessions:number};type NamedCount={name:string;value:number};type Metric='page_views'|'sessions'|'visitors';
function niceDay(day:string){const date=new Date(`${day}T00:00:00`);return date.toLocaleDateString(undefined,{month:'short',day:'numeric'});}function path(values:number[],width:number,height:number,pad=18,maxOverride?:number){const max=Math.max(1,maxOverride||0,...values);return values.map((value,index)=>{const x=values.length<=1?pad:pad+(index/(values.length-1))*(width-pad*2);const y=height-pad-(value/max)*(height-pad*2);return `${index?'L':'M'}${x.toFixed(1)},${y.toFixed(1)}`;}).join(' ');}
function isoDaysAgo(days:number){return new Date(Date.now()-(days-1)*86400000).toISOString().slice(0,10)}
export function TrafficTrendChart({daily,visible=['page_views','sessions','visitors']}:{daily:Daily[];visible?:Metric[]}){const width=760,height=250;const series:Record<Metric,number[]>={page_views:daily.map(r=>Number(r.page_views||0)),sessions:daily.map(r=>Number(r.sessions||0)),visitors:daily.map(r=>Number(r.visitors||0))};const active:Metric[]=visible.length?visible:['page_views'];const max=Math.max(1,...active.flatMap((m:Metric)=>series[m]));return <article style={{border:'1px solid rgba(255,255,255,.1)',borderRadius:16,padding:18,background:'rgba(255,255,255,.025)'}}><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Traffic trend chart" style={{width:'100%',height:'auto',overflow:'visible'}}>{[0,.25,.5,.75,1].map((n,i)=><g key={i}><line x1="18" x2={width-18} y1={height-18-n*(height-36)} y2={height-18-n*(height-36)} stroke="currentColor" opacity=".08"/><text x="2" y={height-14-n*(height-36)} fill="currentColor" opacity=".48" fontSize="10">{Math.round(max*n)}</text></g>)}{active.includes('page_views')&&<path d={path(series.page_views,width,height,18,max)} fill="none" stroke="currentColor" strokeWidth="3" opacity=".95"/>}{active.includes('sessions')&&<path d={path(series.sessions,width,height,18,max)} fill="none" stroke="currentColor" strokeWidth="2" opacity=".6" strokeDasharray="8 5"/>}{active.includes('visitors')&&<path d={path(series.visitors,width,height,18,max)} fill="none" stroke="currentColor" strokeWidth="2" opacity=".38"/>}{daily.length>1&&<><text x="18" y={height-2} fill="currentColor" opacity=".5" fontSize="10">{niceDay(daily[0].day)}</text><text x={width-18} y={height-2} textAnchor="end" fill="currentColor" opacity=".5" fontSize="10">{niceDay(daily[daily.length-1].day)}</text></>}</svg></article>}

export function TrafficTrendExplorer({excludeAdmin,excludedIps}:{excludeAdmin:boolean;excludedIps:string[]}){
 const[start,setStart]=useState(isoDaysAgo(30)),[end,setEnd]=useState(new Date().toISOString().slice(0,10)),[pathFilter,setPathFilter]=useState(''),[query,setQuery]=useState(''),[visible,setVisible]=useState<Metric[]>(['page_views','sessions','visitors']),[daily,setDaily]=useState<Daily[]>([]),[totals,setTotals]=useState({pageViews:0,sessions:0,visitors:0}),[loading,setLoading]=useState(false),[error,setError]=useState('');
 function setRange(days:number){setStart(isoDaysAgo(days));setEnd(new Date().toISOString().slice(0,10));}
 useEffect(()=>{const timer=window.setTimeout(()=>setQuery(pathFilter.trim()),300);return()=>window.clearTimeout(timer)},[pathFilter]);
 useEffect(()=>{setLoading(true);setError('');const params=new URLSearchParams({start,end,excludeAdmin:excludeAdmin?'1':'0'});if(query)params.set('path',query);if(excludedIps.length)params.set('excludeIps',excludedIps.join(','));fetch(`/api/admin/analytics?${params}`,{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||'Trend query failed.');return d.trend;}).then(t=>{setDaily(t.daily||[]);setTotals(t.totals||{pageViews:0,sessions:0,visitors:0});}).catch(e=>setError(e instanceof Error?e.message:'Trend query failed.')).finally(()=>setLoading(false));},[start,end,query,excludeAdmin,excludedIps]);
 const toggle=(metric:Metric)=>setVisible(current=>current.includes(metric)?(current.length===1?current:current.filter(v=>v!==metric)):[...current,metric]);
 const labels:Record<Metric,string>={page_views:'Page views',sessions:'Sessions',visitors:'Visitors'};const metricTotals:Record<Metric,number>={page_views:totals.pageViews,sessions:totals.sessions,visitors:totals.visitors};
 return <section><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'flex-end',flexWrap:'wrap',marginBottom:12}}><div><strong style={{fontSize:18}}>Traffic explorer</strong><div style={{opacity:.65,fontSize:12}}>Search a page, choose dates, and isolate any metric.</div></div><div style={{display:'flex',gap:6,flexWrap:'wrap'}}>{[7,30,60,90].map(n=><button key={n} type="button" onClick={()=>setRange(n)}>{n}d</button>)}</div></div><div style={{display:'grid',gridTemplateColumns:'minmax(220px,2fr) repeat(2,minmax(145px,1fr))',gap:8,marginBottom:10}}><input value={pathFilter} onChange={e=>setPathFilter(e.target.value)} placeholder="Search page path, e.g. /account or /"/><label>From<input type="date" value={start} max={end} onChange={e=>setStart(e.target.value)}/></label><label>To<input type="date" value={end} min={start} max={new Date().toISOString().slice(0,10)} onChange={e=>setEnd(e.target.value)}/></label></div><div style={{display:'flex',gap:8,flexWrap:'wrap',marginBottom:10}}>{(['page_views','sessions','visitors'] as Metric[]).map(metric=><button key={metric} type="button" aria-pressed={visible.includes(metric)} onClick={()=>toggle(metric)} style={{border:visible.includes(metric)?'1px solid var(--accent)':'1px solid rgba(255,255,255,.12)',background:visible.includes(metric)?'rgba(103,214,110,.12)':'transparent',color:'inherit',borderRadius:999,padding:'8px 11px'}}>{labels[metric]} · {metricTotals[metric].toLocaleString()}</button>)}</div>{loading&&<div style={{opacity:.65,fontSize:12,marginBottom:6}}>Updating graph…</div>}{error&&<div style={{color:'#ffb3b3',fontSize:12,marginBottom:6}}>{error}</div>}<TrafficTrendChart daily={daily} visible={visible}/></section>
}

export function RankedBarChart({title,subtitle,rows}:{title:string;subtitle:string;rows:NamedCount[]}){const max=Math.max(1,...rows.map(row=>row.value));return <article style={{border:'1px solid rgba(255,255,255,.1)',borderRadius:16,padding:18,background:'rgba(255,255,255,.025)'}}><strong style={{fontSize:18}}>{title}</strong><div style={{opacity:.65,fontSize:12,marginBottom:16}}>{subtitle}</div><div style={{display:'grid',gap:10}}>{rows.length?rows.slice(0,8).map((row,index)=><div key={`${row.name}-${index}`} style={{display:'grid',gridTemplateColumns:'minmax(90px,160px) 1fr auto',gap:10,alignItems:'center'}}><span style={{fontSize:12,overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}} title={row.name}>{row.name}</span><span style={{display:'block',height:9,borderRadius:999,background:'rgba(255,255,255,.07)',overflow:'hidden'}}><i style={{display:'block',height:'100%',width:`${Math.max(2,(row.value/max)*100)}%`,background:'var(--accent)',borderRadius:999}}/></span><strong style={{fontSize:12}}>{row.value.toLocaleString()}</strong></div>):<span style={{opacity:.65,fontSize:13}}>No data yet.</span>}</div></article>}
