'use client';

import {useEffect,useMemo,useState} from 'react';

type Visitor={visitorId:string;userId:string;ipAddress:string;networkId:string;sessions:number;pageViews:number;firstSeen:string;lastSeen:string;country:string;region:string;city:string;device:string;browser:string;landingPath:string;referrer:string};
type Props={days:number;excludeAdmin:boolean;excludedIps:string[]};
function when(value:string){return value?new Date(value).toLocaleString():'—';}
function shortId(value:string){return value.length>16?`${value.slice(0,12)}…`:value;}

export default function AdminIndividualVisitors({days,excludeAdmin,excludedIps}:Props){
 const [users,setUsers]=useState<Visitor[]>([]),[query,setQuery]=useState(''),[rows,setRows]=useState(25),[page,setPage]=useState(1),[loading,setLoading]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let cancelled=false;setLoading(true);setError('');const params=new URLSearchParams({mode:'users',days:String(days),excludeAdmin:excludeAdmin?'1':'0'});if(excludedIps.length)params.set('excludeIps',excludedIps.join(','));fetch(`/api/admin/analytics?${params}`,{cache:'no-store'}).then(async r=>{const data=await r.json();if(r.status===401){location.href='/admin/login';return null;}if(!r.ok)throw new Error(data.error||'Individual users failed to load.');return data;}).then(data=>{if(!cancelled&&data)setUsers(Array.isArray(data.users)?data.users:[]);}).catch(e=>{if(!cancelled)setError(e instanceof Error?e.message:'Individual users failed to load.');}).finally(()=>{if(!cancelled)setLoading(false);});return()=>{cancelled=true};},[days,excludeAdmin,excludedIps]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return users;return users.filter(u=>`${u.userId} ${u.ipAddress} ${u.city} ${u.region} ${u.country} ${u.device} ${u.browser} ${u.landingPath} ${u.referrer}`.toLowerCase().includes(q));},[users,query]);
 useEffect(()=>setPage(1),[query,rows,days,excludeAdmin,excludedIps]);
 const pages=Math.max(1,Math.ceil(filtered.length/rows)),safePage=Math.min(page,pages),start=(safePage-1)*rows,shown=filtered.slice(start,start+rows);
 return <section className="admin-individual-visitors traffic-individual-users">
  <div className="admin-individual-visitors-head"><div><span>INDIVIDUAL USERS</span><h3>Who is using GeoWeedo</h3><p>Only useful visitor records with a captured IP address or signed-in GeoWeedo account are shown. Legacy anonymous network-only records are excluded.</p></div><strong>{filtered.length.toLocaleString()} identified</strong></div>
  <div className="admin-individual-visitors-tools"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search IP, location, account, device…"/><label>Rows <select value={rows} onChange={e=>setRows(Number(e.target.value))}><option value={10}>10</option><option value={25}>25</option><option value={50}>50</option><option value={100}>100</option></select></label></div>
  <div className="admin-individual-visitors-status">{loading?'Loading identified visitors…':error||`${filtered.length.toLocaleString()} identified visitor${filtered.length===1?'':'s'} · Page ${safePage} of ${pages}`}</div>
  {!loading&&!error&&<div className="admin-individual-visitors-table-wrap"><table className="admin-table admin-individual-visitors-table"><thead><tr><th>IP address</th><th>Location</th><th>Account</th><th>Device</th><th>Sessions</th><th>Views</th><th>Last seen</th><th>First seen</th><th>Entry / referrer</th></tr></thead><tbody>{shown.length?shown.map(user=><tr key={user.visitorId}><td>{user.ipAddress?<code>{user.ipAddress}</code>:<span className="admin-visitor-anonymous">Signed-in account</span>}</td><td>{[user.city,user.region,user.country].filter(Boolean).join(', ')||'Location unavailable'}</td><td>{user.userId?<code title={user.userId}>{shortId(user.userId)}</code>:<span className="admin-visitor-anonymous">—</span>}</td><td>{user.device} · {user.browser}</td><td>{user.sessions.toLocaleString()}</td><td>{user.pageViews.toLocaleString()}</td><td>{when(user.lastSeen)}</td><td>{when(user.firstSeen)}</td><td><span className="admin-visitor-route">{user.landingPath||'/'}</span>{user.referrer&&<small>{user.referrer}</small>}</td></tr>):<tr><td colSpan={9}>No identified visitors in this range yet. New traffic will appear here once an IP or signed-in account is captured.</td></tr>}</tbody></table></div>}
  {pages>1&&<div className="admin-individual-visitors-pages"><button disabled={safePage<=1} onClick={()=>setPage(1)}>First</button><button disabled={safePage<=1} onClick={()=>setPage(p=>Math.max(1,p-1))}>Previous</button><span>{start+1}–{Math.min(start+rows,filtered.length)} of {filtered.length}</span><button disabled={safePage>=pages} onClick={()=>setPage(p=>Math.min(pages,p+1))}>Next</button><button disabled={safePage>=pages} onClick={()=>setPage(pages)}>Last</button></div>}
 </section>;
}
