'use client';

import {useEffect,useMemo,useState} from 'react';
import {DISPENSARY_LICENSE_TYPES} from '@/lib/licenseTypes';
import DispensaryLogoUploader from '@/components/DispensaryLogoUploader';

const DAYS=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
type Row={id:string;kind:'dispensary'|'candidate';name:string;street_address?:string;city?:string;region?:string;postal_code?:string;country?:string;latitude?:number|null;longitude?:number|null;website?:string;phone?:string;license_number?:string;license_status?:string;license_type?:string;license_types?:string[];data_source?:string;source_url?:string;source_license?:string;recreational?:number;medical?:number;verified?:number;active?:number;status?:string;imagery_status?:string;imagery_provider?:string;priority_weight?:number|null;sponsored_until?:string;profile?:{overview?:string;phone?:string;website?:string;hours?:Record<string,string>;amenities?:string[];social?:Record<string,string>}};
type Form={name:string;streetAddress:string;city:string;region:string;postalCode:string;country:string;latitude:string;longitude:string;website:string;phone:string;licenseNumber:string;licenseStatus:string;licenseType:string;licenseTypes:string[];dataSource:string;sourceUrl:string;sourceLicense:string;recreational:boolean;medical:boolean;verified:boolean;active:boolean;status:string;imageryStatus:string;priorityWeight:string;sponsoredUntil:string;overview:string;hours:Record<string,string>;amenities:string;instagram:string;facebook:string;twitter:string};
type SortKey='name'|'city'|'region'|'country'|'kind'|'status'|'gameplay';
type GameplayFilter='all'|'enabled'|'disabled'|'not-ready';

function makeForm(r:Row):Form{return{name:r.name||'',streetAddress:r.street_address||'',city:r.city||'',region:r.region||'',postalCode:r.postal_code||'',country:r.country||'',latitude:r.latitude==null?'':String(r.latitude),longitude:r.longitude==null?'':String(r.longitude),website:r.profile?.website||r.website||'',phone:r.profile?.phone||r.phone||'',licenseNumber:r.license_number||'',licenseStatus:r.license_status||'',licenseType:r.license_type||'',licenseTypes:r.license_types||[],dataSource:r.data_source||'',sourceUrl:r.source_url||'',sourceLicense:r.source_license||'',recreational:Boolean(r.recreational),medical:Boolean(r.medical),verified:Boolean(r.verified),active:r.active!==0,status:r.status||'candidate',imageryStatus:r.imagery_status||'unchecked',priorityWeight:r.priority_weight==null?'':String(r.priority_weight),sponsoredUntil:r.sponsored_until||'',overview:r.profile?.overview||'',hours:Object.fromEntries(DAYS.map(d=>[d,r.profile?.hours?.[d]||''])),amenities:(r.profile?.amenities||[]).join(', '),instagram:r.profile?.social?.instagram||'',facebook:r.profile?.social?.facebook||'',twitter:r.profile?.social?.twitter||''};}
function rowStatus(r:Row){return r.kind==='dispensary'?(r.active===0?'disabled':'enabled'):(r.status||'candidate');}
function hasCoordinates(r:Row){return Number.isFinite(Number(r.latitude))&&Number.isFinite(Number(r.longitude));}
function gameReady(r:Row){return r.kind==='dispensary'&&hasCoordinates(r)&&Boolean(r.imagery_provider);}
function gameplayStatus(r:Row){if(r.kind!=='dispensary')return 'candidate';if(!gameReady(r))return 'not-ready';return r.verified?'enabled':'disabled';}
function cmp(a:string,b:string){return a.localeCompare(b,undefined,{numeric:true,sensitivity:'base'});}

export default function AdminFullDispensaryEditor(){
 const[rows,setRows]=useState<Row[]>([]),[query,setQuery]=useState(''),[country,setCountry]=useState('all'),[region,setRegion]=useState('all'),[kind,setKind]=useState('all'),[recordStatus,setRecordStatus]=useState('all'),[gameplayFilter,setGameplayFilter]=useState<GameplayFilter>('all'),[sortKey,setSortKey]=useState<SortKey>('name'),[sortDir,setSortDir]=useState<'asc'|'desc'>('asc'),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(50),[selected,setSelected]=useState<Row|null>(null),[form,setForm]=useState<Form|null>(null),[status,setStatus]=useState('Loading all dispensary records…'),[busy,setBusy]=useState(false);
 async function load(){const r=await fetch('/api/admin/dispensary-records',{cache:'no-store'});if(r.status===401){location.href='/admin/login';return;}const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load dispensaries.');setRows(d.records||[]);setStatus(`${(d.records||[]).length.toLocaleString()} dispensary records loaded.`);}
 useEffect(()=>{load().catch(e=>setStatus(e instanceof Error?e.message:'Load failed.'));},[]);
 useEffect(()=>{setPage(1);},[query,country,region,kind,recordStatus,gameplayFilter,sortKey,sortDir,pageSize]);
 const countries=useMemo(()=>Array.from(new Set(rows.map(r=>r.country||'').filter(Boolean))).sort(cmp),[rows]);
 const regions=useMemo(()=>Array.from(new Set(rows.filter(r=>country==='all'||r.country===country).map(r=>r.region||'').filter(Boolean))).sort(cmp),[rows,country]);
 const statuses=useMemo(()=>Array.from(new Set(rows.map(rowStatus))).sort(cmp),[rows]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();const list=rows.filter(r=>{if(country!=='all'&&r.country!==country)return false;if(region!=='all'&&r.region!==region)return false;if(kind!=='all'&&r.kind!==kind)return false;if(recordStatus!=='all'&&rowStatus(r)!==recordStatus)return false;if(gameplayFilter!=='all'&&gameplayStatus(r)!==gameplayFilter)return false;if(!q)return true;return `${r.name} ${r.street_address||''} ${r.city||''} ${r.region||''} ${r.country||''} ${r.license_number||''} ${r.license_type||''} ${(r.license_types||[]).join(' ')} ${r.data_source||''}`.toLowerCase().includes(q);});list.sort((a,b)=>{const av=sortKey==='kind'?a.kind:sortKey==='status'?rowStatus(a):sortKey==='gameplay'?gameplayStatus(a):String((a as any)[sortKey]||'');const bv=sortKey==='kind'?b.kind:sortKey==='status'?rowStatus(b):sortKey==='gameplay'?gameplayStatus(b):String((b as any)[sortKey]||'');const n=cmp(av,bv);return sortDir==='asc'?n:-n;});return list;},[rows,query,country,region,kind,recordStatus,gameplayFilter,sortKey,sortDir]);
 const totalPages=Math.max(1,Math.ceil(filtered.length/pageSize)),safePage=Math.min(page,totalPages),visible=filtered.slice((safePage-1)*pageSize,safePage*pageSize);
 function choose(r:Row){setSelected(r);setForm(makeForm(r));setStatus(`Editing ${r.name}.`);}
 useEffect(()=>{const handler=(event:Event)=>{const id=(event as CustomEvent<{id?:string}>).detail?.id;if(!id)return;const record=rows.find(r=>r.id===id);if(!record){setStatus('Could not find that dispensary in the editor.');return;}clearFilters();choose(record);window.requestAnimationFrame(()=>document.querySelector('.full-dispensary-editor')?.scrollIntoView({behavior:'smooth',block:'start'}));};window.addEventListener('geoweedo:edit-dispensary',handler);return()=>window.removeEventListener('geoweedo:edit-dispensary',handler);},[rows]);
 function toggleLicense(type:string){if(!form)return;setForm({...form,licenseTypes:form.licenseTypes.includes(type)?form.licenseTypes.filter(x=>x!==type):[...form.licenseTypes,type]});}
 function clearFilters(){setQuery('');setCountry('all');setRegion('all');setKind('all');setRecordStatus('all');setGameplayFilter('all');setSortKey('name');setSortDir('asc');setPage(1);}
 function setGameplay(enabled:boolean){if(!selected||!form||selected.kind!=='dispensary')return;if(enabled&&!gameReady(selected)){setStatus('Gameplay cannot be enabled until this dispensary has valid coordinates and an approved Street View imagery provider.');return;}setForm({...form,verified:enabled,active:enabled?true:form.active});setStatus(enabled?'Gameplay will be enabled when you save.':'Gameplay will be disabled when you save. The dispensary can remain active on the browse map.');}
 async function save(){if(!selected||!form)return;setBusy(true);setStatus('Saving all dispensary information…');try{const details={...form,latitude:form.latitude===''?null:Number(form.latitude),longitude:form.longitude===''?null:Number(form.longitude),priorityWeight:form.priorityWeight===''?null:Number(form.priorityWeight),amenities:form.amenities.split(',').map(v=>v.trim()).filter(Boolean),social:{instagram:form.instagram,facebook:form.facebook,twitter:form.twitter}};const r=await fetch('/api/admin/dispensary-records',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:selected.id,kind:selected.kind,details})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Save failed.');await load();setSelected(null);setForm(null);setStatus('Dispensary information saved. Public profile and gameplay eligibility are updated immediately.');}catch(e){setStatus(e instanceof Error?e.message:'Save failed.');}finally{setBusy(false);}}
 if(!form&&selected)setSelected(null);
 return <section className="admin-panel full-dispensary-editor" style={{marginBottom:24}}>
  <div><span className="eyebrow">FULL DISPENSARY EDITOR</span><h2 style={{margin:'4px 0'}}>All dispensary information</h2><p style={{margin:0,color:'var(--muted)'}}>Filter, sort and edit approved shops and imported browse-only records, including game eligibility.</p></div>
  <div style={{display:'grid',gridTemplateColumns:'minmax(220px,2fr) repeat(5,minmax(130px,1fr))',gap:8,marginTop:16}}><input placeholder="Search name, address, city, license, source…" value={query} onChange={e=>setQuery(e.target.value)}/><select value={country} onChange={e=>{setCountry(e.target.value);setRegion('all')}}><option value="all">All countries</option>{countries.map(v=><option key={v}>{v}</option>)}</select><select value={region} onChange={e=>setRegion(e.target.value)}><option value="all">All states / regions</option>{regions.map(v=><option key={v}>{v}</option>)}</select><select value={kind} onChange={e=>setKind(e.target.value)}><option value="all">All record types</option><option value="dispensary">Approved dispensaries</option><option value="candidate">Imported candidates</option></select><select value={recordStatus} onChange={e=>setRecordStatus(e.target.value)}><option value="all">All statuses</option>{statuses.map(v=><option key={v}>{v}</option>)}</select><select value={gameplayFilter} onChange={e=>setGameplayFilter(e.target.value as GameplayFilter)}><option value="all">All gameplay</option><option value="enabled">Gameplay enabled</option><option value="disabled">Gameplay disabled</option><option value="not-ready">Not game ready</option></select></div>
  <div style={{display:'flex',gap:8,alignItems:'center',flexWrap:'wrap',marginTop:8}}><label>Sort <select value={sortKey} onChange={e=>setSortKey(e.target.value as SortKey)}><option value="name">Name</option><option value="city">City</option><option value="region">State / region</option><option value="country">Country</option><option value="kind">Record type</option><option value="status">Status</option><option value="gameplay">Gameplay</option></select></label><select value={sortDir} onChange={e=>setSortDir(e.target.value as 'asc'|'desc')}><option value="asc">A → Z</option><option value="desc">Z → A</option></select><label>Rows <select value={pageSize} onChange={e=>setPageSize(Number(e.target.value))}><option value={25}>25</option><option value={50}>50</option><option value={100}>100</option></select></label><button className="ghost" type="button" onClick={clearFilters}>Clear filters</button><span style={{marginLeft:'auto',color:'var(--muted)',fontSize:13}}>{filtered.length.toLocaleString()} matches</span></div>
  <div className="admin-status" style={{margin:'12px 0'}}>{status}</div>
  <div style={{display:'grid',gridTemplateColumns:selected?'minmax(360px,.9fr) minmax(480px,1.5fr)':'1fr',gap:18}}><div><div style={{overflow:'auto',border:'1px solid var(--border)',borderRadius:12}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:13}}><thead><tr><th>Name</th><th>City</th><th>State / region</th><th>Type</th><th>Status</th><th>Gameplay</th></tr></thead><tbody>{visible.map(r=><tr key={`${r.kind}:${r.id}`} onClick={()=>choose(r)} style={{cursor:'pointer',borderTop:'1px solid var(--border)'}}><td style={{padding:10}}><strong>{r.name}</strong>{r.license_number&&<div style={{fontSize:11,color:'var(--muted)'}}>{r.license_number}</div>}</td><td>{r.city||'—'}</td><td>{r.region||'—'}</td><td>{r.kind==='candidate'?'Candidate':'Approved'}</td><td>{rowStatus(r)}</td><td>{gameplayStatus(r)==='enabled'?'Enabled':gameplayStatus(r)==='disabled'?'Disabled':gameplayStatus(r)==='not-ready'?'Not ready':'—'}</td></tr>)}</tbody></table></div><div style={{display:'flex',justifyContent:'space-between',marginTop:10}}><span>Page {safePage} of {totalPages}</span><div style={{display:'flex',gap:6}}><button className="ghost" disabled={safePage<=1} onClick={()=>setPage(1)}>First</button><button className="ghost" disabled={safePage<=1} onClick={()=>setPage(p=>p-1)}>Previous</button><button className="ghost" disabled={safePage>=totalPages} onClick={()=>setPage(p=>p+1)}>Next</button><button className="ghost" disabled={safePage>=totalPages} onClick={()=>setPage(totalPages)}>Last</button></div></div></div>
  {selected&&form&&<div className="admin-form" style={{alignContent:'start'}}><div style={{display:'flex',justifyContent:'space-between'}}><div><span className="eyebrow">{selected.kind.toUpperCase()}</span><h3>{selected.name}</h3></div><button className="ghost" onClick={()=>{setSelected(null);setForm(null)}}>Close</button></div>
   <input placeholder="Name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input placeholder="Street address" value={form.streetAddress} onChange={e=>setForm({...form,streetAddress:e.target.value})}/><div className="field-row"><input placeholder="City" value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/><input placeholder="State / region" value={form.region} onChange={e=>setForm({...form,region:e.target.value})}/></div><div className="field-row"><input placeholder="Postal code" value={form.postalCode} onChange={e=>setForm({...form,postalCode:e.target.value})}/><input placeholder="Country" value={form.country} onChange={e=>setForm({...form,country:e.target.value})}/></div><div className="field-row"><input placeholder="Latitude" value={form.latitude} onChange={e=>setForm({...form,latitude:e.target.value})}/><input placeholder="Longitude" value={form.longitude} onChange={e=>setForm({...form,longitude:e.target.value})}/></div><div className="field-row"><input placeholder="Phone" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><input placeholder="Website" value={form.website} onChange={e=>setForm({...form,website:e.target.value})}/></div><textarea placeholder="Overview / business description" value={form.overview} onChange={e=>setForm({...form,overview:e.target.value})}/>
   <h4>Hours of operation</h4>{DAYS.map(day=><div className="field-row" key={day}><label>{day}</label><input placeholder="9:00 AM - 9:00 PM or Closed" value={form.hours[day]||''} onChange={e=>setForm({...form,hours:{...form.hours,[day]:e.target.value}})}/></div>)}<input placeholder="Amenities / services, comma separated" value={form.amenities} onChange={e=>setForm({...form,amenities:e.target.value})}/><div className="field-row"><input placeholder="Instagram URL" value={form.instagram} onChange={e=>setForm({...form,instagram:e.target.value})}/><input placeholder="Facebook URL" value={form.facebook} onChange={e=>setForm({...form,facebook:e.target.value})}/></div><input placeholder="X / Twitter URL" value={form.twitter} onChange={e=>setForm({...form,twitter:e.target.value})}/>
   <h4>Dispensary branding</h4><div style={{border:'1px solid var(--border)',borderRadius:12,padding:12}}><p style={{fontSize:12,color:'var(--muted)',margin:'0 0 10px'}}>Custom logo shown on this dispensary's public GeoWeedo profile.</p><DispensaryLogoUploader locationId={selected.id} compact/></div>
   <h4>License & source</h4><div className="field-row"><input placeholder="License number" value={form.licenseNumber} onChange={e=>setForm({...form,licenseNumber:e.target.value})}/>{selected.kind==='candidate'&&<input placeholder="License status" value={form.licenseStatus} onChange={e=>setForm({...form,licenseStatus:e.target.value})}/>}</div>
   <div><strong style={{display:'block',marginBottom:8}}>License type(s)</strong><div className="check-row" style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:8}}>{DISPENSARY_LICENSE_TYPES.map(t=><label key={t.id}><input type="checkbox" checked={form.licenseTypes.includes(t.id)} onChange={()=>toggleLicense(t.id)}/> {t.label}</label>)}</div><p style={{fontSize:12,color:'var(--muted)'}}>Select every license category that applies. These standardized types can be used for filtering and display.</p></div>
   {selected.kind==='candidate'&&<input placeholder="Raw license type from official source" value={form.licenseType} onChange={e=>setForm({...form,licenseType:e.target.value})}/>}<div className="field-row"><input placeholder="Data source" value={form.dataSource} onChange={e=>setForm({...form,dataSource:e.target.value})}/><input placeholder="Source URL" value={form.sourceUrl} onChange={e=>setForm({...form,sourceUrl:e.target.value})}/></div><textarea placeholder="Source license / permission note" value={form.sourceLicense} onChange={e=>setForm({...form,sourceLicense:e.target.value})}/>
   {selected.kind==='dispensary'?<><h4>Gameplay</h4><div style={{border:'1px solid var(--border)',borderRadius:12,padding:12}}><label style={{display:'flex',gap:10,alignItems:'center',fontWeight:700}}><input type="checkbox" checked={form.verified} disabled={!form.verified&&!gameReady(selected)} onChange={e=>setGameplay(e.target.checked)}/> Enable Gameplay</label><p style={{fontSize:12,color:'var(--muted)',margin:'8px 0 0'}}>Include this dispensary in random GeoWeedo games. Requires valid coordinates and approved Street View imagery.</p><p style={{fontSize:12,margin:'6px 0 0'}}><strong>{gameReady(selected)?(form.verified?'Game Ready · Enabled':'Game Ready · Disabled'):'Not Game Ready'}</strong>{!hasCoordinates(selected)?' · Missing coordinates':''}{!selected.imagery_provider?' · Missing Street View':''}</p></div><div className="check-row"><label><input type="checkbox" checked={form.recreational} onChange={e=>setForm({...form,recreational:e.target.checked})}/> Adult-use</label><label><input type="checkbox" checked={form.medical} onChange={e=>setForm({...form,medical:e.target.checked})}/> Medical</label><label><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> Active on browse map</label></div><div className="field-row"><input placeholder="Priority weight" value={form.priorityWeight} onChange={e=>setForm({...form,priorityWeight:e.target.value})}/><input placeholder="Sponsored until" value={form.sponsoredUntil} onChange={e=>setForm({...form,sponsoredUntil:e.target.value})}/></div><p style={{fontSize:12,color:'var(--muted)'}}>Imagery provider: {selected.imagery_provider||'—'}</p></>:<div className="field-row"><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="candidate">Candidate</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select><select value={form.imageryStatus} onChange={e=>setForm({...form,imageryStatus:e.target.value})}><option value="unchecked">Imagery unchecked</option><option value="missing_coordinates">Missing coordinates</option><option value="ready">Imagery ready</option><option value="rejected">Imagery rejected</option></select></div>}
   <button className="primary" disabled={busy} onClick={save}>{busy?'Saving…':'Save all dispensary information'}</button>
  </div>}</div>
 </section>;
}