'use client';

import {useEffect,useMemo,useRef,useState} from 'react';

type JobReason={status:string;message:string;count:number};
type Job={id:string;status:string;total:number;counts:Record<string,number>;reasons?:JobReason[];scope:any;auto_apply:number;created_at:string};
type Review={id:string;location_id:string;location_name:string;review_type:'google_places'|'enrichment';confidence:string;score?:number|null;payload:any;created_at:string};
type Source={id:string;label:string;configured:boolean;primary:boolean};
type Data={options:{countries:string[];regions:string[]};jobs:Job[];reviews:Review[];googlePlacesConfigured?:boolean;enrichmentSources?:Source[]};
type PendingControl='pause'|'cancel'|null;

function formatValue(value:any){if(value==null||value==='')return '—';if(Array.isArray(value))return value.length?value.join(', '):'—';if(typeof value==='object'){const entries=Object.entries(value);return entries.length?entries.map(([k,v])=>`${k}: ${String(v)}`).join(' · '):'—';}return String(value);}
function sleep(ms:number){return new Promise(resolve=>window.setTimeout(resolve,ms));}

export default function AdminBatchEnrichmentQueue(){
 const[data,setData]=useState<Data>({options:{countries:[],regions:[]},jobs:[],reviews:[]}),[country,setCountry]=useState(''),[region,setRegion]=useState(''),[recordType,setRecordType]=useState('all'),[missing,setMissing]=useState('any'),[autoApply,setAutoApply]=useState(true),[busy,setBusy]=useState(false),[running,setRunning]=useState<string|null>(null),[message,setMessage]=useState(''),[runLimit,setRunLimit]=useState(50),[chunkSize,setChunkSize]=useState(5),[delayMs,setDelayMs]=useState(2000);
 const stopRequestedRef=useRef(false),pendingControlRef=useRef<PendingControl>(null);
 async function load(){const r=await fetch('/api/admin/dispensary-batch-enrichment',{cache:'no-store'});if(r.status===401){location.href='/admin/login';return;}const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load batch enrichment queue.');setData(d);return d as Data;}
 useEffect(()=>{load().catch(e=>setMessage(e instanceof Error?e.message:'Load failed.'));},[]);
 const regions=useMemo(()=>data.options.regions,[data.options.regions]);
 async function post(body:any){const r=await fetch('/api/admin/dispensary-batch-enrichment',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Batch operation failed.');return d;}
 async function control(jobId:string,controlAction:'pause'|'resume'|'cancel'){const d=await post({action:'control',jobId,control:controlAction});await load();return d;}
 async function create(){setBusy(true);setMessage('Creating Google Places enrichment queue…');try{const d=await post({action:'create',scope:{country:country||undefined,region:region||undefined,recordType,missing},autoApply});await load();const processable=Number(d.job?.counts?.pending||0),blocked=Number(d.job?.counts?.blocked||0);setMessage(`${d.job.total.toLocaleString()} matching records · ${processable.toLocaleString()} ready${blocked?` · ${blocked.toLocaleString()} blocked until Google Places is configured`:''}.`);if(processable)void run(d.job.id);}catch(e){setMessage(e instanceof Error?e.message:'Could not create batch.');}finally{setBusy(false);}}
 async function run(jobId:string){if(running)return;const ceiling=Math.min(250,Math.max(1,runLimit)),chunk=Math.min(10,Math.max(1,chunkSize)),delay=Math.min(10000,Math.max(0,delayMs));stopRequestedRef.current=false;pendingControlRef.current=null;setRunning(jobId);setMessage(`Running up to ${ceiling} records · ${chunk} per chunk · ${delay?`${delay/1000}s delay`:'no delay'}.`);let processed=0,lastJob:Job|null=null;try{const resumed=await control(jobId,'resume');lastJob=resumed.job||null;if(lastJob?.status==='completed'){setMessage('Batch is already complete.');return;}while(processed<ceiling&&!stopRequestedRef.current){const requestSize=Math.min(chunk,ceiling-processed);const d=await post({action:'process',jobId,chunkSize:requestSize});lastJob=d.job||null;const advanced=Number(d.processed||0);processed+=advanced;await load();if(lastJob?.status==='completed'){const c=lastJob.counts||{};setMessage(`Batch complete · ${c.applied||0} applied · ${c.review||0} review · ${c.blocked||0} blocked · ${c.failed||0} failed.`);return;}if(lastJob?.status==='cancelled'||lastJob?.status==='paused')break;if(advanced<=0)break;if(processed<ceiling&&!stopRequestedRef.current&&delay>0)await sleep(delay);}const requested=pendingControlRef.current;if(requested){await control(jobId,requested);setMessage(requested==='cancel'?`Batch cancelled after ${processed} records.`:`Batch paused after ${processed} records.`);}else if(lastJob?.status!=='completed'&&lastJob?.status!=='cancelled'){await control(jobId,'pause');setMessage(`Run ceiling reached after ${processed} records. Batch paused safely.`);}}catch(e){setMessage(e instanceof Error?e.message:'Batch processing stopped.');}finally{stopRequestedRef.current=false;pendingControlRef.current=null;setRunning(null);await load().catch(()=>{});}}
 async function pause(jobId:string){if(running===jobId){stopRequestedRef.current=true;pendingControlRef.current='pause';setMessage('Pause requested. Current chunk will finish first.');return;}setBusy(true);try{await control(jobId,'pause');setMessage('Batch paused.');}catch(e){setMessage(e instanceof Error?e.message:'Could not pause batch.');}finally{setBusy(false);}}
 async function cancel(jobId:string){if(!window.confirm('Cancel this enrichment batch?'))return;if(running===jobId){stopRequestedRef.current=true;pendingControlRef.current='cancel';setMessage('Cancel requested. Current chunk will finish first.');return;}setBusy(true);try{await control(jobId,'cancel');setMessage('Batch cancelled.');}catch(e){setMessage(e instanceof Error?e.message:'Could not cancel batch.');}finally{setBusy(false);}}
 async function retryBlocked(jobId:string){setBusy(true);setMessage('Requeuing blocked records…');try{const d=await post({action:'retryBlocked',jobId});await load();setMessage(`${Number(d.recovery?.requeued||0).toLocaleString()} blocked records requeued for Google Places.`);}catch(e){setMessage(e instanceof Error?e.message:'Could not requeue blocked records.');}finally{setBusy(false);}}
 async function review(id:string,action:'approve'|'reject'){setBusy(true);try{const r=await fetch('/api/admin/dispensary-batch-enrichment',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({reviewId:id,action})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Review action failed.');await load();setMessage(action==='approve'?'Review approved and applied.':'Review rejected.');}catch(e){setMessage(e instanceof Error?e.message:'Review action failed.');}finally{setBusy(false);}}
 return <section className="admin-panel" style={{marginBottom:24}}>
  <div className="admin-panel-heading"><div><span className="eyebrow">AUTOMATED ENRICHMENT</span><h2>Google Places enrichment queue</h2></div></div>
  <p className="admin-copy">Google Places is now the primary enrichment source. It matches each dispensary using name, address and distance, then enriches name, address, coordinates, phone, website, hours, business status, rating and rating count. Only high-confidence matches auto-apply; uncertain matches go to Admin Review.</p>
  <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:10,margin:'12px 0 16px'}}>
   {(data.enrichmentSources||[{id:'google_places',label:'Google Places',configured:Boolean(data.googlePlacesConfigured),primary:true},{id:'official_website',label:'Official website',configured:true,primary:false}]).map(source=><div key={source.id} className="admin-status" style={{margin:0}}><b>{source.label}</b> · {source.configured?'Ready':'Not configured'}{source.primary?' · Primary':''}{source.id==='official_website'?' · Secondary fill-in only':''}</div>)}
  </div>
  {!data.googlePlacesConfigured&&<p className="admin-status"><b>Google Places is not configured.</b> Add <b>GOOGLE_PLACES_API_KEY</b> to the shared environment before running a batch.</p>}
  <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(170px,1fr))',gap:10}}><label>Country<select value={country} onChange={e=>{setCountry(e.target.value);setRegion('');}}><option value="">All countries</option>{data.options.countries.map(v=><option key={v}>{v}</option>)}</select></label><label>State / region<select value={region} onChange={e=>setRegion(e.target.value)}><option value="">All states / regions</option>{regions.map(v=><option key={v}>{v}</option>)}</select></label><label>Records<select value={recordType} onChange={e=>setRecordType(e.target.value)}><option value="all">Approved + candidates</option><option value="dispensary">Approved dispensaries</option><option value="candidate">Imported candidates</option></select></label><label>Needs<select value={missing} onChange={e=>setMissing(e.target.value)}><option value="any">Any missing information</option><option value="website">Website</option><option value="phone">Phone</option><option value="hours">Hours</option><option value="amenities">Amenities / services</option></select></label></div>
  <div style={{marginTop:14,padding:14,border:'1px solid rgba(255,255,255,.08)',borderRadius:12}}><span className="eyebrow">RUN CONTROLS</span><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:10,marginTop:8}}><label>Records per run<select value={runLimit} onChange={e=>setRunLimit(Number(e.target.value))}><option value={25}>25</option><option value={50}>50</option><option value={100}>100</option><option value={250}>250 max</option></select></label><label>Records per chunk<select value={chunkSize} onChange={e=>setChunkSize(Number(e.target.value))}><option value={1}>1</option><option value={3}>3</option><option value={5}>5</option><option value={10}>10 max</option></select></label><label>Delay between chunks<select value={delayMs} onChange={e=>setDelayMs(Number(e.target.value))}><option value={0}>No delay</option><option value={1000}>1 second</option><option value={2000}>2 seconds</option><option value={3000}>3 seconds</option><option value={5000}>5 seconds</option></select></label></div><small style={{display:'block',marginTop:8,opacity:.75}}>Each run pauses at the selected ceiling. Google Places runs first; official website parsing only fills remaining details when a website is available.</small></div>
  <div style={{display:'flex',gap:12,alignItems:'center',marginTop:14,flexWrap:'wrap'}}><label style={{display:'flex',gap:7,alignItems:'center'}}><input type="checkbox" checked={autoApply} onChange={e=>setAutoApply(e.target.checked)}/> Auto-apply high-confidence Google Places matches only</label><button className="primary" disabled={busy||Boolean(running)||!data.googlePlacesConfigured} onClick={()=>void create()}>Create & run batch</button></div>
  {message&&<p className="admin-status" style={{marginTop:12}}>{message}</p>}
  <h3>Recent batch jobs</h3><div style={{overflowX:'auto'}}><table className="admin-table"><thead><tr><th>Scope</th><th>Status</th><th>Total</th><th>Pending</th><th>Applied</th><th>Review</th><th>Blocked</th><th>Skipped</th><th>Failed</th><th>Controls</th></tr></thead><tbody>{data.jobs.map(j=>{const active=running===j.id,terminal=j.status==='completed'||j.status==='cancelled';return <tr key={j.id}><td><div>{[j.scope?.country||'All',j.scope?.region,j.scope?.recordType!=='all'?j.scope?.recordType:null,j.scope?.missing].filter(Boolean).join(' · ')}</div>{j.reasons?.slice(0,3).map((reason,index)=><small key={index} style={{display:'block',opacity:.75}}>{reason.count} {reason.status}: {reason.message}</small>)}</td><td><b>{active?'running':j.status}</b></td><td>{j.total}</td><td>{j.counts?.pending||0}</td><td>{j.counts?.applied||0}</td><td>{j.counts?.review||0}</td><td>{j.counts?.blocked||0}</td><td>{j.counts?.skipped||0}</td><td>{j.counts?.failed||0}</td><td><div style={{display:'flex',gap:6,flexWrap:'wrap'}}>{Number(j.counts?.blocked||0)>0&&data.googlePlacesConfigured&&!terminal&&<button className="ghost" disabled={busy||Boolean(running)} onClick={()=>void retryBlocked(j.id)}>Retry blocked</button>}{!terminal&&!active&&<button className="primary" disabled={busy||Boolean(running)} onClick={()=>void run(j.id)}>{j.status==='paused'?'Resume':'Run'}</button>}{!terminal&&active&&<button className="ghost" onClick={()=>void pause(j.id)}>Pause</button>}{!terminal&&<button className="ghost" disabled={busy||(Boolean(running)&&!active)} onClick={()=>void cancel(j.id)}>Cancel</button>}</div></td></tr>})}</tbody></table></div>
  <div style={{display:'flex',justifyContent:'space-between',alignItems:'end',gap:10,marginTop:20}}><div><span className="eyebrow">ADMIN REVIEW</span><h3 style={{margin:'4px 0'}}>Uncertain matches</h3></div><strong>{data.reviews.length} pending</strong></div>
  {!data.reviews.length?<p className="admin-copy">No enrichment results currently need manual review.</p>:<div style={{display:'grid',gap:10,marginTop:10}}>{data.reviews.map(r=>{const p=r.payload||{},changes=Object.entries(p.changes||{});return <div className="admin-card" key={r.id}><div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><div><strong>{r.location_name}</strong><div><small>{r.review_type==='google_places'?'Google Places match':'Official website enrichment'} · confidence {r.confidence}{r.score!=null?` · score ${r.score}`:''}</small></div></div><div style={{display:'flex',gap:8}}><button className="primary" disabled={busy} onClick={()=>void review(r.id,'approve')}>Approve</button><button className="ghost" disabled={busy} onClick={()=>void review(r.id,'reject')}>Reject</button></div></div>{r.review_type==='google_places'?<div style={{marginTop:10,fontSize:13}}><div><b>Google name:</b> {formatValue(p.name)}</div><div><b>Address:</b> {formatValue(p.formattedAddress)}</div><div><b>Phone:</b> {formatValue(p.phone)}</div><div><b>Website:</b> {formatValue(p.website)}</div><div><b>Business status:</b> {formatValue(p.businessStatus)}</div><div><b>Rating:</b> {p.rating==null?'—':`${p.rating} (${p.ratingCount||0} ratings)`}</div><div><b>Distance:</b> {p.match?.distanceMeters==null?'—':`${Math.round(p.match.distanceMeters)} m`}</div></div>:<div style={{marginTop:10,fontSize:13}}>{changes.length?changes.map(([field,value]:any)=><div key={field}><b>{field}:</b> {formatValue(value?.from)} → {formatValue(value?.to)}</div>):<div>No field differences listed.</div>}</div>}</div>})}</div>}
 </section>;
}
