'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import styles from './AdminCultivarGenetics.module.css';

type Stats={cultivars:number;aliases:number;lineageClaims:number;sources:number;productLinks:number;geneticRelationships:number};
type Cultivar={id:string;canonical_name:string;breeder:string|null;cultivar_type:string|null;origin:string|null;status:string;alias_count:number;parent_claim_count:number;child_claim_count:number;product_count:number};
type Source={id:string;source_name:string;source_type:string;source_url:string|null;external_id:string|null;evidence_type:string;license_note:string|null;verified:number};
type Lineage={id:string;child_name:string;parent_name:string;parent_role:string;relationship_type:string;generation:string|null;confidence:number;status:string;source_name:string|null;source_url:string|null;evidence_type:string|null;notes:string|null};
type Product={id:string;brand_name:string|null;product_name:string;product_type:string|null;net_contents:string|null};
type ProductLink={id:string;product_id:string;cultivar_id:string;brand_name:string|null;product_name:string;cultivar_name:string;confidence:number;status:string;source_name:string|null;source_url:string|null};
type GeneticRelationship={id:string;cultivar_a_name:string;cultivar_b_name:string;relationship_label:string;similarity_score:number|null;source_name:string;source_url:string|null;evidence_type:string;verified:number};
type Payload={stats:Stats;cultivars:Cultivar[];sources:Source[];lineage:Lineage[];products:Product[];productLinks:ProductLink[];geneticRelationships:GeneticRelationship[]};

const empty:Payload={stats:{cultivars:0,aliases:0,lineageClaims:0,sources:0,productLinks:0,geneticRelationships:0},cultivars:[],sources:[],lineage:[],products:[],productLinks:[],geneticRelationships:[]};
const evidenceTypes=['breeder_primary','multi_source_confirmed','database_reported','registrant_reported','genetic_dataset','editorial','community_reported','unknown'];
const claimStatuses=['verified_source','multiple_sources_agree','single_source_claim','conflicting_pedigree','community_reported','unknown'];
const relationshipTypes=['cross','backcross','self','clone','selection','unknown'];

function label(value:string|null|undefined){return String(value||'').replace(/_/g,' ');}
function productLabel(p:Product){return `${p.brand_name?`${p.brand_name} · `:''}${p.product_name}${p.net_contents?` · ${p.net_contents}`:''}`;}

export default function AdminCultivarGenetics(){
 const[data,setData]=useState<Payload>(empty),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[filter,setFilter]=useState('');
 const[cultivarForm,setCultivarForm]=useState({canonicalName:'',breeder:'',cultivarType:'',origin:'',status:'unverified'});
 const[sourceForm,setSourceForm]=useState({sourceName:'',sourceType:'breeder',sourceUrl:'',externalId:'',evidenceType:'breeder_primary',licenseNote:'',verified:false});
 const[aliasForm,setAliasForm]=useState({cultivarId:'',alias:'',sourceId:'',verified:false});
 const[lineageForm,setLineageForm]=useState({childCultivarId:'',parentCultivarId:'',parentRole:'unknown',relationshipType:'cross',generation:'',sourceId:'',confidence:'70',status:'single_source_claim',notes:''});
 const[productForm,setProductForm]=useState({productId:'',cultivarId:'',sourceId:'',confidence:'70',status:'single_source_claim',notes:''});
 const[geneticForm,setGeneticForm]=useState({cultivarAId:'',cultivarBId:'',sourceId:'',relationshipLabel:'genetic_relative',similarityScore:'',verified:false});

 async function load(){const r=await fetch('/api/admin/cultivar-genetics',{cache:'no-store'});if(r.status===401){window.location.href='/admin/login';return;}const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.error||'Could not load cultivar genetics.');setData({...empty,...body});}
 useEffect(()=>{load().catch(e=>setError(e instanceof Error?e.message:'Could not load cultivar genetics.')).finally(()=>setLoading(false));},[]);
 async function post(action:string,payload:Record<string,unknown>){setSaving(true);setError('');setNotice('');try{const r=await fetch('/api/admin/cultivar-genetics',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...payload})});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.error||'Update failed.');if(body.data)setData({...empty,...body.data});setNotice('Cultivar genetics updated.');return body;}catch(e){setError(e instanceof Error?e.message:'Update failed.');return null;}finally{setSaving(false);}}

 const filteredCultivars=useMemo(()=>{const q=filter.trim().toLowerCase();if(!q)return data.cultivars;return data.cultivars.filter(c=>[c.canonical_name,c.breeder,c.cultivar_type,c.origin,c.status].some(v=>String(v||'').toLowerCase().includes(q)));},[data.cultivars,filter]);
 const filteredLineage=useMemo(()=>{const q=filter.trim().toLowerCase();if(!q)return data.lineage;return data.lineage.filter(row=>[row.child_name,row.parent_name,row.source_name,row.status,row.relationship_type,row.generation].some(v=>String(v||'').toLowerCase().includes(q)));},[data.lineage,filter]);

 async function createCultivar(e:FormEvent){e.preventDefault();const result=await post('create-cultivar',cultivarForm);if(result){setCultivarForm({canonicalName:'',breeder:'',cultivarType:'',origin:'',status:'unverified'});}}
 async function addSource(e:FormEvent){e.preventDefault();const result=await post('add-source',sourceForm);if(result){setSourceForm({sourceName:'',sourceType:'breeder',sourceUrl:'',externalId:'',evidenceType:'breeder_primary',licenseNote:'',verified:false});}}
 async function addAlias(e:FormEvent){e.preventDefault();const result=await post('add-alias',aliasForm);if(result)setAliasForm(v=>({...v,alias:''}));}
 async function addLineage(e:FormEvent){e.preventDefault();const result=await post('add-lineage',lineageForm);if(result)setLineageForm(v=>({...v,generation:'',notes:''}));}
 async function linkProduct(e:FormEvent){e.preventDefault();const result=await post('link-product',productForm);if(result)setProductForm(v=>({...v,notes:''}));}
 async function addGenetic(e:FormEvent){e.preventDefault();const result=await post('add-genetic-relationship',geneticForm);if(result)setGeneticForm(v=>({...v,similarityScore:''}));}

 if(loading)return <main className={styles.shell}><div className={styles.loading}>Loading cultivar genetics…</div></main>;
 return <main className={styles.shell}>
  <header className={styles.header}><div><span>WEEDO FACTS · CULTIVAR GENETICS</span><h1>Cultivar pedigree</h1><p>Curate source-backed cultivar identity, aliases, reported ancestry, product links, and measured genetic relationships without treating strain-name lore as laboratory fact.</p></div><a href="/admin">← Admin</a></header>
  <section className={styles.stats}><article><strong>{data.stats.cultivars}</strong><span>Cultivars</span></article><article><strong>{data.stats.lineageClaims}</strong><span>Pedigree claims</span></article><article><strong>{data.stats.sources}</strong><span>Sources</span></article><article><strong>{data.stats.aliases}</strong><span>Aliases</span></article><article><strong>{data.stats.productLinks}</strong><span>Product links</span></article><article><strong>{data.stats.geneticRelationships}</strong><span>Genetic relationships</span></article></section>
  {error?<div className={styles.error}>{error}</div>:null}{notice?<div className={styles.notice}>{notice}</div>:null}

  <section className={styles.grid}>
   <article className={styles.panel}><div className={styles.panelHead}><span>IDENTITY</span><h2>Create cultivar</h2><p>Canonical names are identities; alternate spellings and marketing names belong in aliases.</p></div><form className={styles.form} onSubmit={createCultivar}><label>Canonical name<input required value={cultivarForm.canonicalName} onChange={e=>setCultivarForm(v=>({...v,canonicalName:e.target.value}))} placeholder="Blueberry Cookies"/></label><div className={styles.row}><label>Breeder<input value={cultivarForm.breeder} onChange={e=>setCultivarForm(v=>({...v,breeder:e.target.value}))}/></label><label>Type<input value={cultivarForm.cultivarType} onChange={e=>setCultivarForm(v=>({...v,cultivarType:e.target.value}))} placeholder="Hybrid, clone-only…"/></label></div><label>Origin<input value={cultivarForm.origin} onChange={e=>setCultivarForm(v=>({...v,origin:e.target.value}))} placeholder="California, breeder program…"/></label><label>Status<select value={cultivarForm.status} onChange={e=>setCultivarForm(v=>({...v,status:e.target.value}))}><option value="unverified">Unverified</option><option value="source_backed">Source-backed</option><option value="verified">Verified source identity</option><option value="conflicting">Conflicting identity</option></select></label><button disabled={saving}>Save cultivar</button></form></article>

   <article className={styles.panel}><div className={styles.panelHead}><span>PROVENANCE</span><h2>Register source</h2><p>Record the source and reuse/licensing note before importing pedigree claims.</p></div><form className={styles.form} onSubmit={addSource}><div className={styles.row}><label>Source name<input required value={sourceForm.sourceName} onChange={e=>setSourceForm(v=>({...v,sourceName:e.target.value}))} placeholder="Breeder / registry / dataset"/></label><label>Source type<input required value={sourceForm.sourceType} onChange={e=>setSourceForm(v=>({...v,sourceType:e.target.value}))} placeholder="breeder, registry, dataset"/></label></div><label>Source URL<input type="url" value={sourceForm.sourceUrl} onChange={e=>setSourceForm(v=>({...v,sourceUrl:e.target.value}))}/></label><div className={styles.row}><label>Evidence type<select value={sourceForm.evidenceType} onChange={e=>setSourceForm(v=>({...v,evidenceType:e.target.value}))}>{evidenceTypes.map(x=><option key={x} value={x}>{label(x)}</option>)}</select></label><label>External ID<input value={sourceForm.externalId} onChange={e=>setSourceForm(v=>({...v,externalId:e.target.value}))}/></label></div><label>License / reuse note<textarea value={sourceForm.licenseNote} onChange={e=>setSourceForm(v=>({...v,licenseNote:e.target.value}))} placeholder="Permission, license, citation-only restriction, import notes…"/></label><label className={styles.check}><input type="checkbox" checked={sourceForm.verified} onChange={e=>setSourceForm(v=>({...v,verified:e.target.checked}))}/><span>Source reviewed by GeoWeedo</span></label><button disabled={saving}>Register source</button></form></article>
  </section>

  <section className={styles.grid}>
   <article className={styles.panel}><div className={styles.panelHead}><span>NAMES</span><h2>Add alias</h2><p>Aliases never create a second cultivar identity.</p></div><form className={styles.form} onSubmit={addAlias}><label>Cultivar<select required value={aliasForm.cultivarId} onChange={e=>setAliasForm(v=>({...v,cultivarId:e.target.value}))}><option value="">Choose cultivar…</option>{data.cultivars.map(c=><option key={c.id} value={c.id}>{c.canonical_name}</option>)}</select></label><label>Alias<input required value={aliasForm.alias} onChange={e=>setAliasForm(v=>({...v,alias:e.target.value}))}/></label><label>Source<select value={aliasForm.sourceId} onChange={e=>setAliasForm(v=>({...v,sourceId:e.target.value}))}><option value="">No source / internal normalization</option>{data.sources.map(s=><option key={s.id} value={s.id}>{s.source_name} · {label(s.evidence_type)}</option>)}</select></label><label className={styles.check}><input type="checkbox" checked={aliasForm.verified} onChange={e=>setAliasForm(v=>({...v,verified:e.target.checked}))}/><span>Verified alias</span></label><button disabled={saving}>Add alias</button></form></article>

   <article className={styles.panel}><div className={styles.panelHead}><span>PEDIGREE CLAIM</span><h2>Add reported parent</h2><p>Each parent edge keeps its own source, confidence, and conflict status.</p></div><form className={styles.form} onSubmit={addLineage}><div className={styles.row}><label>Child<select required value={lineageForm.childCultivarId} onChange={e=>setLineageForm(v=>({...v,childCultivarId:e.target.value}))}><option value="">Choose child…</option>{data.cultivars.map(c=><option key={c.id} value={c.id}>{c.canonical_name}</option>)}</select></label><label>Parent<select required value={lineageForm.parentCultivarId} onChange={e=>setLineageForm(v=>({...v,parentCultivarId:e.target.value}))}><option value="">Choose parent…</option>{data.cultivars.map(c=><option key={c.id} value={c.id}>{c.canonical_name}</option>)}</select></label></div><div className={styles.row}><label>Parent role<select value={lineageForm.parentRole} onChange={e=>setLineageForm(v=>({...v,parentRole:e.target.value}))}><option value="parent_a">Parent A</option><option value="parent_b">Parent B</option><option value="seed">Seed parent</option><option value="pollen">Pollen parent</option><option value="unknown">Unknown</option></select></label><label>Relationship<select value={lineageForm.relationshipType} onChange={e=>setLineageForm(v=>({...v,relationshipType:e.target.value}))}>{relationshipTypes.map(x=><option key={x} value={x}>{label(x)}</option>)}</select></label></div><div className={styles.row}><label>Generation<input value={lineageForm.generation} onChange={e=>setLineageForm(v=>({...v,generation:e.target.value}))} placeholder="F1, BX1, S1…"/></label><label>Confidence 0–100<input type="number" min="0" max="100" value={lineageForm.confidence} onChange={e=>setLineageForm(v=>({...v,confidence:e.target.value}))}/></label></div><label>Source<select value={lineageForm.sourceId} onChange={e=>setLineageForm(v=>({...v,sourceId:e.target.value}))}><option value="">Unknown / unsourced claim</option>{data.sources.map(s=><option key={s.id} value={s.id}>{s.source_name} · {label(s.evidence_type)}</option>)}</select></label><label>Status<select value={lineageForm.status} onChange={e=>setLineageForm(v=>({...v,status:e.target.value}))}>{claimStatuses.map(x=><option key={x} value={x}>{label(x)}</option>)}</select></label><label>Notes<textarea value={lineageForm.notes} onChange={e=>setLineageForm(v=>({...v,notes:e.target.value}))}/></label><button disabled={saving}>Add pedigree claim</button></form></article>
  </section>

  <section className={styles.grid}>
   <article className={styles.panel}><div className={styles.panelHead}><span>WEEDO FACTS LINK</span><h2>Link product to cultivar</h2><p>This associates a retail product with cultivar identity without copying cultivar pedigree into batch chemistry.</p></div><form className={styles.form} onSubmit={linkProduct}><label>Product<select required value={productForm.productId} onChange={e=>setProductForm(v=>({...v,productId:e.target.value}))}><option value="">Choose product…</option>{data.products.map(p=><option key={p.id} value={p.id}>{productLabel(p)}</option>)}</select></label><label>Cultivar<select required value={productForm.cultivarId} onChange={e=>setProductForm(v=>({...v,cultivarId:e.target.value}))}><option value="">Choose cultivar…</option>{data.cultivars.map(c=><option key={c.id} value={c.id}>{c.canonical_name}</option>)}</select></label><div className={styles.row}><label>Source<select value={productForm.sourceId} onChange={e=>setProductForm(v=>({...v,sourceId:e.target.value}))}><option value="">No source</option>{data.sources.map(s=><option key={s.id} value={s.id}>{s.source_name}</option>)}</select></label><label>Confidence<input type="number" min="0" max="100" value={productForm.confidence} onChange={e=>setProductForm(v=>({...v,confidence:e.target.value}))}/></label></div><label>Status<select value={productForm.status} onChange={e=>setProductForm(v=>({...v,status:e.target.value}))}>{claimStatuses.map(x=><option key={x} value={x}>{label(x)}</option>)}</select></label><label>Notes<textarea value={productForm.notes} onChange={e=>setProductForm(v=>({...v,notes:e.target.value}))}/></label><button disabled={saving}>Link product</button></form></article>

   <article className={styles.panel}><div className={styles.panelHead}><span>GENETIC EVIDENCE</span><h2>Add measured relationship</h2><p>Use only for genotype/DNA evidence. This does not create a parent/child pedigree edge.</p></div><form className={styles.form} onSubmit={addGenetic}><div className={styles.row}><label>Cultivar A<select required value={geneticForm.cultivarAId} onChange={e=>setGeneticForm(v=>({...v,cultivarAId:e.target.value}))}><option value="">Choose…</option>{data.cultivars.map(c=><option key={c.id} value={c.id}>{c.canonical_name}</option>)}</select></label><label>Cultivar B<select required value={geneticForm.cultivarBId} onChange={e=>setGeneticForm(v=>({...v,cultivarBId:e.target.value}))}><option value="">Choose…</option>{data.cultivars.map(c=><option key={c.id} value={c.id}>{c.canonical_name}</option>)}</select></label></div><label>Genetic dataset source<select required value={geneticForm.sourceId} onChange={e=>setGeneticForm(v=>({...v,sourceId:e.target.value}))}><option value="">Choose source…</option>{data.sources.filter(s=>s.evidence_type==='genetic_dataset').map(s=><option key={s.id} value={s.id}>{s.source_name}</option>)}</select></label><div className={styles.row}><label>Relationship label<input value={geneticForm.relationshipLabel} onChange={e=>setGeneticForm(v=>({...v,relationshipLabel:e.target.value}))}/></label><label>Similarity score<input inputMode="decimal" value={geneticForm.similarityScore} onChange={e=>setGeneticForm(v=>({...v,similarityScore:e.target.value}))} placeholder="Dataset-specific"/></label></div><label className={styles.check}><input type="checkbox" checked={geneticForm.verified} onChange={e=>setGeneticForm(v=>({...v,verified:e.target.checked}))}/><span>Genetic evidence reviewed</span></label><button disabled={saving}>Add genetic relationship</button></form></article>
  </section>

  <section className={styles.audit}><div className={styles.auditHead}><div className={styles.panelHead}><span>CURATION VIEW</span><h2>Cultivars & pedigree claims</h2><p>The graph visualization comes after this evidence layer is populated and trustworthy.</p></div><input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Filter cultivar, breeder, parent, source…"/></div><div className={styles.tables}>
   <div className={styles.tableWrap}><table><thead><tr><th>Cultivar</th><th>Identity</th><th>Pedigree</th><th>Products</th></tr></thead><tbody>{filteredCultivars.map(c=><tr key={c.id}><td><strong>{c.canonical_name}</strong><small>{c.breeder||'Breeder unknown'}</small></td><td><span>{label(c.status)}</span><small>{Number(c.alias_count||0)} aliases · {c.cultivar_type||'type unknown'}</small></td><td><span>{Number(c.parent_claim_count||0)} parent claims</span><small>{Number(c.child_claim_count||0)} descendant claims</small></td><td>{Number(c.product_count||0)}</td></tr>)}</tbody></table></div>
   <div className={styles.tableWrap}><table><thead><tr><th>Reported pedigree</th><th>Relationship</th><th>Evidence</th><th>Confidence</th></tr></thead><tbody>{filteredLineage.map(row=><tr key={row.id}><td><strong>{row.child_name}</strong><small>← {row.parent_name}</small></td><td><span>{label(row.relationship_type)} {row.generation||''}</span><small>{label(row.parent_role)} · {label(row.status)}</small></td><td>{row.source_url?<a href={row.source_url} target="_blank" rel="noreferrer">{row.source_name||'Source'} ↗</a>:<span>{row.source_name||'Unsourced'}</span>}<small>{label(row.evidence_type)}</small></td><td><b>{row.confidence}%</b></td></tr>)}</tbody></table></div>
  </div></section>
 </main>;
}
