'use client';

import {useEffect,useMemo,useState} from 'react';

type Visitor={visitorId:string;userId:string;ipAddress:string;networkId:string;sessions:number;pageViews:number;firstSeen:string;lastSeen:string;country:string;region:string;city:string;device:string;browser:string;landingPath:string;referrer:string;currentPage:string;currentPageAt:string;activeNow:boolean};
type Props={days:number;excludeAdmin:boolean;excludedIps:string[]};
function when(value:string){return value?new Date(value).toLocaleString():'—';}
function shortId(value:string){return value.length>16?`${value.slice(0,12)}…`:value;}
async function responseJson(response:Response){const text=await response.text();if(!text)throw new Error(`Analytics API returned an empty response (${response.status}).`);try{return JSON.parse(text);}catch{throw new Error(`Analytics API returned an invalid response (${response.status}).`);}}

export default function AdminIndividualVisitors({days,excludeAdmin,excludedIps}:Props){
 const [users,setUsers]=useState<Visitor[]>([]),[query,setQuery]=useState(''),[rows,setRows]=useState(25),[page,setPage]=useState(1),[loading,setLoading]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let cancelled=false,timer:ReturnType<typeof setInterval>|null=null;const load=async(initial=false)=>{if(initial)setLoading(true);try{const params=new URLSearchParams({mode:'users',days:String(days),excludeAdmin:excludeAdmin?'1':'0'});if(excludedIps.length)params.set('excludeIps',excludedIps.join(','));const response=await fetch(`/api/admin/analytics?${params}`,{cache:'no-store'});const data=await responseJson(response);if(response.status===401){location.href='/admin/login';return;}if(!response.ok)throw new Error(data?.error||'Individual users failed to load.');if(!cancelled){setUsers(Array.isArray(data?.users)?data.users:[]);setError('');}}catch(e){if(!cancelled)setError(e instanceof Error?e.message:'Individual users failed to load.');}finally{if(initial&&!cancelled)setLoading(false);}};void load(true);timer=setInterval(()=>void load(false),15000);return()=>{cancelled=true;if(timer)clearInterval(timer);};},[days,excludeAdmin,excludedIps]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return users;return users.filter(u=>`${u.userId} ${u.ipAddress} ${u.city} ${u.region} ${u.country} ${u.device} ${u.browser} ${u.landingPath} ${u.currentPage} ${u.referrer}`.toLowerCase().includes(q));},[users,query]);
 useEffect(()=>setPage(1),[query,rows,days,excludeAdmin,excludedIps]);
 const pages=Math.max(1,Math.ceil(filtered.length/rows)),safePage=Math.min(page,pages),start=(safePage-1)*rows,shown=filtered.slice(start,start+rows),liveCount=filtered.filter(user=>user.activeNow).length;
 return <section className="admin-individual-visitors traffic-individual-users">
  <div className="admin-individual-visitors-head"><div><span>INDIVIDUAL USERS</span><h3>Who is using GeoWeedo</h3><p>Identified visitor records are shown with their latest page. A LIVE badge means the visitor has been seen within the last 10 minutes.</p></div><strong>{filtered.length.toLocaleString()} identified{liveCount?` · ${liveCount.toLocaleString()} live`:''}</strong></div>
  <div className="admin-individual-visitors-tools"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search IP, location, account, device, page…"/><label>Rows <select value={rows} onChange={e=>setRows(Number(e.target.value))}><option value={10}>10</option><option value={25}>25</option><option value={50}>50</option><option value={100}>100</option></select></label></div>
  <div className="admin-individual-visitors-status">{loading?'Loading identified visitors…':error||`${filtered.length.toLocaleString()} identified visitor${filtered.length===1?'':'s'} · Page ${safePage} of ${pages} · refreshes every 15s`}</div>
  {!loading&&!error&&<div className="admin-individual-visitors-table-wrap"><table className="admin-table admin-individual-visitors-table"><thead><tr><th>IP address</th><th>Location</th><th>Account</th><th>Device</th><th>Current / last page</th><th>Sessions</th><th>Views</th><th>Last seen</th><th>First seen</th><th>Entry / referrer</th></tr></thead><tbody>{shown.length?shown.map(user=><tr key={user.visitorId}><td>{user.ipAddress?<code>{user.ipAddress}</code>:<span className="admin-visitor-anonymous">Signed-in account</span>}</td><td>{[user.city,user.region,user.country].filter(Boolean).join(', ')||'Location unavailable'}</td><td>{user.userId?<code title={user.userId}>{shortId(user.userId)}</code>:<span className="admin-visitor-anonymous">—</span>}</td><td>{user.device} · {user.browser}</td><td><div style={{display:'flex',gap:6,alignItems:'center',flexWrap:'wrap'}}>{user.activeNow&&<strong style={{fontSize:10,padding:'2px 6px',borderRadius:999,background:'rgba(103,214,110,.16)',border:'1px solid rgba(103,214,110,.35)'}}>LIVE</strong>}<span className="admin-visitor-route" title={user.currentPage||user.landingPath||'/'}>{user.currentPage||user.landingPath||'/'}</span></div><small>{user.currentPageAt?when(user.currentPageAt):'Latest route unavailable'}</small></td><td>{user.sessions.toLocaleString()}</td><td>{user.pageViews.toLocaleString()}</td><td>{when(user.lastSeen)}</td><td>{when(user.firstSeen)}</td><td><span className="admin-visitor-route">{user.landingPath||'/'}</span>{user.referrer&&<small>{user.referrer}</small>}</td></tr>):<tr><td colSpan={10}>No identified visitors in this range yet. New traffic will appear here once an IP or signed-in account is captured.</td></tr>}</tbody></table></div>}
  {pages>1&&<div className="admin-individual-visitors-pages"><button disabled={safePage<=1} onClick={()=>setPage(1)}>First</button><button disabled={safePage<=1} onClick={()=>setPage(p=>Math.max(1,p-1))}>Previous</button><span>{start+1}–{Math.min(start+rows,filtered.length)} of {filtered.length}</span><button disabled={safePage>=pages} onClick={()=>setPage(p=>Math.min(pages,p+1))}>Next</button><button disabled={safePage>=pages} onClick={()=>setPage(pages)}>Last</button></div>}
 </section>;
}