'use client';

import {useEffect,useMemo,useState} from 'react';

type Row={
 id:string;kind:'dispensary'|'candidate';name:string;street_address?:string;city?:string;region?:string;postal_code?:string;country?:string;
 latitude?:number|null;longitude?:number|null;website?:string;phone?:string;license_number?:string;license_status?:string;license_type?:string;license_types?:string[];
 data_source?:string;source_url?:string;source_license?:string;recreational?:number;medical?:number;verified?:number;active?:number;status?:string;
 imagery_status?:string;imagery_provider?:string;sponsored_until?:string;profile?:{overview?:string;phone?:string;website?:string;hours?:Record<string,string>;amenities?:string[];social?:Record<string,string>};
};
type Need='all'|'website'|'phone'|'hours'|'address'|'license'|'overview'|'amenities'|'social'|'source';
const DAYS=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
function value(r:Row,key:'website'|'phone'){return String(r.profile?.[key]||r[key]||'').trim();}
function hoursCount(r:Row){return DAYS.filter(day=>String(r.profile?.hours?.[day]||'').trim()).length;}
function hasAddress(r:Row){return Boolean(String(r.street_address||'').trim()&&String(r.city||'').trim()&&String(r.region||'').trim()&&String(r.country||'').trim());}
function hasCoords(r:Row){return Number.isFinite(Number(r.latitude))&&Number.isFinite(Number(r.longitude));}
function completeness(r:Row){const checks=[Boolean(value(r,'website')),Boolean(value(r,'phone')),hoursCount(r)>=7,hasAddress(r),hasCoords(r),Boolean(String(r.license_number||'').trim()),Boolean(String(r.profile?.overview||'').trim()),Boolean(r.profile?.amenities?.length),Boolean(Object.values(r.profile?.social||{}).some(Boolean)),Boolean(String(r.data_source||'').trim()&&String(r.source_url||'').trim()),Boolean(r.imagery_provider)];return Math.round(checks.filter(Boolean).length/checks.length*100);}
function missing(r:Row,need:Need){if(need==='all')return true;if(need==='website')return !value(r,'website');if(need==='phone')return !value(r,'phone');if(need==='hours')return hoursCount(r)<7;if(need==='address')return !hasAddress(r);if(need==='license')return !String(r.license_number||'').trim();if(need==='overview')return !String(r.profile?.overview||'').trim();if(need==='amenities')return !(r.profile?.amenities?.length);if(need==='social')return !Object.values(r.profile?.social||{}).some(Boolean);if(need==='source')return !(String(r.data_source||'').trim()&&String(r.source_url||'').trim());return false;}
function badge(ok:boolean,label:string,detail?:string){return <span style={{display:'inline-flex',gap:5,alignItems:'center',padding:'4px 7px',border:'1px solid rgba(255,255,255,.09)',borderRadius:999,fontSize:11,opacity:ok?1:.58}}>{ok?'✓':'—'} {label}{detail?` ${detail}`:''}</span>}

export default function AdminEnabledProfileAudit(){
 const[rows,setRows]=useState<Row[]>([]),[need,setNeed]=useState<Need>('all'),[query,setQuery]=useState(''),[sort,setSort]=useState<'worst'|'name'>('worst'),[message,setMessage]=useState('Loading enabled dispensaries…');
 async function load(){const r=await fetch('/api/admin/dispensary-records',{cache:'no-store'});if(r.status===401){location.href='/admin/login';return;}const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load dispensaries.');const enabled=(d.records||[]).filter((x:Row)=>x.kind==='dispensary'&&x.active!==0&&Boolean(x.verified)&&hasCoords(x)&&Boolean(x.imagery_provider));setRows(enabled);setMessage(`${enabled.length.toLocaleString()} gameplay-enabled dispensaries audited.`);}
 useEffect(()=>{load().catch(e=>setMessage(e instanceof Error?e.message:'Audit failed.'));},[]);
 const stats=useMemo(()=>({total:rows.length,website:rows.filter(r=>Boolean(value(r,'website'))).length,phone:rows.filter(r=>Boolean(value(r,'phone'))).length,hours:rows.filter(r=>hoursCount(r)>=7).length,address:rows.filter(hasAddress).length,license:rows.filter(r=>Boolean(String(r.license_number||'').trim())).length,overview:rows.filter(r=>Boolean(String(r.profile?.overview||'').trim())).length,amenities:rows.filter(r=>Boolean(r.profile?.amenities?.length)).length,source:rows.filter(r=>Boolean(String(r.data_source||'').trim()&&String(r.source_url||'').trim())).length}),[rows]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();const list=rows.filter(r=>missing(r,need)&&(!q||`${r.name} ${r.city||''} ${r.region||''} ${r.country||''}`.toLowerCase().includes(q)));list.sort((a,b)=>sort==='worst'?completeness(a)-completeness(b)||a.name.localeCompare(b.name):a.name.localeCompare(b.name));return list;},[rows,need,query,sort]);
 const pct=(n:number)=>stats.total?Math.round(n/stats.total*100):0;
 return <section className="admin-panel enabled-profile-audit" style={{marginBottom:24}}>
  <div className="admin-panel-heading"><div><span className="eyebrow">ENABLED PROFILE AUDIT</span><h2>Gameplay dispensary profile quality</h2><p className="admin-copy">Audit only currently gameplay-enabled dispensaries. A stored website is counted as present, not automatically proven live; use Open website or the enrichment queue to verify current business information.</p></div></div>
  <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(145px,1fr))',gap:10,margin:'14px 0'}}>
   {([['Enabled',stats.total,100],['Website',stats.website,pct(stats.website)],['Phone',stats.phone,pct(stats.phone)],['7-day hours',stats.hours,pct(stats.hours)],['Full address',stats.address,pct(stats.address)],['License',stats.license,pct(stats.license)],['Overview',stats.overview,pct(stats.overview)],['Amenities',stats.amenities,pct(stats.amenities)],['Source',stats.source,pct(stats.source)]] as const).map(([label,count,percent])=><article className="admin-card" key={label} style={{minHeight:0,padding:12}}><span className="eyebrow">{label}</span><h3 style={{margin:'4px 0',fontSize:24}}>{count.toLocaleString()}</h3><small>{percent}% coverage</small></article>)}
  </div>
  <div style={{display:'grid',gridTemplateColumns:'minmax(220px,2fr) minmax(180px,1fr) minmax(150px,1fr)',gap:8,marginBottom:10}}><input placeholder="Search enabled dispensary…" value={query} onChange={e=>setQuery(e.target.value)}/><select value={need} onChange={e=>setNeed(e.target.value as Need)}><option value="all">All enabled</option><option value="website">Missing website</option><option value="phone">Missing telephone</option><option value="hours">Incomplete hours</option><option value="address">Incomplete address</option><option value="license">Missing license number</option><option value="overview">Missing overview</option><option value="amenities">Missing amenities/services</option><option value="social">Missing social links</option><option value="source">Missing source/provenance</option></select><select value={sort} onChange={e=>setSort(e.target.value as 'worst'|'name')}><option value="worst">Lowest completeness first</option><option value="name">Name A → Z</option></select></div>
  <p className="admin-status">{message} · {filtered.length.toLocaleString()} shown.</p>
  <div style={{overflowX:'auto',maxHeight:620,border:'1px solid rgba(255,255,255,.08)',borderRadius:12}}><table className="admin-table" style={{minWidth:1150}}><thead><tr><th>Dispensary</th><th>Complete</th><th>Profile checks</th><th>Website</th><th>Actions</th></tr></thead><tbody>{filtered.map(r=>{const site=value(r,'website'),phone=value(r,'phone'),score=completeness(r),hc=hoursCount(r);return <tr key={r.id}><td><strong>{r.name}</strong><div><small>{[r.city,r.region,r.country].filter(Boolean).join(', ')}</small></div></td><td><strong>{score}%</strong></td><td><div style={{display:'flex',gap:5,flexWrap:'wrap',maxWidth:520}}>{badge(Boolean(phone),'Phone')}{badge(hc>=7,'Hours',`${hc}/7`)}{badge(hasAddress(r),'Address')}{badge(Boolean(r.license_number),'License')}{badge(Boolean(r.profile?.overview),'Overview')}{badge(Boolean(r.profile?.amenities?.length),'Amenities')}{badge(Object.values(r.profile?.social||{}).some(Boolean),'Social')}{badge(Boolean(r.data_source&&r.source_url),'Source')}{badge(Boolean(r.imagery_provider),'Street View')}</div></td><td>{site?<a href={site} target="_blank" rel="noreferrer" style={{wordBreak:'break-all'}}>Open website ↗</a>:<span style={{opacity:.6}}>Missing</span>}</td><td><div style={{display:'flex',gap:6,flexWrap:'wrap'}}><a className="ghost" href={`/admin/dispensaries#dispensary-edit-panel`}>Edit</a>{site&&<a className="ghost" href={site} target="_blank" rel="noreferrer">Verify site</a>}</div></td></tr>})}</tbody></table></div>
  <div style={{marginTop:14,padding:14,border:'1px solid rgba(103,214,110,.18)',borderRadius:12}}><span className="eyebrow">RECOMMENDED PROFILE STANDARD</span><p className="admin-copy" style={{marginBottom:0}}>For a strong public listing, establish: legal/store name, complete address, coordinates, active website, telephone, seven-day opening hours, license number/status/type, recreational/medical availability, short overview, amenities/services, social links, official source/provenance, current Street View, and a periodic last-verified date. Future useful fields: accessibility, pickup/delivery, online ordering/menu URL, payment methods, age/entry notes, parking, and owner-claimed status.</p></div>
 </section>;
}
