'use client';

import { useEffect, useMemo, useState } from 'react';

type Player = { id:string; handle:string; yerbasAddress:string; rewardEligible:boolean };
type Reward = { id:string; playerId:string; amountYerb:number; reason:string; reference?:string; status:string; createdAt:string };
type RewardPolicy = {
  enabled:boolean; classicEnabled:boolean; huntEnabled:boolean; dailyEnabled:boolean;
  yerbPerPoint:number; classicPerfectRewardYerb:number; huntPerfectRewardYerb:number; dailyPerfectRewardYerb:number;
  dailyCapYerb:number; perGameCapYerb:number; reviewRequired:boolean; rewardCooldownMinutes:number; maxRewardedGamesPerDay:number;
  huntMaxGuesses:number; huntWinRadiusKm:number; huntStateClueGuess:number; huntCityClueGuess:number;
};
const DEFAULT_POLICY:RewardPolicy={enabled:true,classicEnabled:true,huntEnabled:true,dailyEnabled:true,yerbPerPoint:.0004,classicPerfectRewardYerb:10,huntPerfectRewardYerb:2,dailyPerfectRewardYerb:2,dailyCapYerb:25,perGameCapYerb:10,reviewRequired:true,rewardCooldownMinutes:0,maxRewardedGamesPerDay:0,huntMaxGuesses:10,huntWinRadiusKm:10,huntStateClueGuess:3,huntCityClueGuess:6};

export default function AdminRewardManager(){
 const[players,setPlayers]=useState<Player[]>([]),[rewards,setRewards]=useState<Reward[]>([]),[playerId,setPlayerId]=useState(''),[amount,setAmount]=useState('1'),[reason,setReason]=useState('GeoWeedo gameplay reward'),[reference,setReference]=useState(''),[status,setStatus]=useState('Loading YERB reward ledger…'),[policy,setPolicy]=useState<RewardPolicy>(DEFAULT_POLICY),[savingPolicy,setSavingPolicy]=useState(false);
 const playerMap=useMemo(()=>new Map(players.map(x=>[x.id,x])),[players]);
 async function load(){const[r,p]=await Promise.all([fetch('/api/admin/rewards',{cache:'no-store'}),fetch('/api/admin/rewards/policy',{cache:'no-store'})]);if(r.status===401||p.status===401){location.href='/admin/login';return;}const rd=await r.json(),pd=await p.json();if(!r.ok)throw new Error(rd.error||'Admin access failed.');if(!p.ok)throw new Error(pd.error||'Could not load reward policy.');setPlayers(rd.players||[]);setRewards((rd.rewards||[]).slice().reverse());setPolicy({...DEFAULT_POLICY,...(pd.policy||{})});setPlayerId(v=>v||rd.players?.[0]?.id||'');setStatus(`Loaded ${rd.rewards?.length||0} reward entries.`);}
 useEffect(()=>{load().catch(e=>setStatus(e.message));},[]);
 async function savePolicy(){setSavingPolicy(true);try{const r=await fetch('/api/admin/rewards/policy',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(policy)}),d=await r.json();if(!r.ok)throw new Error(d.error||'Could not save gameplay reward policy.');setPolicy({...DEFAULT_POLICY,...d.policy});setStatus(`Saved rewards · Classic ${d.policy.classicPerfectRewardYerb} YERB · Hunt ${d.policy.huntPerfectRewardYerb} YERB · Daily ${d.policy.dailyPerfectRewardYerb} YERB.`);}catch(e){setStatus(e instanceof Error?e.message:'Could not save gameplay reward policy.');}finally{setSavingPolicy(false);}}
 async function queue(){const r=await fetch('/api/admin/rewards',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({playerId,amountYerb:Number(amount),reason,reference})}),d=await r.json();if(!r.ok)return setStatus(d.error||'Could not queue reward.');setStatus(`Queued ${d.reward.amountYerb} YERB.`);setReference('');await load();}
 async function setState(item:Reward,next:string){const r=await fetch('/api/admin/rewards',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:item.id,status:next})}),d=await r.json();if(!r.ok)return setStatus(d.error||'Could not update reward.');await load();}
 async function logout(){await fetch('/api/admin/auth/logout',{method:'POST'});location.href='/admin/login';}
 const numberField=(key:keyof RewardPolicy,label:string,help:string,step='0.00000001')=><div className="admin-form"><label>{label}<input type="number" min="0" step={step} value={String(policy[key])} onChange={e=>setPolicy({...policy,[key]:Number(e.target.value)})}/></label><small>{help}</small></div>;
 return <main className="admin-shell">
  <header className="admin-header"><div><span className="eyebrow">GEOWEEDO ADMIN</span><h1>YERB reward control</h1></div><div className="admin-links"><a href="/admin/data">Data</a><a href="/admin/dispensaries">Imagery</a><a href="/admin/wallet">Wallet</a><a href="/admin/sponsorships">Sponsorships</a><a href="/">Game</a><button className="ghost" onClick={logout}>Log out</button></div></header>
  <div className="admin-status">{status}</div>
  <section className="admin-panel" style={{marginBottom:20}}>
   <div style={{display:'flex',justifyContent:'space-between',gap:18,alignItems:'flex-start',flexWrap:'wrap'}}><div><span className="eyebrow">GAMEPLAY REWARD POLICY</span><h2 style={{marginTop:6}}>Control each game’s YERB value</h2><p className="admin-help">Each mode has an independent perfect-score reward. Lower scores scale proportionally. Daily player caps and timing rules still apply across all modes.</p></div><label style={{display:'flex',gap:10,alignItems:'center',fontWeight:800}}><input type="checkbox" checked={policy.enabled} onChange={e=>setPolicy({...policy,enabled:e.target.checked})}/> Gameplay rewards enabled</label></div>
   <div className="admin-grid" style={{marginTop:18}}>
    <div className="admin-panel" style={{padding:16}}><label style={{display:'flex',gap:10,alignItems:'center'}}><input type="checkbox" checked={policy.classicEnabled} onChange={e=>setPolicy({...policy,classicEnabled:e.target.checked})}/><strong>🎮 Classic GeoWeedo</strong></label><div className="admin-form" style={{marginTop:12}}><label>Perfect game reward (25,000 points)<input type="number" min="0" step="0.00000001" value={policy.classicPerfectRewardYerb} onChange={e=>setPolicy({...policy,classicPerfectRewardYerb:Number(e.target.value)})}/></label><small>YERB awarded for a perfect five-round Classic game.</small></div></div>
    <div className="admin-panel" style={{padding:16}}><label style={{display:'flex',gap:10,alignItems:'center'}}><input type="checkbox" checked={policy.huntEnabled} onChange={e=>setPolicy({...policy,huntEnabled:e.target.checked})}/><strong>🌿 Weedo Hunt</strong></label><div className="admin-form" style={{marginTop:12}}><label>Perfect Hunt reward (5,000 points)<input type="number" min="0" step="0.00000001" value={policy.huntPerfectRewardYerb} onChange={e=>setPolicy({...policy,huntPerfectRewardYerb:Number(e.target.value)})}/></label><small>Maximum YERB for a 5,000-point Hunt.</small></div></div>
    <div className="admin-panel" style={{padding:16}}><label style={{display:'flex',gap:10,alignItems:'center'}}><input type="checkbox" checked={policy.dailyEnabled} onChange={e=>setPolicy({...policy,dailyEnabled:e.target.checked})}/><strong>🌎 Daily Weedo</strong></label><div className="admin-form" style={{marginTop:12}}><label>Perfect Daily reward (5,000 points)<input type="number" min="0" step="0.00000001" value={policy.dailyPerfectRewardYerb} onChange={e=>setPolicy({...policy,dailyPerfectRewardYerb:Number(e.target.value)})}/></label><small>Maximum YERB for a perfect Daily guess.</small></div></div>
   </div>
   <div style={{marginTop:22,borderTop:'1px solid rgba(255,255,255,.08)',paddingTop:20}}><span className="eyebrow">GLOBAL REWARD LIMITS</span><div className="admin-grid" style={{marginTop:12}}>{numberField('dailyCapYerb','Daily YERB cap per player','Maximum total gameplay YERB a player can earn in one day.')}<div className="admin-form"><label style={{display:'flex',gap:10,alignItems:'center'}}><input type="checkbox" checked={policy.reviewRequired} onChange={e=>setPolicy({...policy,reviewRequired:e.target.checked})}/> Require reward review</label><small>Hold earned YERB for Admin review before posting.</small></div>{numberField('rewardCooldownMinutes','Cooldown between rewarded games (minutes)','0 = no cooldown.','1')}{numberField('maxRewardedGamesPerDay','Maximum rewarded games per player / day','0 = unlimited.','1')}</div></div>
   <div style={{marginTop:22,borderTop:'1px solid rgba(255,255,255,.08)',paddingTop:20}}><span className="eyebrow">WEEDO HUNT DIFFICULTY</span><div className="admin-grid" style={{marginTop:12}}>{numberField('huntMaxGuesses','Maximum guesses','Default: 10.','1')}{numberField('huntWinRadiusKm','Win radius (km)','Default: 10 km.','0.1')}{numberField('huntStateClueGuess','Reveal state/province after guess','Default: 3.','1')}{numberField('huntCityClueGuess','Reveal city first letter after guess','Default: 6.','1')}</div></div>
   <div style={{display:'flex',justifyContent:'flex-end',marginTop:20}}><button className="primary" disabled={savingPolicy} onClick={savePolicy}>{savingPolicy?'Saving…':'Save gameplay reward policy'}</button></div>
  </section>
  <section className="admin-grid"><div className="admin-panel"><h2>Queue reviewed reward</h2><div className="admin-form"><select value={playerId} onChange={e=>setPlayerId(e.target.value)}>{players.map(p=><option value={p.id} key={p.id}>{p.handle} — {p.yerbasAddress}</option>)}</select><input type="number" min="0" step="0.00000001" value={amount} onChange={e=>setAmount(e.target.value)}/><input value={reason} onChange={e=>setReason(e.target.value)}/><input value={reference} onChange={e=>setReference(e.target.value)} placeholder="Unique game/reference ID (optional)"/><button className="primary" disabled={!playerId||Number(amount)<=0} onClick={queue}>Add pending reward</button></div></div><div className="admin-panel"><h2>Reward model</h2><div className="source-note"><strong>Independent values</strong><span>Classic, Hunt, and Daily can be priced separately.</span></div><div className="source-note"><strong>Proportional scoring</strong><span>50% of a mode’s perfect score earns 50% of that mode’s configured perfect reward, before daily limits.</span></div><div className="source-note"><strong>Shared safeguards</strong><span>Daily cap, cooldown, game-count limit, eligibility, and review rules apply to every mode.</span></div></div></section>
  <section className="admin-panel approved-list"><h2>Reward entries</h2>{rewards.length===0?<p>No rewards queued yet.</p>:rewards.map(item=>{const p=playerMap.get(item.playerId);return <div className="candidate-row" key={item.id}><div><strong>{item.amountYerb} YERB · {p?.handle||item.playerId}</strong><span>{item.reason}{item.reference?` · ${item.reference}`:''}</span><small>{p?.yerbasAddress||'No verified address'}</small></div><div className="candidate-actions"><span className={`status-pill ${item.status}`}>{item.status}</span>{item.status==='pending'&&<button onClick={()=>setState(item,'held')}>Hold</button>}{item.status==='held'&&<button onClick={()=>setState(item,'pending')}>Release</button>}{item.status!=='posted'&&item.status!=='cancelled'&&<button onClick={()=>setState(item,'posted')}>Credit balance</button>}</div></div>;})}</section>
 </main>;
}
