'use client';
import {useEffect,useState} from 'react';
import {createPortal} from 'react-dom';

export default function AmsterdamCoffeeshopImporter(){
 const[busy,setBusy]=useState(false),[status,setStatus]=useState(''),[target,setTarget]=useState<HTMLElement|null>(null);
 useEffect(()=>{
  const locate=()=>{
   const headings=Array.from(document.querySelectorAll('.admin-panel h2'));
   const heading=headings.find(node=>node.textContent?.trim()==='Nationwide official-source sync'||node.textContent?.trim()==='Official-source sync by country');
   const panel=heading?.closest('.admin-panel') as HTMLElement|null;
   if(!panel)return false;
   if(heading)heading.textContent='Official-source sync by country';
   if(!panel.querySelector('[data-country-heading="USA"]')){
    const firstNote=panel.querySelector('.source-note');
    if(firstNote){const usa=document.createElement('div');usa.dataset.countryHeading='USA';usa.style.cssText='margin:14px 0 8px;padding:8px 10px;border-top:1px solid var(--line);border-bottom:1px solid var(--line);font-size:11px;font-weight:900;letter-spacing:.12em;color:var(--muted)';usa.innerHTML='<span style="color:var(--text)">UNITED STATES</span><small style="display:block;margin-top:3px;font-size:10px;font-weight:600;letter-spacing:.03em;color:var(--muted)">Integrated state licensing feeds</small>';panel.insertBefore(usa,firstNote);}
   }
   setTarget(panel);return true;
  };
  if(locate())return;
  const observer=new MutationObserver(()=>{if(locate())observer.disconnect();});observer.observe(document.body,{childList:true,subtree:true});return()=>observer.disconnect();
 },[]);
 async function run(){setBusy(true);setStatus('Fetching Amsterdam coffeeshops from the official permit source…');try{const r=await fetch('/api/admin/candidates/fetch-amsterdam',{method:'POST'});if(r.status===401){location.href='/admin/login';return;}const d=await r.json();if(!r.ok)throw new Error(d.error||'Amsterdam import failed.');const source=d.sourceType==='osm-fallback'?'OpenStreetMap fallback':'Gemeente Amsterdam';const warning=d.warning?` ${d.warning}`:'';setStatus(`Amsterdam · ${source}: ${d.fetched} coffeeshops fetched · ${d.added} new candidates · ${d.geocoded} map-ready.${warning} Refreshing the page will show them in the review queue.`);}catch(e){setStatus(e instanceof Error?e.message:'Amsterdam import failed.');}finally{setBusy(false);}}
 async function validate(){setBusy(true);setStatus('Validating Amsterdam candidates for duplicates, suspicious businesses, location quality, and imagery…');try{const r=await fetch('/api/admin/candidates/validate-amsterdam',{method:'POST'});if(r.status===401){location.href='/admin/login';return;}const d=await r.json();if(!r.ok)throw new Error(d.error||'Amsterdam validation failed.');const ids:string[]=Array.isArray(d.imageryIds)?d.imageryIds:[];let checked=0,playable=0,noCoverage=0,errors=0;for(let i=0;i<ids.length;i+=10){const batch=ids.slice(i,i+10);setStatus(`Amsterdam structural validation complete. Checking imagery ${Math.min(i+10,ids.length)}/${ids.length}…`);const ir=await fetch('/api/admin/candidates/check-imagery',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids:batch,limit:10})});if(ir.status===401){location.href='/admin/login';return;}const idata=await ir.json();if(!ir.ok)throw new Error(idata.error||'Amsterdam imagery validation failed.');const results=Array.isArray(idata.results)?idata.results:[];checked+=results.length;playable+=results.filter((x:any)=>x?.imageryStatus==='coverage').length;noCoverage+=results.filter((x:any)=>x?.imageryStatus==='no_coverage').length;errors+=results.filter((x:any)=>x?.imageryStatus==='error').length;}const s=d.summary||{};setStatus(`Amsterdam validation complete: ${s.scanned||0} scanned · ${s.passed||0} structurally passed · ${s.duplicates||0} duplicates rejected · ${s.nonCoffeeshop||0} obvious non-coffeeshops rejected · ${s.review||0} held for manual review · imagery ${checked} checked / ${playable} playable / ${noCoverage} no coverage / ${errors} errors. Refresh the review queue to inspect results.`);}catch(e){setStatus(e instanceof Error?e.message:'Amsterdam validation failed.');}finally{setBusy(false);}}
 if(!target)return null;
 return createPortal(<div data-country-heading="Netherlands" style={{marginTop:16,paddingTop:12,borderTop:'1px solid var(--line)'}}><div style={{marginBottom:8,fontSize:11,fontWeight:900,letterSpacing:'.12em',color:'var(--muted)'}}><span style={{color:'var(--text)'}}>NETHERLANDS</span><small style={{display:'block',marginTop:3,fontSize:10,fontWeight:600,letterSpacing:'.03em',color:'var(--muted)'}}>Amsterdam · North Holland</small></div><div className="source-note"><strong>Amsterdam coffeeshops</strong><span>Prefer the public Gemeente Amsterdam horeca exploitation-permit dataset. If that source is empty or unavailable, GeoWeedo falls back to supplemental OpenStreetMap cannabis-shop data and labels those candidates accordingly.</span><div style={{display:'flex',gap:10,flexWrap:'wrap'}}><button className="secondary" disabled={busy} onClick={run}>{busy?'Working…':'Fetch Amsterdam coffeeshops'}</button><button className="secondary" disabled={busy} onClick={validate}>Validate Amsterdam candidates</button></div><small style={{display:'block',marginTop:6,color:'var(--muted)'}}>Validation rejects probable duplicates and obvious non-coffeeshops, holds questionable records for review, checks Amsterdam bounds/address quality, then runs imagery checks in safe batches.</small>{status&&<div className="admin-status" style={{marginTop:10}}>{status}</div>}</div></div>,target);
}
