'use client';

import { useEffect, useMemo, useState } from 'react';

type Candidate={region?:string;status:string;streetAddress?:string;city?:string;name:string;latitude?:number;longitude?:number};
type StateStat={region:string;total:number;mapped:number;missing:number;ready:number;manual:number};

function supportsLocationFallback(region:string){return ['montana','alaska','new jersey'].includes(region.trim().toLowerCase());}
function fallbackReady(item:Candidate){return supportsLocationFallback(String(item.region||''))&&Boolean(item.city?.trim())&&Boolean(item.name?.trim());}

export default function CoordinateEnrichmentAllStates(){
 const[candidates,setCandidates]=useState<Candidate[]>([]),[busy,setBusy]=useState<string|null>(null),[message,setMessage]=useState('');
 async function load(){const response=await fetch('/api/admin/candidates',{cache:'no-store'});if(!response.ok)return;const data=await response.json();setCandidates(Array.isArray(data.candidates)?data.candidates:[]);}
 useEffect(()=>{void load();},[]);
 const states=useMemo(()=>{const groups=new Map<string,StateStat>();for(const item of candidates){if(item.status!=='candidate')continue;const region=String(item.region||'').trim();if(!region||String((item as any).country||'USA').toUpperCase()!=='USA')continue;const current=groups.get(region)||{region,total:0,mapped:0,missing:0,ready:0,manual:0};current.total++;const mapped=Number.isFinite(item.latitude)&&Number.isFinite(item.longitude);if(mapped)current.mapped++;else{current.missing++;if(item.streetAddress?.trim()||fallbackReady(item))current.ready++;else current.manual++;}groups.set(region,current);}return Array.from(groups.values()).sort((a,b)=>a.region.localeCompare(b.region));},[candidates]);
 async function enrich(region:string){setBusy(region);setMessage(`${region}: enriching missing coordinates…`);try{const response=await fetch('/api/admin/candidates/geocode-batch',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({limit:2000,fallbackLimit:500,region})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Coordinate enrichment failed.');setMessage(`${region}: ${data.matched||0} matched · ${data.unmatched||0} unmatched · ${data.remaining||0} remaining.`);await load();}catch(error){setMessage(error instanceof Error?error.message:'Coordinate enrichment failed.');}finally{setBusy(null);}}
 if(!states.length)return null;
 return <section className="admin-panel approved-list" style={{marginTop:18}}><div className="queue-toolbar"><div><h2>Coordinate enrichment · all states</h2><p className="admin-help">Uses the official U.S. Census geocoder for records with street addresses. Montana, Alaska, and New Jersey can also use a conservative OpenStreetMap/Nominatim business-name + city fallback when the official source omits street addresses; only high-confidence in-state matches are accepted.</p></div></div>{message&&<p className="admin-help">{message}</p>}<div style={{display:'grid',gap:8,marginTop:14}}>{states.map(item=>{const complete=item.missing===0;const fallback=supportsLocationFallback(item.region);return <div key={item.region} style={{display:'grid',gridTemplateColumns:'minmax(180px,1fr) auto',gap:14,alignItems:'center',padding:'10px 12px',border:'1px solid var(--line)',borderRadius:10}}><div><strong>{complete?'✓ ':''}{item.region}</strong><small style={{display:'block',color:'var(--muted)',marginTop:3}}>{item.total} loaded · {item.mapped} mapped · {item.missing} need coordinates · {item.ready} {fallback?'fallback-ready':'address-ready'}{item.manual?` · ${item.manual} need address/manual review`:''}</small></div><button className="secondary" disabled={busy!==null||item.ready===0} onClick={()=>enrich(item.region)}>{busy===item.region?'Enriching…':complete?'Fully mapped':fallback?`Enrich ${item.region}`:'Enrich coordinates'}</button></div>})}</div></section>;
}
