'use client';

import {useEffect} from 'react';

type Leader={rank:number;player:string;score:number;earnedYerb:number;rewardStatus:string};
function dateKey(){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Los_Angeles',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());}
function esc(value:unknown){return String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]||ch));}

export default function DailyWeedoEnhancer(){
 useEffect(()=>{
  if(window.location.pathname!=='/daily')return;
  let disposed=false,refreshTimer=0,lastSignature='';
  const shareStatus=(message:string)=>{const button=Array.from(document.querySelectorAll<HTMLButtonElement>('button')).find(item=>item.textContent?.trim()==='Share Daily Result');if(!button)return;let status=button.parentElement?.querySelector<HTMLElement>('[data-daily-share-status]')||null;if(!status){status=document.createElement('div');status.dataset.dailyShareStatus='1';status.style.cssText='font-size:12px;text-align:center;color:#9fe7a5;margin-top:2px;';button.insertAdjacentElement('afterend',status);}status.textContent=message;window.setTimeout(()=>{if(status?.isConnected)status.textContent='';},3500);};
  const copyText=async(text:string)=>{try{await navigator.clipboard.writeText(text);return true;}catch{}try{const area=document.createElement('textarea');area.value=text;area.style.position='fixed';area.style.opacity='0';document.body.appendChild(area);area.focus();area.select();const ok=document.execCommand('copy');area.remove();return ok;}catch{return false;}};
  const handleClick=async(event:Event)=>{const target=event.target as HTMLElement|null;const button=target?.closest('button');if(!button||button.textContent?.trim()!=='Share Daily Result')return;event.preventDefault();event.stopImmediatePropagation();const today=dateKey();let saved:any=null;try{saved=JSON.parse(localStorage.getItem(`geoweedo-daily-${today}`)||'null');}catch{}const score=Number(saved?.score||0),distanceKm=Number(saved?.distanceKm||0),miles=distanceKm*.621371;const rewardText=Array.from(document.querySelectorAll('.daily-weedo-reward strong')).map(item=>item.textContent||'').find(Boolean)||'';const text=`🌎 Daily Weedo ${today}\n📍 ${miles<.1?`${Math.round(miles*5280)} ft`:`${miles.toFixed(1)} mi`}\n⭐ ${score.toLocaleString()} / 5,000${rewardText?`\n🪙 ${rewardText.replace(/^Reward earned:\s*/i,'')}`:''}\nhttps://geoweedo.com/daily\n#GeoWeedo`;
   if(navigator.share){try{await navigator.share({title:'Daily Weedo',text,url:'https://geoweedo.com/daily'});shareStatus('Shared!');return;}catch(error){if((error as Error)?.name==='AbortError'){shareStatus('Share cancelled.');return;}}}
   const copied=await copyText(text);shareStatus(copied?'Daily result copied to clipboard.':'Could not open sharing. Copy your score manually.');
  };
  const render=async()=>{if(disposed)return;const page=document.querySelector('.daily-weedo-page');if(!page)return;try{const response=await fetch('/api/leaderboard/daily',{cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error();const leaders=(data.leaders||[]) as Leader[],signature=JSON.stringify(leaders.map(item=>[item.rank,item.player,item.score,item.earnedYerb]));if(signature===lastSignature&&document.querySelector('[data-daily-leaderboard]'))return;lastSignature=signature;let section=document.querySelector<HTMLElement>('[data-daily-leaderboard]');if(!section){section=document.createElement('section');section.dataset.dailyLeaderboard='1';section.className='daily-leaderboard result-card';page.appendChild(section);}section.innerHTML=`<div class="daily-leaderboard-head"><div><div class="eyebrow">TODAY'S TOP PLAYERS</div><h2>🏆 Daily Weedo Leaderboard</h2></div><span>${esc(data.date||dateKey())}</span></div>${leaders.length?`<div class="daily-leaderboard-table"><div class="daily-leaderboard-row header"><span>Rank</span><span>Player</span><span>Score</span><span>Earned YERB</span></div>${leaders.map(item=>`<div class="daily-leaderboard-row"><strong>#${item.rank}</strong><span>${esc(item.player)}</span><strong>${Number(item.score||0).toLocaleString()}</strong><strong>${Number(item.earnedYerb||0).toFixed(4)} YERB</strong></div>`).join('')}</div>`:'<p>No Daily scores yet. Be the first on the board.</p>'}`;
   }catch{}
  };
  const scheduleRefresh=()=>{window.clearTimeout(refreshTimer);refreshTimer=window.setTimeout(()=>void render(),500);};
  document.addEventListener('click',handleClick,true);const observer=new MutationObserver(scheduleRefresh);observer.observe(document.body,{childList:true,subtree:true,characterData:true});void render();
  const style=document.createElement('style');style.dataset.dailyLeaderboardStyle='1';style.textContent=`.daily-leaderboard{max-width:1360px!important;margin:18px auto 0!important;padding:22px!important;text-align:left!important}.daily-leaderboard-head{display:flex;justify-content:space-between;gap:16px;align-items:end;margin-bottom:14px}.daily-leaderboard-head h2{margin:4px 0 0}.daily-leaderboard-head>span{opacity:.7;font-size:12px}.daily-leaderboard-table{display:grid;gap:1px;border:1px solid rgba(255,255,255,.1);border-radius:12px;overflow:hidden}.daily-leaderboard-row{display:grid;grid-template-columns:70px minmax(120px,1fr) 120px 150px;gap:12px;align-items:center;padding:11px 13px;background:rgba(255,255,255,.025)}.daily-leaderboard-row.header{font-size:10px;text-transform:uppercase;letter-spacing:.08em;color:#9aa69d;background:rgba(255,255,255,.05)}.daily-leaderboard-row>strong:last-child{color:#67d66e}@media(max-width:650px){.daily-leaderboard-row{grid-template-columns:48px minmax(90px,1fr) 80px 110px;font-size:12px;gap:7px;padding:10px 8px}.daily-leaderboard-row.header{font-size:8px}.daily-leaderboard{padding:15px!important}}`;document.head.appendChild(style);
  return()=>{disposed=true;window.clearTimeout(refreshTimer);observer.disconnect();document.removeEventListener('click',handleClick,true);document.querySelector('[data-daily-leaderboard]')?.remove();style.remove();};
 },[]);
 return null;
}
