'use client';

import { useEffect, useState } from 'react';
import { hoursStatus } from '@/lib/dispensaryHours';

type Detail={location:{id:string;name:string;streetAddress?:string;city:string;region:string;postalCode?:string;country:string;website?:string;phone?:string;overview?:string;licenseNumber?:string;dataSource?:string;sourceUrl?:string;hours?:Record<string,string>;amenities?:string[];social?:Record<string,string>;recreational?:boolean;medical?:boolean;verified?:boolean};ratings:{count:number;average:number};reviews:Array<{id:string;author:string;rating:number;title?:string;body?:string;images:string[];createdAt:string}>};
type ClaimState={authenticated:boolean;claim:null|{id:string;status:'pending'|'approved'|'rejected';adminNote?:string;reviewedAt?:string}};
function stars(value:number){return '★★★★★'.split('').map((star,index)=><span key={index} className={index<Math.round(value)?'community-star active':'community-star'}>{star}</span>);}
function normalizeWebsite(value?:string){if(!value)return null;return /^https?:\/\//i.test(value)?value:`https://${value}`;}

export default function DispensaryCommunityDetails({locationId}:{locationId:string}){
 const[data,setData]=useState<Detail|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[showReview,setShowReview]=useState(false),[rating,setRating]=useState(5),[title,setTitle]=useState(''),[body,setBody]=useState(''),[files,setFiles]=useState<File[]>([]),[submitting,setSubmitting]=useState(false),[message,setMessage]=useState<string|null>(null);
 const[claimState,setClaimState]=useState<ClaimState>({authenticated:false,claim:null}),[showClaim,setShowClaim]=useState(false),[claimantName,setClaimantName]=useState(''),[businessEmail,setBusinessEmail]=useState(''),[businessPhone,setBusinessPhone]=useState(''),[roleTitle,setRoleTitle]=useState(''),[businessWebsite,setBusinessWebsite]=useState(''),[evidenceText,setEvidenceText]=useState(''),[claimBusy,setClaimBusy]=useState(false),[claimMessage,setClaimMessage]=useState<string|null>(null);
 useEffect(()=>{let alive=true;setLoading(true);setError(null);Promise.all([fetch(`/api/dispensaries/${encodeURIComponent(locationId)}`,{cache:'no-store'}),fetch(`/api/dispensaries/${encodeURIComponent(locationId)}/claim`,{cache:'no-store'})]).then(async([details,claim])=>{const text=await details.text();let parsed:any={};try{parsed=text?JSON.parse(text):{};}catch{throw new Error(`Location details returned HTTP ${details.status}.`);}if(!details.ok)throw new Error(parsed.error||'Could not load location details.');const claimText=await claim.text();let claimParsed:ClaimState={authenticated:false,claim:null};try{claimParsed=claimText?JSON.parse(claimText):claimParsed;}catch{}return{parsed,claimParsed};}).then(v=>{if(alive){setData(v.parsed);setClaimState(v.claimParsed);}}).catch(e=>{if(alive)setError(e instanceof Error?e.message:'Could not load location details.');}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[locationId]);
 async function submit(){setSubmitting(true);setMessage(null);try{const r=await fetch(`/api/dispensaries/${encodeURIComponent(locationId)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rating,title,body})});const text=await r.text();let parsed:any={};try{parsed=text?JSON.parse(text):{};}catch{throw new Error(`Review request returned HTTP ${r.status}.`);}if(!r.ok)throw new Error(parsed.error||'Review failed.');for(const file of files.slice(0,6)){const form=new FormData();form.set('file',file);const upload=await fetch(`/api/dispensaries/${encodeURIComponent(locationId)}/review-images`,{method:'POST',body:form});if(!upload.ok)throw new Error('Photo upload failed.');}setMessage(files.length?`Review and ${Math.min(files.length,6)} photo(s) submitted for moderation.`:(parsed.message||'Review submitted.'));setTitle('');setBody('');setFiles([]);setShowReview(false);}catch(e){setMessage(e instanceof Error?e.message:'Review failed.');}finally{setSubmitting(false);}}
 async function submitClaim(){setClaimBusy(true);setClaimMessage(null);try{const r=await fetch(`/api/dispensaries/${encodeURIComponent(locationId)}/claim`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({claimantName,businessEmail,businessPhone,roleTitle,businessWebsite,evidenceText})});const text=await r.text();let parsed:any={};try{parsed=text?JSON.parse(text):{};}catch{throw new Error(`Claim request returned HTTP ${r.status}.`);}if(!r.ok)throw new Error(parsed.error||'Could not submit ownership claim.');setClaimState({authenticated:true,claim:parsed.claim});setClaimMessage(parsed.message||'Ownership claim submitted.');setShowClaim(false);}catch(e){setClaimMessage(e instanceof Error?e.message:'Could not submit ownership claim.');}finally{setClaimBusy(false);}}
 if(loading)return <div className="community-details-loading">Loading shop details…</div>;if(error||!data)return <div className="community-details-loading">{error||'Details unavailable.'}</div>;
 const l=data.location,website=normalizeWebsite(l.website),address=[l.streetAddress,l.city,l.region,l.postalCode,l.country].filter(Boolean).join(', '),claim=claimState.claim,hours=hoursStatus(l.hours,l.region,l.country);
 return <div className="community-details">
  <section className="profile-summary-grid"><div className="profile-summary-main"><div className="community-rating"><span className="community-stars">{stars(data.ratings.average)}</span><strong>{data.ratings.count?data.ratings.average.toFixed(1):'New'}</strong><small>{data.ratings.count?`${data.ratings.count} review${data.ratings.count===1?'':'s'}`:'No reviews yet'}</small></div><div className="profile-badges"><span className={`profile-open-badge ${hours.state}`}>{hours.label}</span>{l.recreational&&<span>Adult-use</span>}{l.medical&&<span>Medical</span>}{claim?.status==='approved'&&<span>✓ Verified owner</span>}</div>{l.overview?<p className="community-overview">{l.overview}</p>:<p className="community-overview muted">Business overview has not been added yet.</p>}</div><aside className="profile-today"><span>TODAY</span><strong>{hours.today}</strong><small>{hours.label}</small></aside></section>
  <section className="profile-info-grid"><article className="profile-info-card"><span>ADDRESS</span>{address?<a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(address)}`} target="_blank" rel="noreferrer">📍 {address}</a>:<p>Address unavailable</p>}</article><article className="profile-info-card"><span>CONTACT</span>{l.phone?<a href={`tel:${l.phone.replace(/[^+\d]/g,'')}`}>☎ {l.phone}</a>:<p>Phone unavailable</p>}{website?<a href={website} target="_blank" rel="noreferrer">↗ Visit website</a>:<p>Website unavailable</p>}</article></section>
  {l.hours&&Object.keys(l.hours).length>0&&<section className="profile-section-card"><div className="profile-section-head"><span>HOURS</span><strong>Hours of operation</strong></div><div className="profile-hours-grid">{Object.entries(l.hours).map(([day,value])=><div key={day}><span>{day}</span><strong>{value}</strong></div>)}</div></section>}
  <section className="profile-section-card"><div className="profile-section-head"><span>SHOP DETAILS</span><strong>Services & information</strong></div>{l.amenities&&l.amenities.length>0?<div className="community-amenities">{l.amenities.map(item=><span key={item}>{item}</span>)}</div>:<p className="profile-empty">Amenities and services have not been added yet.</p>}{l.social&&Object.keys(l.social).length>0&&<div className="profile-socials">{Object.entries(l.social).filter(([,v])=>Boolean(v)).map(([network,url])=><a key={network} href={normalizeWebsite(url)||'#'} target="_blank" rel="noreferrer">{network}</a>)}</div>}</section>
  <section className="community-owner-claim"><div><strong>Own or manage this dispensary?</strong><p>Claim this profile to keep business details current. GeoWeedo verifies ownership before edit access is granted.</p></div>{claim?.status==='approved'?<a className="community-owner-action" href="/owner">✓ Verified · Manage profile</a>:claim?.status==='pending'?<span className="community-owner-status">Verification pending</span>:!claimState.authenticated?<a className="community-owner-action" href="/account">Sign in to claim</a>:<button className="community-owner-action" type="button" onClick={()=>setShowClaim(v=>!v)}>{claim?.status==='rejected'?'Resubmit claim':'Claim this dispensary'}</button>}</section>
  {claim?.status==='rejected'&&claim.adminNote&&<div className="community-claim-note"><strong>Claim needs changes:</strong> {claim.adminNote}</div>}{showClaim&&<div className="community-claim-form"><input value={claimantName} onChange={e=>setClaimantName(e.target.value)} maxLength={100} placeholder="Your full name"/><div className="community-claim-grid"><input value={businessEmail} onChange={e=>setBusinessEmail(e.target.value)} maxLength={180} placeholder="Business email"/><input value={businessPhone} onChange={e=>setBusinessPhone(e.target.value)} maxLength={80} placeholder="Business phone"/></div><input value={roleTitle} onChange={e=>setRoleTitle(e.target.value)} maxLength={120} placeholder="Your role, e.g. Owner or General Manager"/><input value={businessWebsite} onChange={e=>setBusinessWebsite(e.target.value)} maxLength={500} placeholder="Business website (optional)"/><textarea value={evidenceText} onChange={e=>setEvidenceText(e.target.value)} maxLength={5000} placeholder="Tell GeoWeedo how we can verify you."/><button type="button" disabled={claimBusy} onClick={submitClaim}>{claimBusy?'Submitting…':'Submit ownership claim'}</button></div>}{claimMessage&&<div className="community-review-message">{claimMessage}</div>}
  <div className="community-review-head"><strong>Community reviews</strong><button type="button" onClick={()=>setShowReview(v=>!v)}>★ Write a review</button></div>{showReview&&<div className="community-review-form"><div className="community-rating-picker">{[1,2,3,4,5].map(v=><button type="button" key={v} className={v<=rating?'active':''} onClick={()=>setRating(v)}>★</button>)}</div><input value={title} onChange={e=>setTitle(e.target.value)} maxLength={120} placeholder="Review title (optional)"/><textarea value={body} onChange={e=>setBody(e.target.value)} maxLength={3000} placeholder="What should other visitors know?"/><label className="community-photo-input">Add photos (up to 6)<input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={e=>setFiles(Array.from(e.target.files||[]).slice(0,6))}/></label>{files.length>0&&<small>{files.length} photo(s) selected</small>}<button type="button" disabled={submitting} onClick={submit}>{submitting?'Submitting…':'Submit for moderation'}</button></div>}{message&&<div className="community-review-message">{message}</div>}<div className="community-reviews">{data.reviews.length===0?<small>Be the first to review this dispensary.</small>:data.reviews.map(review=><article key={review.id}><div><span className="community-stars">{stars(review.rating)}</span><strong>{review.author}</strong></div>{review.title&&<h4>{review.title}</h4>}{review.body&&<p>{review.body}</p>}{review.images.length>0&&<div className="community-review-images">{review.images.map(src=><img key={src} src={src} alt="User submitted dispensary review" loading="lazy"/>)}</div>}</article>)}</div>
  <section className="profile-record-card"><span>OFFICIAL RECORD</span><div>{l.licenseNumber&&<p><strong>License</strong><span>{l.licenseNumber}</span></p>}{l.dataSource&&<p><strong>Source</strong><span>{l.dataSource}</span></p>}{l.sourceUrl&&<a href={l.sourceUrl} target="_blank" rel="noreferrer">View official source ↗</a>}</div></section>
 </div>;
}
