'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import GuessMap, { LatLng } from '@/components/GuessMap';
import SiteHeader from '@/components/SiteHeader';
import StreetViewStage from '@/components/StreetViewStage';
import { dispensaries, type Dispensary } from '@/data/dispensaries';
import { yerbFromScore } from '@/lib/yerbasRewards';

const MAX_SCORE=5000;
type PublicMapCandidate={id:string;name:string;latitude:number;longitude:number;city?:string;region?:string;country?:string;dataSource?:string;status?:string;imageryStatus?:string;mapCandidate?:boolean};
type PublicMapStats={total:number;mapped:number;missingCoordinates:number;states:number;regions?:number;countries?:number};
type PublicRewardPolicy={enabled:boolean;yerbPerPoint:number;dailyCapYerb:number;perGameCapYerb:number;reviewRequired:boolean};
type RewardSubmission={state:'submitting'|'done'|'error';amountYerb?:number;status?:string;message?:string};
type Props={initialApprovedDispensaries:Dispensary[]};

const DEFAULT_REWARD_POLICY:PublicRewardPolicy={enabled:true,yerbPerPoint:0.0004,dailyCapYerb:25,perGameCapYerb:10,reviewRequired:true};
function distanceKm(a:LatLng,b:LatLng){const r=6371.0088,rad=(v:number)=>(v*Math.PI)/180,dLat=rad(b.lat-a.lat),dLng=rad(b.lng-a.lng),lat1=rad(a.lat),lat2=rad(b.lat),h=Math.sin(dLat/2)**2+Math.cos(lat1)*Math.cos(lat2)*Math.sin(dLng/2)**2;return r*2*Math.atan2(Math.sqrt(h),Math.sqrt(1-h));}
function scoreFromDistance(km:number){return Math.max(0,Math.min(MAX_SCORE,Math.round(MAX_SCORE*Math.exp(-km/500))));}
function shuffle<T>(items:T[]){const copy=items.slice();for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));const tmp=copy[i];copy[i]=copy[j];copy[j]=tmp;}return copy;}
function rewardFromScore(score:number,policy:PublicRewardPolicy){if(!policy.enabled)return 0;return Number(Math.min(yerbFromScore(score,policy.yerbPerPoint),policy.perGameCapYerb).toFixed(8));}

export default function HomeClient({initialApprovedDispensaries}:Props){
 const[started,setStarted]=useState(false),[round,setRound]=useState(0),[scores,setScores]=useState<number[]>([]),[guess,setGuess]=useState<LatLng|null>(null),[revealed,setRevealed]=useState(false),[roundDistance,setRoundDistance]=useState<number|null>(null),[roundScore,setRoundScore]=useState<number|null>(null),[approvedDispensaries,setApprovedDispensaries]=useState<Dispensary[]>(initialApprovedDispensaries),[mapCandidates,setMapCandidates]=useState<PublicMapCandidate[]>([]),[mapStats,setMapStats]=useState<PublicMapStats|null>(null),[gameRounds,setGameRounds]=useState<Dispensary[]>([]),[homeCardOpen,setHomeCardOpen]=useState(true),[rewardPolicy,setRewardPolicy]=useState<PublicRewardPolicy>(DEFAULT_REWARD_POLICY),[gameId,setGameId]=useState<string|null>(null),[gameStartedAt,setGameStartedAt]=useState<string|null>(null),[rewardSubmission,setRewardSubmission]=useState<RewardSubmission|null>(null);

 useEffect(()=>{fetch('/api/dispensaries',{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject()).then(d=>{if(Array.isArray(d.dispensaries))setApprovedDispensaries(d.dispensaries);}).catch(()=>{});fetch('/api/map-candidates',{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject()).then(d=>{setMapCandidates(Array.isArray(d.candidates)?d.candidates:[]);setMapStats(d.stats&&typeof d.stats==='object'?d.stats:null);}).catch(()=>{setMapCandidates([]);setMapStats(null);});fetch('/api/rewards/policy',{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject()).then(d=>setRewardPolicy({...DEFAULT_REWARD_POLICY,...d})).catch(()=>setRewardPolicy(DEFAULT_REWARD_POLICY));},[]);

 const playableLocations=useMemo(()=>approvedDispensaries.filter(item=>item.active&&item.verified&&item.imageryPhotoId),[approvedDispensaries]);
 const rounds=started?gameRounds:playableLocations;
 const homeLocations=useMemo(()=>{const starterFallback=approvedDispensaries.length===0?dispensaries.filter(item=>item.active):[];const merged=[...approvedDispensaries.filter(item=>item.active).map(item=>({id:item.id,name:item.name,lat:item.latitude,lng:item.longitude,city:item.city,region:item.region,country:(item as any).country||'USA',sponsored:item.sponsored,approved:true,imageryReady:Boolean(item.verified&&item.imageryPhotoId),source:'GeoWeedo approved'})),...mapCandidates.map(item=>({id:item.id,name:item.name,lat:item.latitude,lng:item.longitude,city:item.city||'',region:item.region||'',country:item.country||'USA',sponsored:false,approved:item.status==='approved',imageryReady:item.imageryStatus==='coverage',source:item.dataSource||'Official source'})),...starterFallback.map(item=>({id:item.id,name:item.name,lat:item.latitude,lng:item.longitude,city:item.city,region:item.region,country:(item as any).country||'USA',sponsored:item.sponsored,approved:false,imageryReady:false,source:'GeoWeedo starter'}))];const seen=new Set<string>();return merged.filter(item=>{if(!Number.isFinite(item.lat)||!Number.isFinite(item.lng))return false;const key=`${item.name}|${item.lat.toFixed(5)}|${item.lng.toFixed(5)}`.toLowerCase();if(seen.has(key))return false;seen.add(key);return true;});},[approvedDispensaries,mapCandidates]);
 const current=rounds[round],total=scores.reduce((s,v)=>s+v,0),completedTotal=total+(revealed&&roundScore!==null?roundScore:0),estimatedYerb=rewardFromScore(completedTotal,rewardPolicy),onGuess=useCallback((v:LatLng)=>setGuess(v),[]);

 useEffect(()=>{
  if(!started||!gameId||!rewardPolicy.enabled||!gameRounds.length||round<gameRounds.length||scores.length!==gameRounds.length||rewardSubmission)return;
  setRewardSubmission({state:'submitting'});
  fetch('/api/rewards/game',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({gameId,startedAt:gameStartedAt,scores,dispensaryIds:gameRounds.map(item=>item.id)})})
   .then(async r=>{const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Could not record gameplay reward.');return d;})
   .then(d=>setRewardSubmission({state:'done',amountYerb:Number(d.amountYerb||0),status:String(d.status||'earned')}))
   .catch(e=>setRewardSubmission({state:'error',message:e instanceof Error?e.message:'Could not record gameplay reward.'}));
 },[started,gameId,gameStartedAt,gameRounds,round,scores,rewardPolicy.enabled,rewardSubmission]);

 const beginGame=()=>{const randomized=shuffle(playableLocations).slice(0,Math.min(5,playableLocations.length));setGameRounds(randomized);setGameId(`game-${crypto.randomUUID()}`);setGameStartedAt(new Date().toISOString());setRewardSubmission(null);setStarted(true);setRound(0);setScores([]);setGuess(null);setRevealed(false);setRoundDistance(null);setRoundScore(null);};
 const backToMap=()=>{setStarted(false);setRound(0);setScores([]);setGuess(null);setRevealed(false);setRoundDistance(null);setRoundScore(null);setGameRounds([]);setGameId(null);setGameStartedAt(null);setRewardSubmission(null);setHomeCardOpen(false);};
 const revealGuess=()=>{if(!guess||!current)return;const distance=distanceKm(guess,{lat:current.latitude,lng:current.longitude});setRoundDistance(distance);setRoundScore(scoreFromDistance(distance));setRevealed(true);};
 const nextRound=()=>{if(roundScore===null)return;setScores(p=>[...p,roundScore]);setRound(p=>p+1);setGuess(null);setRevealed(false);setRoundDistance(null);setRoundScore(null);};

 if(!started)return <main className="landing-shell map-first-home"><SiteHeader/><section className="home-map-stage"><div className="home-map-canvas"><GuessMap guess={null} revealed={false} onGuess={()=>{}} browseMode locations={homeLocations as any}/></div>{homeCardOpen?<div className="home-play-card"><button type="button" aria-label="Close game intro" onClick={()=>setHomeCardOpen(false)} style={{position:'absolute',right:14,top:14,width:34,height:34,border:0,borderRadius:'50%',background:'rgba(255,255,255,.07)',color:'var(--text)',fontSize:22,lineHeight:1,cursor:'pointer'}}>×</button><div className="eyebrow" style={{paddingRight:36}}>THE DISPENSARY GEOGRAPHY GAME</div><h1>GeoWeedo</h1><p>Explore real dispensary locations, read the clues, and pinpoint where you are.</p><button className="primary home-play-button" onClick={beginGame} disabled={playableLocations.length===0}>{playableLocations.length?`Play GeoWeedo · ${Math.min(5,playableLocations.length)} random round${Math.min(5,playableLocations.length)===1?'':'s'}`:'No quality-approved rounds yet'}</button><div className="home-play-meta"><span>{playableLocations.length} playable</span><span>{homeLocations.length.toLocaleString()} mapped</span>{mapStats&&<span>{mapStats.total.toLocaleString()} candidates</span>}{mapStats&&<span>{mapStats.countries||1} countr{(mapStats.countries||1)===1?'y':'ies'}</span>}{mapStats&&<span>{mapStats.states} U.S. states</span>}<span>{rewardPolicy.enabled?'YERB rewards':'Rewards paused'}</span></div>{playableLocations.length===0&&<p className="map-coverage-note">Browse locations are visible, but gameplay stays disabled until Street View is confirmed for gameplay.</p>}{mapStats&&mapStats.missingCoordinates>0&&<p className="map-coverage-note">{mapStats.missingCoordinates.toLocaleString()} imported locations still need coordinates before they can appear on the public map.</p>}</div>:<button type="button" onClick={()=>setHomeCardOpen(true)} aria-label="Show game intro" style={{position:'absolute',zIndex:5,left:18,bottom:18,border:'1px solid rgba(255,255,255,.14)',borderRadius:12,background:'rgba(11,14,12,.92)',color:'var(--text)',padding:'10px 14px',fontWeight:800,cursor:'pointer'}}>Play GeoWeedo</button>}</section></main>;

 if(!current){
  if(scores.length===0)return <main className="result-shell"><div className="result-card"><div className="eyebrow">NO PLAYABLE ROUNDS</div><h1>0</h1><p>GeoWeedo only starts rounds with confirmed gameplay-ready Street View.</p><button className="primary" onClick={backToMap}>Back to Map</button></div></main>;
  const rewardText=!rewardPolicy.enabled?'Gameplay rewards are currently paused by GeoWeedo Admin.':rewardSubmission?.state==='submitting'?'Recording your YERB reward…':rewardSubmission?.state==='done'?(rewardSubmission.status==='pending_review'?`Reward pending review: ${Number(rewardSubmission.amountYerb||0).toFixed(8)} YERB`:rewardSubmission.status==='daily_cap_reached'?'Daily YERB reward cap reached.':`Reward earned: ${Number(rewardSubmission.amountYerb||0).toFixed(8)} YERB`):rewardSubmission?.state==='error'?`Reward not recorded: ${rewardSubmission.message}`:`Estimated eligible reward: ${rewardFromScore(total,rewardPolicy)} YERB`;
  return <main className="result-shell"><div className="result-card"><div className="eyebrow">GAME COMPLETE</div><h1>{total.toLocaleString()} <small>/ {(rounds.length*MAX_SCORE).toLocaleString()}</small></h1><p className="yerb-score">{rewardText}</p><div className="score-list">{scores.map((score,index)=><div key={index}><span>Round {index+1}</span><strong>{score.toLocaleString()}</strong></div>)}</div><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:10,marginTop:18}}><button className="secondary" onClick={backToMap}>Back to Map</button><a className="secondary" href="/account" style={{display:'flex',alignItems:'center',justifyContent:'center',textDecoration:'none'}}>Go to Account</a><button className="primary" onClick={beginGame}>Play Again</button></div></div></main>;
 }

 const actual={lat:current.latitude,lng:current.longitude};const roundDistanceMiles=roundDistance===null?null:roundDistance*0.621371;
 return <main className="game-shell"><header className="game-header"><a className="brand brand-link" href="/"><span className="brand-pin">✦</span> GEOWEEDO</a><div className="round-meter">ROUND {round+1} / {rounds.length}</div><div className="running-score">{completedTotal.toLocaleString()} pts · <span className="yerb-score">{rewardPolicy.enabled?`~${estimatedYerb} YERB`:'rewards paused'}</span></div></header><section className="panorama-stage live-panorama"><StreetViewStage latitude={current.imageryLatitude??current.latitude} longitude={current.imageryLongitude??current.longitude} heading={current.imageryHeading??current.heading} photoId={current.imageryPhotoId} imageryProvider={current.imageryProvider} imageUrl={current.imageryUrl} projection={current.imageryProjection} fieldOfView={current.imageryFieldOfView}/><aside className="guess-card live-guess-card"><GuessMap guess={guess} actual={actual} revealed={revealed} onGuess={onGuess}/>{!revealed?<div className="guess-actions"><div className="guess-status">{guess?'Pin placed — move it by clicking elsewhere.':'Place a pin where you think the dispensary is.'}</div><button className="primary full" disabled={!guess} onClick={revealGuess}>{guess?'Make Guess':'Place a Pin First'}</button></div>:<div className="reveal"><span className="eyebrow">ACTUAL LOCATION</span><h3>{current.name}</h3><p>{current.city}, {current.region}{current.sponsored?' · Featured':''}</p><div className="reveal-stat"><span>Distance</span><strong>{roundDistanceMiles===null?'—':roundDistanceMiles<0.1?`${Math.round(roundDistanceMiles*5280)} ft`:`${roundDistanceMiles.toFixed(1)} mi`}</strong></div><div className="reveal-stat"><span>Score</span><strong>{roundScore?.toLocaleString()??'—'}</strong></div><button className="primary full" onClick={nextRound}>{round+1===rounds.length?'See Results':'Next Round'}</button></div>}</aside></section></main>;
}
