'use client';

import { useEffect, useState } from 'react';

type Admin={role?:string;permissions?:string[]};
type RecordData={id:string;kind:'dispensary';name:string;street_address?:string;city?:string;region?:string;postal_code?:string;country?:string;latitude?:number|null;longitude?:number|null;website?:string;phone?:string;license_number?:string;data_source?:string;source_url?:string;source_license?:string;recreational?:number;medical?:number;verified?:number;active?:number;priority_weight?:number|null;sponsored_until?:string|null;license_types?:string[];profile?:{overview?:string;phone?:string;website?:string;hours?:Record<string,string>;amenities?:string[];social?:Record<string,string>}};
type Form={name:string;streetAddress:string;city:string;region:string;postalCode:string;country:string;latitude:string;longitude:string;website:string;phone:string;licenseNumber:string;overview:string;recreational:boolean;medical:boolean};

function toForm(r:RecordData):Form{return {name:r.name||'',streetAddress:r.street_address||'',city:r.city||'',region:r.region||'',postalCode:r.postal_code||'',country:r.country||'',latitude:r.latitude==null?'':String(r.latitude),longitude:r.longitude==null?'':String(r.longitude),website:r.profile?.website||r.website||'',phone:r.profile?.phone||r.phone||'',licenseNumber:r.license_number||'',overview:r.profile?.overview||'',recreational:Boolean(r.recreational),medical:Boolean(r.medical)};}

export default function ModeratorDispensaryEditor({locationId}:{locationId:string}){
 const[allowed,setAllowed]=useState(false),[open,setOpen]=useState(false),[record,setRecord]=useState<RecordData|null>(null),[form,setForm]=useState<Form|null>(null),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{fetch('/api/admin/auth/me',{cache:'no-store'}).then(async r=>{if(!r.ok)return null;return r.json();}).then(d=>{const admin=d?.admin as Admin|undefined;setAllowed(Boolean(admin&&(admin.role==='admin'||admin.permissions?.includes('locations.manage'))));}).catch(()=>{});},[]);
 async function begin(){setOpen(true);setStatus('Loading dispensary information…');try{const r=await fetch(`/api/admin/dispensary-records?id=${encodeURIComponent(locationId)}`,{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load dispensary.');setRecord(d.record);setForm(toForm(d.record));setStatus('Edit the dispensary information below.');}catch(e){setStatus(e instanceof Error?e.message:'Could not load dispensary.');}}
 async function save(){if(!record||!form)return;setBusy(true);setStatus('Saving…');try{const details={...record,name:form.name,streetAddress:form.streetAddress,city:form.city,region:form.region,postalCode:form.postalCode,country:form.country,latitude:form.latitude===''?null:Number(form.latitude),longitude:form.longitude===''?null:Number(form.longitude),website:form.website,phone:form.phone,licenseNumber:form.licenseNumber,overview:form.overview,recreational:form.recreational,medical:form.medical,licenseTypes:record.license_types||[],dataSource:record.data_source||'',sourceUrl:record.source_url||'',sourceLicense:record.source_license||'',verified:Boolean(record.verified),active:record.active!==0,priorityWeight:record.priority_weight??null,sponsoredUntil:record.sponsored_until||'',hours:record.profile?.hours||{},amenities:record.profile?.amenities||[],social:record.profile?.social||{}};const r=await fetch('/api/admin/dispensary-records',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:locationId,kind:'dispensary',details})}),d=await r.json();if(!r.ok)throw new Error(d.error||'Save failed.');setStatus('Dispensary information saved.');setRecord({...record,name:form.name,street_address:form.streetAddress,city:form.city,region:form.region,postal_code:form.postalCode,country:form.country,latitude:form.latitude===''?null:Number(form.latitude),longitude:form.longitude===''?null:Number(form.longitude),website:form.website,phone:form.phone,license_number:form.licenseNumber,recreational:form.recreational?1:0,medical:form.medical?1:0,profile:{...(record.profile||{}),overview:form.overview,website:form.website,phone:form.phone}});setTimeout(()=>window.location.reload(),500);}catch(e){setStatus(e instanceof Error?e.message:'Save failed.');}finally{setBusy(false);}}
 if(!allowed)return null;
 return <section style={{margin:'18px 0',padding:14,border:'1px solid var(--border)',borderRadius:12,background:'rgba(255,255,255,.025)'}}><div style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:10,flexWrap:'wrap'}}><div><strong>Moderator tools</strong><div style={{fontSize:12,color:'var(--muted)'}}>Edit this dispensary directly from its public profile.</div></div><button type="button" onClick={()=>open?setOpen(false):void begin()}>{open?'Close editor':'Edit dispensary'}</button></div>{open&&<div style={{marginTop:14}}>{!form?<div>{status}</div>:<div style={{display:'grid',gap:9}}><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Dispensary name"/><input value={form.streetAddress} onChange={e=>setForm({...form,streetAddress:e.target.value})} placeholder="Street address"/><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8}}><input value={form.city} onChange={e=>setForm({...form,city:e.target.value})} placeholder="City"/><input value={form.region} onChange={e=>setForm({...form,region:e.target.value})} placeholder="State / region"/></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8}}><input value={form.postalCode} onChange={e=>setForm({...form,postalCode:e.target.value})} placeholder="Postal code"/><input value={form.country} onChange={e=>setForm({...form,country:e.target.value})} placeholder="Country"/></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8}}><input value={form.latitude} onChange={e=>setForm({...form,latitude:e.target.value})} placeholder="Latitude"/><input value={form.longitude} onChange={e=>setForm({...form,longitude:e.target.value})} placeholder="Longitude"/></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8}}><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="Phone"/><input value={form.website} onChange={e=>setForm({...form,website:e.target.value})} placeholder="Website"/></div><input value={form.licenseNumber} onChange={e=>setForm({...form,licenseNumber:e.target.value})} placeholder="License number"/><textarea rows={4} value={form.overview} onChange={e=>setForm({...form,overview:e.target.value})} placeholder="Overview / business description"/><div style={{display:'flex',gap:18,flexWrap:'wrap'}}><label><input type="checkbox" checked={form.recreational} onChange={e=>setForm({...form,recreational:e.target.checked})}/> Recreational</label><label><input type="checkbox" checked={form.medical} onChange={e=>setForm({...form,medical:e.target.checked})}/> Medical</label></div><div style={{display:'flex',alignItems:'center',gap:10}}><button type="button" onClick={save} disabled={busy}>{busy?'Saving…':'Save dispensary'}</button><span style={{fontSize:12,color:'var(--muted)'}}>{status}</span></div></div>}</div>}</section>;
}
