'use client';

import { useEffect, useMemo, useState } from 'react';

type SavedDispensary={id:string;name:string;streetAddress?:string;city:string;region:string;country:string;latitude:number;longitude:number;website?:string;imageryProvider:string;dataSource?:string;sourceUrl?:string;sourceLicense?:string;recreational:boolean;medical:boolean;active:boolean};
type Candidate={id:string;name:string;streetAddress?:string;city?:string;region?:string;country?:string;latitude?:number;longitude?:number;website?:string;dataSource?:string;sourceUrl?:string;sourceLicense?:string;status?:string;imageryStatus?:string;imageryCount?:number};
type EditForm={name:string;streetAddress:string;city:string;region:string;country:string;website:string;dataSource:string;sourceUrl:string;sourceLicense:string;latitude:string;longitude:string;recreational:boolean;medical:boolean};
type StateItem={kind:'dispensary'|'candidate';id:string;name:string;streetAddress?:string;city:string;region:string;country:string;latitude?:number;longitude?:number;website?:string;dataSource?:string;active?:boolean;imageryProvider?:string;status?:string;imageryStatus?:string;source?:SavedDispensary|Candidate};
function editFrom(item:SavedDispensary):EditForm{return{name:item.name,streetAddress:item.streetAddress||'',city:item.city||'',region:item.region||'',country:item.country||'USA',website:item.website||'',dataSource:item.dataSource||'manual',sourceUrl:item.sourceUrl||'',sourceLicense:item.sourceLicense||'',latitude:String(item.latitude),longitude:String(item.longitude),recreational:Boolean(item.recreational),medical:Boolean(item.medical)};}

export default function StateGroupedDispensaryManager(){
 const[dispensaries,setDispensaries]=useState<SavedDispensary[]>([]),[candidates,setCandidates]=useState<Candidate[]>([]),[search,setSearch]=useState(''),[expanded,setExpanded]=useState<Record<string,boolean>>({}),[status,setStatus]=useState('Loading dispensaries and candidates…'),[busy,setBusy]=useState(false),[editing,setEditing]=useState<SavedDispensary|null>(null),[form,setForm]=useState<EditForm|null>(null);
 async function load(){const [dispensaryResponse,candidateResponse]=await Promise.all([fetch('/api/admin/dispensaries',{cache:'no-store'}),fetch('/api/admin/candidates',{cache:'no-store'})]);if(dispensaryResponse.status===401||candidateResponse.status===401){window.location.href='/admin/login';return;}const [dispensaryData,candidateData]=await Promise.all([dispensaryResponse.json(),candidateResponse.json()]);if(!dispensaryResponse.ok)throw new Error(dispensaryData.error||'Could not load dispensaries.');if(!candidateResponse.ok)throw new Error(candidateData.error||'Could not load imported candidates.');const nextDispensaries=dispensaryData.dispensaries||[],nextCandidates=candidateData.candidates||[];setDispensaries(nextDispensaries);setCandidates(nextCandidates);setStatus(`${nextDispensaries.length} game-pool dispensaries · ${nextCandidates.length} imported candidates.`);}
 useEffect(()=>{load().catch(e=>setStatus(e.message));},[]);
 const allItems=useMemo<StateItem[]>(()=>[
  ...dispensaries.map(item=>({kind:'dispensary' as const,id:item.id,name:item.name,streetAddress:item.streetAddress,city:item.city||'',region:item.region||'Unknown state',country:item.country||'USA',latitude:item.latitude,longitude:item.longitude,website:item.website,dataSource:item.dataSource,active:item.active,imageryProvider:item.imageryProvider,source:item})),
  ...candidates.filter(item=>item.status!=='rejected').map(item=>({kind:'candidate' as const,id:item.id,name:item.name,streetAddress:item.streetAddress,city:item.city||'',region:item.region||'Unknown state',country:item.country||'USA',latitude:item.latitude,longitude:item.longitude,website:item.website,dataSource:item.dataSource,status:item.status||'candidate',imageryStatus:item.imageryStatus,source:item}))
 ],[dispensaries,candidates]);
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return allItems.filter(item=>!q||`${item.name} ${item.city} ${item.region} ${item.streetAddress||''} ${item.dataSource||''}`.toLowerCase().includes(q));},[allItems,search]);
 const groups=useMemo(()=>{const map=new Map<string,StateItem[]>();for(const item of filtered){const state=(item.region||'Unknown state').trim()||'Unknown state';const arr=map.get(state);if(arr)arr.push(item);else map.set(state,[item]);}return Array.from(map.entries()).sort(([a],[b])=>a.localeCompare(b)).map(([state,list])=>({state,list:list.sort((a,b)=>a.city.localeCompare(b.city)||a.name.localeCompare(b.name)),enabled:list.filter(i=>i.kind==='dispensary'&&i.active).length,disabled:list.filter(i=>i.kind==='dispensary'&&!i.active).length,candidateCount:list.filter(i=>i.kind==='candidate').length}));},[filtered]);
 function toggleState(state:string){setExpanded(current=>({...current,[state]:!current[state]}));}
 function beginEdit(item:StateItem){if(item.kind!=='dispensary')return;const source=item.source as SavedDispensary;setEditing(source);setForm(editFrom(source));}
 function reviewCandidate(item:StateItem){if(item.kind!=='candidate')return;sessionStorage.setItem('geoweedo-candidate-draft',JSON.stringify(item.source));window.location.href='/admin/dispensaries';}
 async function toggle(item:StateItem){if(item.kind!=='dispensary')return;const source=item.source as SavedDispensary;setBusy(true);try{const r=await fetch('/api/admin/dispensaries',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:source.id,active:!source.active})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Status update failed.');setStatus(`${source.name} ${source.active?'deactivated':'activated'}.`);await load();}catch(e){setStatus(e instanceof Error?e.message:'Status update failed.');}finally{setBusy(false);}}
 async function saveEdit(){if(!editing||!form)return;setBusy(true);try{const latitude=Number(form.latitude),longitude=Number(form.longitude);if(!form.name.trim()||!form.city.trim()||!form.region.trim()||!form.country.trim())throw new Error('Name, city, state, and country are required.');if(!Number.isFinite(latitude)||!Number.isFinite(longitude)||latitude<-90||latitude>90||longitude<-180||longitude>180)throw new Error('Enter valid latitude and longitude.');const r=await fetch('/api/admin/dispensaries',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:editing.id,details:{...form,latitude,longitude}})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Dispensary update failed.');setStatus(`${d.dispensary.name} details updated.`);setEditing(null);setForm(null);await load();}catch(e){setStatus(e instanceof Error?e.message:'Dispensary update failed.');}finally{setBusy(false);}}
 const enabledTotal=dispensaries.filter(i=>i.active).length,disabledTotal=dispensaries.filter(i=>!i.active).length,candidateTotal=candidates.filter(i=>i.status!=='rejected').length;
 return <section className="admin-panel state-grouped-dispensaries">
  <style>{`
   .state-grouped-dispensaries{margin-bottom:24px!important;padding:22px!important;background:#111714!important;border:1px solid #2b3830!important;color:#f2f7f3!important}
   .state-grouped-head{display:flex;justify-content:space-between;gap:18px;align-items:flex-end;flex-wrap:wrap;margin-bottom:16px}
   .state-grouped-head h2{font-size:26px;line-height:1.1;margin:4px 0 8px;color:#fff}
   .state-grouped-head .eyebrow{font-size:12px;letter-spacing:.12em;color:#76e27f;font-weight:800}
   .state-grouped-summary{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}
   .state-stat{display:inline-flex;align-items:center;min-height:30px;padding:5px 10px;border-radius:999px;background:#18221c;border:1px solid #314137;font-size:12px;color:#d9e7dd;font-weight:700}
   .state-grouped-search{min-width:320px;max-width:460px;width:min(460px,100%);background:#0b100d!important;color:#fff!important;border:1px solid #3c5142!important;padding:11px 13px!important}
   .state-grouped-status{margin:0 0 16px;padding:10px 12px;border-radius:8px;background:#0b100d;color:#aec2b4;border:1px solid #253229;font-size:12px}
   .state-groups{display:grid;grid-template-columns:repeat(auto-fit,minmax(360px,1fr));gap:12px}
   .state-card{border:1px solid #314137;border-radius:12px;background:#0c120f;overflow:hidden;min-width:0}
   .state-card-head{width:100%;display:flex;justify-content:space-between;align-items:center;gap:16px;padding:16px 18px!important;text-align:left!important;background:#151e18!important;color:#fff!important;border:0!important;border-radius:0!important}
   .state-card-head:hover{background:#1b2820!important}
   .state-name{font-size:18px;font-weight:800;line-height:1.2}
   .state-counts{display:flex;gap:6px;flex-wrap:wrap;margin-top:7px}
   .state-counts span{font-size:11px;padding:3px 7px;border-radius:999px;background:#0d140f;border:1px solid #304038;color:#bdcec2}
   .state-counts .enabled{color:#7cf088;border-color:#315e39}.state-counts .candidate{color:#f2d67a;border-color:#66582c}
   .state-chevron{font-size:22px;color:#76e27f;line-height:1}
   .state-list{border-top:1px solid #28352d}
   .state-item{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:16px;align-items:center;padding:13px 16px;border-bottom:1px solid #202b25;background:#0f1512}
   .state-item:last-child{border-bottom:0}.state-item strong{display:block;color:#fff;font-size:14px;margin-bottom:4px}.state-item-meta{display:block;color:#b3c3b8;font-size:12px;line-height:1.45}.state-item-detail{display:block;color:#829289;font-size:11px;margin-top:3px;line-height:1.4;word-break:break-word}
   .state-item-actions{display:flex;gap:7px;flex-wrap:wrap;justify-content:flex-end}.state-item-actions button{white-space:nowrap}
   .state-badge{display:inline-flex;margin-left:7px;padding:2px 6px;border-radius:999px;font-size:9px;vertical-align:1px;border:1px solid #3b4c41;color:#b9c8bd}.state-badge.live{color:#7cf088;border-color:#315e39}.state-badge.candidate{color:#f2d67a;border-color:#66582c}.state-badge.disabled{color:#c7aaa7;border-color:#60413e}
   @media(max-width:760px){.state-groups{grid-template-columns:1fr}.state-grouped-search{min-width:0}.state-item{grid-template-columns:1fr}.state-item-actions{justify-content:flex-start}}
  `}</style>
  <div className="state-grouped-head"><div><span className="eyebrow">DISPENSARIES BY STATE</span><h2>State location manager</h2><div className="state-grouped-summary"><span className="state-stat">{groups.length} states</span><span className="state-stat">{enabledTotal} enabled</span><span className="state-stat">{disabledTotal} disabled</span><span className="state-stat">{candidateTotal} candidates</span><span className="state-stat">{filtered.length} shown</span></div></div><input className="state-grouped-search" placeholder="Search name, city, state, address, or source" value={search} onChange={e=>setSearch(e.target.value)}/></div>
  <div className="state-grouped-status">{status}</div>
  {editing&&form&&<div id="state-dispensary-edit" style={{marginBottom:18,padding:16,border:'1px solid #52745d',borderRadius:12,background:'#0b100d'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12}}><div><span className="eyebrow">EDIT DISPENSARY</span><strong style={{display:'block',marginTop:4,fontSize:17}}>{editing.name}</strong></div><button type="button" onClick={()=>{setEditing(null);setForm(null);}}>Cancel</button></div><div className="admin-form" style={{marginTop:14}}><input placeholder="Dispensary name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input placeholder="Street address" value={form.streetAddress} onChange={e=>setForm({...form,streetAddress:e.target.value})}/><div className="field-row"><input placeholder="City" value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/><input placeholder="State / region" value={form.region} onChange={e=>setForm({...form,region:e.target.value})}/></div><div className="field-row"><input placeholder="Country" value={form.country} onChange={e=>setForm({...form,country:e.target.value})}/><input placeholder="Website" value={form.website} onChange={e=>setForm({...form,website:e.target.value})}/></div><div className="field-row"><input placeholder="Latitude" value={form.latitude} onChange={e=>setForm({...form,latitude:e.target.value})}/><input placeholder="Longitude" value={form.longitude} onChange={e=>setForm({...form,longitude:e.target.value})}/></div><div className="field-row"><input placeholder="Data source" value={form.dataSource} onChange={e=>setForm({...form,dataSource:e.target.value})}/><input placeholder="Source URL" value={form.sourceUrl} onChange={e=>setForm({...form,sourceUrl:e.target.value})}/></div><input placeholder="Source license / permission" value={form.sourceLicense} onChange={e=>setForm({...form,sourceLicense:e.target.value})}/><div className="check-row"><label><input type="checkbox" checked={form.recreational} onChange={e=>setForm({...form,recreational:e.target.checked})}/> Recreational</label><label><input type="checkbox" checked={form.medical} onChange={e=>setForm({...form,medical:e.target.checked})}/> Medical</label></div><button className="primary" type="button" disabled={busy} onClick={saveEdit}>{busy?'Saving…':'Save details'}</button></div></div>}
  <div className="state-groups">{groups.length===0?<p>No dispensaries or candidates match this search.</p>:groups.map(group=>{const open=Boolean(search.trim())||Boolean(expanded[group.state]);return <div className="state-card" key={group.state}><button className="state-card-head" type="button" onClick={()=>toggleState(group.state)} aria-expanded={open}><span><span className="state-name">{group.state}</span><span className="state-counts"><span>{group.list.length} total</span>{group.enabled>0&&<span className="enabled">{group.enabled} enabled</span>}{group.disabled>0&&<span>{group.disabled} disabled</span>}{group.candidateCount>0&&<span className="candidate">{group.candidateCount} candidates</span>}</span></span><b className="state-chevron">{open?'−':'+'}</b></button>{open&&<div className="state-list">{group.list.map(item=><div className="state-item" key={`${item.kind}-${item.id}`}><div><strong>{item.name}{item.kind==='candidate'?<span className="state-badge candidate">CANDIDATE</span>:item.active?<span className="state-badge live">ENABLED</span>:<span className="state-badge disabled">DISABLED</span>}</strong><span className="state-item-meta">{item.city||'City pending'}{item.imageryProvider?` · ${item.imageryProvider}`:''}{item.imageryStatus?` · imagery ${item.imageryStatus}`:''}{item.dataSource?` · ${item.dataSource}`:''}</span><span className="state-item-detail">{item.streetAddress||'Address pending'}{Number.isFinite(item.latitude)&&Number.isFinite(item.longitude)?` · ${Number(item.latitude).toFixed(5)}, ${Number(item.longitude).toFixed(5)}`:' · coordinates pending'}</span></div><div className="state-item-actions">{item.kind==='candidate'?<button type="button" onClick={()=>reviewCandidate(item)}>Review imagery</button>:<><button type="button" onClick={()=>beginEdit(item)}>Edit details</button><button type="button" disabled={busy} onClick={()=>toggle(item)}>{item.active?'Deactivate':'Activate'}</button></>}</div></div>)}</div>}</div>;})}</div>
 </section>;
}
