export type HoursMap=Record<string,string>;

const REGION_TZ:Record<string,string>={
 'Alaska':'America/Anchorage','Arizona':'America/Phoenix','California':'America/Los_Angeles','Colorado':'America/Denver','Connecticut':'America/New_York','Delaware':'America/New_York','Illinois':'America/Chicago','Maine':'America/New_York','Maryland':'America/New_York','Massachusetts':'America/New_York','Michigan':'America/Detroit','Minnesota':'America/Chicago','Missouri':'America/Chicago','Montana':'America/Denver','Nevada':'America/Los_Angeles','New Jersey':'America/New_York','New York':'America/New_York','Oregon':'America/Los_Angeles','Rhode Island':'America/New_York','Virginia':'America/New_York','Washington':'America/Los_Angeles','British Columbia':'America/Vancouver','Alberta':'America/Edmonton','Saskatchewan':'America/Regina','Manitoba':'America/Winnipeg','Ontario':'America/Toronto','Quebec':'America/Toronto','New Brunswick':'America/Moncton','Nova Scotia':'America/Halifax','Prince Edward Island':'America/Halifax','Newfoundland and Labrador':'America/St_Johns','Yukon':'America/Whitehorse','Northwest Territories':'America/Yellowknife','Nunavut':'America/Iqaluit'};
const DAYS=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
function minutes(value:string){const m=value.trim().match(/^(\d{1,2})(?::(\d{2}))?\s*(am|pm)?$/i);if(!m)return null;let h=Number(m[1]),min=Number(m[2]||0);const ap=m[3]?.toLowerCase();if(ap){if(h===12)h=0;if(ap==='pm')h+=12;}if(h>23||min>59)return null;return h*60+min;}
export function timezoneFor(region?:string,country?:string){if(country==='Netherlands')return 'Europe/Amsterdam';return region?REGION_TZ[region]||null:null;}
export function hoursStatus(hours:HoursMap|undefined,region?:string,country?:string,now=new Date()){
 const tz=timezoneFor(region,country);if(!hours||!Object.keys(hours).length)return{label:'Hours unavailable',state:'unknown' as const,today:'Hours unavailable'};
 const parts=new Intl.DateTimeFormat('en-US',{timeZone:tz||undefined,weekday:'long',hour:'numeric',minute:'2-digit',hour12:false}).formatToParts(now);const day=parts.find(p=>p.type==='weekday')?.value||DAYS[now.getDay()];const hour=Number(parts.find(p=>p.type==='hour')?.value||now.getHours());const minute=Number(parts.find(p=>p.type==='minute')?.value||now.getMinutes());const today=hours[day]||hours[day.slice(0,3)]||'';if(!today)return{label:'Hours unavailable',state:'unknown' as const,today:'Hours unavailable'};if(/closed/i.test(today))return{label:'Closed',state:'closed' as const,today};if(/24\s*hours|open 24/i.test(today))return{label:'Open',state:'open' as const,today};const range=today.split(/\s*(?:-|–|—|to)\s*/i);if(range.length<2)return{label:'Hours unavailable',state:'unknown' as const,today};const start=minutes(range[0]),end=minutes(range[1]);if(start==null||end==null)return{label:'Hours unavailable',state:'unknown' as const,today};const current=hour*60+minute;const open=end>start?current>=start&&current<end:current>=start||current<end;return{label:open?'Open':'Closed',state:open?'open' as const:'closed' as const,today};
}
