export type Hours=Record<string,string>;

const US_TZ:Record<string,string>={'California':'America/Los_Angeles','Nevada':'America/Los_Angeles','Washington':'America/Los_Angeles','Oregon':'America/Los_Angeles','Arizona':'America/Phoenix','Colorado':'America/Denver','Montana':'America/Denver','Utah':'America/Denver','New Mexico':'America/Denver','Wyoming':'America/Denver','Idaho':'America/Boise','Texas':'America/Chicago','Oklahoma':'America/Chicago','Kansas':'America/Chicago','Nebraska':'America/Chicago','South Dakota':'America/Chicago','North Dakota':'America/Chicago','Minnesota':'America/Chicago','Iowa':'America/Chicago','Missouri':'America/Chicago','Arkansas':'America/Chicago','Louisiana':'America/Chicago','Wisconsin':'America/Chicago','Illinois':'America/Chicago','Mississippi':'America/Chicago','Alabama':'America/Chicago','Tennessee':'America/Chicago','Michigan':'America/Detroit','Indiana':'America/Indiana/Indianapolis','Kentucky':'America/New_York','Ohio':'America/New_York','Georgia':'America/New_York','Florida':'America/New_York','South Carolina':'America/New_York','North Carolina':'America/New_York','Virginia':'America/New_York','West Virginia':'America/New_York','Pennsylvania':'America/New_York','New York':'America/New_York','New Jersey':'America/New_York','Delaware':'America/New_York','Maryland':'America/New_York','Connecticut':'America/New_York','Rhode Island':'America/New_York','Massachusetts':'America/New_York','Vermont':'America/New_York','New Hampshire':'America/New_York','Maine':'America/New_York','District of Columbia':'America/New_York','Alaska':'America/Anchorage','Hawaii':'Pacific/Honolulu'};
const CA_TZ:Record<string,string>={'British Columbia':'America/Vancouver','Alberta':'America/Edmonton','Saskatchewan':'America/Regina','Manitoba':'America/Winnipeg','Ontario':'America/Toronto','Quebec':'America/Toronto','New Brunswick':'America/Moncton','Nova Scotia':'America/Halifax','Prince Edward Island':'America/Halifax','Newfoundland and Labrador':'America/St_Johns','Yukon':'America/Whitehorse','Northwest Territories':'America/Yellowknife','Nunavut':'America/Iqaluit'};

export function timezoneForLocation(country:string,region:string){if(/netherlands/i.test(country))return'Europe/Amsterdam';if(/canada/i.test(country))return CA_TZ[region]||null;return US_TZ[region]||null;}
export function currentLocalInfo(timeZone:string,at=new Date()){const parts=new Intl.DateTimeFormat('en-US',{timeZone,weekday:'long',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(at);const weekday=parts.find(p=>p.type==='weekday')?.value||'',hour=Number(parts.find(p=>p.type==='hour')?.value||0),minute=Number(parts.find(p=>p.type==='minute')?.value||0);return{weekday,minutes:hour*60+minute};}
export function todaysHours(hours:Hours|undefined,weekday:string){if(!hours)return'';const target=weekday.toLowerCase();const key=Object.keys(hours).find(k=>k.toLowerCase()===target||k.toLowerCase().startsWith(target.slice(0,3)));return key?String(hours[key]||'').trim():'';}
function parseClock(value:string){const clean=value.trim().toLowerCase().replace(/\./g,''),m=clean.match(/^(\d{1,2})(?::(\d{2}))?\s*(am|pm)?$/);if(!m)return null;let hour=Number(m[1]),minute=Number(m[2]||0);if(hour>24||minute>59)return null;if(m[3]){if(hour>12)return null;if(m[3]==='am'&&hour===12)hour=0;if(m[3]==='pm'&&hour!==12)hour+=12;}if(hour===24&&minute===0)return 1440;if(hour>23)return null;return hour*60+minute;}
export function openState(schedule:string,currentMinutes:number){const normalized=schedule.trim();if(!normalized)return'unknown' as const;if(/closed/i.test(normalized))return'closed' as const;if(/24\s*hours|open\s*24|24\/7/i.test(normalized))return'open' as const;const range=normalized.split(/\s*(?:-|–|—|\bto\b)\s*/i);if(range.length<2)return'unknown' as const;const start=parseClock(range[0]),end=parseClock(range[1]);if(start==null||end==null)return'unknown' as const;if(start===end)return'open' as const;if(end>start)return currentMinutes>=start&&currentMinutes<end?'open':'closed';return currentMinutes>=start||currentMinutes<end?'open':'closed';}
export function locationOpenState(input:{country?:string;region?:string;hours?:Hours},at=new Date()){const zone=timezoneForLocation(String(input.country||''),String(input.region||''));if(!zone)return{state:'unknown' as const,schedule:'',timeZone:null};const local=currentLocalInfo(zone,at),schedule=todaysHours(input.hours,local.weekday);return{state:openState(schedule,local.minutes),schedule,timeZone:zone};}
