import 'server-only';

import crypto from 'crypto';
import type { NextRequest } from 'next/server';
import { getDatabase } from '@/lib/sqlite';
import type { RequestGeo } from '@/lib/requestGeo';

export const USER_COOKIE='geoweedo_user_session';
const SESSION_DAYS=30;
function hashToken(token:string){return crypto.createHash('sha256').update(token).digest('hex');}
function normalizeEmail(email:string){return email.trim().toLowerCase();}
export function hashUserPassword(password:string){const salt=crypto.randomBytes(16).toString('hex');const hash=crypto.scryptSync(password,salt,64).toString('hex');return `scrypt$${salt}$${hash}`;}
function verifyPassword(password:string,encoded:string){const [scheme,salt,expected]=String(encoded||'').split('$');if(scheme!=='scrypt'||!salt||!expected)return false;const actual=crypto.scryptSync(password,salt,64);const target=Buffer.from(expected,'hex');return actual.length===target.length&&crypto.timingSafeEqual(actual,target);}
function ensureLoginLocations(db:any){db.exec(`CREATE TABLE IF NOT EXISTS user_login_locations (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,session_id TEXT,ip_address TEXT,city TEXT,region TEXT,country TEXT,latitude REAL,longitude REAL,geo_source TEXT,user_agent TEXT,created_at TEXT NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(session_id) REFERENCES user_sessions(id) ON DELETE SET NULL);CREATE INDEX IF NOT EXISTS user_login_locations_user_idx ON user_login_locations(user_id,created_at DESC);`);}
function ensureWallet(db:any,userId:string,now:string){let wallet=db.prepare('SELECT id FROM wallets WHERE user_id=?').get(userId) as any;if(!wallet){const id=`wallet-${crypto.randomUUID()}`;db.prepare(`INSERT INTO wallets (id,user_id,currency,status,created_at,updated_at) VALUES (?,?,'YERB','active',?,?)`).run(id,userId,now,now);wallet={id};}return wallet.id as string;}
function createSession(db:any,user:any,userAgent?:string|null,geo?:RequestGeo|null){ensureLoginLocations(db);const now=new Date(),iso=now.toISOString(),walletId=ensureWallet(db,user.id,iso),rawToken=crypto.randomBytes(32).toString('base64url'),expires=new Date(now.getTime()+SESSION_DAYS*86400000),sessionId=`us-${crypto.randomUUID()}`;db.prepare(`INSERT INTO user_sessions (id,user_id,token_hash,user_agent,expires_at,last_seen_at,created_at) VALUES (?,?,?,?,?,?,?)`).run(sessionId,user.id,hashToken(rawToken),userAgent||null,expires.toISOString(),iso,iso);db.prepare(`INSERT INTO user_login_locations (id,user_id,session_id,ip_address,city,region,country,latitude,longitude,geo_source,user_agent,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`).run(`ull-${crypto.randomUUID()}`,user.id,sessionId,geo?.ip||null,geo?.city||null,geo?.region||null,geo?.country||null,geo?.latitude??null,geo?.longitude??null,geo?.source||'unavailable',userAgent||null,iso);db.prepare(`UPDATE users SET last_login_at=?,updated_at=? WHERE id=?`).run(iso,iso,user.id);return{token:rawToken,expires,user:{id:user.id,handle:user.display_name||user.username||'Player',email:user.email||null,yerbasAddress:user.yerbas_address||null,walletVerifiedAt:user.wallet_verified_at||null,rewardEligible:Boolean(user.reward_eligible),walletId}};}
export function registerEmailUser(displayName:string,email:string,password:string,userAgent?:string|null,geo?:RequestGeo|null){const normalized=normalizeEmail(email);if(!/^\S+@\S+\.\S+$/.test(normalized))throw new Error('Enter a valid email address.');if(password.length<8)throw new Error('Password must be at least 8 characters.');const db=getDatabase();if(db.prepare('SELECT id FROM users WHERE email=? COLLATE NOCASE').get(normalized))throw new Error('An account with that email already exists.');const now=new Date().toISOString(),id=`user-${crypto.randomUUID()}`;db.prepare(`INSERT INTO users (id,display_name,email,password_hash,reward_eligible,account_status,created_at,updated_at) VALUES (?,?,?,?,1,'active',?,?)`).run(id,displayName.trim()||null,normalized,hashUserPassword(password),now,now);return createSession(db,db.prepare('SELECT * FROM users WHERE id=?').get(id),userAgent,geo);}
export function loginEmailUser(email:string,password:string,userAgent?:string|null,geo?:RequestGeo|null){const db=getDatabase(),user=db.prepare('SELECT * FROM users WHERE email=? COLLATE NOCASE').get(normalizeEmail(email)) as any;if(!user||!user.password_hash||!verifyPassword(password,user.password_hash))return null;if(user.account_status!=='active')throw new Error('This account is not active.');return createSession(db,user,userAgent,geo);}
export function attachEmailLogin(userId:string,email:string,password:string){const normalized=normalizeEmail(email);if(!/^\S+@\S+\.\S+$/.test(normalized))throw new Error('Enter a valid email address.');if(password.length<8)throw new Error('Password must be at least 8 characters.');const db=getDatabase(),user=db.prepare('SELECT id,email,password_hash FROM users WHERE id=?').get(userId) as any;if(!user)throw new Error('Account not found.');const owner=db.prepare('SELECT id FROM users WHERE email=? COLLATE NOCASE AND id<>?').get(normalized,userId) as any;if(owner)throw new Error('That email address is already used by another account.');const now=new Date().toISOString();db.prepare('UPDATE users SET email=?,password_hash=?,updated_at=? WHERE id=?').run(normalized,hashUserPassword(password),now,userId);return{email:normalized,replaced:Boolean(user.email||user.password_hash)};}
export function issueWalletLoginChallenge(address:string){const db=getDatabase(),now=new Date(),expires=new Date(now.getTime()+600000),nonce=crypto.randomBytes(24).toString('hex'),message=`GeoWeedo wallet login\nAddress: ${address}\nNonce: ${nonce}\nExpires: ${expires.toISOString()}`;db.prepare('DELETE FROM login_challenges WHERE expires_at <= ? OR used_at IS NOT NULL').run(now.toISOString());db.prepare(`INSERT INTO login_challenges (id,yerbas_address,challenge,purpose,expires_at,created_at) VALUES (?,?,?,'wallet_login',?,?)`).run(`lc-${crypto.randomUUID()}`,address,message,expires.toISOString(),now.toISOString());return{message,expiresAt:expires.toISOString()};}
export function consumeWalletLoginChallenge(address:string){const db=getDatabase(),now=new Date().toISOString(),row=db.prepare(`SELECT id,challenge FROM login_challenges WHERE yerbas_address=? AND purpose='wallet_login' AND used_at IS NULL AND expires_at>? ORDER BY created_at DESC LIMIT 1`).get(address,now) as any;if(!row)return null;db.prepare('UPDATE login_challenges SET used_at=? WHERE id=?').run(now,row.id);return row.challenge as string;}
export function createOrLoginUser(handle:string,address:string,userAgent?:string|null,geo?:RequestGeo|null){const db=getDatabase(),now=new Date().toISOString(),normalizedHandle=handle.trim();let user=db.prepare('SELECT * FROM users WHERE yerbas_address=?').get(address) as any;if(!user){const id=`user-${crypto.randomUUID()}`;db.prepare(`INSERT INTO users (id,display_name,yerbas_address,wallet_verified_at,reward_eligible,account_status,created_at,updated_at) VALUES (?,?,?,?,1,'active',?,?)`).run(id,normalizedHandle||null,address,now,now,now);user=db.prepare('SELECT * FROM users WHERE id=?').get(id);}else{db.prepare(`UPDATE users SET display_name=COALESCE(NULLIF(?,''),display_name),wallet_verified_at=?,reward_eligible=1,updated_at=? WHERE id=?`).run(normalizedHandle,now,now,user.id);user=db.prepare('SELECT * FROM users WHERE id=?').get(user.id);}return createSession(db,user,userAgent,geo);}
export function getUserFromRequest(request:NextRequest){const token=request.cookies.get(USER_COOKIE)?.value;if(!token)return null;const db=getDatabase(),now=new Date().toISOString(),row=db.prepare(`SELECT u.id,u.username,u.display_name,u.email,u.password_hash,u.yerbas_address,u.wallet_verified_at,u.reward_eligible,s.id AS session_id,w.id AS wallet_id FROM user_sessions s JOIN users u ON u.id=s.user_id LEFT JOIN wallets w ON w.user_id=u.id WHERE s.token_hash=? AND s.revoked_at IS NULL AND s.expires_at>? AND u.account_status='active'`).get(hashToken(token),now) as any;if(!row)return null;db.prepare('UPDATE user_sessions SET last_seen_at=? WHERE id=?').run(now,row.session_id);return{id:row.id,handle:row.display_name||row.username||'Player',email:row.email||null,emailLoginEnabled:Boolean(row.email&&row.password_hash),yerbasAddress:row.yerbas_address||null,walletVerifiedAt:row.wallet_verified_at,rewardEligible:Boolean(row.reward_eligible),walletId:row.wallet_id as string|null,sessionId:row.session_id};}
