'use client';
import { useEffect,useMemo,useState } from 'react';
import styles from '../admin.module.css';

type UserRow={id:string;username?:string;displayName?:string;email?:string;yerbasAddress?:string;walletVerifiedAt?:string;rewardEligible:boolean;accountStatus:string;lastLoginAt?:string;createdAt:string;walletId?:string;balanceYerb:number;depositCount:number;withdrawalCount:number;gameCount:number};
export default function AdminUsersPage(){
 const[users,setUsers]=useState<UserRow[]>([]),[selected,setSelected]=useState<any>(null),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{fetch('/api/admin/users',{cache:'no-store'}).then(async r=>{if(r.status===401){location.href='/admin/login';return null;}const d=await r.json();if(!r.ok)throw new Error(d.error||'Failed to load users');return d;}).then(d=>{if(d)setUsers(d.users||[]);}).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);
 const visible=useMemo(()=>{const q=query.trim().toLowerCase();return users.filter(u=>!q||`${u.displayName||''} ${u.username||''} ${u.email||''} ${u.yerbasAddress||''}`.toLowerCase().includes(q));},[users,query]);
 async function openUser(id:string){setSelected({loading:true});const r=await fetch(`/api/admin/users?id=${encodeURIComponent(id)}`,{cache:'no-store'});const d=await r.json();setSelected(r.ok?d:{error:d.error||'Failed to load user'});}
 const fmt=(v:any)=>v?new Date(v).toLocaleString():'—';
 return <main className={styles.shell}><header className={styles.header}><div><span className={styles.eyebrow}>GEOWEEDO ADMIN</span><h1>User information</h1><p>One record for account status, verified YERB address, GeoWeedo balance, deposits, withdrawals, rewards, and game history.</p></div><div className={styles.headerActions}><a className={styles.ghost} href="/admin">Control center</a><a className={styles.ghost} href="/admin/wallet">Yerbas wallet</a></div></header>
 <section className={styles.section}><div className={styles.sectionHead}><div><span className={styles.eyebrow}>PLAYERS</span><h2>{visible.length.toLocaleString()} accounts</h2></div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search user, email, or YERB address" style={{minWidth:320,padding:'12px 14px',borderRadius:10,border:'1px solid rgba(255,255,255,.1)',background:'#131815',color:'#fff'}}/></div>{loading?<div className={styles.loading}>Loading users…</div>:error?<p>{error}</p>:<div style={{display:'grid',gridTemplateColumns:'minmax(320px,420px) 1fr',gap:16,alignItems:'start'}}><div style={{display:'grid',gap:8,maxHeight:'70vh',overflow:'auto'}}>{visible.map(u=><button key={u.id} onClick={()=>openUser(u.id)} style={{textAlign:'left',padding:14,borderRadius:12,border:'1px solid rgba(255,255,255,.08)',background:'#131815',color:'#fff',cursor:'pointer'}}><strong>{u.displayName||u.username||'Player'}</strong><div style={{fontSize:12,color:'#9aa69d',marginTop:5}}>{u.yerbasAddress||'No verified YERB address'}</div><div style={{display:'flex',gap:10,marginTop:8,fontSize:11,color:'#9aa69d'}}><span>{u.balanceYerb.toLocaleString()} YERB</span><span>{u.gameCount} games</span><span>{u.accountStatus}</span></div></button>)}</div><div>{!selected?<article className={styles.card}><h3>Select a user</h3><p>Choose an account to open its consolidated record.</p></article>:selected.loading?<div className={styles.loading}>Loading user record…</div>:selected.error?<p>{selected.error}</p>:<div style={{display:'grid',gap:14}}><article className={styles.card} style={{minHeight:0}}><span className={styles.liveBadge}>{selected.user.accountStatus}</span><h3>{selected.user.displayName||selected.user.username||'Player'}</h3><p>{selected.user.email||'No email'}<br/>{selected.user.yerbasAddress||'No YERB address'}<br/>Wallet verified: {fmt(selected.user.walletVerifiedAt)}<br/>Last login: {fmt(selected.user.lastLoginAt)}</p><div style={{fontSize:28,fontWeight:800}}>{Number(selected.user.balanceYerb||0).toLocaleString()} YERB</div></article><div className={styles.grid}>{[['Deposits',selected.deposits],['Withdrawals',selected.withdrawals],['Rewards',selected.rewards],['Games',selected.games]].map(([title,rows]:any)=><article className={styles.card} key={title} style={{minHeight:0}}><h3>{title}</h3><p>{rows.length} recent records</p><div style={{display:'grid',gap:7,maxHeight:260,overflow:'auto'}}>{rows.length?rows.map((r:any)=><div key={r.id} style={{padding:'8px 0',borderTop:'1px solid rgba(255,255,255,.06)',fontSize:12}}><strong>{r.status||r.reward_status||r.mode||r.entry_type}</strong><div style={{color:'#9aa69d'}}>{r.amountYerb!==undefined?`${r.amountYerb} YERB`:r.total_score!==undefined?`${r.total_score} points`:''} {fmt(r.detected_at||r.requested_at||r.created_at||r.started_at)}</div></div>):<span style={{color:'#9aa69d'}}>No records</span>}</div></article>)}</div></div>}</div></div>}</section></main>;
}
