'use client';

import { useEffect, useState } from 'react';

type Scout={id:string;username?:string|null;displayName?:string|null;email?:string|null;scoutEnabled:boolean;scoutStatus:string;scoutSince?:string|null;lastLoginAt?:string|null;contributions:number;accepted:number;pending:number;rejected:number;lastContributionAt?:string|null};
type Payload={summary:{scouts:number;active7d:number;contributions:number;pending:number;accepted:number;rejected:number};scouts:Scout[]};

export default function ScoutsAdminPage(){
  const[data,setData]=useState<Payload|null>(null),[status,setStatus]=useState('Loading Scouts…'),[busy,setBusy]=useState('');
  async function load(){const r=await fetch('/api/admin/scouts',{cache:'no-store'});if(r.status===401){window.location.href='/admin/login';return;}const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load Scouts.');setData(d);setStatus('Scout activity ready.');}
  useEffect(()=>{load().catch(e=>setStatus(e.message));},[]);
  async function toggle(row:Scout){setBusy(row.id);try{const r=await fetch('/api/admin/scouts',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId:row.id,enabled:!row.scoutEnabled})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not update Scout.');setData(d);setStatus(row.scoutEnabled?'Scout privileges suspended.':'Scout privileges enabled.');}catch(e){setStatus(e instanceof Error?e.message:'Could not update Scout.');}finally{setBusy('');}}
  return <main className="admin-shell"><style>{`
    .scout-grid{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:10px;margin:16px 0}.metric{padding:14px;border:1px solid var(--line);border-radius:12px;background:var(--panel)}.metric strong{display:block;font-size:24px}.metric span,.muted{color:var(--muted);font-size:12px}.scout-table{width:100%;border-collapse:collapse}.scout-table th,.scout-table td{padding:11px 9px;border-bottom:1px solid var(--line);text-align:left;font-size:12px}.scout-table th{color:var(--muted);font-size:10px;text-transform:uppercase;letter-spacing:.06em}.state{font-weight:800}.state.active{color:#67d66e}.state.suspended{color:#f5c451}@media(max-width:900px){.scout-grid{grid-template-columns:repeat(2,1fr)}.table-wrap{overflow:auto}}
  `}</style><header className="admin-header"><div><a href="/admin" className="eyebrow" style={{textDecoration:'none',color:'inherit'}}>GEOWEEDO ADMIN</a><h1>Scouts</h1><p className="muted">Community contributors, their activity, and evidence quality. Scouts are users — never staff.</p></div><div className="admin-links"><a href="/admin">Control center</a><a href="/admin/users">Users</a><a href="/admin/staff">Staff</a></div></header><div className="admin-status">{status}</div>
  {data?<><section className="scout-grid"><div className="metric"><strong>{data.summary.scouts}</strong><span>Enabled Scouts</span></div><div className="metric"><strong>{data.summary.active7d}</strong><span>Active · 7d</span></div><div className="metric"><strong>{data.summary.contributions}</strong><span>Contributions</span></div><div className="metric"><strong>{data.summary.accepted}</strong><span>Accepted</span></div><div className="metric"><strong>{data.summary.pending}</strong><span>Pending</span></div><div className="metric"><strong>{data.summary.rejected}</strong><span>Rejected</span></div></section><section className="admin-panel"><h2>Scout community</h2><p className="muted">Community evidence never grants Verified COA status. Independent official lab evidence remains required.</p><div className="table-wrap"><table className="scout-table"><thead><tr><th>Scout</th><th>Status</th><th>Contributions</th><th>Accepted</th><th>Pending</th><th>Rejected</th><th>Last contribution</th><th></th></tr></thead><tbody>{data.scouts.length?data.scouts.map(row=><tr key={row.id}><td><strong>{row.displayName||row.username||'User'}</strong><div className="muted">{row.email||row.username||row.id}</div></td><td><span className={`state ${row.scoutEnabled?'active':'suspended'}`}>{row.scoutEnabled?'ACTIVE':'SUSPENDED'}</span></td><td>{row.contributions}</td><td>{row.accepted}</td><td>{row.pending}</td><td>{row.rejected}</td><td>{row.lastContributionAt?new Date(row.lastContributionAt).toLocaleString():'—'}</td><td><button type="button" disabled={busy===row.id} onClick={()=>toggle(row)}>{busy===row.id?'Saving…':row.scoutEnabled?'Suspend Scout':'Enable Scout'}</button></td></tr>):<tr><td colSpan={8}>No Scouts yet. Existing users can be enabled as Scouts without creating staff accounts.</td></tr>}</tbody></table></div></section></>:null}</main>;
}
