'use client';

import { useEffect, useState } from 'react';
import styles from '../admin.module.css';

type Assigned={location_id:string;name:string;city?:string;region?:string};
const days=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
export default function OwnerDispensaryPage(){
 const[assigned,setAssigned]=useState<Assigned[]>([]),[selected,setSelected]=useState(''),[overview,setOverview]=useState(''),[phone,setPhone]=useState(''),[website,setWebsite]=useState(''),[amenities,setAmenities]=useState(''),[hours,setHours]=useState<Record<string,string>>({}),[instagram,setInstagram]=useState(''),[facebook,setFacebook]=useState(''),[message,setMessage]=useState<string|null>(null),[loading,setLoading]=useState(true);
 useEffect(()=>{fetch('/api/admin/owner-profile',{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load assigned shops.');const rows=d.locations||[];setAssigned(rows);if(rows[0])setSelected(rows[0].location_id);}).catch(e=>setMessage(e instanceof Error?e.message:'Could not load assigned shops.')).finally(()=>setLoading(false));},[]);
 useEffect(()=>{if(!selected)return;fetch(`/api/admin/owner-profile/${encodeURIComponent(selected)}`,{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load shop profile.');const p=d.profile||{};setOverview(p.overview||'');setPhone(p.phone||d.location?.phone||'');setWebsite(p.website||d.location?.website||'');setAmenities((p.amenities||[]).join(', '));setHours(p.hours||{});setInstagram(p.social?.instagram||'');setFacebook(p.social?.facebook||'');}).catch(e=>setMessage(e instanceof Error?e.message:'Could not load shop profile.'));},[selected]);
 async function save(){setMessage(null);const r=await fetch(`/api/admin/owner-profile/${encodeURIComponent(selected)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({overview,phone,website,hours,amenities:amenities.split(',').map(v=>v.trim()).filter(Boolean),social:{instagram,facebook}})});const d=await r.json().catch(()=>({}));setMessage(r.ok?'Shop profile saved.':d.error||'Save failed.');}
 return <main className={styles.shell}><header className={styles.header}><div><a href="/admin" className={styles.adminHomeLink}><span className={styles.eyebrow}>GEOWEEDO ADMIN</span></a><h1>My dispensary</h1><p>Verified owner workspace. Changes here affect only your assigned public shop profile.</p></div></header>{loading?<div className={styles.loading}>Loading assigned shop…</div>:assigned.length===0?<section className={styles.section}><article className={styles.card}><h3>No verified shop assignment</h3><p>An administrator must verify ownership and assign your dispensary before this editor becomes available.</p></article></section>:<section className={styles.section}><article className={styles.card}><div className="owner-profile-editor"><label>Shop<select value={selected} onChange={e=>setSelected(e.target.value)}>{assigned.map(x=><option key={x.location_id} value={x.location_id}>{x.name} · {[x.city,x.region].filter(Boolean).join(', ')}</option>)}</select></label><label>Overview<textarea value={overview} maxLength={5000} onChange={e=>setOverview(e.target.value)} placeholder="Tell visitors about the shop, specialties, atmosphere, accessibility, and what makes it useful."/></label><div className="owner-profile-grid"><label>Phone<input value={phone} onChange={e=>setPhone(e.target.value)}/></label><label>Website<input value={website} onChange={e=>setWebsite(e.target.value)} placeholder="https://…"/></label><label>Instagram<input value={instagram} onChange={e=>setInstagram(e.target.value)}/></label><label>Facebook<input value={facebook} onChange={e=>setFacebook(e.target.value)}/></label></div><label>Amenities<input value={amenities} onChange={e=>setAmenities(e.target.value)} placeholder="Delivery, ATM, Parking, Wheelchair accessible…"/></label><div className="owner-hours"><strong>Hours</strong>{days.map(day=><label key={day}><span>{day}</span><input value={hours[day]||''} onChange={e=>setHours(current=>({...current,[day]:e.target.value}))} placeholder="9:00 AM – 8:00 PM"/></label>)}</div><button className={styles.primaryLink} onClick={save}>Save public profile</button>{message&&<div className="admin-community-message">{message}</div>}<p className="owner-scope-note">License data, official source fields, coordinates, gameplay approval, reviews, users, rewards, and finance records cannot be changed from an owner account.</p></div></article></section>}</main>;
}
