import { NextRequest, NextResponse } from 'next/server';
import { getAdminFromRequest } from '@/lib/adminAuth';
import { importCandidates } from '@/lib/candidateStore';
import { fetchAlaskaCandidates } from '@/lib/officialSources/alaska';
import { fetchColoradoCandidates } from '@/lib/officialSources/colorado';
import { fetchConnecticutCandidates } from '@/lib/officialSources/connecticut';
import { fetchDelawareCandidates } from '@/lib/officialSources/delaware';
import { fetchIllinoisCandidates } from '@/lib/officialSources/illinois';
import { fetchMaineCandidates } from '@/lib/officialSources/maine';
import { fetchMarylandCandidates } from '@/lib/officialSources/maryland';
import { fetchMichiganCandidates } from '@/lib/officialSources/michigan';
import { fetchMinnesotaCandidates } from '@/lib/officialSources/minnesota';
import { fetchMissouriCandidates } from '@/lib/officialSources/missouri';
import { fetchNewJerseyCandidates } from '@/lib/officialSources/newJersey';
import { fetchVirginiaCandidates } from '@/lib/officialSources/virginia';

export const runtime='nodejs';
type CandidateRow={name:string;streetAddress?:string;city?:string;region?:string;country:string;latitude?:number;longitude?:number;website?:string;licenseNumber?:string;dataSource:string;sourceUrl:string;sourceLicense:string;imageryStatus:'unchecked'|'missing_coordinates'};
type SyncDetail={ok:boolean;source:string;fetched:number;added:number;geocoded:number;total?:number;error?:string};
function key(v:string){return v.toLowerCase().replace(/[^a-z0-9]/g,'');}
function pick(r:Record<string,any>,names:string[]){for(const n of names){const v=r[n];if(v!==undefined&&v!==null&&String(v).trim()!=='')return String(v).trim();}return '';}
function coord(v:unknown){if(v==null||v==='')return undefined;const n=Number(v);return Number.isFinite(n)?n:undefined;}
function readiness(lat?:number,lng?:number){return lat!==undefined&&lng!==undefined?'unchecked' as const:'missing_coordinates' as const;}
function point(v:any){if(!v)return {};if(typeof v==='object')return{latitude:coord(v.latitude??v.lat??v.coordinates?.[1]),longitude:coord(v.longitude??v.lng??v.lon??v.coordinates?.[0])};const m=String(v).match(/POINT\s*\(\s*(-?\d+(?:\.\d+)?)\s+(-?\d+(?:\.\d+)?)\s*\)/i);return m?{longitude:Number(m[1]),latitude:Number(m[2])}:{};}
function normalizeObject(input:Record<string,any>){const out:Record<string,any>={};for(const [k,v] of Object.entries(input))out[key(k)]=v;return out;}
function browserHeaders(){return{Accept:'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8','User-Agent':'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/124 Safari/537.36','Accept-Language':'en-US,en;q=0.9'};}
async function getJson(url:string){let response:Response;try{response=await fetch(url,{headers:{Accept:'application/json','User-Agent':'GeoWeedo/0.7 (https://geoweedo.com)'},cache:'no-store',signal:AbortSignal.timeout(30000)});}catch(error){throw new Error(`Could not connect to official data source: ${error instanceof Error?error.message:String(error)}`);}if(!response.ok)throw new Error(`Official data source ${new URL(url).host} returned ${response.status}`);return response.json();}
async function getHtml(url:string,label:string){const response=await fetch(url,{headers:browserHeaders(),cache:'no-store',signal:AbortSignal.timeout(30000)});if(!response.ok)throw new Error(`${label} returned ${response.status}`);return response.text();}
async function fetchCalifornia():Promise<CandidateRow[]>{const sourceUrl='https://search.cannabis.ca.gov/';const api='https://as-dcc-pub-cann-w-p-002.azurewebsites.net/licenses/filteredsearch';const all:any[]=[];let page=1,hasNext=true;while(hasNext&&page<=100){const body:any=await getJson(`${api}?pageSize=500&pageNumber=${page}&searchQuery=`);const data=Array.isArray(body?.data)?body.data:[];all.push(...data);hasNext=Boolean(body?.metadata?.hasNext);page++;}if(hasNext)throw new Error('California DCC sync stopped after 100 pages; refusing a partial import.');return all.map(raw=>normalizeObject(raw)).filter(r=>{const lic=pick(r,['licensenumber','license']),type=pick(r,['licensetype','type']),status=pick(r,['licensestatus','status']);return(/^c10-/i.test(lic)||(/retailer/i.test(type)&&!/nonstorefront|non-storefront|delivery/i.test(type)))&&(/^active\b/i.test(status)||/about to expire/i.test(status));}).map(r=>{const geo=point(r.georeference??r.location??r.geolocation??r.point),latitude=coord(r.premiselatitude??r.latitude)??geo.latitude,longitude=coord(r.premiselongitude??r.longitude)??geo.longitude;return{name:pick(r,['businessdbaname','dbaname','businesslegalname','legalbusinessname','businessname','name']),streetAddress:pick(r,['premisestreetaddress','streetaddress','premiseaddress','address'])||undefined,city:pick(r,['premisecity','city'])||undefined,region:'California',country:'USA',latitude,longitude,website:pick(r,['businesswebsite','website','url'])||undefined,licenseNumber:pick(r,['licensenumber','license'])||undefined,dataSource:'California DCC Unified License Search',sourceUrl,sourceLicense:'Official California Department of Cannabis Control public license-search data; active storefront retailers only.',imageryStatus:readiness(latitude,longitude)};}).filter(r=>r.name);}
async function fetchOregon():Promise<CandidateRow[]>{const sourceUrl='https://data.oregon.gov/Business/OLCC-Cannabis-Business-Licenses-Endorsements/q32u-cmam';const data:any=await getJson('https://data.oregon.gov/resource/q32u-cmam.json?$limit=5000');return(Array.isArray(data)?data:[]).filter((r:any)=>String(r.license_type||'').toLowerCase().includes('retail')&&!String(r.license_expired||'').toLowerCase().includes('yes')).map((r:any)=>{const latitude=coord(r.latitude),longitude=coord(r.longitude);return{name:String(r.business_name||r.business_licenses||'').trim(),streetAddress:String(r.physical_address||'').trim()||undefined,region:'Oregon',country:'USA',latitude,longitude,licenseNumber:String(r.license_number||'').trim()||undefined,dataSource:'Oregon OLCC Open Data',sourceUrl,sourceLicense:'Official Oregon Open Data.',imageryStatus:readiness(latitude,longitude)};}).filter((r:any)=>r.name);}
async function fetchMassachusetts():Promise<CandidateRow[]>{const sourceUrl='https://masscannabiscontrol.com/open-data/data-catalog/';const data:any=await getJson('https://masscannabiscontrol.com/resource/l_licenses_commence_ops.json');return(Array.isArray(data)?data:[]).map((raw:any)=>normalizeObject(raw)).filter(r=>/marijuana retailer/i.test(pick(r,['licensetype']))).map(r=>{const latitude=coord(r.latitude??r.establishmentlatitude),longitude=coord(r.longitude??r.establishmentlongitude);return{name:pick(r,['dbaname','businessname','establishmentname']),streetAddress:pick(r,['establishmentaddress1','businessaddress1'])||undefined,city:pick(r,['establishmentcity','businesscity'])||undefined,region:'Massachusetts',country:'USA',latitude,longitude,licenseNumber:pick(r,['licensenumber','licensenumberbase'])||undefined,dataSource:'Massachusetts CCC Commence Operations',sourceUrl,sourceLicense:'Official Massachusetts Cannabis Control Commission open data; adult-use Marijuana Retailer licenses.',imageryStatus:readiness(latitude,longitude)};}).filter(r=>r.name);}
async function fetchNevada():Promise<CandidateRow[]>{const sourceUrl='https://ccb.nv.gov/list-of-licensees/',html=await getHtml(sourceUrl,'Nevada CCB'),plain=html.replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&nbsp;/g,' ').replace(/\s+/g,' '),rows:CandidateRow[]=[];const re=/([A-Z0-9][A-Z0-9 '&.!/()-]{2,80})\s*[–-]\s*([^|]{5,120}?)\s*[–-]\s*(Adult Use|Medical Only)\s*\|?\s*(\d{15,25})/gi;let m:RegExpExecArray|null;while((m=re.exec(plain))!==null)rows.push({name:m[1].trim(),streetAddress:m[2].trim(),region:'Nevada',country:'USA',licenseNumber:m[4],dataSource:'Nevada CCB Licensed Retail Locations',sourceUrl,sourceLicense:'Official Nevada Cannabis Compliance Board public retail-location list.',imageryStatus:'missing_coordinates'});return rows;}
async function fetchWashington():Promise<CandidateRow[]>{const sourceUrl='https://data.wa.gov/d/brpd-b6zd',data:any=await getJson('https://data.wa.gov/resource/brpd-b6zd.json?$limit=50000');return(Array.isArray(data)?data:[]).map((raw:any)=>normalizeObject(raw)).map(r=>{const geo=point(r.location??r.geolocation??r.point??r.geocodedcolumn),latitude=coord(r.latitude??r.lat)??geo.latitude,longitude=coord(r.longitude??r.lng??r.lon)??geo.longitude,licenseNumber=pick(r,['licensenumber','license','licenseid','licenseidentifier','ubi']);return{name:pick(r,['tradename','businessname','businesslegalname','companyname','licenseename','name'])||`Washington Cannabis Renewal ${licenseNumber}`,streetAddress:pick(r,['streetaddress','address','premiseaddress','locationaddress','physicaladdress'])||undefined,city:pick(r,['city','premisecity','locationcity'])||undefined,region:'Washington',country:'USA',latitude,longitude,licenseNumber:licenseNumber||undefined,dataSource:'Washington LCB Cannabis Renewal Open Data',sourceUrl,sourceLicense:'Official Washington State Liquor and Cannabis Board Cannabis Renewal dataset.',imageryStatus:readiness(latitude,longitude)};}).filter(r=>r.name);}
async function fetchNewYork():Promise<CandidateRow[]>{const sourceUrl='https://data.ny.gov/d/jskf-tt3q',data:any=await getJson('https://data.ny.gov/resource/jskf-tt3q.json?$limit=10000');return(Array.isArray(data)?data:[]).map((raw:any)=>normalizeObject(raw)).filter(r=>!pick(r,['licensetype'])||/retail dispensary|registered organization dispensary/i.test(pick(r,['licensetype']))).map(r=>({name:pick(r,['dba','entityname']),streetAddress:[pick(r,['addressline1']),pick(r,['addressline2'])].filter(Boolean).join(', ')||undefined,city:pick(r,['city'])||undefined,region:'New York',country:'USA',website:pick(r,['businesswebsite'])||undefined,licenseNumber:pick(r,['licensenumber'])||undefined,dataSource:'New York OCM Current Licenses',sourceUrl,sourceLicense:'Official New York Office of Cannabis Management Current OCM Licenses dataset; retail-dispensary records only.',imageryStatus:'missing_coordinates' as const})).filter(r=>r.name);}
async function fetchMontana():Promise<CandidateRow[]>{const sourceUrl='https://revenue.mt.gov/card/cannabis/cannabis-licenses/lists/dispensary-locations',html=await getHtml(sourceUrl,'Montana DOR'),rows:CandidateRow[]=[];const tr=/<tr[^>]*>([\s\S]*?)<\/tr>/gi;let m:RegExpExecArray|null;while((m=tr.exec(html))!==null){const cells:string[]=[];const td=/<t[dh][^>]*>([\s\S]*?)<\/t[dh]>/gi;let c:RegExpExecArray|null;while((c=td.exec(m[1]))!==null)cells.push(c[1].replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim());if(cells.length>=3&&!/licensee.?s name/i.test(cells[0]))rows.push({name:cells[2]||cells[0],city:cells[1],region:'Montana',country:'USA',dataSource:'Montana DOR Licensed Dispensary Locations',sourceUrl,sourceLicense:'Official Montana Department of Revenue licensed dispensary list.',imageryStatus:'missing_coordinates'});}return rows;}

const officialSources=[
 {preset:'alaska-amco',label:'Alaska AMCO',fetcher:fetchAlaskaCandidates},{preset:'california-dcc',label:'California DCC',fetcher:fetchCalifornia},{preset:'oregon-olcc',label:'Oregon OLCC',fetcher:fetchOregon},{preset:'colorado-med',label:'Colorado MED',fetcher:fetchColoradoCandidates},{preset:'massachusetts-ccc',label:'Massachusetts CCC',fetcher:fetchMassachusetts},{preset:'illinois-idfpr',label:'Illinois IDFPR',fetcher:fetchIllinoisCandidates},{preset:'nevada-ccb',label:'Nevada CCB',fetcher:fetchNevada},{preset:'washington-lcb',label:'Washington LCB',fetcher:fetchWashington},{preset:'connecticut-dcp',label:'Connecticut DCP',fetcher:fetchConnecticutCandidates},{preset:'new-york-ocm',label:'New York OCM',fetcher:fetchNewYork},{preset:'montana-dor',label:'Montana DOR',fetcher:fetchMontana},{preset:'virginia-cca',label:'Virginia CCA',fetcher:fetchVirginiaCandidates},{preset:'delaware-omc',label:'Delaware OMC',fetcher:fetchDelawareCandidates},{preset:'maine-ocp',label:'Maine OCP',fetcher:fetchMaineCandidates},{preset:'maryland-mca',label:'Maryland MCA',fetcher:fetchMarylandCandidates},{preset:'michigan-cra',label:'Michigan CRA',fetcher:fetchMichiganCandidates},{preset:'minnesota-ocm',label:'Minnesota OCM',fetcher:fetchMinnesotaCandidates},{preset:'missouri-dhss',label:'Missouri DHSS',fetcher:fetchMissouriCandidates},{preset:'new-jersey-crc',label:'New Jersey CRC',fetcher:fetchNewJerseyCandidates}
] as const;
async function syncSource(source:(typeof officialSources)[number]):Promise<SyncDetail>{try{const rows=await source.fetcher() as CandidateRow[];if(!rows.length)throw new Error(`${source.label} returned zero valid dispensary records.`);const result=await importCandidates(rows as any[]);return{ok:true,source:source.label,fetched:rows.length,added:result.added,geocoded:rows.filter(r=>Number.isFinite(r.latitude)&&Number.isFinite(r.longitude)).length,total:result.total};}catch(error){return{ok:false,source:source.label,fetched:0,added:0,geocoded:0,error:error instanceof Error?error.message:String(error)};}}
export async function POST(request:NextRequest){if(!getAdminFromRequest(request))return NextResponse.json({error:'Unauthorized.'},{status:401});const body=await request.json().catch(()=>null),preset=String(body?.preset||'');if(preset==='all'){const details:SyncDetail[]=[];for(const source of officialSources)details.push(await syncSource(source));const successful=details.filter(d=>d.ok);return NextResponse.json({added:successful.reduce((s,d)=>s+d.added,0),fetched:successful.reduce((s,d)=>s+d.fetched,0),geocoded:successful.reduce((s,d)=>s+d.geocoded,0),details,failed:details.length-successful.length,succeeded:successful.length,source:'Official multi-state sync'},{status:successful.length?201:502});}const source=officialSources.find(item=>item.preset===preset);if(!source)return NextResponse.json({error:'Unknown official-data preset.'},{status:400});const detail=await syncSource(source);return detail.ok?NextResponse.json({...detail,source:source.label},{status:201}):NextResponse.json({error:detail.error,details:[detail]},{status:502});}
