'use client';

import { useEffect, useMemo, useState } from 'react';
import GuessMap, { type LatLng } from '@/components/GuessMap';
import SiteHeader from '@/components/SiteHeader';

type DailyLocation={id:string;name:string;latitude:number;longitude:number;city?:string;region?:string;country?:string};
function distanceKm(a:LatLng,b:LatLng){const r=6371.0088,rad=(v:number)=>(v*Math.PI)/180,dLat=rad(b.lat-a.lat),dLng=rad(b.lng-a.lng),lat1=rad(a.lat),lat2=rad(b.lat),h=Math.sin(dLat/2)**2+Math.cos(lat1)*Math.cos(lat2)*Math.sin(dLng/2)**2;return r*2*Math.atan2(Math.sqrt(h),Math.sqrt(1-h));}
function scoreFromDistance(km:number){return Math.max(0,Math.min(5000,Math.round(5000*Math.exp(-km/500))));}
function dateKey(){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Los_Angeles',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());}
function hashString(input:string){let h=2166136261;for(let i=0;i<input.length;i++){h^=input.charCodeAt(i);h=Math.imul(h,16777619);}return h>>>0;}
export default function DailyWeedo(){
 const[locations,setLocations]=useState<DailyLocation[]>([]),[guess,setGuess]=useState<LatLng|null>(null),[revealed,setRevealed]=useState(false),[distance,setDistance]=useState<number|null>(null),[score,setScore]=useState<number|null>(null);
 const today=dateKey();
 useEffect(()=>{fetch('/api/map-candidates',{cache:'no-store'}).then(r=>r.json()).then(d=>{const rows=(Array.isArray(d.candidates)?d.candidates:[]).filter((x:any)=>Number.isFinite(x.latitude)&&Number.isFinite(x.longitude));setLocations(rows);}).catch(()=>{});},[]);
 const target=useMemo(()=>locations.length?locations[hashString(`geoweedo-daily-${today}`)%locations.length]:null,[locations,today]);
 const submit=()=>{if(!guess||!target||revealed)return;const km=distanceKm(guess,{lat:target.latitude,lng:target.longitude});setDistance(km);setScore(scoreFromDistance(km));setRevealed(true);try{localStorage.setItem(`geoweedo-daily-${today}`,JSON.stringify({score:scoreFromDistance(km),distanceKm:km,guess}));}catch{}};
 const share=async()=>{if(score===null||distance===null)return;const miles=distance*.621371;const text=`🌎 Daily Weedo ${today}\n📍 ${miles<.1?`${Math.round(miles*5280)} ft`:`${miles.toFixed(1)} mi`}\n⭐ ${score.toLocaleString()} / 5,000\n#GeoWeedo`;if(navigator.share){try{await navigator.share({title:'Daily Weedo',text});return;}catch{}}try{await navigator.clipboard.writeText(text);}catch{}};
 return <main className="landing-shell"><SiteHeader/><section className="daily-weedo-page"><div className="daily-weedo-heading"><div><div className="eyebrow">ONE LOCATION · EVERY DAY</div><h1>🌎 Daily Weedo</h1><p>Everyone gets the same dispensary today. You get one guess, one score, and a fresh challenge tomorrow.</p></div><a className="secondary" href="/">Back to GeoWeedo</a></div>{!target?<div className="result-card"><h2>Loading today’s Weedo…</h2><p>Choosing today’s mapped dispensary.</p></div>:<div className="daily-weedo-layout"><div className="daily-weedo-map"><GuessMap guess={guess} actual={revealed?{lat:target.latitude,lng:target.longitude}:undefined} revealed={revealed} onGuess={revealed?()=>{}:setGuess}/></div><aside className="result-card daily-weedo-status"><div className="eyebrow">DAILY CHALLENGE · {today}</div>{!revealed?<><h2>Where is today’s Weedo?</h2><p>Drop your best pin on the map. There are no retries after you submit.</p><button className="primary full" disabled={!guess} onClick={submit}>{guess?'Lock In Daily Guess':'Drop a Pin First'}</button></>:<><h2>{target.name}</h2><p>{target.city}{target.city&&target.region?', ':''}{target.region}</p><div className="score-list"><div><span>Distance</span><strong>{distance===null?'—':`${(distance*.621371).toFixed(distance<1?2:1)} mi`}</strong></div><div><span>Score</span><strong>{score?.toLocaleString()} / 5,000</strong></div></div><button className="primary full" style={{marginTop:16}} onClick={share}>Share Daily Result</button><p style={{opacity:.7,marginTop:12}}>Come back tomorrow for a new Daily Weedo.</p></>}</aside></div>}</section><style jsx global>{`
.daily-weedo-page{max-width:1360px;margin:0 auto;padding:24px 22px 36px}.daily-weedo-heading{display:flex;gap:18px;align-items:end;justify-content:space-between;flex-wrap:wrap;margin-bottom:16px}.daily-weedo-heading h1{margin:5px 0 4px;font-size:34px;line-height:1.05}.daily-weedo-heading p{margin:0;max-width:760px;color:#dbe3dd}.daily-weedo-layout{display:grid;grid-template-columns:minmax(0,1fr) minmax(300px,360px);gap:16px;align-items:stretch}.daily-weedo-map{height:clamp(540px,68vh,760px);min-width:0;border-radius:18px;overflow:hidden;border:1px solid rgba(255,255,255,.12);background:#202820}.daily-weedo-map .guess-map-wrap{height:100%!important;min-height:100%;margin:0!important;border-radius:0!important}.daily-weedo-map .guess-map-canvas{height:100%!important;min-height:100%}.daily-weedo-status{margin:0!important;text-align:left!important;max-width:none!important;width:100%!important;padding:26px!important;overflow:auto}@media(max-width:900px){.daily-weedo-page{padding:18px 14px 28px}.daily-weedo-layout{grid-template-columns:1fr}.daily-weedo-map{height:clamp(460px,62vh,640px)}.daily-weedo-status{padding:22px!important}.daily-weedo-heading{align-items:start}.daily-weedo-heading h1{font-size:30px}}@media(max-width:560px){.daily-weedo-page{padding:14px 10px 24px}.daily-weedo-heading h1{font-size:27px}.daily-weedo-heading p{font-size:14px}.daily-weedo-map{height:58vh;min-height:390px;border-radius:14px}.daily-weedo-status{padding:18px!important}}
`}</style></main>;
}
