'use client';

import { useEffect, useState } from 'react';
import GuessMap, { type LatLng } from '@/components/GuessMap';
import SiteHeader from '@/components/SiteHeader';

type DailyLocation={id:string;name:string;latitude:number;longitude:number;city?:string;region?:string;country?:string;website?:string;dataSource?:string;sponsored?:boolean};
type RewardPolicy={enabled:boolean;dailyEnabled:boolean;dailyPerfectRewardYerb:number;dailyCapYerb:number;reviewRequired:boolean};
type RewardState={state:'idle'|'submitting'|'done'|'error';amountYerb?:number;status?:string;message?:string};
const DEFAULT_POLICY:RewardPolicy={enabled:true,dailyEnabled:true,dailyPerfectRewardYerb:2,dailyCapYerb:25,reviewRequired:true};
function distanceKm(a:LatLng,b:LatLng){const r=6371.0088,rad=(v:number)=>(v*Math.PI)/180,dLat=rad(b.lat-a.lat),dLng=rad(b.lng-a.lng),lat1=rad(a.lat),lat2=rad(b.lat),h=Math.sin(dLat/2)**2+Math.cos(lat1)*Math.cos(lat2)*Math.sin(dLng/2)**2;return r*2*Math.atan2(Math.sqrt(h),Math.sqrt(1-h));}
function scoreFromDistance(km:number){return Math.max(0,Math.min(5000,Math.round(5000*Math.exp(-km/500))));}
function dateKey(){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Los_Angeles',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());}
function rewardValue(points:number,policy:RewardPolicy){if(!policy.enabled||!policy.dailyEnabled)return 0;const safe=Math.max(0,Math.min(5000,points||0));return Number(((safe/5000)*policy.dailyPerfectRewardYerb).toFixed(8));}

export default function DailyWeedo(){
 const[target,setTarget]=useState<DailyLocation|null>(null),[guess,setGuess]=useState<LatLng|null>(null),[revealed,setRevealed]=useState(false),[distance,setDistance]=useState<number|null>(null),[score,setScore]=useState<number|null>(null),[loadError,setLoadError]=useState(''),[policy,setPolicy]=useState<RewardPolicy>(DEFAULT_POLICY),[reward,setReward]=useState<RewardState>({state:'idle'});
 const today=dateKey(),maxDailyYerb=policy.dailyPerfectRewardYerb;
 useEffect(()=>{fetch('/api/daily-weedo',{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load Daily Weedo.');setTarget(d.location||null);}).catch(e=>setLoadError(e instanceof Error?e.message:'Could not load Daily Weedo.'));fetch('/api/rewards/policy',{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject()).then(d=>setPolicy({...DEFAULT_POLICY,...d})).catch(()=>setPolicy(DEFAULT_POLICY));},[]);
 const submitReward=async(pin:LatLng)=>{setReward({state:'submitting'});try{const response=await fetch('/api/rewards/daily',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({guessLat:pin.lat,guessLng:pin.lng})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Could not record Daily Weedo reward.');setReward({state:'done',amountYerb:Number(data.amountYerb||0),status:String(data.status||'earned')});}catch(error){setReward({state:'error',message:error instanceof Error?error.message:'Could not record Daily Weedo reward.'});}};
 const submit=()=>{if(!guess||!target||revealed)return;const pin=guess,km=distanceKm(pin,{lat:target.latitude,lng:target.longitude}),points=scoreFromDistance(km);setDistance(km);setScore(points);setRevealed(true);try{localStorage.setItem(`geoweedo-daily-${today}`,JSON.stringify({score:points,distanceKm:km,guess:pin,targetId:target.id}));}catch{}void submitReward(pin);};
 const share=async()=>{if(score===null||distance===null)return;const miles=distance*.621371,text=`🌎 Daily Weedo ${today}\n📍 ${miles<.1?`${Math.round(miles*5280)} ft`:`${miles.toFixed(1)} mi`}\n⭐ ${score.toLocaleString()} / 5,000\n🪙 ${rewardValue(score,policy).toFixed(4)} YERB potential\n#GeoWeedo`;if(navigator.share){try{await navigator.share({title:'Daily Weedo',text});return;}catch{}}try{await navigator.clipboard.writeText(text);}catch{}};
 const rewardText=!policy.enabled||!policy.dailyEnabled?'Daily YERB rewards are currently disabled.':reward.state==='submitting'?'Recording your Daily YERB reward…':reward.state==='done'?(reward.status==='pending_review'?`Reward pending review: ${Number(reward.amountYerb||0).toFixed(8)} YERB`:reward.status==='daily_cap_reached'?'Daily YERB cap reached.':reward.status==='cooldown'?'Reward cooldown is still active.':reward.status==='daily_game_limit'?'Daily rewarded-game limit reached.':reward.status==='mode_disabled'||reward.status==='rewards_disabled'?'Daily YERB rewards are currently disabled.':`Reward earned: ${Number(reward.amountYerb||0).toFixed(8)} YERB`):reward.state==='error'?reward.message||'Reward could not be recorded.':score===null?`Up to ${maxDailyYerb.toFixed(4)} YERB today`:`Estimated reward: ${rewardValue(score,policy).toFixed(8)} YERB`;
 return <main className="landing-shell"><SiteHeader/><section className="daily-weedo-page"><div className="daily-weedo-heading"><div><div className="eyebrow">ONE LOCATION · EVERY DAY</div><h1>🌎 Daily Weedo</h1><p>Everyone gets the same dispensary today. Daily sponsorship is a clearly labeled presentation placement and never changes which location is selected.</p></div><a className="secondary" href="/">Back to GeoWeedo</a></div>{!target?<div className="result-card"><h2>{loadError?'Daily Weedo unavailable':'Loading today’s Weedo…'}</h2><p>{loadError||'Choosing today’s enabled dispensary.'}</p></div>:<div className="daily-weedo-layout"><div className="daily-weedo-map"><GuessMap guess={guess} actual={revealed?{lat:target.latitude,lng:target.longitude}:undefined} revealed={revealed} onGuess={revealed?()=>{}:setGuess}/></div><aside className="result-card daily-weedo-status"><div className="eyebrow">DAILY CHALLENGE · {today}</div>{!revealed?<><h2>Where is today’s Weedo?</h2><p>Drop your best pin on the map. There are no retries after you submit.</p><div className="daily-weedo-yervalue"><span>DAILY YERB VALUE</span><strong>{policy.enabled&&policy.dailyEnabled?`Up to ${maxDailyYerb.toFixed(4)} YERB`:'Rewards disabled'}</strong><small>Configured by GeoWeedo Admin. Final reward scales with your score and remains subject to daily limits.</small></div><button className="primary full" disabled={!guess} onClick={submit}>{guess?'Lock In Daily Guess':'Drop a Pin First'}</button></>:<><div className="daily-weedo-feature-badge">📍 DAILY LOCATION</div><h2>{target.name}</h2><p>{[target.city,target.region,target.country].filter(Boolean).join(', ')}</p><div className="score-list"><div><span>Distance</span><strong>{distance===null?'—':`${(distance*.621371).toFixed(distance<1?2:1)} mi`}</strong></div><div><span>Score</span><strong>{score?.toLocaleString()} / 5,000</strong></div><div><span>YERB value</span><strong>{score===null?'—':`${rewardValue(score,policy).toFixed(4)} YERB`}</strong></div></div><div className="daily-weedo-reward"><strong>{rewardText}</strong><span>One Daily Weedo reward record per player per day. Account eligibility, cooldowns, caps, and review policy still apply.</span></div><div className="daily-weedo-actions"><a className="secondary full" href={`/?location=${encodeURIComponent(target.id)}`}>View Location</a>{target.website&&<a className="secondary full" href={target.website} target="_blank" rel="noreferrer">Visit Website</a>}<button className="primary full" onClick={share}>Share Daily Result</button></div><p style={{opacity:.7,marginTop:12}}>Come back tomorrow for a new Daily Weedo.</p></>}</aside></div>}</section><style jsx global>{`
.daily-weedo-page{max-width:1360px;margin:0 auto;padding:24px 22px 36px}.daily-weedo-heading{display:flex;gap:18px;align-items:end;justify-content:space-between;flex-wrap:wrap;margin-bottom:16px}.daily-weedo-heading h1{margin:5px 0 4px;font-size:34px;line-height:1.05}.daily-weedo-heading p{margin:0;max-width:780px;color:#dbe3dd}.daily-weedo-layout{display:grid;grid-template-columns:minmax(0,1fr) minmax(300px,360px);gap:16px;align-items:stretch}.daily-weedo-map{height:clamp(540px,68vh,760px);min-width:0;border-radius:18px;overflow:hidden;border:1px solid rgba(255,255,255,.12);background:#202820}.daily-weedo-map .guess-map-wrap{height:100%!important;min-height:100%;margin:0!important;border-radius:0!important}.daily-weedo-map .guess-map-canvas{height:100%!important;min-height:100%}.daily-weedo-status{margin:0!important;text-align:left!important;max-width:none!important;width:100%!important;padding:26px!important;overflow:auto}.daily-weedo-yervalue{display:grid;gap:5px;margin:16px 0;padding:14px;border:1px solid rgba(103,214,110,.25);border-radius:12px;background:rgba(103,214,110,.06)}.daily-weedo-yervalue span{font-size:9px;letter-spacing:.1em;font-weight:900;color:#9aa69d}.daily-weedo-yervalue strong{font-size:22px;color:#67d66e}.daily-weedo-yervalue small{font-size:11px;color:#cbd5cd}.daily-weedo-reward{display:grid;gap:5px;margin-top:14px;padding:13px;border-radius:11px;border:1px solid rgba(103,214,110,.2);background:rgba(103,214,110,.045)}.daily-weedo-reward strong{color:#67d66e}.daily-weedo-reward span{font-size:11px;color:#cbd5cd}.daily-weedo-feature-badge{display:inline-flex;margin:12px 0 4px;padding:7px 10px;border:1px solid rgba(255,255,255,.12);border-radius:999px;font-size:10px;font-weight:900;letter-spacing:.08em;color:#cbd5cd}.daily-weedo-actions{display:grid;gap:8px;margin-top:16px}.daily-weedo-actions a{text-decoration:none;text-align:center}@media(max-width:900px){.daily-weedo-page{padding:18px 14px 28px}.daily-weedo-layout{grid-template-columns:1fr}.daily-weedo-map{height:clamp(460px,62vh,640px)}.daily-weedo-status{padding:22px!important}.daily-weedo-heading{align-items:start}.daily-weedo-heading h1{font-size:30px}}@media(max-width:560px){.daily-weedo-page{padding:14px 10px 24px}.daily-weedo-heading h1{font-size:27px}.daily-weedo-heading p{font-size:14px}.daily-weedo-map{height:58vh;min-height:390px;border-radius:14px}.daily-weedo-status{padding:18px!important}}
`}</style></main>;
}
