'use client';

import { useEffect, useMemo, useState } from 'react';
import GuessMap, { type LatLng } from '@/components/GuessMap';
import SiteHeader from '@/components/SiteHeader';

type DailyLocation={id:string;name:string;latitude:number;longitude:number;city?:string;region?:string;country?:string};
function distanceKm(a:LatLng,b:LatLng){const r=6371.0088,rad=(v:number)=>(v*Math.PI)/180,dLat=rad(b.lat-a.lat),dLng=rad(b.lng-a.lng),lat1=rad(a.lat),lat2=rad(b.lat),h=Math.sin(dLat/2)**2+Math.cos(lat1)*Math.cos(lat2)*Math.sin(dLng/2)**2;return r*2*Math.atan2(Math.sqrt(h),Math.sqrt(1-h));}
function scoreFromDistance(km:number){return Math.max(0,Math.min(5000,Math.round(5000*Math.exp(-km/500))));}
function dateKey(){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Los_Angeles',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());}
function hashString(input:string){let h=2166136261;for(let i=0;i<input.length;i++){h^=input.charCodeAt(i);h=Math.imul(h,16777619);}return h>>>0;}
export default function DailyWeedo(){
 const[locations,setLocations]=useState<DailyLocation[]>([]),[guess,setGuess]=useState<LatLng|null>(null),[revealed,setRevealed]=useState(false),[distance,setDistance]=useState<number|null>(null),[score,setScore]=useState<number|null>(null);
 const today=dateKey();
 useEffect(()=>{fetch('/api/map-candidates',{cache:'no-store'}).then(r=>r.json()).then(d=>{const rows=(Array.isArray(d.candidates)?d.candidates:[]).filter((x:any)=>Number.isFinite(x.latitude)&&Number.isFinite(x.longitude));setLocations(rows);}).catch(()=>{});},[]);
 const target=useMemo(()=>locations.length?locations[hashString(`geoweedo-daily-${today}`)%locations.length]:null,[locations,today]);
 const submit=()=>{if(!guess||!target||revealed)return;const km=distanceKm(guess,{lat:target.latitude,lng:target.longitude});setDistance(km);setScore(scoreFromDistance(km));setRevealed(true);try{localStorage.setItem(`geoweedo-daily-${today}`,JSON.stringify({score:scoreFromDistance(km),distanceKm:km,guess}));}catch{}};
 const share=async()=>{if(score===null||distance===null)return;const miles=distance*0.621371;const text=`🌎 Daily Weedo ${today}\n📍 ${miles<0.1?`${Math.round(miles*5280)} ft`:`${miles.toFixed(1)} mi`}\n⭐ ${score.toLocaleString()} / 5,000\n#GeoWeedo`;if(navigator.share){try{await navigator.share({title:'Daily Weedo',text});return;}catch{}}try{await navigator.clipboard.writeText(text);}catch{}};
 return <main className="landing-shell"><SiteHeader/><section style={{maxWidth:1200,margin:'0 auto',padding:'28px 18px 48px'}}><div style={{display:'flex',gap:18,alignItems:'end',justifyContent:'space-between',flexWrap:'wrap',marginBottom:18}}><div><div className="eyebrow">ONE LOCATION · EVERY DAY</div><h1 style={{margin:'6px 0'}}>🌎 Daily Weedo</h1><p style={{margin:0,maxWidth:680}}>Everyone gets the same dispensary today. You get one guess, one score, and a fresh challenge tomorrow.</p></div><a className="secondary" href="/">Back to GeoWeedo</a></div>{!target?<div className="result-card"><h2>Loading today’s Weedo…</h2><p>Choosing today’s mapped dispensary.</p></div>:<div style={{display:'grid',gridTemplateColumns:'minmax(0,1fr) minmax(280px,350px)',gap:16,alignItems:'stretch'}}><div style={{minHeight:560,borderRadius:18,overflow:'hidden',border:'1px solid rgba(255,255,255,.12)'}}><GuessMap guess={guess} actual={revealed?{lat:target.latitude,lng:target.longitude}:undefined} revealed={revealed} onGuess={revealed?()=>{}:setGuess}/></div><aside className="result-card" style={{margin:0,textAlign:'left',maxWidth:'none'}}><div className="eyebrow">DAILY CHALLENGE · {today}</div>{!revealed?<><h2>Where is today’s Weedo?</h2><p>Drop your best pin on the map. There are no retries after you submit.</p><button className="primary full" disabled={!guess} onClick={submit}>{guess?'Lock In Daily Guess':'Drop a Pin First'}</button></>:<><h2>{target.name}</h2><p>{target.city}{target.city&&target.region?', ':''}{target.region}</p><div className="score-list"><div><span>Distance</span><strong>{distance===null?'—':`${(distance*0.621371).toFixed(distance<1?2:1)} mi`}</strong></div><div><span>Score</span><strong>{score?.toLocaleString()} / 5,000</strong></div></div><button className="primary full" style={{marginTop:16}} onClick={share}>Share Daily Result</button><p style={{opacity:.7,marginTop:12}}>Come back tomorrow for a new Daily Weedo.</p></>}</aside></div>}</section></main>;
}
